### ISSUE TITLE
Unable to build project

### ISSUE THREAD

**Issue by shamage** [TrinityCore/TrinityCore#30138]
### Description

Already during the attempt to compile the project using CMake, it prints an error : 
```
Selecting Windows SDK version 10.0.26100.0 to target Windows 10.0.22631.
The C compiler identification is MSVC 19.40.33813.0
The CXX compiler identification is MSVC 19.40.33813.0
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.40.33807/bin/Hostx64/x64/cl.exe - skipped
Detecting C compile features
Detecting C compile features - done
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.40.33807/bin/Hostx64/x64/cl.exe - skipped
Detecting CXX compile features
Detecting CXX compile features - done
Detected 64-bit platform
Detected amd64 processor architecture
MSVC: Minimum version required is 19.32, found 19.40.33813.0 - ok!
MSVC: 64-bit platform, enforced -D_WIN64 parameter
MSVC: Enabled increased number of sections in object files
MSVC: Overloaded standard names
MSVC: Disabled NON-SECURE warnings
MSVC: Disabled POSIX warnings
MSVC: Disabled generic compiletime warnings
Found Git: C:/Program Files/Git/cmd/git.exe (found suitable version "2.46.0.windows.1", minimum required is "1.7")
Found MySQL:   found components: binary
Found MySQL executable: C:/Program Files/MySQL/MySQL Server 8.0/bin/mysql.exe

* TrinityCore revision   : d72e91bee27f 2024-08-03 13:40:17 +0200 (master branch)

* Install core to        : C:/Program Files (x86)/TrinityCore
* Install configs to     : C:/Program Files (x86)/TrinityCore

* Build world/auth       : Yes (default)
* Build with scripts     : Yes (static)
* Build map/vmap tools   : Yes (default)
* Build unit tests       : No (default)
* Build core w/PCH       : Yes (default)
* Build scripts w/PCH    : Yes (default)
* Show compile-warnings  : No  (default)
* Use coreside debug     : No  (default)
* Show source tree       : Yes (hierarchical)
* Use GIT revision hash  : Yes (default)

Performing Test CMAKE_HAVE_LIBC_PTHREAD
Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
Looking for pthread_create in pthreads
Looking for pthread_create in pthreads - not found
Looking for pthread_create in pthread
Looking for pthread_create in pthread - not found
Found Threads: TRUE
CMake Error at dep/boost/CMakeLists.txt:43 (find_package):
  Could not find a package configuration file provided by "Boost" (requested
  version 1.78) with any of the following names:

    BoostConfig.cmake
    boost-config.cmake

  Add the installation prefix of "Boost" to CMAKE_PREFIX_PATH or set
  "Boost_DIR" to a directory containing one of the above files.  If "Boost"
  provides a separate development package or SDK, be sure it has been
  installed.


Configuring incomplete, errors occurred!
```

### Expected behaviour

The project should build without error

### Steps to reproduce the problem

1. download the current version of TC
2. Run the build via CMake
3. Monitor processing

### Branch

master

### TC rev. hash/commit

TrinityCore revision   : d72e91bee27f 2024-08-03 13:40:17 +0200 (master branch)

### Operating system

Win 11 Pro

### Custom changes

I made a change to the error-free process of building the code by removing the highlighted area: (see printscreen)

However, I am not sure if this change does not have any negative impact on something else in the code for building the project.
![Ashampoo_Snap_nedeľa 4  augusta 2024_12h17m4s](https://github.com/user-attachments/assets/c2bb9919-9c31-4212-9794-f7050e36e175)

**Comment by Shauren** [comment]
You must be doing something nonstandard with boost installation because nobody else has this issue

**Comment by shamage** [comment]
Regarding BOOST, I use the latest version: [Version 1.85.0](https://www.boost.org/users/history/version_1_85_0.html)

**Comment by Mematoru23** [comment]
Not sure about other versions, but 1.80.0 works for sure so i would recommand using it
Also, install the lib from [here](https://sourceforge.net/projects/boost/files/boost-binaries/1.80.0/boost_1_80_0-msvc-14.3-64.exe/download).

**Comment by Shauren** [comment]
1.85 works too (i am using it)

Did you not set BOOST_ROOT environment variable?

**Comment by shamage** [comment]
BOOST_ROOT is set as follows: : 
![Ashampoo_Snap_nedeľa 4  augusta 2024_13h14m18s](https://github.com/user-attachments/assets/88b741c9-d639-472e-93d1-88f2834357f3)

it is interesting that if it is a code without changes, the result is like this (with an error) :

![Ashampoo_Snap_nedeľa 4  augusta 2024_13h15m58s](https://github.com/user-attachments/assets/36ca9ac6-36ae-407e-a5c6-fd94cd45b67d)

if I make the change as I announced, the result is as follows :

![Ashampoo_Snap_nedeľa 4  augusta 2024_13h16m28s](https://github.com/user-attachments/assets/1dc9b2ac-c1ea-4344-8c23-5979e1e674c7)

**Comment by Shauren** [comment]
boost_1_85_0/stage? what on earth did you download?

**Comment by Shauren** [comment]
Basically, your boost installation is broken/custom/unsupported

Your changes to CMakeLists also revert how boost is found to use a legacy method that will stop working in future cmake versions

**Comment by shamage** [comment]
Exactly this : https://archives.boost.io/release/1.85.0/source/boost_1_85_0.zip

![Ashampoo_Snap_nedeľa 4  augusta 2024_13h29m0s](https://github.com/user-attachments/assets/c567553a-e0c3-438a-a97f-b745b5603b8a)

**Comment by Shauren** [comment]
You need this: https://www.boost.org/users/download/
![obraz](https://github.com/user-attachments/assets/ad916724-aa78-492c-af77-6901b3b96984)

**Comment by shamage** [comment]
Thank you very much for your support

**Comment by shamage** [comment]
I will add new facts here : 

@Mematoru23 :  indeed, the version BOOST 1.80 mentioned by you is problem-free and there is no need to make any modifications in Core. ( check image )  
![Ashampoo_Snap_štvrtok 8  augusta 2024_17h22m1s](https://github.com/user-attachments/assets/23f2e596-0f10-458d-9965-8fe6a610bb5e)
![Ashampoo_Snap_štvrtok 8  augusta 2024_17h22m30s](https://github.com/user-attachments/assets/7dd19d47-6390-4e18-a867-74eb22e010ee)

@Shauren :  I really tried all the options I could think of to make it work with the BOOST 1.85 version without the need for any modification in Core - I didn't succeed - I really don't know where the problem could be. Well, as I already wrote above, the BOOST 1.80 version works without problems, no modifications in Core are necessary.

**Comment by shamage** [comment]
> You need this: https://www.boost.org/users/download/ ![obraz](https://private-user-images.githubusercontent.com/297439/354898524-ad916724-aa78-492c-af77-6901b3b96984.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMzA4NzMsIm5iZiI6MTcyMzEzMDU3MywicGF0aCI6Ii8yOTc0MzkvMzU0ODk4NTI0LWFkOTE2NzI0LWFhNzgtNDkyYy1hZjc3LTY5MDFiM2I5Njk4NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQxNTIyNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ODRiMjc4NjZmZjljMzc5NTFjNDM3OThiNTRlMmM2YmQyNzNmMWVhMDU2MDc3OWRhYmQ5ZGFmOTU3Nzc5YTk5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uTAlp7u7Np9B3xFhlrY8pCRyLpzpvPBfDPdsDuy6QyE)

I also downloaded exactly the edition you recommended - it's still unchanged - the result is with an error

**Comment by Mematoru23** [comment]
> I will add new facts here :
> 
> @Mematoru23 : indeed, the version BOOST 1.80 mentioned by you is problem-free and there is no need to make any modifications in Core. ( check image ) ![Ashampoo_Snap_štvrtok 8 augusta 2024_17h22m1s](https://private-user-images.githubusercontent.com/7515044/356283383-23f2e596-0f10-458d-9965-8fe6a610bb5e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMzMwNjQsIm5iZiI6MTcyMzEzMjc2NCwicGF0aCI6Ii83NTE1MDQ0LzM1NjI4MzM4My0yM2YyZTU5Ni0wZjEwLTQ1OGQtOTk2NS04ZmU2YTYxMGJiNWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDhUMTU1OTI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmJiNDc5NDE0OWQyOTY1YmMxYjZkMTYwYWU1NGU2NzRhMTUwZWZjZGNjZDRjOTUyNWRhNTQ4NWY4M2Q4OGY2MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.iP5Rw-2KLn0iOFRDeZvCUeR8TOka8bSymYUBcV7w7NM) ![Ashampoo_Snap_štvrtok 8 augusta 2024_17h22m30s](https://private-user-images.githubusercontent.com/7515044/356283403-7dd19d47-6390-4e18-a867-74eb22e010ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMzMwNjQsIm5iZiI6MTcyMzEzMjc2NCwicGF0aCI6Ii83NTE1MDQ0LzM1NjI4MzQwMy03ZGQxOWQ0Ny02MzkwLTRlMTgtYTg2Ny03NGViMjJlMDEwZWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDhUMTU1OTI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTkwM2I1YTBhMjMzYzNhNjMyMDY3OTQzNzZlZGE3YTc0YTEwNWU5MmE1YWYxMjkyYTdiM2MxNDMzZTEzNjVjOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.nHwAQqHln8cPD0GNbKyEna-Vjz7sCOuiHffP_bhXdF0)
> 
> @Shauren : I really tried all the options I could think of to make it work with the BOOST 1.85 version without the need for any modification in Core - I didn't succeed - I really don't know where the problem could be. Well, as I already wrote above, the BOOST 1.80 version works without problems, no modifications in Core are necessary.

I changed to 1.85 and it works perfectly fine so idk what you do wrong.

**Comment by shamage** [comment]
> > I will add new facts here :
> > @Mematoru23 : indeed, the version BOOST 1.80 mentioned by you is problem-free and there is no need to make any modifications in Core. ( check image ) ![Ashampoo_Snap_štvrtok 8 augusta 2024_17h22m1s](https://private-user-images.githubusercontent.com/7515044/356283383-23f2e596-0f10-458d-9965-8fe6a610bb5e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMzMwNjQsIm5iZiI6MTcyMzEzMjc2NCwicGF0aCI6Ii83NTE1MDQ0LzM1NjI4MzM4My0yM2YyZTU5Ni0wZjEwLTQ1OGQtOTk2NS04ZmU2YTYxMGJiNWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDhUMTU1OTI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmJiNDc5NDE0OWQyOTY1YmMxYjZkMTYwYWU1NGU2NzRhMTUwZWZjZGNjZDRjOTUyNWRhNTQ4NWY4M2Q4OGY2MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.iP5Rw-2KLn0iOFRDeZvCUeR8TOka8bSymYUBcV7w7NM) ![Ashampoo_Snap_štvrtok 8 augusta 2024_17h22m30s](https://private-user-images.githubusercontent.com/7515044/356283403-7dd19d47-6390-4e18-a867-74eb22e010ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMzMwNjQsIm5iZiI6MTcyMzEzMjc2NCwicGF0aCI6Ii83NTE1MDQ0LzM1NjI4MzQwMy03ZGQxOWQ0Ny02MzkwLTRlMTgtYTg2Ny03NGViMjJlMDEwZWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDhUMTU1OTI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTkwM2I1YTBhMjMzYzNhNjMyMDY3OTQzNzZlZGE3YTc0YTEwNWU5MmE1YWYxMjkyYTdiM2MxNDMzZTEzNjVjOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.nHwAQqHln8cPD0GNbKyEna-Vjz7sCOuiHffP_bhXdF0)
> > @Shauren : I really tried all the options I could think of to make it work with the BOOST 1.85 version without the need for any modification in Core - I didn't succeed - I really don't know where the problem could be. Well, as I already wrote above, the BOOST 1.80 version works without problems, no modifications in Core are necessary.
> 
> I changed to 1.85 and it works perfectly fine so idk what you do wrong.

This is exactly what I don't know.

**Comment by shamage** [comment]
Finally, success - by manually entering the exact BOOST_DIR path, it started correctly...
I don't understand why with BOOST version 1.80 it finds the path automatically but not with BOOST version 1.85 and it is necessary to enter it manually
![Ashampoo_Snap_štvrtok 8  augusta 2024_18h56m44s](https://github.com/user-attachments/assets/2ccedd68-b098-4195-b818-562f29ed1cc8)

**Comment by shamage** [comment]
Additional info:

So that I don't have to explain the fix of the problem mentioned here (see communication above) to everyone separately (those who turn to me for help) and to avoid unnecessary and difficult searching for the problem on my own. , here is a fix for this problem that works in all circumstances (at least for me and for those who have already done it with my help) and then it is possible to build without errors :

```
# This file is part of the TrinityCore Project. See AUTHORS file for Copyright information
#
# This file is free software; as a special exception the author gives
# unlimited permission to copy and/or distribute it, with or without
# modifications, as long as this notice is preserved.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

set(BOOST_SEARCH_HINTS)
if(WIN32)
  if(DEFINED ENV{BOOST_ROOT})
    set(BOOST_ROOT $ENV{BOOST_ROOT})
  endif()
  if(DEFINED BOOST_ROOT AND MSVC)
    # insert a dot (.) character before last digit of MSVC_TOOLSET_VERSION
    # turn 143 into 14.3
    string(LENGTH "${MSVC_TOOLSET_VERSION}" _BOOST_MSVC_TOOLSET_VERSION_LENGTH)
    math(EXPR _BOOST_MSVC_TOOLSET_VERSION_LENGTH "${_BOOST_MSVC_TOOLSET_VERSION_LENGTH} - 1" OUTPUT_FORMAT DECIMAL)
    string(SUBSTRING "${MSVC_TOOLSET_VERSION}" 0 ${_BOOST_MSVC_TOOLSET_VERSION_LENGTH} _BOOST_MSVC_TOOLSET_VERSION_MAJOR)
    string(SUBSTRING "${MSVC_TOOLSET_VERSION}" ${_BOOST_MSVC_TOOLSET_VERSION_LENGTH} -1 _BOOST_MSVC_TOOLSET_VERSION_MINOR)

    file(TO_CMAKE_PATH "${BOOST_ROOT}" BOOST_ROOT)
    set(BOOST_SEARCH_HINTS "${BOOST_ROOT}/lib${PLATFORM}-msvc-${_BOOST_MSVC_TOOLSET_VERSION_MAJOR}.${_BOOST_MSVC_TOOLSET_VERSION_MINOR}/cmake")

    unset(_BOOST_MSVC_TOOLSET_VERSION_LENGTH)
    unset(_BOOST_MSVC_TOOLSET_VERSION_MAJOR)
    unset(_BOOST_MSVC_TOOLSET_VERSION_MINOR)
  endif()

  set(Boost_USE_STATIC_LIBS        ON)
  set(Boost_USE_MULTITHREADED      ON)
  set(Boost_USE_STATIC_RUNTIME     OFF)
endif()

if (WIN32)
  # On windows the requirements are higher according to the wiki.
  set(BOOST_REQUIRED_VERSION 1.78)
else()
  set(BOOST_REQUIRED_VERSION 1.74)
endif()

# Setting the path to Boost
if(NOT DEFINED ENV{BOOST_ROOT} AND NOT DEFINED Boost_DIR AND NOT DEFINED BOOST_ROOT AND NOT DEFINED BOOSTROOT)
  message(FATAL_ERROR "No BOOST_ROOT environment variable could be found! Please make sure it is set and the points to your Boost installation.")
else()
  if(DEFINED ENV{BOOST_ROOT})
    set(CMAKE_PREFIX_PATH $ENV{BOOST_ROOT})
  elseif(DEFINED BOOST_ROOT)
    set(CMAKE_PREFIX_PATH ${BOOST_ROOT})
  endif()
endif()

# Explicitly add the path to Boost - here enter your path to the Boost folder in quotes
list(APPEND CMAKE_PREFIX_PATH "C:/local/boost_1_86_0")

find_package(Boost ${BOOST_REQUIRED_VERSION}
  REQUIRED
  COMPONENTS
    system
    filesystem
    program_options
    regex
    locale)

if(NOT Boost_FOUND)
  message(FATAL_ERROR "Could not find Boost")
endif()

add_library(boost INTERFACE)

target_link_libraries(boost
  INTERFACE
    ${Boost_LIBRARIES})

target_include_directories(boost
  INTERFACE
    ${Boost_INCLUDE_DIRS})

target_compile_definitions(boost
  INTERFACE
    BOOST_ALL_NO_LIB
    BOOST_CONFIG_SUPPRESS_OUTDATED_MESSAGE
    BOOST_ASIO_NO_DEPRECATED
    BOOST_BIND_NO_PLACEHOLDERS
    BOOST_SYSTEM_USE_UTF8)

if (WITH_BOOST_STACKTRACE AND NOT WIN32)
  message(STATUS "libbacktrace will be linked")

  include(CheckIncludeFile)

  if (BOOST_STACKTRACE_BACKTRACE_INCLUDE_FILE)
    check_include_file("${BOOST_STACKTRACE_BACKTRACE_INCLUDE_FILE}" HAS_BACKTRACE)
    target_compile_definitions(boost
      INTERFACE
        BOOST_STACKTRACE_BACKTRACE_INCLUDE_FILE=${BOOST_STACKTRACE_BACKTRACE_INCLUDE_FILE})
  else()
    check_include_file("backtrace.h" HAS_BACKTRACE)
  endif()

  if (NOT HAS_BACKTRACE)
    message(FATAL_ERROR "Required header 'backtrace.h' not found. If building with a compiler other than GCC, please specify the full path in the CMake option BOOST_STACKTRACE_BACKTRACE_INCLUDE_FILE.")
  endif()

  target_compile_definitions(boost
    INTERFACE
      BOOST_STACKTRACE_USE_BACKTRACE)

  target_link_libraries(boost
    INTERFACE
      backtrace)
endif()

```
if someone doesn't know, the path to repair the folder is: `dep\boost\CMakeLists.txt `


**Attention, I do not claim that it is a perfect fix - it is certainly possible to do it differently, maybe even better, some may not agree, I just want them to be able to build for this component after making the latest change in Core - because as I already mentioned above, without this modification of mine, I have not been able to make any correct construction without errors.**

**Comment by Faq** [comment]
Not sure what you changed in that code as it is not diff, but perhaps you can make PR?

**Comment by shamage** [comment]
> Not sure what you changed in that code as it is not diff, but perhaps you can make PR?

If you mean the final output of the build - then it's the same as before.
Here I wanted to solve the problem with building for myself and others and to avoid the error during the compilation, which I have already mentioned in detail above. Unfortunately, I couldn't find a solution to my problem in any other way, so I was forced to solve it somehow differently (even if it might be uncomfortable).

My changes are not automated and involve a one-time manual user intervention by setting the default path to the Boost folder specifically in the line below the note text:

"Explicitly add the path to Boost - here enter your path to the Boost folder in quotes"

I think PR is not a good idea as this is not an automated system - rather only a possible concept for improvement, with the need to additionally modify this code and improve it so that it works automatically without the need for user intervention to insert or modify anything in this file with no erroneous build result .

Changes I made:

![Ashampoo_Snap_utorok 22  októbra 2024_18h10m1s](https://github.com/user-attachments/assets/1d9443ed-53e6-46d2-9970-94c72d6e1013)


![Ashampoo_Snap_utorok 22  októbra 2024_18h10m47s](https://github.com/user-attachments/assets/cd0348cb-f406-447a-a40f-71610a703bdb)

**Comment by shamage** [comment]
I'll also add another version of the code (very simplified) where the Boost loading also works correctly for me and the final output of the build is error-free:

```
   cmake_minimum_required(VERSION 3.10)
   project(CheckBoost)

   find_package(Boost 1.78 REQUIRED COMPONENTS system filesystem program_options regex locale)

   if(Boost_FOUND)
     message(STATUS "Boost found: ${Boost_VERSION}")
     message(STATUS "Boost include dirs: ${Boost_INCLUDE_DIRS}")
     message(STATUS "Boost libraries: ${Boost_LIBRARIES}")
   else()
     message(FATAL_ERROR "Boost not found")
   endif()
   
```

I deleted the entire content of the code and replaced it with this very simplified code - result: no error

```
1> [CMake] -- Detected 64-bit platform
1> [CMake] -- Detected amd64 processor architecture
1> [CMake] -- MSVC: Minimum version required is 19.32, found 19.38.33141.0 - ok!
1> [CMake] -- MSVC: Enabled increased number of sections in object files
1> [CMake] -- MSVC: Overloaded standard names
1> [CMake] -- MSVC: Disabled NON-SECURE warnings
1> [CMake] -- MSVC: Disabled POSIX warnings
1> [CMake] -- MSVC: Disabled generic compiletime warnings
1> [CMake] -- Found MySQL executable: C:/Program Files/MySQL/MySQL Workbench 8.0/mysql.exe
1> [CMake] 
1> [CMake] * TrinityCore revision   : caccb0619037+ 2024-10-21 02:34:00 +0200 (master branch)
1> [CMake] * TrinityCore buildtype  : Debug
1> [CMake] 
1> [CMake] * Install core to        : F:/source/TrinityCore/out/install/x64-debug
1> [CMake] * Install configs to     : F:/source/TrinityCore/out/install/x64-debug
1> [CMake] 
1> [CMake] * Build world/auth       : Yes (default)
1> [CMake] * Build with scripts     : Yes (static)
1> [CMake] * Build map/vmap tools   : Yes (default)
1> [CMake] * Build unit tests       : No (default)
1> [CMake] * Build core w/PCH       : Yes (default)
1> [CMake] * Build scripts w/PCH    : Yes (default)
1> [CMake] * Show all warnings      : No  (default)
1> [CMake] * Stop build on warning  : No  (default)
1> [CMake] * Use coreside debug     : No  (default)
1> [CMake] * Show source tree       : Yes (hierarchical)
1> [CMake] * Use GIT revision hash  : Yes (default)
1> [CMake] 
1> [CMake] CMake Warning (dev) at dep/boost/CMakeLists.txt:4 (find_package):
1> [CMake]   Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
1> [CMake]   Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
1> [CMake]   command to set the policy and suppress this warning.
1> [CMake] 
1> [CMake]   Environment variable Boost_ROOT is set to:
1> [CMake] 
1> [CMake]     C:\local\boost_1_86_0
1> [CMake] 
1> [CMake]   For compatibility, CMake is ignoring the variable.
1> [CMake] This warning is for project developers.  Use -Wno-dev to suppress it.
```

**Comment by CraftedRO** [comment]
I still think this was user error and you downloaded wrong boost, btw wiki link was updated https://github.com/TrinityCore/tc-wiki/commit/0c359349bdb9d1cf8f06aabe953cb71f98feaca3 / https://trinitycore.info/en/install/requirements/windows
