### ISSUE TITLE
Revamped Commands Suggestion

### ISSUE THREAD

**Issue by Amit86** [TrinityCore/TrinityCore#3013]
Hey
I recently asked around and thought it would be better to post it as a suggestion and see what other people think
At the moment commands table is built in a way that allows us to change security level of commands.
|name|security|help|

allowing us to set security per command helps in some level but many commands now days can be used with with targeting other people and sometimes these commands are set for higher level security just for being a target-able command
i.e:
gm fly on
additem
modify 'anything'
etc, etc
If it was possible to add another column to `command` table and make core check for more than just security, for example:
|name|security|self|help|

More than that, even if the commands themselves could have been added simultaneously / used with a mask for example
additem will be self for security level 1,2 but 3,4,5 can use it with targeting so each command would have 5 lines in command list that would define self/not self use

Personally I think this can take command system to a new level, something that hasn't been done before and can be very usfull for future test and testees

your thoughts? :)

**Comment by Killyana** [comment]
Gm Commands security level were rewritten.
