### ISSUE TITLE
Test master

### ISSUE THREAD

**Issue by jackpoz** [TrinityCore/TrinityCore#30141]
### Description

Test a

### Expected behaviour

Test a

### Steps to reproduce the problem

Test a

### Branch

master

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/b0b81dd31badd6e25f36a74bb519da9097e36ec1

### Operating system

Windows

### Custom changes

None

**Comment by CraftedRO** [comment]
you may also wanna test merge some pull requests buttons too :D
