### ISSUE TITLE
Quests are not Complete/Rewardable - Stuck in Complete Screen

### ISSUE THREAD

**Issue by coreretail6** [TrinityCore/TrinityCore#30167]
### Description

Quests are not Complete/Rewardable - Stuck in Complete Screen
![image](https://github.com/user-attachments/assets/03accd45-8d7e-49f8-8be7-67c5c2f47f9d)

### Expected behaviour

Quests are Complete/Rewardable

### Steps to reproduce the problem

Try to complete any quest.

### Branch

master

### TC rev. hash/commit

df1ec76d54db3a91759fc93f4d6b6828d4ec0f59

### Operating system

Windows Server 2022

### Custom changes

Some custom spawns

**Comment by xuehyc** [comment]
Same question

**Comment by coreretail6** [comment]
I still cant complete quests which needs an item
