### ISSUE TITLE
All quest that require one or more items

### ISSUE THREAD

**Issue by Ryzen-0** [TrinityCore/TrinityCore#30168]
### Description

All quest that require one or more items can't be completed. Stuck in quest givers dialog to complete. 

Quest example
https://www.wowhead.com/quest=26669/in-a-dark-corner

### Expected behaviour

Dialogue should close and the quest complete.

### Steps to reproduce the problem

Gather quest items and speak with giver.

### Branch

master

### TC rev. hash/commit

TrinityCore rev. https://github.com/TrinityCore/TrinityCore/commit/1f952893fc82bc677058737f77de710c426c60ee

### Operating system

Windows 11

### Custom changes

None

**Comment by MaxtorCoder** [comment]
Known issue: #30167

**Comment by xuehyc** [comment]
Same question,works before.
