### ISSUE TITLE
GPL violation, Praevus core

### ISSUE THREAD

**Issue by SODIX** [TrinityCore/TrinityCore#30170]
### Description

There is such a project, called praevius core legion 7.3.5, basically it's a best solution for WoW Legion server, they not hide that they are based on TrininityCore, but they VIOLATE GPL LICENSE, and don't open sources. They based there:
https://discord.gg/single-player-project-291115666097045506

You are big project, please contact with them for violating law.

### Expected behaviour

SinglePlayer Project open sources of their fork.

### Steps to reproduce the problem

Server

### Branch

master

### TC rev. hash/commit

Server

### Operating system

Windows 10

### Custom changes

![234324534534](https://github.com/user-attachments/assets/81d3b9f2-3d69-47cb-8230-85529c740f7b)

**Comment by jackpoz** [comment]
Do they release binaries without the source code or ?

**Comment by CraftedRO** [comment]
Something ordinary nowadays it seems, fsf told me that "leaders" shoud make complaints but noone cared at the right time about this, now it's too late.

**Comment by SODIX** [comment]
> Do they release binaries without the source code or ?

Yes.


> Something ordinary nowadays it seems, fsf told me that "leaders" shoud make complaints but noone cared at the right time about this, now it's too late.

Project MUST complain about license violation, because of future development.

**Comment by SODIX** [comment]
I just mailed RMS.

**Comment by jackpoz** [comment]
What was their response when you asked for a copy of the source code ?

**Comment by acidmanifesto** [comment]
> What was their response when you asked for a copy of the source code ?

He never asked. No record of dms to me, no emails, and this is a whine due to him being muted for spamming the at here by the automod.

But he if it appeases him, the base is on of the branches here.
https://github.com/conan513/SingleCore_TC

@SODIX Have fun with the make believe legal and threats you are sending members in the discord. Be sure to inckude this picture the time you wish to whine instead of actually communicating with people.

![image](https://github.com/user-attachments/assets/6e40d19c-8e76-404c-a958-c96a90dc0de9)

**Comment by acidmanifesto** [comment]
> @acidmanifesto this is 6yr old sources! and project updates in a half of a year!

There are branches there. You do know what branches are?

> PS. I don't care being banned in SPP discord, I just want my GPL edits back into main(merge).

You are welcome to exit the discord as you were never banned but muted for doing a @ here ping by automod.

**Comment by SODIX** [comment]
> Lets just wait to see what RMS says since you wrote who ever that is, since that is your end all.

![RMS](https://github.com/user-attachments/assets/0abd61ee-2547-4bd4-9cde-0f221b3b4de5)

**Comment by lineagedr** [comment]
> > Lets just wait to see what RMS says since you wrote who ever that is, since that is your end all.
> 
> ![RMS](https://private-user-images.githubusercontent.com/22780561/359583828-0abd61ee-2547-4bd4-9cde-0f221b3b4de5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNzU5NjEsIm5iZiI6MTcyNDE3NTY2MSwicGF0aCI6Ii8yMjc4MDU2MS8zNTk1ODM4MjgtMGFiZDYxZWUtMjU0Ny00YmQ0LTljZGUtMGYyMjFiM2I0ZGU1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDE3NDEwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxMmQ1ZTQ3YjEwNTA2NjVhZGYxOTA3MzlkYWRiZWI2NmEzNzZiNWNhOTkwMGU5ZWU4OTdkZWQ2YzViNGI4MGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pdz5pdHiulCdfng1vexLsSBU6TAdNOpwEu6fAcalU24)

What is he gonna do, kidnap m'dic?
