### ISSUE TITLE
ModifierTreeType  typo

### ISSUE THREAD

**Issue by Selenium** [TrinityCore/TrinityCore#30172]
### Description

 https://github.com/TrinityCore/TrinityCore/commit/df511503815b7798c83acbffbb1ce5208f189ce7#diff-f0b21109ad695f08ffa438b97d760312cd4039d52b3d2b2083c14d97ce08bbb6R1749

Value 387 is assigned twice

### Expected behaviour

.

### Steps to reproduce the problem

.

### Branch

master

### TC rev. hash/commit

44719eb78015c2f64e45bc84226ff5337d7ae33d

### Operating system

.

### Custom changes

.

**Comment by acidmanifesto** [comment]
Value 389 as well
