### ISSUE TITLE
Can not Whisper to others

### ISSUE THREAD

**Issue by TheFrozenThr0ne** [TrinityCore/TrinityCore#30182]
### Description

Somehow when i whisper to a player, this message shows up.
![image](https://github.com/user-attachments/assets/b92dc0fa-f3da-428a-9f43-ddc278a9e149)

### Expected behaviour

To be able private chatting

### Steps to reproduce the problem

Whisper to a Player

### Branch

master

### TC rev. hash/commit

TrinityCore rev. 498f32b8f532 2024-08-24 13:14:11 +0200 (master branch) (Win64, Release, Static) (worldserver-daemon)

### Operating system

Windows

### Custom changes

In the moment i discovered the bug, None.
Cuz i check anohter thing about creature boss damage but that may be on a next issue post.

**Comment by Ovahlord** [comment]
Are both accounts you tried to whisper with non-GM accounts?

**Comment by TheFrozenThr0ne** [comment]
Yes.

**Comment by TheFrozenThr0ne** [comment]
It was GM Accounts.

**Comment by Shauren** [comment]
Don't test with GM accounts

Also `.whispers on`
