### ISSUE TITLE
Core/Maps: Breathing bar appearing in Maraudon dungeon

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCore#30205]
### Description

Well since original issue was closed but still valid, I had to reopen it.

![image](https://github.com/TrinityCore/TrinityCore/assets/24683355/0d4b86c0-ce3f-46eb-9da3-07bdd8013fdd)

### Expected behaviour

No breathing bar while on land and not under water.

### Steps to reproduce the problem

.go xyz -1460.429443 2685.802734 77.320488 1
Notice

### Branch

3.3.5

### TC rev. hash/commit

0b10514289a2a9db2f8ff3ef1c535f7d9a77d6a2

### Operating system

Windows 11 x64

### Custom changes

None

**Comment by Ovahlord** [comment]
![Uploading WoWScrnShot_090224_053307.jpg…]()
Valid for Cata Classic too so it's probably broken in master as well

**Comment by shamage** [comment]
This problem is also for masters 
![Ashampoo_Snap_štvrtok 5  septembra 2024_19h6m43s](https://github.com/user-attachments/assets/e5513d8b-d97f-4074-99f7-10fba3fa1a71)

TrinityCore rev. 05fdb6a82ad0 2024-09-05 15:42:59 +0200 (master branch)
