### ISSUE TITLE
Core/Gameobject：Almost all quest interaction objects with gameobject type have lost highlights. Can this issue be fixed?

### ISSUE THREAD

**Issue by carl3175** [TrinityCore/TrinityCore#30213]
### Description

Almost all quest interaction objects with gameobject type have lost highlights. Can this issue be fixed?

### Expected behaviour

All quest interaction objects with gameobject type have highlights when doing quests

### Steps to reproduce the problem

many

### Branch

master

### TC rev. hash/commit

TrinityCore rev. 3bbb6eb20f4e 2024-09-04 21:09:51 +0200 (11.0.2.56421 branch) (Windows, AMD64, RelWithDebInfo, Static) (worldserver-daemon)

### Operating system

Win11 23H2

### Custom changes

None

**Comment by shamage** [comment]
Could you give at least one concrete example where the problem you mentioned is happening?
( map, zoneid, areaid, specific location, GO id - GUID ... etc. )

**Comment by aquadeus** [comment]
https://github.com/TrinityCore/TrinityCore/pull/30123

**Comment by carl3175** [comment]
Quest 28608(The Shadow Grave)
gameobject_template.entry in (207255,207256)

#30123 should have resolved this issue, hope it to be merged as soon as possible.
Thanks for your reply~
