### ISSUE TITLE
FreeBSD 14.1 Compile Issues (Clang and GCC)

### ISSUE THREAD

**Issue by Espionage724** [TrinityCore/TrinityCore#30218]
### Description

Clang: https://gist.github.com/Espionage724/9d247e51cf43890e40b0acf74e0114a0

GCC: https://gist.github.com/Espionage724/e365498a90176191b15031bff443ef22

### Expected behaviour

No compile errors

### Steps to reproduce the problem

```
pkg install git-lite readline boost-all mariadb114-client cmake bzip2 gcc14
```

```
cd ~ && mkdir -p ~/'Projects' && rm -Rf ~/'Projects/trinity-335/src' && git clone --branch '3.3.5' --depth '1' --recurse-submodules 'https://github.com/TrinityCore/TrinityCore.git' ~/'Projects/trinity-335/src' && sync
```

```
rm -Rf ~/'Projects/trinity-335/build' ~/'Projects/trinity-335/run' && mkdir -p ~/'Projects/trinity-335/build' ~/'Projects/trinity-335/run' && cd ~/'Projects/trinity-335/build' && cmake ~/'Projects/trinity-335/src' -DCMAKE_INSTALL_PREFIX=~/'Projects/trinity-335/run' -DCMAKE_BUILD_TYPE='Release' -DTOOLS='1' && sync && make -j '8' install && sync
```

```
CC='/usr/local/bin/gcc14' CXX='/usr/local/bin/g++14' -DUSE_COREPCH='0' 
```

### Branch

3.3.5

### TC rev. hash/commit

b5ebf0281d471801b983b753f8f635271d4cffc6

### Operating system

FreeBSD 14.1

### Custom changes

None

**Comment by CraftedRO** [comment]
3.3.5 but hash you provided is for master ?

**Comment by Espionage724** [comment]
> 3.3.5 but hash you provided is for master ?

My bad :p I'm definitely using 3.3.5 though and updated the hash

**Comment by Shauren** [comment]
FreeBSD is to blame here - it picks up your system fmt (/usr/local/include/fmt) instead of the one that TrinityCore supports that lives inside our repository

**Comment by paulfloyd** [comment]
Doesn't this comflict with any system that has fmtlib installed?

**Comment by Espionage724** [comment]
I'm re-trying this now and it's compiling past the point previous, but I might have caused the issue myself :p 

I was using `mariadb114-client` which pulls in `libfmt` as a dependency. Switched to `mysql84-client` (no `libfmt` dep) and compiling is still happening around 48% so far!

Which I guess now has me retract what I said about dropping MariaDB support https://github.com/TrinityCore/TrinityCore/pull/29960#issuecomment-2275939610

**Comment by Espionage724** [comment]
Looks all good! Used Clang and LibreSSL

![wowtcfreebsd](https://github.com/user-attachments/assets/088d7f1f-5d7c-4a3e-be30-66569b2d836d)
