### ISSUE TITLE
[MSVC] [WINDOWS]VMapAssembler.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: bool __cdecl std::_Tree<class std::_Tmap_traits<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class boost::program_options::variable_value,struct std::less<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >,class std::allocator<struct std::pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const ,class boost::program_options::variable_value> >,0> >::contains(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)const "

### ISSUE THREAD

**Issue by liukai12345614** [TrinityCore/TrinityCore#30227]
### Description

[MSVC] [WINDOWS] VMapAssembler.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: bool __cdecl std::_Tree<class std::_Tmap_traits<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class boost::program_options::variable_value,struct std::less<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >,class std::allocator<struct std::pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const ,class boost::program_options::variable_value> >,0> >::contains(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)const " (__imp_?contains@?$_Tree@V?$_Tmap_traits@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@Vvariable_value@program_options@boost@@U?$less@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@V?$allocator@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@Vvariable_value@program_options@boost@@@std@@@2@$0A@@std@@@std@@QEBA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@2@@Z) referenced in function "class std::optional<int> __cdecl HandleArgs(int,char * * const,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *,unsigned int *)" (?HandleArgs@@YA?AV?$optional@H@std@@HQEAPEADPEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@2@1PEAI@Z)
.\vmap4assembler.exe : fatal error LNK1120: 1 unresolved externals. It can be reproduced on this commit 8ec9b58. Could you please help and take a look at this? Thanks in advance!

### Expected behaviour

Build Success

### Steps to reproduce the problem

1. git -C "C:\gitP" clone --no-checkout https://github.com/TrinityCore/TrinityCore TrinityCore\TrinityCore
2. git -C "C:\gitP\TrinityCore\TrinityCore" checkout 8ec9b58
3. Open a VS2022 x64 cmd
4. set VSCMD_SKIP_SENDTELEMETRY=1 & "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" -host_arch=amd64 -arch=amd64 & set _CL_= /Bcapture_repro C:\logs\TrinityCore\preprocessed_repro_build & set _LINK_= /onfailrepro:C:\logs\TrinityCore\link_repro_build
5. set PATH=C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;%PATH%
6. cd /d C:\gitP\TrinityCore\TrinityCore\build_amd64
7. set MYSQL_ROOT=C:\gitP\TrinityCore\TrinityCore\mysql\mysql-5.7.44-winx64
8. cmake -G "Visual Studio 17 2022" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.22621.0 -DCMAKE_TOOLCHAIN_FILE=C:\gitP\Microsoft\vcpkg\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows -DSCRIPTS=dynamic -DTOOLS=True -DCMAKE_BUILD_TYPE=Release .. 2>&1
9. msbuild /maxcpucount:8 /p:Platform=x64 /p:Configuration=Release TrinityCore.sln /t:Rebuild 2>&1

### Branch

master

### TC rev. hash/commit

8ec9b58

### Operating system

Windows Server 2022 Datacenter x64

### Custom changes

None

**Comment by Shauren** [comment]
Using boost in shared variant (dlls) is broken (not our bug), either use x64-windows-static triplet or abandon vcpkg and use prebuilt boost binaries like our wiki recommends

**Comment by CraftedRO** [comment]
Pro tip: next time try not to cover half of the screen with issue title.

**Comment by liukai12345614** [comment]
> Using boost in shared variant (dlls) is broken (not our bug), either use x64-windows-static triplet or abandon vcpkg and use prebuilt boost binaries like our wiki recommends

Hi Shauren, I try to use command "cmake -G "Visual Studio 17 2022" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.22621.0 -DCMAKE_TOOLCHAIN_FILE=C:\gitP\Microsoft\vcpkg\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows-static -DSCRIPTS=static -DTOOLS=True -DCMAKE_BUILD_TYPE=Release .. 2>&1" and "cmake -G "Visual Studio 17 2022" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.22621.0 -DCMAKE_TOOLCHAIN_FILE=C:\gitP\Microsoft\vcpkg\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows-static -DTOOLS=True -DCMAKE_BUILD_TYPE=Release .. 2>&1" to config TrinityCore. It report error "boost_filesystem-vc143-mt-x64-1_85.lib(path_traits.cpp.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in TileAssembler.obj [C:\gitP\TrinityCore\TrinityCore\build_amd64\src\tools\vmap4_assembler\vmap4assembler.vcxproj]". Could you please help take a look this issue? Thanks in adcance!

**Comment by Shauren** [comment]
You need VCPKG_CRT_LINKAGE=dynamic
