### ISSUE TITLE
Spells/Mage: Ice Block cannot be used

### ISSUE THREAD

**Issue by Polytrih** [TrinityCore/TrinityCore#30241]
### Description

The Ice Block spell cannot be casted as it shows an "Immune" error message.
https://www.wowhead.com/spell=45438/ice-block

### Expected behaviour

Ice Block should freeze the character and made it immune to all attacks and damage.

### Steps to reproduce the problem

1. Create a Mage
2. Select Frost specialization
3. Select "Ice Block" from the talent tree
4. Cast Ice Block

### Branch

master

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/4a574c0ce1149825c0fba77b0bea60608cbc470f

### Operating system

Windows 10 x64

### Custom changes

None

**Comment by Naddley** [comment]
Duplicate: https://github.com/TrinityCore/TrinityCore/issues/28698
