### ISSUE TITLE
Repair rogue's stealth

### ISSUE THREAD

**Issue by yaniel1230** [TrinityCore/TrinityCore#30246]
not working

### Expected behaviour

Make it invisible that works

### Steps to reproduce the problem

https://www.wowhead.com/es/spell=1784/sigilo

### Branch

master

### TC rev. hash/commit

I don't know

### Operating system

Windows 10

### Custom changes

I don't know

**Comment by CraftedRO** [comment]
wait, now rogue Stealth does make him invincible, interesting

**Comment by yaniel1230** [comment]
> Espera, ahora el sigilo del pícaro lo hace invencible, interesante.

You understand what I'm telling you, that doesn't work.
