### ISSUE TITLE
word of shadows death

### ISSUE THREAD

**Issue by yaniel1230** [TrinityCore/TrinityCore#30248]
### Description

when you activate it it kills you it only happens with low level.
![IMG_20240916_164547](https://github.com/user-attachments/assets/32b2b4a6-8a88-409c-8c2f-2403cdee6cc4)

### Expected behaviour

https://www.wowhead.com/es/spell=32379/palabra-de-las-sombras-muerte

### Steps to reproduce the problem

https://www.wowhead.com/es/spell=32379/palabra-de-las-sombras-muerte

### Branch

master

### TC rev. hash/commit

https://www.wowhead.com/es/spell=32379/palabra-de-las-sombras-muerte

### Operating system

10 x64

### Custom changes

not working

**Comment by CraftedRO** [comment]
https://github.com/TrinityCore/TrinityCore/commit/33507e010774d74690169558f6a12aa76c29b052
