### ISSUE TITLE
DB/Misc: Fix Alliance GY when dying in Thunder Bluff

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCore#30272]
### Description

Add Bloodhoof Village graveyard and remove wrong Ratchet one when dying in Thunder Bluff as Alliance, as tested on cata ptr 4.4.1.56574 here:
https://www.youtube.com/watch?v=Ed5WpTl7rB8

To test:
.tele thunderbluff
.die

### SQL fix

```sql
-- Deletes Ratchet as Ally GY when dying in Thunder Bluff
DELETE FROM `graveyard_zone` WHERE `ID`= 249 AND `GhostZone`= 1638;
-- Adds Bloodhoof Village as Ally GY when dying in Thunder Bluff
DELETE FROM `graveyard_zone` WHERE `ID`= 89 AND `GhostZone`= 1638;
INSERT INTO `graveyard_zone` (`ID`, `GhostZone`, `Faction`, `Comment`) VALUES
(89, 1638, 469, 'Mulgore, Bloodhoof Village GY - Mulgore');
```

### Branch

3.3.5

### TC rev. hash/commit

b18ba61140cbb2c26eb5d006826eb61097f44726

**Comment by acidmanifesto** [comment]
> Add Bloodhoof Village graveyard and remove wrong Ratchet one when dying in Thunder Bluff as Alliance, as tested on cata ptr 4.4.1.56574 here: https://www.youtube.com/watch?v=Ed5WpTl7rB8

 New meaning to death from above.
