### ISSUE TITLE
Bags have an incorrect number of free slots and cannot be used

### ISSUE THREAD

**Issue by shamage** [TrinityCore/TrinityCore#30280]
### Description

When you buy a bag or just want to see how much free space it provides, instead of the correct value, it shows the value zero - it is unusable. The second picture is a summary of the bags that are defective .
![Ashampoo_Snap_nedeľa 29  septembra 2024_17h30m59s](https://github.com/user-attachments/assets/29e26fac-ae72-48d7-9693-901d4ce5e108)
![Ashampoo_Snap_nedeľa 29  septembra 2024_17h35m4s](https://github.com/user-attachments/assets/e87896ce-a295-4440-a3d0-4ce258f3646a)

### Expected behaviour

Bags should be usable with the exact number of free positions for storing things.

### Steps to reproduce the problem

1. enter .additem 221603 (or use any value from the second image)
2. see item / item info
3. try the item and see if it offers you free positions

### Branch

master

### TC rev. hash/commit

TrinityCore rev. be04c17916aa 2024-09-26 19:36:49 +0200 (master branch) 

### Operating system

Win 11 Pro

### Custom changes

none

**Comment by Shauren** [comment]
This is not a bug. Those are some placeholder test items only, they really have 0 slots in ItemSparse.db2
https://www.wowhead.com/item=221611/leatherworking-bag

**Comment by CraftedRO** [comment]
They added it directly deprecated :trollface:

![Captură de ecran 2024-09-29 195600](https://github.com/user-attachments/assets/decc8292-8567-4bf6-88d6-75b3f5b7fa72)

**Comment by shamage** [comment]
> They added it directly deprecated :trollface:
> 
> ![Captură de ecran 2024-09-29 195600](https://private-user-images.githubusercontent.com/24683355/371872844-decc8292-8567-4bf6-88d6-75b3f5b7fa72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2MzIxNjEsIm5iZiI6MTcyNzYzMTg2MSwicGF0aCI6Ii8yNDY4MzM1NS8zNzE4NzI4NDQtZGVjYzgyOTItODU2Ny00YmY2LTg4ZDYtNzViM2Y1YjdmYTcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI5VDE3NDQyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5ZmUyZTQ5NWYwZTkzYjE4ZjU2NjRhYTRmNTMyMDk4NTZjYmNhZmIxZDAzYzVhYmJiMDFjM2E1YTk4ZTMwNWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fOOPdD6KcDz5olnJXJO6QCSK9SoGN8NnWn-7P8XP3GE)

Oops - I didn't check this. It is extremely funny - they write Added in patch 11.0.0.55793 and it is already Obsolete - unusable.
