### ISSUE TITLE
2024_09_26_00_auth.sql: Access denied; you need (at least one of) the SYSTEM_USER privilege(s) for this operation

### ISSUE THREAD

**Issue by Espionage724** [TrinityCore/TrinityCore#30287]
### Description

```
Using SSL version: OpenSSL 3.2.2 4 Jun 2024 (library: OpenSSL 3.2.2 4 Jun 2024)
Using Boost version: 1.83.0
Updating Auth database...
>> Applying update "2024_09_26_00_auth.sql" 'E37C399'...
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1227 (42000) at line 6 in file: '/home/espionage724/Projects/trinity-335/src/sql/updates/auth/3.3.5/2024_09_26_00_auth.sql': Access denied; you need (at least one of) the SYSTEM_USER privilege(s) for this operation
Applying of file '/home/espionage724/Projects/trinity-335/src/sql/updates/auth/3.3.5/2024_09_26_00_auth.sql' to database 'authserver' failed! If you are a user, please pull the latest revision from the repository. Also make sure you have not applied any of the databases with your sql client. You cannot use auto-update system and import sql files from TrinityCore repository with your sql client. If you are a developer, please fix your sql query.
Could not update the Login database, see log for details.
```

### Expected behaviour

authserver and worldserver do the update sqls and start fine

### Steps to reproduce the problem

1. Start authserver and worldserver
2. Run into error

### Branch

3.3.5

### TC rev. hash/commit

0a059c7c7182b94c7921862688a8a0bbd34ff91e

### Operating system

Fedora Linux 41 (Workstation Edition Prerelease)

### Custom changes

None

**Comment by Aokromes** [comment]
fix your permisions.

**Comment by Shauren** [comment]
This issue only happens when you import full database as a different user than the one that later runs sql updates

**Comment by Espionage724** [comment]
Is this the result of a relatively recent change or something MySQL 8.4 (not MariaDB) specific?

I'm trying to understand `SYSTEM_USER`, but never had to use that years ago up until recent, and it seems odd security-wise to have to set that on limited `trinity` accounts that already have the `GRANT ALL` on the limited `trinity` users?

**Comment by Shauren** [comment]
> Is this the result of a relatively recent change or something MySQL 8.4 (not MariaDB) specific?
> 
> I'm trying to understand `SYSTEM_USER`, but never had to use that years ago up until recent, and it seems odd security-wise to have to set that on limited `trinity` accounts that already have the `GRANT ALL` (assumed full-access) on the limited `trinity` dbs?

Just don't import full db as root

**Comment by Shauren** [comment]
And yes, this is new in mysql 8.0.16

**Comment by Espionage724** [comment]
Dropped-in MariaDB 11.5 server with the same database/user permissions and that problem didn't happen (SQL updates applied from auth/worldservers no problem)



> > Is this the result of a relatively recent change or something MySQL 8.4 (not MariaDB) specific?
> > I'm trying to understand `SYSTEM_USER`, but never had to use that years ago up until recent, and it seems odd security-wise to have to set that on limited `trinity` accounts that already have the `GRANT ALL` (assumed full-access) on the limited `trinity` dbs?
> 
> Just don't import full db as root

I restore authserver and characters databases from .sql backup and import them through root, but later set the trinity users to those dbs with GRANT ALL. I figure since I'm restoring the backup myself that it should be done from the root account (I'm doing the restore initially vs TC doing anything with it), and expect TC to do whatever it needs to do with those dbs afterwards.
