### ISSUE TITLE
DB/Loot: Fix thorium ore prospection sometimes resulting in 0 items

### ISSUE THREAD

**Issue by Odyssey** [TrinityCore/TrinityCore#30284]
### Description

> Patch 2.1.0 (2007-05-22) Prospecting now always yields at least 1 gem

```sql
SELECT * FROM `prospecting_loot_template` WHERE `entry`=10620;
```

The non-referenced prospecting loot items for thorium ore are set to a combined chance of 90%, which sometimes causes thorium ore prospections to yield no loot if both the referenced and non-referenced chances miss.

Dividing the remaining 10% amongst them adds up to 100% and guarantees loot while still keeping the same relative chances for every gem to come out.

_**If you want to reproduce the issue yourself, you can do the following:**_
* .learn 31252
* .setskill 755 250
* .add 10620 600
* Disable autoloot and keep using the following macro until eventually you get an empty window with no loot
```
#showtooltip Prospecting
/cast Prospecting
/use Thorium ore
```

### SQL fix

```sql
-- Raise the total combined chance of prospecting gems from thorium ore from 90 to 100%
UPDATE `prospecting_loot_template` SET `Chance`=`Chance`+2 WHERE `Entry`=10620 AND `Reference`=0;
```

### Branch

3.3.5

### TC rev. hash/commit

c5663d554eb015e4f50d6e8f823781b09ff8a4c8

**Comment by CraftedRO** [comment]
here's the proof video on latest 0a059c7c7182b94c7921862688a8a0bbd34ff91e,that confirm you can get no loot: https://youtu.be/Np5PPHqE-q8

**Comment by meji46** [comment]
Rather than increasing chance, we can do this (implicit equal chance)

```sql
UPDATE `prospecting_loot_template` SET `Chance`=0 WHERE `Entry`=10620 AND `ItemId` IN (12361, 12364, 12799, 12800);
```
