### ISSUE TITLE
DB/Creature: Replace wrong fixed orientation value with default NULL

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCore#30332]
### Description

There are few (405) lines that have most likely wrong orientation values like 100 or 255, this is most likely wrong and have to be NULL.

Tested ingame.

### SQL fix

```sql
-- Replace wrong 100 and 255 fixed orientation value with default NULL
UPDATE `waypoint_data` SET `orientation`=NULL WHERE `orientation`=100 OR `orientation`=255;
```

### Branch

3.3.5

### TC rev. hash/commit

af1f9c1edda80fcdc7cd07d70f9acb647b81808b

**Comment by Aokromes** [comment]
how about simply...

```
-- Replace wrong 100 and 255 fixed orientation value with default NULL
UPDATE `waypoint_data` SET `orientation`=NULL WHERE `orientation`>7;

**Comment by CraftedRO** [comment]
that shoud work too
