### ISSUE TITLE
The Far Watch Offensive

### ISSUE THREAD

**Issue by infidelus** [TrinityCore/TrinityCore#30337]
### Description

[Quest](https://www.wowhead.com/quest=872/the-far-watch-offensive)

All mobs are level 1 and none drop any loot, including the required [Kreenig Snarlsnout's Tusk](https://www.wowhead.com/item=5063/kreenig-snarlsnouts-tusk)

### Expected behaviour

Mobs should be at player level and presumably drop random loot.  Kreenig Snarlsnout's tusk should be available to loot once he has been killed.

### Steps to reproduce the problem

Kill five Razormane Defenders and Thornweavers
Loot Kreenig Snarlsnout's tusk to complete quest

### Branch

master

### TC rev. hash/commit

TrinityCore rev. 00d12f8b8d25 2024-10-07 21:20:00 +0200 (master branch) (Linux, x86_64, RelWithDebInfo, Static)

### Operating system

Linux Mint 22

### Custom changes

None

**Comment by carl3175** [comment]
Set creature_template_defficulty.DifficultyID to modify level of the creature, add creature_loot_template to set loot of the creature.

**Comment by Naddley** [comment]
I allready prepared a Fix for this. This happens cause of a second entry of creature_template_difficulty.
