### ISSUE TITLE
Loading pet level stats... Causing some table errors on startup

### ISSUE THREAD

**Issue by TheFrozenThr0ne** [TrinityCore/TrinityCore#30341]
### Description

Getting spamed with errors on server startup

Loading pet level stats...
Unused (> MaxPlayerLevel in worldserver.conf) level 81 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 82 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 83 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 84 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 85 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 81 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 82 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 83 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 84 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 85 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 81 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 82 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 83 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 84 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 85 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 81 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 82 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 83 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 84 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 85 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 81 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 82 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 83 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 84 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 85 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 81 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 82 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 83 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 84 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 85 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 81 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 82 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 83 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 84 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 85 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 81 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 82 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 83 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 84 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 85 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 81 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 82 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 83 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 84 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 85 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 81 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 82 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 83 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 84 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 85 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 81 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 82 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 83 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 84 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 85 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 81 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 82 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 83 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 84 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 85 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 81 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 82 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 83 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 84 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 85 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 81 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 82 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 83 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 84 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 85 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 81 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 82 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 83 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 84 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 85 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 81 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 82 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 83 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 84 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 85 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 81 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 82 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 83 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 84 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 85 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 81 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 82 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 83 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 84 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 85 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 81 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 82 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 83 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 84 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 85 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 81 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 82 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 83 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 84 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 85 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 81 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 82 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 83 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 84 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 85 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 81 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 82 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 83 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 84 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 85 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 81 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 82 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 83 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 84 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 85 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 81 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 82 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 83 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 84 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 85 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 81 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 82 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 83 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 84 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 85 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 81 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 82 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 83 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 84 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 85 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 81 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 82 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 83 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 84 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 85 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 81 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 82 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 83 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 84 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 85 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 81 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 82 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 83 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 84 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 85 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 81 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 82 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 83 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 84 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 85 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 81 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 82 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 83 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 84 in `pet_levelstats` table, ignoring.
Unused (> MaxPlayerLevel in worldserver.conf) level 85 in `pet_levelstats` table, ignoring.

### Expected behaviour

Not getting errors on startup from this table.

### Steps to reproduce the problem

Startup the server and check logs.

### Branch

master

### TC rev. hash/commit

TrinityCore rev. d13501f15736+ 2024-10-11 11:26:37 +0200 (master branch) (Windows, AMD64, Release, Static) (worldserver-daemon)

### Operating system

Windows Server 2022

### Custom changes

Solo LFG
1 Custom Hook
Few Scripts

**Comment by CraftedRO** [comment]
probably all values should be decreased with a specified percentage or overwritten with new sniffed ones
