### ISSUE TITLE
DB / NPC : Dorak - add missing waypoint

### ISSUE THREAD

**Issue by shamage** [TrinityCore/TrinityCore#30360]
### Description

- add missing waypoints
- [Dorak](https://www.wowhead.com/npc=34284/dorak)

### SQL fix

```sql
SET @ACGUID := 304070;
SET @PATH := @ACGUID * 100;
DELETE FROM `waypoint_path` WHERE `PathId`=@PATH;
INSERT INTO `waypoint_path` (`PathId`, `MoveType`, `Flags`, `Comment`) VALUES
(@PATH, 0, 0, 'Dorak - Northen Barrens');

DELETE FROM `waypoint_path_node` WHERE `PathId`= @PATH;
INSERT INTO `waypoint_path_node` (`PathId`, `NodeId`, `PositionX`, `PositionY`, `PositionZ`, `Orientation`, `Delay`) VALUES
(@PATH, 0, 69.16949, -3618.468, 28.68636, 3.612831592559814453, 4258),
(@PATH, 1, 66.85916, -3643.826, 27.43744, NULL, 0),
(@PATH, 2, 66.50076, -3653.195, 27.26537, 2.670353651046752929, 5482);

UPDATE `creature` SET `position_x`= 66.85916, `position_y`= -3643.826, `position_z`= 27.43744, `orientation`= 0, `MovementType`= 2 WHERE `guid`= @ACGUID;

DELETE FROM `creature_addon` WHERE `guid`= @ACGUID;
INSERT INTO `creature_addon` (`guid`, `PathId`, `mount`, `StandState`, `SheathState`, `emote`, `visibilityDistanceType`, `auras`) VALUES
(@ACGUID, @PATH, 0, 0, 1, 0, 0, '');
```

### Branch

master

### TC rev. hash/commit

[77b8066](https://github.com/TrinityCore/TrinityCore/commit/77b80661474d26e38c19bb8b1fbc150858d9ce38)

**Comment by Naddley** [comment]
Why do you update the Template to use SAI but there is no Script included? :D
Also would be nice if possible to use our current codestyle for waypoints.

**Comment by shamage** [comment]
>Why do you update the Template to use SAI but there is no Script included? :D

Deleted - it shouldn't have been there

>Also would be nice if possible to use our current codestyle for waypoints.

If I need to correct it, I just don't know exactly what you mean - just give me an example

**Comment by meji46** [comment]
> > Also would be nice if possible to use our current codestyle for waypoints.
> 
> If I need to correct it, I just don't know exactly what you mean - just give me an example
https://github.com/TrinityCore/TrinityCore/commit/a9e4f5a9ceaf88dc9de8a07b6ed3f1d114553899#diff-678dc3cc26ef0e36ac32c00e52273f60a9f6029f13f565e219975736bb4b3b42R5

**Comment by shamage** [comment]
Updated

**Comment by Naddley** [comment]
struct is still not updated :)

**Comment by Naddley** [comment]
Also your delays are way to high and wrong for the Path

**Comment by shamage** [comment]
> Also your delays are way to high and wrong for the Path

You are indeed right, I had to sniff again because the previous sniff after extracting wpp gave me strange data.

I will add the NPC orientation later.

**Comment by shamage** [comment]
NPC orientation added
