### ISSUE TITLE
dbc - Incorrect layout hash (possibly wrong client version)

### ISSUE THREAD

**Issue by shamage** [TrinityCore/TrinityCore#30380]
### Description

After extraction using "mapextractor" from the client version 11.0.5.57212 which extracts the dbc folder and after running world.exe reports an error: "Incorrect layout hash..."

```
Initialize data stores...
Incorrect layout hash in ./dbc/enUS/BroadcastTextDuration.db2, expected 0xE60CAC24, got 0x9CBEE39C (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/ChrCustomizationOption.db2, expected 0x3F9B06FB, got 0x1EB3451E (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/Difficulty.db2, expected 0xDDC70D8E, got 0x017A4F91 (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/LFGDungeons.db2, expected 0xBA9CE7CB, got 0x9274FE74 (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/SpellMisc.db2, expected 0x4823459D, got 0xB2E0F1E4 (possibly wrong client version)
Unable to load db2 files for enUS locale specified in DBC.Locale config!
```
More info : [link](https://gist.github.com/shamage/db34c76725a01b959014e53aec48321d)

All entries in the dbc folder point to version 11.0.5.56865 instead of the current retail version, even though the entire retail folder is guaranteed to be up to date.
![Ashampoo_Snap_nedeľa 27  októbra 2024_10h53m59s](https://github.com/user-attachments/assets/e36d5214-d826-4c16-a2cf-c348f6834a80)

### Expected behaviour

The world should start without error

### Steps to reproduce the problem

1. Extract the current retail version
2. build the current TC version
3. run world.exe

### Branch

master

### TC rev. hash/commit

TrinityCore rev. 6bdae6999f3e+ 2024-10-27 01:27:26 +0200 (master branch) 

### Operating system

Win 11 Pro

### Custom changes

none

**Comment by MaxtorCoder** [comment]
11.0.5 is not supported.

**Comment by shamage** [comment]
> 11.0.5 is not supported.

So which version is supported? Because the older (previous) version still worked for me

**Comment by MaxtorCoder** [comment]
> > 11.0.5 is not supported.
> 
> 
> 
> So which version is supported? Because the older (previous) version still worked for me

I mean.. Literally the previous version?? 11.0.2?? If github repo description does not say the last version it's supported it's not smart to try it.

**Comment by shamage** [comment]
> > > > 11.0.5 is not supported.
> > > 
> > > 
> > > So which version is supported? Because the older (previous) version still worked for me
> > 
> > 
> > I mean.. Literally the previous version?? 11.0.2?? If github repo description does not say the last version it's supported it's not smart to try it.
> 
> you need new glasses https://i.imgur.com/I6YB2mo.png

yes you're right, my fault for not taking into account the stated supported version and trying something new
