### ISSUE TITLE
Client Extractor Tool not working

### ISSUE THREAD

**Issue by biocatalyst** [TrinityCore/TrinityCore#30389]
### Description

When you go to run the extractor tool, extractor.bat, provided in the trinitycore master repository clone, in the client folder with the relevant mapextractor.exe, mmaps_generator.exe, vmap4assembler.exe and vmap4extractor.exe there, it doesn't run anything, it exits.

### Expected behaviour

Expected behaviour is for it to extract the files.

### Steps to reproduce the problem

Step 1: Copy "extractor.exe" from "<Repo Clone>\contrib" to the client root folder, eg: "D:\Game\Private"
Step 2: Copy "mapextractor.exe", "mmaps_generator.exe", "vmap4assembler.exe" and "vmap4extractor.exe" from the "<Build>\bin\Release" to the client root folder, eg: "D:\Game\Private"
Step 3: Run "extractor.exe"
Step 4: Select any option (1 to 4)
Result: Nothing happens

### Branch

master

### TC rev. hash/commit

214580d345616b492ce9654ef30c1a436d224b25

### Operating system

Windows Server 2022

### Custom changes

None

**Comment by Shauren** [comment]
No issues with extractors on my end (not using script)
