### ISSUE TITLE
DB/Creature: Icecrown - Ymirheim Updates v1

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCore#30394]
### Description

Few Icecrown - Ymirheim Updates based on sniffs.
Tested ingame.

### SQL fix

```sql
https://gist.github.com/CraftedRO/bc67e4cdf7b53765aa38c36e9ee291a1
```

### Branch

3.3.5

### TC rev. hash/commit

61803931637ecddb5d4dfc966bb81484fa95b536

**Comment by Rushor** [comment]
This is really nice content man! <3
