### ISSUE TITLE
Fix startup errors from Issue #30270

### ISSUE THREAD

**Issue by malcrom** [TrinityCore/TrinityCore#30404]
### Description

Startup errors were created after copying chest spawn locations from Mangos that were missing rotaions. Rotations are from 1.15.4 sniff

### SQL fix

```sql
UPDATE `gameobject` SET `rotation2`=-0.99026775360107421, `rotation3`=0.139175355434417724 WHERE `guid` IN (13553);
UPDATE `gameobject` SET `rotation2`=-0.13917255401611328, `rotation3`=0.990268170833587646 WHERE `guid` IN (13563);
```

### Branch

3.3.5

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/0b10514289a2a9db2f8ff3ef1c535f7d9a77d6a2

**Comment by CraftedRO** [comment]
do we have parser for 1.15.4 ?

**Comment by malcrom** [comment]
> do we have parser for 1.15.4 ?

Was updated today. Killerwife added it.

**Comment by CraftedRO** [comment]
oh nice
