### ISSUE TITLE
Extractor/Vmaps: Crashes, when I try to extract the vmaps.

### ISSUE THREAD

**Issue by osleyder85** [TrinityCore/TrinityCore#30414]
### Description

Crashes: When I try to extract the vmaps, it closes the vmap4extractor.exe file, and does not extract all the vmaps. [Crashlog](https://gist.github.com/osleyder85/40ba8b6491f803bf1b7cdec528de9aa3)

### Expected behaviour

Properly extract all vmpas

### Steps to reproduce the problem

1. Run mapextractor.exe file
2. Run vmap4extractor.exe file

### Branch

master

### TC rev. hash/commit

Revision: TrinityCore rev. 783693a0a07a 2024-11-09 18:36:33 +0100 (master branch) (Windows, AMD64, RelWithDebInfo, Static)

*** Hardware ***
Processor: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
Number Of Processors: 12
Physical Memory: 16628420 KB (Available: 9852376 KB)
Commit Charge Limit: 21212336 KB

Using SSL version: OpenSSL 3.4.0 22 Oct 2024 (library: OpenSSL 3.4.0 22 Oct 2024)
Using Boost version: 1.86.0

### Operating system

Microsoft Windows 11 Pro

### Custom changes

None

**Comment by Shauren** [comment]
Crash? No log? Doubt

**Comment by Shauren** [comment]
This doesn't make sense to me

Do you have some modified client?

My file id 973469 is `item/objectcomponents/weapon/staff_2h_nerzhul_d_01.m2` which doesn't have `HSXG` anywhere inside it (thats what the extractor found in yours)

**Comment by osleyder85** [comment]
> This doesn't make sense to me
> 
> Do you have some modified client?
> 
> My file id 973469 is `item/objectcomponents/weapon/staff_2h_nerzhul_d_01.m2` which doesn't have `HSXG` anywhere inside it (thats what the extractor found in yours)

Let the client update again...

**Comment by osleyder85** [comment]
> This doesn't make sense to me
> 
> Do you have some modified client?
> 
> My file id 973469 is `item/objectcomponents/weapon/staff_2h_nerzhul_d_01.m2` which doesn't have `HSXG` anywhere inside it (thats what the extractor found in yours)

With that client I play on the Blizzard.

**Comment by osleyder85** [comment]
Problem solved
