### ISSUE TITLE
Core/Loot: The Loot System doesn't seem to be working properly

### ISSUE THREAD

**Issue by carl3175** [TrinityCore/TrinityCore#30418]
### Description

According to the preset setting is to drop 1 to 5 items, but the result is always dropped 5 items.

![01](https://github.com/user-attachments/assets/9b010457-8a48-407f-96e5-14d2995389e1)
![02](https://github.com/user-attachments/assets/a767cbe4-43da-414f-a09a-c43f9dfefecf)
![03](https://github.com/user-attachments/assets/5d9da83e-9e2c-4d47-be10-9f56b8e0326c)
![04](https://github.com/user-attachments/assets/c6dc032b-8049-4891-8303-90776fe43a43)

### Expected behaviour

It should be dropped according to the preset settings

### Steps to reproduce the problem

kill Onyxia and see what to loot
guid: 47572
entry:10184

### Branch

master

### TC rev. hash/commit

TrinityCore rev. b98d83ca5341 2024-11-09 22:34:59 +0100 (master branch) (Windows, AMD64, Release, Static)

### Operating system

Win11 23H2

### Custom changes

None

**Comment by Ovahlord** [comment]
how many attemts did you do to make sure that it's not just coincidence?

**Comment by carl3175** [comment]
> how many attemts did you do to make sure that it's not just coincidence?

I tried many times to kill different bosses and the situation was the same as before.

**Comment by meji46** [comment]
It's working as expected

ItemType == 1 so that's a reference. MaxCount for references is the number of times the reference is to be rolled (MinCount is ignored for these cases)
