### ISSUE TITLE
sometimes people gets stuck on combat with Rimefang  after killing tyrannus

### ISSUE THREAD

**Issue by Aokromes** [TrinityCore/TrinityCore#30420]
### Description

sometimes people gets stuck on combat with Rimefang  after killing tyrannus, this again is a very random bug

### Expected behaviour

no stuck on combat

### Steps to reproduce the problem

queue into df to pit of saron
complete instance
be unluck

### Branch

3.3.5

### TC rev. hash/commit

a377ce28c208

### Operating system

debian 12 x64

### Custom changes

n/r

**Comment by CraftedRO** [comment]
In my tests, I think we are remaining in combat with a strange Tyrannus clone spawned near ick and krick spawn, here (after I killed it with gm, combat was gone):

![WoWScrnShot_111624_134725](https://github.com/user-attachments/assets/389cf2ff-61bc-4280-86d7-29e5dd594a03)

**Comment by Aokromes** [comment]
indeed, i confirm killing that 2nd Tyrannus removes players from combat.

**Comment by Odyssey** [comment]
That leftover Tyrannus is the passenger of NPC_TYRANNUS_EVENTS , which visually is the Rimefang vehicle itself.
```sql
SELECT * FROM vehicle_template_accessory WHERE entry=36794;
```
When the Krick and Ick script calls DespawnOrUnsummon() on it, it's despawning the vehicle but not the passenger, that is falling to the ground instead. There should maybe be a generic way to handle this so when a vehicle creature is despawned its accessories despawn too (?).

In the meantime,
```diff
diff --git a/src/server/scripts/Northrend/FrozenHalls/PitOfSaron/boss_krickandick.cpp b/src/server/scripts/Northrend/FrozenHalls/PitOfSaron/boss_krickandick.cpp
index 33ad236f79..7ed76c112c 100644
--- a/src/server/scripts/Northrend/FrozenHalls/PitOfSaron/boss_krickandick.cpp
+++ b/src/server/scripts/Northrend/FrozenHalls/PitOfSaron/boss_krickandick.cpp
@@ -488,8 +488,11 @@ struct boss_krick : public ScriptedAI
                     break;
                 case EVENT_OUTRO_END:
                     if (Creature* tyrannus = ObjectAccessor::GetCreature(*me, _tyrannusGUID))
+                    {
+                        if (Creature* passenger = tyrannus->GetVehicleKit()->GetPassenger(0)->ToCreature())
+                            passenger->DespawnOrUnsummon();
                         tyrannus->DespawnOrUnsummon();
-
+                    }
                     me->DisappearAndDie();
                     break;
                 default:
```

**Comment by meji46** [comment]
Can you check value for vehicle_template_accessory.minion? If it's 0, try to set it to 1

**Comment by Odyssey** [comment]
> Can you check value for vehicle_template_accessory.minion? If it's 0, try to set it to 1

Confirming that this change does indeed fix it for me.

```sql
-- Pit of Saron: Set Tyrannus as vehicle minion
UPDATE `vehicle_template_accessory` SET `minion`=1 WHERE `entry`=36794;
```

**Comment by CraftedRO** [comment]
yeah when the event drake's gone the tyrannus clone will fall to ground then instantly despawn, I guess is a lot better that atm.

**Comment by CraftedRO** [comment]
hmm strange, on heroic I was still in combat but not sure with who this time

**Comment by Aokromes** [comment]
.debug hostil

**Comment by CraftedRO** [comment]
this time you remain with drake

![WoWScrnShot_112224_024822](https://github.com/user-attachments/assets/6b4b7234-9637-4d6e-8b4e-37b8af45e220)

**Comment by CraftedRO** [comment]
even if the boss is not engaged and does not threathen any unit, anyway seems related to location or smth, looks like if you move you will get out of cb

**Comment by Aokromes** [comment]
[23:39:55] Combat refs: (Combat state: 1 | Manager state: 1)
[23:39:55] [PvE] Rimefang (SpawnID 202135)

**Comment by Aokromes** [comment]
still bugged on 19382995de1a

**Comment by Aokromes** [comment]
still bugged on 91dcae5

**Comment by Aokromes** [comment]
still bugged on 

31f9e173c419
