### ISSUE TITLE
DB/Quest: Update Cloth Scavenging Completion (RewardText)

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCore#30438]
### Description

Tested ingame (clearing client cache might be needed before test).

https://wowpedia.fandom.com/wiki/Cloth_Scavenging_(quest)

- Dalaran (13272)
https://web.archive.org/web/20120119104103/http://www.wowhead.com:80/quest=13272

- Valiance Keep (13265)
https://web.archive.org/web/20110629013610/http://www.wowhead.com:80/quest=13265

- Warsong Hold (13270)
https://web.archive.org/web/20101212195950/http://www.wowhead.com:80/quest=13270

### SQL fix

```sql
-- Cloth Scavenging - Dalaran (13272)
UPDATE `quest_offer_reward` SET `RewardText`="I think you will find this skill helps you a great deal on your path to tailoring greatness!" WHERE `ID`=13272;
-- Cloth Scavenging - Valiance Keep (13265)
UPDATE `quest_offer_reward` SET `RewardText`="Turn that extra cloth you find into something that looks marvelous!" WHERE `ID`=13265;
-- Cloth Scavenging - Warsong Hold (13270)
UPDATE `quest_offer_reward` SET `RewardText`="I be appreciatin' your business." WHERE `ID`=13270;
```

### Branch

3.3.5

### TC rev. hash/commit

12b07e0fea25a207e12b1093b3f2eee6c5074d06

**Comment by Rushor** [comment]
Thank you!
