### ISSUE TITLE
Core/maps: When die in Winterfall Village cave and release you will be teleported in Alterac Valley

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCore#30455]
### Description

When die in Winterfall Village cave and release you will be teleported in Alterac Valley.

NOTE: This is an old bug and not related to latest commit.

### Expected behaviour

Most likely you shoud be teleported in Everlook.

### Steps to reproduce the problem

.go xyz 6718.960 -5259.397 778.404 1
.die
press release
notice

### Branch

3.3.5

### TC rev. hash/commit

225a1bbf7dabdc318bd340e15afa7378a7622612

### Operating system

Windows 11 x64

### Custom changes

None

**Comment by Shauren** [comment]
Fixed by another cherry-pick b4d6ca277aef81a49e3654a3eec131ea621da991

**Comment by CraftedRO** [comment]
ty
