### ISSUE TITLE
Sometimes StartPlayerLevel config is ignored for gm-s accounts

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCore#30450]
### Description

Sometimes StartPlayerLevel config is ignored for gm-s accounts and new value won't be updated for this type of accounts even if we restart the server.

### Expected behaviour

StartPlayerLevel config shoud not be ignored for gm-s accounts and new value shoud be updated also for this type of accounts.

### Steps to reproduce the problem

Play with StartPlayerLevel config in worldserver.config (set it to 80) then set it back to 1 or any other level

### Branch

3.3.5

### TC rev. hash/commit

cf27f1cf39c4ba3fb644f0a0e8659e90ff935fac

### Operating system

Windows 11

### Custom changes

Passive Anticheat

**Comment by Shauren** [comment]
How is this a bug? GM accounts use `GM.StartLevel`, not `StartPlayerLevel` (the only restriction that exists is that gm level must be greater or equal to StartPlayerLevel)

**Comment by CraftedRO** [comment]
ah I guess I forgot about existance of that separate config.

**Comment by CraftedRO** [comment]
> (the only restriction that exists is that gm level must be greater or equal to StartPlayerLevel)

Btw maybe we need to add this in config Description, might be usefull in future.
