### ISSUE TITLE
Death Knights shoud start with 20 silver

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCore#30456]
### Description

Death Knights atm start with no money.
Haven't found yet if there is a db table like playercreateinfo to be able to do that or if there is an itemid to match the silver amount we need.

![Captură de ecran 2024-11-20 114829](https://github.com/user-attachments/assets/e3b50da2-47c6-4dfe-8134-e5a9c568e4a3)

https://youtu.be/fsj_qqLi5G4?t=115
https://youtu.be/jP031P6gfWA?t=276
https://youtu.be/23bsQt3gxzw?t=19
https://youtu.be/N_7rowSa_qE?t=81
https://youtu.be/mqhufet3QHs?t=7

### Expected behaviour

Death Knights shoud start with 20 silver even when StartPlayerMoney = 0

When created, the death knight begins at level 55 with [uncommon](https://wowwiki-archive.fandom.com/wiki/Uncommon)​​ [item level](https://wowwiki-archive.fandom.com/wiki/Item_level) 60 gear, 20s, as well as a few spells and abilities already learned.

https://wowwiki-archive.fandom.com/wiki/Starting_a_death_knight

### Steps to reproduce the problem

create a dk
open bags
notice no money
cry

### Branch

3.3.5

### TC rev. hash/commit

a93b1151f20271b4149834912e7d3e7fc3a39747

### Operating system

Windows 11 x64

### Custom changes

None

**Comment by CraftedRO** [comment]
I wonder if we do a check in if (firstLogin) to add some gold when class dk and config 0

**Comment by Roxtedy** [comment]
@CraftedRO 
> check in if (firstLogin)

I may be wrong, but it can be done like this:

`--- a/src/server/game/Entities/Player/Player.cpp
+++ b/src/server/game/Entities/Player/Player.cpp
@@ -554,7 +554,14 @@ bool Player::Create(ObjectGuid::LowType guidlow, CharacterCreateInfo* createInfo
 
     InitRunes();
 
-    SetMoney(sWorld->getIntConfig(CONFIG_START_PLAYER_MONEY));
+
+    uint32 startMoney = sWorld->getIntConfig(CONFIG_START_PLAYER_MONEY);
+    if (createInfo->Class == CLASS_DEATH_KNIGHT)
+        startMoney += 2000;
+
+    SetMoney(startMoney);`

**Comment by Roxtedy** [comment]
@CraftedRO 
> check in if (firstLogin)

I may be wrong, but it can be done like this:

```c++
--- a/src/server/game/Entities/Player/Player.cpp
+++ b/src/server/game/Entities/Player/Player.cpp
@@ -554,7 +554,14 @@ bool Player::Create(ObjectGuid::LowType guidlow, CharacterCreateInfo* createInfo
 
     InitRunes();
 
-    SetMoney(sWorld->getIntConfig(CONFIG_START_PLAYER_MONEY));
+
+    uint32 startMoney = sWorld->getIntConfig(CONFIG_START_PLAYER_MONEY);
+    if (createInfo->Class == CLASS_DEATH_KNIGHT)
+        startMoney += 2000;
+
+    SetMoney(startMoney);
```

**Comment by Roxtedy** [comment]
if we want to use 
> firstLogin 
```c++
--- a/src/server/game/Handlers/CharacterHandler.cpp
+++ b/src/server/game/Handlers/CharacterHandler.cpp
@@ -1013,6 +1013,9 @@ void WorldSession::HandlePlayerLogin(LoginQueryHolder const& holder)
     if (pCurrChar->IsGameMaster())
         SendNotification(LANG_GM_ON);
 
+    if (firstLogin && pCurrChar->GetClass() == CLASS_DEATH_KNIGHT)
+        pCurrChar->SetMoney(2000);
+
```

**Comment by shamage** [comment]
> I wonder if we do a check in if (firstLogin) to add 20 silver when class dk and config 0

that's a pretty good idea - how about this:

```c++
if (pCurrChar->IsGameMaster())
 SendNotification(LANG_GM_ON);

 // Add 20 silver coins on first login if class is Death Knight and configuration is 0
 if (firstLogin && pCurrChar->GetClass() == CLASS_DEATH_KNIGHT && sWorld->getIntConfig(CONFIG_START_PLAYER_MONEY) == 0)
 {
 uint32 startMoney = 2000; // 20 silver coins (1 silver coin = 100 copper coins)
 pCurrChar->SetMoney(startMoney);
 }
```

**Comment by CraftedRO** [comment]
yeah something like that if it build and do what it have to

**Comment by Roxtedy** [comment]
```c++
--- a/src/server/game/Entities/Player/Player.cpp
+++ b/src/server/game/Entities/Player/Player.cpp
@@ -554,7 +554,12 @@ bool Player::Create(ObjectGuid::LowType guidlow, CharacterCreateInfo* createInfo
 
     InitRunes();
 
-    SetMoney(sWorld->getIntConfig(CONFIG_START_PLAYER_MONEY));
+    // set starting money
+    uint32 start_money = GetClass() != CLASS_DEATH_KNIGHT
+        ? sWorld->getIntConfig(CONFIG_START_PLAYER_MONEY)
+        : std::max(uint32(2000), sWorld->getIntConfig(CONFIG_START_PLAYER_MONEY));
+
+    SetMoney(start_money);
```

**Comment by CraftedRO** [comment]
create a PR maybe :D ?

**Comment by shamage** [comment]
Now here's the question:
- my code or the first code is suitable if you want to set the starting money when creating a character. This approach is more general and can be used for all new characters.
( https://github.com/TrinityCore/TrinityCore/issues/30456#issuecomment-2500331064 ) 
- the second code ( @Roxtedy ) is specific to the player's first login and is suitable if you want to add money only on the first login. ( https://github.com/TrinityCore/TrinityCore/issues/30456#issuecomment-2504829050 )

so which one is better?
