### ISSUE TITLE
SPELL_ATTR2_ALLOW_LOW_LEVEL_BUFF should allow enchanting low level items

### ISSUE THREAD

**Issue by robinsch** [TrinityCore/TrinityCore#30482]
### Description

found this in the 335 client `sub_7FFAC0` that checks item target for SPELL_EFFECT_ENCHANT_ITEM, SPELL_EFFECT_ENCHANT_ITEM_TEMPORARY, SPELL_EFFECT_ENCHANT_ITEM_PRISMATIC

![image](https://github.com/user-attachments/assets/ade0a94f-b6e4-4868-8b88-3daac27a0c9f)

### Expected behaviour

Should allow enchant server side

### Steps to reproduce the problem

Did not checked if such an enchant exists in game with attr

### Branch

3.3.5

### TC rev. hash/commit

-

### Operating system

-

### Custom changes

-

**Comment by Shauren** [comment]
yes
![obraz](https://github.com/user-attachments/assets/d3e21f79-21ae-4999-ad2e-182174231457)
