### ISSUE TITLE
DB/Spawns: Defias Thugs in Northshire Valley are not aggroing

### ISSUE THREAD

**Issue by TQPS** [TrinityCore/TrinityCore#30492]
### Description

Defias Thugs in Northshire Valley should be red and aggro.

Currently they are yellow and do not attack unless attacked first.

### Expected behaviour

They should aggro the player when drawing near.

Defias Cutpurses outside Northshire appear fine.

FWIW, if relevant:
- Not a GM, normal account.
- AOWOW shows Defias Thugs as Yellow to AH and faction "creature"
- AOWOW shows Defias Cutpurses as Red to AH and faction "Defias Brotherhood"

### Steps to reproduce the problem

1. Get first quest to get bandanas - easy peasy - you remember it being harder in live
2. Turn in and get quests for Milly's Harvest and Bounty on Garrick Padfoot
3. Enter area and no one budges ..., then you realize, they're yellow and don't aggro

### Branch

3.3.5

### TC rev. hash/commit

TrinityCore rev. 79235118e87c 2024-12-06 21:22:03 +0000 (npcbots_3.3.5 branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

### Operating system

Windows 10 x64

### Custom changes

Npcbots only.

**Comment by kaytotes** [comment]
They were changed to neutral in 3.3.0

https://wowpedia.fandom.com/wiki/Defias_Thug

Pretty much all starting area mobs were.

**Comment by TQPS** [comment]
Fair enough. Free fruit picking it is.

Thank you.

**Comment by CraftedRO** [comment]
https://github.com/TrinityCore/TrinityCore/issues/20095
