### ISSUE TITLE
Moved Server & Lost Guild Bank Items

### ISSUE THREAD

**Issue by infidelus** [TrinityCore/TrinityCore#30498]
### Description

I recently had to reinstall the Ubuntu server I use for WotLK.  Prior to doing so I used pdump to export the characters.  After reinstalling I reimported the characters but noticed when I tried to use the guild bank that I was no longer in a guild.

I looked at the SQL server and can see there are a number of guild entries in the characters database, but this does not appear to be included as part of pdump.

I did have an image of the old server so booted that up elsewhere and exported the characters.guild_ entries and imported them on the new server instance.  Everything seems to be working except the items that were in the guild bank and I noted that the entries in the database kept getting deleted.  I'm not sure whether this was when I started worldserver or when I tried accessing the guild bank.  I then looked at the exported SQL file and grabbed just the code under guild_bank_item then ran a query to import it.  The items are now showing in the database but are still missing when I access the bank.

Is there another database entry I need or something else I'm missing?  The guild bank was almost full and it would be a shame to lose it all.

### Expected behaviour

I would have hoped that when using pdump there might be a way to retain guild info

### Steps to reproduce the problem

1 - Run pdump to export characters
2 - Import to new server
3 - Everything related to the character, including guild info, should still be there

### Branch

3.3.5

### TC rev. hash/commit

TrinityCore rev. 79235118e87c 2024-12-06 21:22:03 +0000 (npcbots_3.3.5 branch) (Unix, RelWithDebInfo, Static)

### Operating system

Ubuntu Server 24.04

### Custom changes

TrinityBots

**Comment by Shauren** [comment]
Guild are not exported, pdump (as its name implies, **P**layer **DUMP**) only exports characters

guild bank contents need guild_bank_item and item_instance rows (linked by guid - keep in mind item_instance holds ALL items on the server, inventory, mail, guild banks, auctions)

**Comment by infidelus** [comment]
I had worked out that pdump was only for the player but as a player can have a guild component I had hoped guild related bits would also be exported as it seems a bit odd, to me at least, that guild info is not part of an export.  It's fine though as you have provided the extra table I needed to restore the server as it was before the migration and everything is now as it should be.

Thanks :+1:

**Comment by jackpoz** [comment]
I would suggest to use MySQL backup and restore tools to move databases across machines

**Comment by infidelus** [comment]
That would have been my preference but the database had become somewhat corrupted somewhere, and was over 1.5 GB in size when backed, up which resulted in TC crashing quite regularly so I opted for the clean install and had hoped the pdump would be sufficient.  It's fine though.  pdump and just reimporting the guild* and item_instance tables has fixed it.
