### ISSUE TITLE
Compile error in src\server\shared\Realm\RealmList.cpp with c++latest

### ISSUE THREAD

**Issue by NEIL-smtg** [TrinityCore/TrinityCore#30511]
### Description

Hi, I work on Microsoft Visual C++ testing, where we regularly build popular open-source projects, including yours, with development builds of our compiler and libraries with some particular cl options such as `/permissive-` and `/std:c++latest` to detect and prevent shipping regressions that would affect you.

Recently, as I build TrinityCore with the latest commit, I encounter the following errors:
```
C:\gitP\TrinityCore\TrinityCore\src\server\shared\Realm\RealmList.cpp(133): error C3083: 'ranges': the symbol to the left of a '::' must be a type
C:\gitP\TrinityCore\TrinityCore\src\server\shared\Realm\RealmList.cpp(133): error C2039: 'contains': is not a member of 'advstd'
C:\gitP\TrinityCore\TrinityCore\src\common\Utilities\advstd.h(31): note: see declaration of 'advstd'
C:\gitP\TrinityCore\TrinityCore\src\server\shared\Realm\RealmList.cpp(133): error C3861: 'contains': identifier not found
```

After looking at the issues reported by others, I noticed that `/std:c++latest` is not currently supported. If there are no plans to support it in the future, feel free to close this issue.

### Expected behaviour

It compiles.

### Steps to reproduce the problem

1. Open x64 native tools command prompt for VS2022
2. git clone https://github.com/TrinityCore/TrinityCore.git
3. mkdir TrinityCore\TrinityCore\build_amd64 & cd TrinityCore\TrinityCore\build_amd64
4. set \_CL\_=%\_CL\_% /std:c++latest /D_HAS_DEPRECATED_SHARED_PTR_UNIQUE=1
5. set MYSQL_ROOT=C:\gitP\TrinityCore\TrinityCore\mysql\mysql-5.7.44-winx64
6. cmake -G Ninja -DCMAKE_TOOLCHAIN_FILE=C:\gitP\Microsoft\vcpkg\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows -DSCRIPTS=dynamic -DTOOLS=True -DCMAKE_BUILD_TYPE=Release -DWITH_WARNINGS_AS_ERRORS=ON -DTOOLS=ON ..
7. ninja 2>&1

Build log: [tc.txt](https://github.com/user-attachments/files/18147168/tc.txt)

### Branch

master

### TC rev. hash/commit

bb583baef686ef3ce76e61852ae8aa1b211a1e2c

### Operating system

windows 11

### Custom changes

none

**Comment by Ovahlord** [comment]
Hey there. Thanks for reaching out. We do currently set C++20 as our standard within our default cmake settings. We will eventually move on to newer  C++ standards when our supported compilers (msvc, gcc and clang) have caught up with the implementations. So c++latest is likely not going to be supported by default but take this with a grain of salt as there are others in charge of setting the standard.

Advstd for example are backports from newer C++ versions which we will replace with the according std counterpart when moving on.

**Comment by Shauren** [comment]
This is now fixed
