### ISSUE TITLE
[Bug]Extra-Dimensional Ghost Revealer

### ISSUE THREAD

**Issue by Crysicle** [TrinityCore/TrinityCore#3052]
This is the list of Npcs that should become visible once you activate Extra-Dimensional Ghost Revealer and gain the buff:
-Gremnik Rizzlesprang(not seen at all, may perhaps be not spawned at all) - http://old.wowhead.com/npc=16123
-Bodley(can be seen even though the item is not used) - http://old.wowhead.com/npc=16033
-Anthion Harmon(can be seen even though the item is not used) - http://old.wowhead.com/npc=16016

Extra-Dimensional Ghost Revealer and the list of mobs to become visible once used - http://www.wowwiki.com/Extra-Dimensional_Ghost_Revealer

Core revision: 14b3ed91647b+
Database revision: TDB 335.11.42
Addons: AHbot & AC1

**Comment by Killyana** [comment]
SET @GUID          := xxxxxx; -- 1 creature guid Set by TC
DELETE FROM `creature` WHERE `id`=16123;
``` sql
INSERT INTO `creature` (`guid`, `id`, `map`, `spawnMask`, `phaseMask`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`,`curhealth`) VALUES
(@GUID, 16123, 0, 1, 1, -14457.221680, 448.084534, 20.406971, 6.115618, 600, 0);

DELETE FROM `creature_template_addon` WHERE `entry` IN (16123, 16033, 16016);
INSERT INTO `creature_template_addon` (`entry`,`bytes1`,`bytes2`, `emote`, `auras`) VALUES
(16123,0,0,0,"27614 17327 44816"),
(16033,0,0,0,"27614 17327"),
(16016,0,0,0,"27614 17327");
