### ISSUE TITLE
DB/Quest: Distracting Jarven issues incorrect quest icon

### ISSUE THREAD

**Issue by TQPS** [TrinityCore/TrinityCore#30534]
### Description

The quest "Distracting Jarven" (QuestID: 308) places a blue repeatable quest icon above Jarven (npc 1373) instead of a yellow.

### Expected behaviour

Quest icon should be yellow. It is not a repeatable quest.

### Steps to reproduce the problem

1. Pick up or issue quest no. 308 "Distracting Jarvan"
2. Locate Jarven under Inn in Kharanos
3. Note he has a blue icon, instead of yellow

### Branch

3.3.5

### TC rev. hash/commit

TrinityCore rev. 79235118e87c 2024-12-06 21:22:03 +0000 (npcbots_3.3.5 branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

### Operating system

Windows 10 x64

### Custom changes

NPC Bots

**Comment by CraftedRO** [comment]
https://www.wowhead.com/wotlk/quest=308/distracting-jarven#comments:id=992261

Most likely because the quest is repeatable as stated in wowhead.

https://youtu.be/s4-91i5L474?t=266

**Comment by CraftedRO** [comment]
https://youtu.be/XkypDA6_MdE?t=218

**Comment by Ovahlord** [comment]
Not an issue, the quest is repeatable, which is why the marks are blue.
