### ISSUE TITLE
Deeprun Tram

### ISSUE THREAD

**Issue by Polytrih** [TrinityCore/TrinityCore#30542]
### Description

Deeprun Tram looks fine but when it starts to move, the player will fall off from it.

https://wowpedia.fandom.com/wiki/Deeprun_Tram

### Expected behaviour

When tram starts to move, the player will stay on the train.

### Steps to reproduce the problem

1. Go to Stormwind
2. Enter the Deeprun Tram instance
3. Get on the train
4. Wait until it starts to go

### Branch

master

### TC rev. hash/commit

69e0e65fd739c799c37cd03bb16df1a015fba83d

### Operating system

Windows 10 x64

### Custom changes

None

**Comment by Naddley** [comment]
duplicate: https://github.com/TrinityCore/TrinityCore/issues/26903
