### ISSUE TITLE
Core/Configuration: Rate.Talent does not work

### ISSUE THREAD

**Issue by Polytrih** [TrinityCore/TrinityCore#30543]
### Description

"Rate.Talent" does not affect the talent points you receive.

### Expected behaviour

When the "Rate.Talent" is set to 2, each level should give 2 talent points instead of 1.

### Steps to reproduce the problem

1. Modify the "Rate.Talent" to 2
2. Create a new Void Elf Mage
3. Select a specialization
4. Level up the character

### Branch

master

### TC rev. hash/commit

69e0e65fd739c799c37cd03bb16df1a015fba83d

### Operating system

Windows 10 x64

### Custom changes

None

**Comment by Shauren** [comment]
This config option will not work with the new talent system added in 10.0.0, consider it deprecated

**Comment by CraftedRO** [comment]
https://github.com/TrinityCore/TrinityCore/commit/9aeaedeefe66c33bb72b5a1b16b17ba82c191633
