### ISSUE TITLE
[Bug]Omen of Clarity

### ISSUE THREAD

**Issue by Crysicle** [TrinityCore/TrinityCore#3088]
Sometimes when Omen of Clarity proces, you are unable to use the buff. For example a druid in cat form gets Clearcasting and has 0 energy at the moment and is trying to use the mangle ability. What will happen is that for a second it will look as if the ability is going to land but it just resets. So far i wasn't able to reproduce this bug since the proc chance is very low and happens quite rarely.

Clearcasting - http://old.wowhead.com/spell=16870

Core revision: 14b3ed91647b+
Database revision: TDB 335.11.42
Addons: AHbot & AC1

**Comment by Rushor** [comment]
some modifications one this once: https://github.com/TrinityCore/TrinityCore/commit/37145b6203c5781856ca0546bd57798bbfcc8ab5 - but this does not affect Omen of Clarity

**Comment by Rushor** [comment]
```c++
class spell_dru_omen_of_clarity_proc : public SpellScriptLoader
{
    public:
        spell_dru_omen_of_clarity_proc() : SpellScriptLoader("spell_dru_omen_of_clarity_proc") { }

        class spell_dru_omen_of_clarity_proc_AuraScript : public AuraScript
        {
            PrepareAuraScript(spell_dru_omen_of_clarity_proc_AuraScript);

            bool Check(ProcEventInfo& eventInfo)
            {
                if (eventInfo.GetSpellInfo())
                {
                    // Path of Illidan Flames
                    if (eventInfo.GetSpellInfo()->SpellIconID == 147)
                    {
                        if (Unit* owner = GetUnitOwner())
                            owner->RemoveAura(16870);
                        return false;
                    }                       
                }
                return true;
            }

            void OnProc(AuraEffect const* aurEff, ProcEventInfo& eventInfo)
            {
                if (Unit* owner = GetUnitOwner())
                    owner->RemoveAura(16870);
            }

            void Register()
            {
                DoCheckProc += AuraCheckProcFn(spell_dru_omen_of_clarity_proc_AuraScript::Check);
                OnEffectProc += AuraEffectProcFn(spell_dru_omen_of_clarity_proc_AuraScript::OnProc, EFFECT_0, SPELL_AURA_ADD_PCT_MODIFIER);
            }
        };

        AuraScript* GetAuraScript() const
        {
            return new spell_dru_omen_of_clarity_proc_AuraScript();
        }
};
```

maybe sth like this - but the problem is still the same:
the spell/buff is bugged if you used a spell while having GCD or while the spell is casted in front of the target (in the case of shred)

**Comment by robinsch** [comment]
@Rushor Try this.
```diff
diff --git a/src/server/game/Spells/Spell.cpp b/src/server/game/Spells/Spell.cpp
index 4a9cc33..1019389 100644
--- a/src/server/game/Spells/Spell.cpp
+++ b/src/server/game/Spells/Spell.cpp
@@ -2900,6 +2900,14 @@ void Spell::prepare(SpellCastTargets const* targets, AuraEffect const* triggered
             triggeredByAura->GetBase()->SetDuration(0);
         }
 
+        if (m_caster->GetTypeId() == TYPEID_PLAYER)
+        {
+            m_caster->ToPlayer()->RestoreSpellMods(this);
+            // cleanup after mod system
+            // triggered spell pointer can be not removed in some cases
+            m_caster->ToPlayer()->SetSpellModTakingSpell(this, false);
+        }
+
         SendCastResult(result);
 
         finish(false);
```

**Comment by Rushor** [comment]
YES, nice :)  i hope it will not break something else but the problems mentioned in the startpost are solved with this 

fucking amasing

**Comment by tkrokli** [comment]
I volunteer to create a PR for that diff, if you want me to do it (since robinsch does not have a TC fork).
I think that a useful title for the PR would be: **[3.3.5] Spells: Omen of Clarity**
Will also use the git command to set robinsch as the author and link the PR back to this issue, of course.

**Comment by Rushor** [comment]
go for it - but i can give detailed information on further cosequences of this fix in ~ 1 week

**Comment by tkrokli** [comment]
OK, I suppose we can work on that in the PR and that I could put [WIP] in the title.

**Comment by Runico** [comment]
the issue still persist

**Comment by Rushor** [comment]
find out the reason for it @Runico

**Comment by tkrokli** [comment]
Indeed. It is a lot easier if we know what to look for. In particular:
- how does the bug appear when you play?
- when does it happen?
- how do you replicate the problem?

Basically, a description on when, how and where it happens would be valuable information.

**Comment by Runico** [comment]
There is description on issue already,

For example a druid in cat form gets Clearcasting and has 0 energy at the moment and is trying to use the mangle ability. What will happen is that for a second it will look as if the ability is going to land but it just resets.
