### ISSUE TITLE
[Quest] Now This is Ram Racing... Almost

### ISSUE THREAD

**Issue by netinet** [TrinityCore/TrinityCore#3129]
While on the Brewfest quests 11318 (alliance) and 11409 (horde) the vehicle Rental Racing Ram (spell ID: 43883) cannot be sped up by Ram Racing Reins item (33306) which is supposed to use spell Giddy Up! (42924).

Also, when turning the quest to get the reward in (after completing it with a gm command) a spell is supposed to be cast on the character to dismount them (spell ID: 44358) and it doesn't seem to happen. 

Another bug I noticed: after using Ram Reins the Giddy Up aura stays on the character infinitely (it's only visible in database, though).

Quests: http://www.wowhead.com/quest=11318 and http://old.wowhead.com/quest=11409
Vehicle spell: http://www.wowhead.com/quest=43883
Item that should be used to control the ram: http://www.wowhead.com/quest=33306
Spell associated with item: http://www.wowhead.com/quest=42924

Core Info:
TrinityCore rev. 2011-09-15 10:56:04 +0200 (Unix, Release)
Hash: 9006e4e8dc1c+ "9006e4e8dc1c2cbf30303dd2d5e34f3d9a2380a9"
TDB: 335.11.42+

No addons.
##

**Comment by Killyana** [comment]
Fixed by https://github.com/TrinityCore/TrinityCore/commit/894378f86728f54a604f6808b6c34e4f498ddd0c#diff-c7e6c7c861bca2cc3c5c7e8729794a71
