### ISSUE TITLE
[Quest] Chug and Chuck!

### ISSUE THREAD

**Issue by netinet** [TrinityCore/TrinityCore#3130]
While on the quests Chug and Chuck! (12022 for alliance and 12191 for horde) the player is supposed to use the available Complimentary Brewfest Sampler (33096) to hit the Self-Turning and Oscillating Utility Target <S.T.O.U.T.> (24108) robot running nearby. 

While the character has the drinking and throwing animation, no quest credit is given, despite standing on top of the robot or anywhere else. 

The item uses a Script Effect spell 42436 (called 'Drink!').

Additionally, the quest giver for alliance version of this quest respawns regardless if the event is going on or not. His name is Boxey Boltspinner (http://old.wowhead.com/npc=27215).

Quests: http://old.wowhead.com/quest=12022 and http://old.wowhead.com/quest=12191
Sampler item (mug): http://old.wowhead.com/item=33096
Item's spell: http://old.wowhead.com/spell=42436
S.T.O.U.T. robot (target): http://old.wowhead.com/npc=24108

Core Info:
TrinityCore rev. 2011-09-20 09:03:12 +0200 (Unix, Release)
Hash: 80800def40a9+ "80800def40a9b70d8cdde9a9e4da72128d21f43e"
TDB: 335.11.42+

No addons.

**Comment by danlapps** [comment]
Is this still an issue ? If so are the data in the above pastebin ok but just need converting from replace into to update ?

**Comment by sirikfoll** [comment]
Fix
```sql
UPDATE `creature_template` SET `AIName`='SmartAI' WHERE `entry`=24108;
DELETE FROM `smart_scripts` WHERE `entryorguid`=24108 AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(24108,0,0,0,8,0,100,0,42436,0,0,0,33,24108,0,0,0,0,0,7,0,0,0,0,0,0,0,'S.T.O.U.T. - On Spellhit Drink! - Call Killed Monster');

**Comment by Killyana** [comment]
Update it with credit spell: SmartAIMgr: Entry 24108 SourceType 0 Event 0 Action 33 Kill Credit: There is a killcredit spell for creatureEntry 24108 (SpellId: 47173 effect: 0)

**Comment by sirikfoll** [comment]
Done
