### ISSUE TITLE
[Achievement/Bug] Defense of the Ancients

### ISSUE THREAD

**Issue by shlomi1515** [TrinityCore/TrinityCore#3170]
Hey Everyone,

Tried to do the "Defense of the Ancients" achievement and I found out that is bugged and
unachieveable, please help me...

Related Links:
http://www.wowhead.com/achievement=1757
http://www.wowhead.com/achievement=2200

TDB: 335.11.42+
Hash: f356f65
Addons: wg(not tc) / ac1 / tc2 / armory / pvprank

**Comment by Aokromes** [comment]
I got the achievement, but on the incorrect side (attackers won achievement instead defenders)

**Comment by Aokromes** [comment]
Edit: Also only 1st team gets achievement, the 2nd round team no.

**Comment by sirikfoll** [comment]
when the achievement check is called, the variable `Attackers` is already updated, so 
`source->GetTeamId() != Attackers` needs to be changed to `source->GetTeamId() == Attackers`
This will solve the Achievement going to the wrong team.

Remains the second issue, the check only gets called on the end of the first round, nothing happens on the end of the second.

```diff
diff --git a/src/server/game/Battlegrounds/Zones/BattlegroundSA.cpp b/src/server/game/Battlegrounds/Zones/BattlegroundSA.cpp
index bfae37c..86e052b 100644
--- a/src/server/game/Battlegrounds/Zones/BattlegroundSA.cpp
+++ b/src/server/game/Battlegrounds/Zones/BattlegroundSA.cpp
@@ -1037,7 +1037,7 @@ bool BattlegroundSA::CheckAchievementCriteriaMeet(uint32 criteriaId, Player cons
         case BG_CRITERIA_CHECK_NOT_EVEN_A_SCRATCH:
             return _allVehiclesAlive[GetTeamIndexByTeamId(source->GetTeam())];
         case BG_CRITERIA_CHECK_DEFENSE_OF_THE_ANCIENTS:
-            return source->GetTeamId() != Attackers && !_gateDestroyed;
+            return source->GetTeamId() == Attackers && !_gateDestroyed;
     }
 
     return Battleground::CheckAchievementCriteriaMeet(criteriaId, source, target, miscValue);

**Comment by sirikfoll** [comment]
This issue was fixed in https://github.com/TrinityCore/TrinityCore/commit/6d8e39f59c80639de3681565f55d68d452223c87
