### ISSUE TITLE
[3.3.5] DB/Quest: Icecrown deprecated Quests - Green Technology

### ISSUE THREAD

**Issue by Crysicle** [TrinityCore/TrinityCore#3202]
You're supposed to go to top of the towerish thingy in Icecrown at 54;36 and then talk to "Fringe Engineer Tezzla" to turn in the quest. Once you land at the top of the tower, the turn in npc and a few other objects should appear but at the moment the phasing event doesn't happen, the top remains empty.

I noticed that there are also  "Cloak Dome (Aura Generator)" and "Cloak Dome (Aura Generator 2)" spawned in the middle of the tower witch are probably the triggers for the phasing event that aren't working properly.
- [Fringe Engineer Tezzla](http://www.wowhead.com/npc=32430/fringe-engineer-tezzla) - http://www.wowhead.com/npc=32430/fringe-engineer-tezzla
- [Green Technology](http://www.wowhead.com/quest=13379/green-technology) - http://www.wowhead.com/quest=13379/green-technology

Core revision: 80800def40a9+
Database revision: TDB 335.11.42
##

**Comment by tkrokli** [comment]
TrinityCore rev. 429700e614c2 2016-09-22 15:22:54 +0200 (3.3.5 branch) (Win64, Release, Static)
TDB 335.61 plus updates up to and including `2016_09_22_00_world.sql`

Just wanted to add links regarding the Alliance quest involved (which can not be completed as of now):
- http://www.wowhead.com/quest=13383/killohertz (cannot be completed, no quest end NPC available)
- http://www.wowhead.com/npc=32444/kibli-killohertz (not spawned or scripted to spawn on quest)

Is it too hacky to perma-spawn the quest NPCs until someone writes Green Technology spell scripts?
-- Yes, I understand that sniff info is unavailable, but what about a "best effort" update to this?

**Comment by sirikfoll** [comment]
I have the alliance spawns! But the invisibility does not work(see issue #17182), removing the invisibility aura from creature_template_addon is a temp solution.
https://gist.github.com/sirikfoll/b5c2505a1de0af0cf01d9cc6db4e8ac7

**Comment by Ghost-R** [comment]
Any updates ?

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/3202#issuecomment-18350306

**Comment by sirikfoll** [comment]
@Killyana Could you see if this can be pushed, is sniffed at least?  https://gist.github.com/sirikfoll/b5c2505a1de0af0cf01d9cc6db4e8ac7

**Comment by Killyana** [comment]
I will take a look.

**Comment by Killyana** [comment]
Gameobject_addon are missing for this reason many gobs doesn't have the correct orientation.

**Comment by illfated** [comment]
TrinityCore rev. e5b3814020fe 2018-05-08 18:28:12 +0200 (3.3.5 branch) (Win64, Release, Static)
Using SSL version: OpenSSL 1.1.0h  27 Mar 2018 (library: OpenSSL 1.1.0h  27 Mar 2018)
Using Boost version: 1.65.1
Using MySQL version: 5.6.38
Using CMake version: 3.10.1
Compiled on: Windows 10.0.17134
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 252191207 bytes
vmaps directory located in ./vmaps. Total size: 588247501 bytes
mmaps directory located in ./mmaps. Total size: 2152621724 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 335.64

Yes, I have read https://github.com/TrinityCore/TrinityCore/issues/3202#issuecomment-18350306, but what will the consequences be for this issue?
Will the missing NPCs and gameobjects never ever be spawned on the 3.3.5 branch?

**Comment by sirikfoll** [comment]
Gist updated to include gameobject_addon data: https://gist.github.com/sirikfoll/b5c2505a1de0af0cf01d9cc6db4e8ac7

**Comment by RR2739-VCN** [comment]
This is still an issue and many phased npcs are also appear invisible.

**Comment by Killyana** [comment]
Spawns are done, just phasing (npcs inside the dome use the aure=59660) and quest scripts remains.
https://github.com/TrinityCore/TrinityCore/commit/feaeb0d6380b2096eeb0802e91c14673331ddf4b
