### ISSUE TITLE
[Vehicles] Friendly Fire (Tested in Ulduar)

### ISSUE THREAD

**Issue by Amit86** [TrinityCore/TrinityCore#3292]
Hey

Im using hash 2a34c5e

Just tested ulduar Salvaged Demolisher and had the following problems:
When using for example Hurl Boulder on another Salvaged Demolisher it gets friendly fire.

I remembered this was a huge issue a year ago back when we were still using googlecode and found this issue:
http://code.google.com/p/trinitycore/issues/detail?id=3558

it has this suggestion of a fix:
http://pastebin.com/L3rwFYmf

This suggestion seems to fix the problem for me, It looks like a hack so I would appreciate someone taking a look on how to convert it to something usable by trinitycore

Thanks :)

**Comment by danlapps** [comment]
Anything in here valid enough to use and close ?

**Comment by Aokromes** [comment]
Conditions looks to be correct.

**Comment by joschiwald** [comment]
imo workaround
