### ISSUE TITLE
[Game_Events] Enhacement

### ISSUE THREAD

**Issue by click** [TrinityCore/TrinityCore#332]
Most of game event occur repeatidly every year on same day. Now, we have occurence, but that value fail if feb has 29 days. So i think we can add a value on game_event table, so the code too; where we can define if event is day linked.
Then for example, Xmas days (25 Dic) it will be day_linked, and it will start ever 25 dic, and occurence will not be checked here for anything. 
On other example, Darkmoon Faire or Battleground Holidays will be not day_linked events, and will start on occurence dependance.

These are the Anual Events
Annually  
New Year · Lunar Festival · Love is in the Air · Noblegarden · Children's Week · Midsummer Fire Festival · Pirates' Day · Brewfest · Harvest Festival · Peon Day · Hallow's End · Day of the Dead · Pilgrim's Bounty · Feast of Winter Veil

Those events will be day_linked
##

**Comment by msoky** [comment]
what about this? https://github.com/TrinityCore/TrinityCore/commit/5c06a5e8eb108a3b60c77b10a71e846d82d410a5

**Comment by Aokromes** [comment]
totally unrelated.

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/commit/951fa46fe9b14a9e275ac9306b2346959e40e3e5
