### ISSUE TITLE
[Item] Tiny Abomination in a Jar is not proccing Seal of Vengeance

### ISSUE THREAD

**Issue by Noonow** [TrinityCore/TrinityCore#3463]
The "mote of anger" proc from Tiny Abomination in a Jar should proc seal damage from Seal of Vengeance but it doesn't. It does proc seal damage when using Seal of Righteousness.
Tiny Abomination in a Jar is thé best ret trinket there in ICC is when properly working, now that it's not properly working it's not even 50% as good as it should be. 

rev: https://github.com/TrinityCore/TrinityCore/commit/0ab9dd3f9f83e59641d422b92ab347c024b3287a

**Comment by Keader** [comment]
@ariel-
