### ISSUE TITLE
spell_effect "Transform Item" don't complete the quest

### ISSUE THREAD

**Issue by narutoka** [TrinityCore/TrinityCore#3505]
http://www.wowhead.com/quest=10716/test-flight-ravens-wood-needs-reward
http://www.wowhead.com/quest=10565/the-stones-of-vekhnir

After completing it question mark appears on map but not on the npc.

Server is running on Trinity Core bcc55489f8ba+
 Database revision: TDB 335.11.42
 OS: Ubuntu 10.04 x64
 Patches/addons: AntiCheat1
##

**Comment by Killyana** [comment]
Same issue as https://github.com/TrinityCore/TrinityCore/issues/3823 the item is transformed and not added, you have to put the item in the bank and take it back to complete the quest.

**Comment by Aokromes** [comment]
@Shauren any hope to fix this?
