### ISSUE TITLE
{Quest}The Frost Wyrm and its Master

### ISSUE THREAD

**Issue by Justiciar** [TrinityCore/TrinityCore#3541]
Dear Sir or Madam,
I have encountered a  problem while I tried to do this quest.
The problem is that the first npc I need to kill, "Wyrmcaller Vile"  can't be found in the place it's supposed to be by any means.
I have asked a friend, he told me this creature is not even exist by guid in the game, only by ID, 0 creatures  of his ID in the game, so he says, I found it true by wondering all over the area.
If this quest would have worked properly, the npc "Wrymcaller vile" would have been in the place it's supposed to be, but he is not and it's seems he is not exist in the game at all.
Sincerely yours,
                            Justiciar.
wowhead quest link(Alliance quest): http://www.wowhead.com/quest=11238

wowhead quest link(Horde quest): http://www.wowhead.com/quest=11267

woehead missing npc link: http://www.wowhead.com/npc=24029

wowhead quest giver(Alliance quest):  http://www.wowhead.com/npc=23888

wowhead quest giver(Horde quest): http://www.wowhead.com/npc=24032  

wowhead quest item-related for later advancement in the quest(in order to summon Glacion):http://www.wowhead.com/item=33282

Hash:25cec68193d9d017ac51cda5a49d0d75d2949077

TDB: 335.11.42+

Addons: wg(not tc) / ac1 / tc2 / armory / pvprank

on Linux
##

**Comment by Frytiks** [comment]
@dr-j Any news ?

**Comment by wrathix** [comment]
Would love to have this working.  Good luck!

**Comment by Frytiks** [comment]
On 11.58 TDB still not working.

**Comment by fvicaria** [comment]
Just tried and the go seems to be missing so can't spawn Wyrmcaller Vile.

TDB 335.11.58+

**Comment by wrathix** [comment]
Pls script this :)

**Comment by Necromonicon** [comment]
Wyrmcaller's Horn
Use: Blow on the wyrmcaller's platform to call down Glacion.

You think that it's location ? No. You are wrong. You must to add gameobject where you want   
Id is 186487
I add it like this:
SET @GOGuid := XXXXXX;
INSERT INTO `gameobject` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `position_x`, `position_y`, `position_z`, `orientation`, `rotation0`, `rotation1`, `rotation2`, `rotation3`, `spawntimesecs`, `animprogress`, `state`, `VerifiedBuild`) VALUES
(@GOGuid, 186487, 571, 0, 0, 1, 1, 2819.76, -3604.16, 245.656, 5.80633, 0, 0, 0.236173, -0.971711, 300, 0, 1, 0);

works

**Comment by tkrokli** [comment]
Practical tip for code readability (code block): add a line with only ```sql above your SQL code,

then add only ``` on the blank line beneath it, to get normal text below that line.

**Comment by Rushor** [comment]
moreover the SAi combatscript for Wyrmcaller Vile http://www.wowhead.com/npc=24029/wyrmcaller-vile#abilities is missing

**Comment by sirikfoll** [comment]
These are the spawns that are missing, and some basis for the SAI, couldn't get sniffs from the quest because I had it completed before. Also I could not find the GameObject 186487
```sql
SET @CGUID := 300000;

DELETE FROM `creature_template_addon` WHERE `entry` IN (24029);
INSERT INTO `creature_template_addon` (`entry`, `mount`, `bytes1`, `bytes2`, `auras`) VALUES
(24029, 0, 0x0, 0x1, 12544); -- Wyrmcaller Vile - Frost Armor

DELETE FROM `creature_addon` WHERE `guid` IN (@CGUID+5);
INSERT INTO `creature_Addon` (`guid`, `mount`, `bytes1`, `bytes2`, `auras`) VALUES
(@CGUID+5, 0, 0x0, 0x1, 43570); -- Invisible Stalker (Floating) - Frost State

DELETE FROM `spell_linked_spell` WHERE `spell_trigger` IN(43568,43569);
INSERT INTO `spell_linked_spell` (`spell_trigger`, `spell_effect`, `type`, `comment`) VALUES
(43568, 34872, 1, 'Frost Strike'),
(43569, 34872, 1, 'Frost trigger ');

DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=13 AND `SourceEntry` IN(43568);
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
(13,1,43568,0,0,31,0,3,15214,0,0,0,0,'',"Spell 'Frost Strike' Effect 0 can hit 'Invisible Stalker'");

DELETE FROM `creature` WHERE `guid` BETWEEN @CGUID AND @CGUID+7;
INSERT INTO `creature` (`guid`, `id`, `map`, `spawnMask`, `phaseMask`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `MovementType`) VALUES
(@CGUID, 15214, 571, 1, 1, 2842.762, -3599.551, 247.2563, 1.658063, 120, 0, 0), -- Invisible Stalker (Area: -Unknown-)
(@CGUID+1, 15214, 571, 1, 1, 2807.391, -3586.93, 247.6916, 3.455752, 120, 0, 0), -- Invisible Stalker (Area: -Unknown-)
(@CGUID+2, 15214, 571, 1, 1, 2833.016, -3621.016, 247.373, 1.850049, 120, 0, 0), -- Invisible Stalker (Area: -Unknown-)
(@CGUID+3, 23033, 571, 1, 1, 2831.685, -3611.948, 257.9287, 0.2479207, 120, 0, 0), -- Invisible Stalker (Floating) (Area: -Unknown-) (Auras: 43570 - Frost State)
(@CGUID+4, 23033, 571, 1, 1, 2832.849, -3638.875, 246.9362, 0.5235988, 120, 0, 0), -- Invisible Stalker (Floating) (Area: -Unknown-)
(@CGUID+5, 23033, 571, 1, 1, 2820.243, -3602.598, 261.4395, 6.161012, 120, 0, 0), -- Invisible Stalker (Floating) (Area: -Unknown-)
(@CGUID+6, 23033, 571, 1, 1, 2855.824, -3596.345, 248.4855, 5.131268, 120, 0, 0), -- Invisible Stalker (Floating) (Area: -Unknown-)
(@CGUID+7, 24029, 571, 1, 1, 2820.328, -3602.552, 247.9988, 3.665191, 120, 0, 0); -- Wyrmcaller Vile (Area: -Unknown-) (Auras: 12544 - Frost Armor)

UPDATE `creature_template` SET `AIName`='SmartAI' WHERE `entry`=24029;
DELETE FROM `smart_scripts` WHERE `entryorguid` IN (24029,-106031,-@CGUID,-(@CGUID+1),-(@CGUID+2)) AND `source_type`=0;
DELETE FROM `smart_scripts` WHERE `entryorguid` IN (@CGUID*100,@CGUID*100+1) AND `source_type`=9;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(24029,0,0,0,1,0,100,0,0,0,3000,3000,11,43568,2,0,0,0,0,1,0,0,0,0,0,0,0,'Wyrmcaller Vile - OOC - Cast \'Frost Strike\''),
(24029,0,1,0,0,0,100,0,0,0,4000,4000,11,9672,0,0,0,0,0,2,0,0,0,0,0,0,0,'Wyrmcaller Vile - IC - Cast \'Frostbolt\''),

(-106031,0,0,0,8,0,100,0,43568,0,0,0,80,@CGUID*100,0,0,0,0,0,1,0,0,0,0,0,0,0,'Invisible Stalker - On SpellHit \'Frost Strike\' - Call ActionList'),
(-@CGUID,0,0,0,8,0,100,0,43568,0,0,0,80,@CGUID*100,0,0,0,0,0,1,0,0,0,0,0,0,0,'Invisible Stalker - On SpellHit \'Frost Strike\' - Call ActionList'),
(-(@CGUID+1),0,0,0,8,0,100,0,43568,0,0,0,80,@CGUID*100,0,0,0,0,0,1,0,0,0,0,0,0,0,'Invisible Stalker - On SpellHit \'Frost Strike\' - Call ActionList'),
(-(@CGUID+2),0,0,0,8,0,100,0,43568,0,0,0,80,@CGUID*100+1,0,0,0,0,0,1,0,0,0,0,0,0,0,'Invisible Stalker - On SpellHit \'Frost Strike\' - Call ActionList'),
(@CGUID*100,9,0,0,0,0,100,0,2400,2400,0,0,11,43569,2,0,0,0,0,19,23033,20,0,0,0,0,0,'Invisible Stalker - Action list - Cast \'Frost\''),
(@CGUID*100+1,9,0,0,0,0,100,0,2400,2400,0,0,11,43569,2,0,0,0,0,10,@CGUID+4,23033,0,0,0,0,0,'Invisible Stalker - Action list - Cast \'Frost\'');

-- This is not working
-- (24029,0,2,0,1,0,100,0,3000,3000,3000,3000,45,0,1,0,0,0,0,10,@CGUID+3,23033,0,0,0,0,0,'Wyrmcaller Vile - OOC - Set Data 0 1'),
-- (-(@CGUID+3),0,0,0,38,0,100,0,0,1,0,0,11,43591,2,0,0,0,0,7,0,0,0,0,0,0,0,'Invisible Stalker (Floating) - On Data 0 1 Set - Cast \'Soul Siphon\''),

**Comment by Killyana** [comment]
``` sql 
SET @Oguid :=5842;
DELETE FROM `gameobject` WHERE `id`=186487;
INSERT INTO `gameobject` (`guid`, `id`, `map`, `spawnMask`, `phaseMask`, `position_x`, `position_y`, `position_z`, `orientation`, `rotation0`, `rotation1`, `rotation2`, `rotation3`, `spawntimesecs`, `animprogress`, `state`) VALUES
(@Oguid, 186487, 571, 1, 1, 2821.75, -3603.67, 245.555, 3.49556, 0, 0, 0.984379, -0.176061, -300, 0, 1);

**Comment by Killyana** [comment]
Looks pretty good I will make some changes to fix the visual issues.

**Comment by sirikfoll** [comment]
creature @CGUID+8 was added to avoid the wyrmcaller "reset"?
this change may be needed to avoid one of he stalkers casting back on the @CGUID+8
```diff
- (@CGUID*100,9,0,0,0,0,100,0,2400,2400,0,0,11,43569,2,0,0,0,0,19,23033,20,0,0,0,0,0,'Invisible Stalker - Action list - Cast \'Frost\''),
+ (@CGUID*100,9,0,0,0,0,100,0,2400,2400,0,0,11,43569,2,0,0,0,0,19,23033,19,0,0,0,0,0,'Invisible Stalker - Action list - Cast \'Frost\''),
```
Maybe a condition to avoid summon multiple drakes, I think Glacion should be summoned in a higher place an fly down, some waypoints, but i don't have this data
```sql
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=17 AND `SourceEntry` IN (42817);
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
(17,0,42817,0,0,29,0,24019,100,0,1,0,0,'','Summon Glacion if !Glacion is near');

**Comment by Killyana** [comment]
Creature @CGUID+8 was added to cast 43568 instead of the Wyrmcaller Vile, because it breaks the other other visual spell.

Distance updated to 19.

For Glacion he's already spawned guid=115879 with waypoints, we need just to add immune to pc, and rescript the spell  42817  or the event_script 15578 to notify Glacion to set it active and start wp to the plateforme, once there remove_immune to pc,  activate gravity and attack closest player.

**Comment by Killyana** [comment]
TO DO:
A spell_script for  42817 that turn  guid=115879 active and start a waypoint to the pate form, once the waypoint ends, disable gravity and attack closest player.

**Comment by ccrs** [comment]
should the wyrm be pre-spawned, or could the spell trigger a summon?

**Comment by Killyana** [comment]
No it's pre-spawned, the actual DB script on event_script 1557 is wrong.

**Comment by ccrs** [comment]
well, if the wyrm spawns on an unactive grid, the script should load it first to access it.
I'll give it a go and wait for other collabs to check it xd

Could you please paste the spawn coords?

**Comment by Killyana** [comment]
The wyrm spawns here: 2536.8, -3681.7, 308.662,  but it has also waypoint_data

**Comment by Aokromes** [comment]
anything here is valid?

**Comment by Aokromes** [comment]
what's missing here to close this ticket?

**Comment by tkrokli** [comment]
May as well close the issue and wait for someone to report new issue tickets with this quest again. Very unlikely there will be any follow-up now that there has been a full year without any new input on this page...

**Comment by Sorikoff** [comment]
Works fine on latest TC.
