### ISSUE TITLE
Hallows End [item] Hallow's End Pumpkin Treat 20557

### ISSUE THREAD

**Issue by lynxzor** [TrinityCore/TrinityCore#3573]
Missing the 4 possible auras when eaten
    Great Pumpkin 24924 which should have a chance trigger Hallow's End Fright 24924 (can proc a chill/ slow effect) on enemy
    Skeletal Giant 24925 
    Ghost 24927 
    Pirate  24926 - no model change or swim speed increase

up 42
dc2bdb8

**Comment by Aokromes** [comment]
Anyone can make a PR with the sugested changes by anubiss?

**Comment by tkrokli** [comment]
I am in the process of making it, just have to finish testing the issues I said I will test. :-)

**Comment by joschiwald** [comment]
cee1c0789acb7d75e453ed355a5d68781a5dec4c
