### ISSUE TITLE
Hallowed End [items] Hallowed Wands

### ISSUE THREAD

**Issue by lynxzor** [TrinityCore/TrinityCore#3574]
Following wands are missing their buff/model change
Ninja 20398
Pirate 20397
Gnome 20399

Also the Random 20413 wand isn't working

up42
dc2bdb8

**Comment by DevRival** [comment]
I work with very bad git, here is my version of the hotfix.

[Link](https://gist.github.com/DevRival/768343d1c114c3ffdba9)

**Comment by tkrokli** [comment]
@DevRival : tell me which file & branch to use, I can help you create a PR with your name on it.

**Comment by DevRival** [comment]
The script was created by a separate file on the way \src\server\scripts\Events\hallowsend.cpp. 

You can choose for yourself the way , just in spell_generic.cpp

**Comment by tkrokli** [comment]
First, a necessary change to the SQL part; `Never delete spell scripts by ID, use ScriptName.`
```sql
DELETE FROM `spell_script_names` WHERE `ScriptName`= 'spell_halloween_wand';
INSERT INTO `spell_script_names` (`spell_id`,`ScriptName`) VALUES
(24717, 'spell_halloween_wand'),
(24718, 'spell_halloween_wand'),
(24719, 'spell_halloween_wand'),
(24720, 'spell_halloween_wand'),
(24737, 'spell_halloween_wand');
```
(Notice also that it is often useful to sort the spell IDs numerically ascending.)

Second, why isn't 24724, 24733 and 24741 included in the SQL, but present in the .cpp?

wowhead link  | .cpp spell name
------------- | -------------
www.wowhead.com/spell=24717/pirate-costume  | `SPELL_HALLOWEEN_WAND_PIRATE`
www.wowhead.com/spell=24718/ninja-costume  | `SPELL_HALLOWEEN_WAND_NINJA`
www.wowhead.com/spell=24719/leper-gnome-costume | `SPELL_HALLOWEEN_WAND_LEPER_GNOME`
www.wowhead.com/spell=24720/random-costume | `SPELL_HALLOWEEN_WAND_RANDOM`
www.wowhead.com/spell=24724/skeleton-costume | `SPELL_HALLOWEEN_WAND_SKELETON`
www.wowhead.com/spell=24733/bat-costume | `SPELL_HALLOWEEN_WAND_BAT`
www.wowhead.com/spell=24737/ghost-costume | `SPELL_HALLOWEEN_WAND_GHOST`
www.wowhead.com/spell=24741/wisp-costume | `SPELL_HALLOWEEN_WAND_WISP`

Notice also the confused spell IDs 24733 (BAT) <=> 24741 (WISP) in your gist file.

**Comment by DevRival** [comment]
Thank you for your help on the error assembly is my fail. Here are the latest changes on all of your tips.

[Link](https://gist.github.com/DevRival/d38d9f702b865e01c30f) 

As you noticed , I moved the script in spell_holiday also changed the name sripts.

**Comment by tkrokli** [comment]
OK, thanks a lot. I also think I found out what I did wrong in my first attempt where I got a compile error.
When I added the new line in `AddSC_holiday_spell_scripts()` I forgot to remove `_SpellScript` at the end.
```diff
 void AddSC_holiday_spell_scripts()
 {
     // Love is in the Air
     new spell_love_is_in_the_air_romantic_picnic();
     // Hallow's End
     new spell_hallow_end_trick();
     new spell_hallow_end_trick_or_treat();
     new spell_hallow_end_tricky_treat();
+    new spell_hallow_end_wand();
     // Pilgrims Bounty
     new spell_pilgrims_bounty_buff_food("spell_gen_slow_roasted_turkey", SPELL_WELL_FED_AP_TRIGGER);
     new spell_pilgrims_bounty_buff_food("spell_gen_cranberry_chutney", SPELL_WELL_FED_ZM_TRIGGER);
```
I am testing your code now, will post an update after compile and initial startup testing is done.

**Comment by DevRival** [comment]
Plz close.

**Comment by tkrokli** [comment]
Hmm, weird. I thought this would automatically close when the PR was merged.
Would it have anything to do with the PR not being cherry-picked into 6.x ?
