### ISSUE TITLE
Hunters pet disappear after change spec

### ISSUE THREAD

**Issue by Bezo** [TrinityCore/TrinityCore#3610]
get some Hunter BM and some tame exotic/elite pet.
put the pet in the stable master
change to different spec. like MM or SURV
the exotic pet disappear when you change back to BM he not in the stable.

Note:
its seems that its removed from the characters_pet for some reason. 

Server info:
Core: ddec56b3e0ec
OS : Linux
TDB 335.11.42+
##

**Comment by jackpoz** [comment]
What should happen in case someone has an exotic pet tamed and tries to change spec ? Should it not allow to change spec if active and not allow to take the pet out of the stabled ones ?

**Comment by Killyana** [comment]
According to some sources:
"If you change specs with a exotic pet it will be de-summoned and you will have to go to a stable master to retrieve a pet you can still use."
"when you switch specs using Dual Specs, or unlearn talents at the trainer, your pet will de-spawn as if you used Dismiss Pet. Then you use Call Pet to get it back."
"If you put him in the stables then he'll stay there til you respec BM. If you have him out when you respec though then you'll lose him completely."

https://legacy.zam.com/wiki/WotLK_Hunter_FAQ_%28WoW%29
https://www.wowhead.com/forums&topic=150236#p1945832

So when you change spec, your pet will always be dismiss and put  inside the stable, if there's no free slot it will be abandoned and lost.

**Comment by illfated** [comment]
Would it be reasonable to say that the code responsible for changing the player spec should check for
- active hunter pet
- if yes, is slot available in stable
- move pet to first free stable slot
- only if no slot is free, delete pet

**Comment by MrSmite** [comment]
> So when you change spec, your pet will always be dismiss and put inside the stable, if there's no free slot it will be abandoned and lost.

Yes, for exotic pets. A normal pet is simply "dismissed" (it doesn't need to go into the stable) and after you respec you simply use "call pet".

With exotic pets, you have to have a free stable slot otherwise they're lost forever. Kinda stupid but so were quivers taking up a bag slot...
