### ISSUE TITLE
Spells -  effectHandleMode

### ISSUE THREAD

**Issue by lost-illusion** [TrinityCore/TrinityCore#3718]
This system is not fully correct.

For example, Spell: Righteous Defense
Targets for EFFECT_1 - SPELL_EFFECT_TRIGGER_SPELL setup in EFFECT_0 - SPELL_EFFECT_DUMMY, but EffectDummy starts only if effectHandleMode == SPELL_EFFECT_HANDLE_HIT_TARGET, EffectTriggerSpell starts if effectHandleMode == SPELL_EFFECT_HANDLE_LAUNCH_TARGET or SPELL_EFFECT_HANDLE_LAUNCH. 
We have:
Casts trigger spell and after setup targets.

Exists more some problem... Need finish work...

**Comment by Pro100Hens** [comment]
any news? i use hackfix
        case 24259: // Spell Lock silence
            spellInfo->speed = 80;
            break;
not work in druid (heal casts) only blanket 3 sec.
