### ISSUE TITLE
{Achievement} All Over The Isle

### ISSUE THREAD

**Issue by durrrr** [TrinityCore/TrinityCore#3773]
Hello,
I have encountered a problem while playing in "Isle of Conquest" Battleground. 

How to reproduce the bug: 
1. Enter "Isle of Conquest" Battleground.
2. Kill a player in the zones: Hangar, Docks, Horde keep, Alliance keep and Workshop in a single Battleground.

What should happen, what happens instead:
You should get a tick after killing an enemy in each zone and after getting all ticks you get the achievment. (notice the achievement data) instead, You get all ticks (Ticks are working), and you dont get the actual achievement after earning all ticks.

Some links:
http://www.wowhead.com/achievement=3853 --> The achievement.
http://www.wowhead.com/zone=4710 --> The Isle of Conquest Zone.

I'm running Unix on hash: 25cec68 , TDB 42 
Addons: AH bot and WG.

**Comment by Aokromes** [comment]
Working as intended on 8b50c142cbf7
