### ISSUE TITLE
{Quest} Sabotage the Warp-Gate!

### ISSUE THREAD

**Issue by durrrr** [TrinityCore/TrinityCore#3795]
Hello,
I have encountered a problem while Questing in "Netherstorm" zone. 

How to reproduce the bug: 
1. Get quest "Sabotage the Warp-Gate!"

What should happen, what happens instead:
You should get the quest "Sabotage the Warp-Gate! and then escort NPC: "Drijya" so she could sabotage the "Warp-Gate" while you defend her. (notice the quest data) instead, You get the quest from "Drijya" and she doesn't move. She doesnt start the Escorting part.

Some links:
http://www.wowhead.com/quest=10310 --> The quest.
http://www.wowhead.com/zone=3523 --> The Netherstorm Zone.
http://www.wowhead.com/npc=20281 --> The NPC

I'm running Unix on hash: 25cec68 , TDB 42 
Addons: AH bot and WG.
##

**Comment by RedSonja** [comment]
Anything new on this one?

**Comment by Rushor** [comment]
https://gist.github.com/Rushor/9980d11b8d935983a090

you may can convert this to sai

**Comment by ikir83** [comment]
Still not working Drijya not moving

Rev: 7834d339ad83
DB 336.60

**Comment by tkrokli** [comment]
@Rushor : your link is broken. Could you post a new link, if the gist still exists in your repo?
