### ISSUE TITLE
{Quest} You, Robot

### ISSUE THREAD

**Issue by durrrr** [TrinityCore/TrinityCore#3809]
Hello,
I have encountered a problem while Questing in "Netherstorm" zone. 

How to reproduce the bug: 
1. Get quest "You, Robot".
2. Get control over "Scrap Reaver X6000" with the item provided ("Scrap Reaver X6000 Controller").
3. Try and target "Negatron".

What should happen, what happens instead:
You should get the quest "You, Robot" and then get controll with the item provided over the robot standing near the quest giver, and then kill "Negatron". (notice the quest data) instead, You get the quest, you get the item provided, controll the robot, try to attack the "Negatron", but you cannot target him.

Some links:
http://www.wowhead.com/quest=10248 --> The quest.
http://www.wowhead.com/zone=3523 --> The Netherstorm Zone.
http://www.wowhead.com/npc=19851 --> The NPC
http://www.wowhead.com/item=28634 --> The object provided

I'm running Unix on hash: 25cec68 , TDB 42 
Addons: AH bot and WG.

**Comment by Frytiks** [comment]
Still not working. After using item nothing is done.

**Comment by Killyana** [comment]
Duplicated: https://github.com/TrinityCore/TrinityCore/issues/12407
