### ISSUE TITLE
{Quest} The Stones of Vekh'nir

### ISSUE THREAD

**Issue by durrrr** [TrinityCore/TrinityCore#3823]
Hello,
I have encountered a problem while questing in "Blade's Edge Mountains" zone. 

How to reproduce the bug: 
1. Get quest "The Stones of Vekh'nir".
2. Collect "Vekh'nir Crystal" and charge it at the "Vekh'nir Spell Circle" to create a "Charged Vekh'nir Crystal".
3. Try and complete the quest.

What should happen, what happens instead:
You should collect the "Vekh'nir Crystal" which drops from the mobs arround, charge in the "Vekh'nir Spell Circle" and return it to the quest giver which is "Dertrok".(notice the quest data) instead, you do everything mentioned above, go to the quest giver, and he doesnt let you complete the quest, still a gray exclamation mark.

Some links:
http://www.wowhead.com/quest=10565 --> The quest.
http://www.wowhead.com/item=30561 --> The object (Before charging).
http://www.wowhead.com/item=30567 --> The object (After charging).
http://www.wowhead.com/npc=21496 --> The NPC.
http://www.wowhead.com/zone=3522 --> The Blade's Edge Mountains Zone.

I'm running Unix on hash: 37abe2528c8efa4a99feca0bd0a8e0b5e6fa3efc , TDB 43+
Addons: AH bot and WG.

**Comment by Killyana** [comment]
Seems like the spell_effect "Transform Item" don't complete the quest as there's no item added in the bag, you have to put the item in the bank and take it back to complete the quest.
http://www.wowhead.com/spell=37172/imbue-crystal

**Comment by danlapps** [comment]
cannot go sniff, horde quest, sorry :)

**Comment by Killyana** [comment]
We don't need sniff in this case, it's a core issue.

**Comment by Aokromes** [comment]
#3505 generic ticket then.
