### ISSUE TITLE
[Sunwell Plateau]

### ISSUE THREAD

**Issue by weyun** [TrinityCore/TrinityCore#3843]
TDB 11_43 all works good except Kalecgos and Kil Jaeden!
Kalecgos is unkillable because at the the became immune to all damage and Kil Jaeden encounter is impossible avoid OBLIVION skill that deal 50k damage AOE, only this because missing orb to became dragon and reduce damage!

**Comment by Trisjdc** [comment]
Kil'Jaeden problem is indeed still around

**Comment by Killyana** [comment]
Kalecgos is fixed rev. 5dba91fb0e38
Kil Jaeden issues here https://github.com/TrinityCore/TrinityCore/issues/11624
