### ISSUE TITLE
[3.3.5][Warrior / Rage] Gaining Rage VS Training Dummies

### ISSUE THREAD

**Issue by EnteringCombat** [TrinityCore/TrinityCore#3856]
Hey,
When warriors auto-attack training dummies all output of rage gain is similiar to a ~level 1 warrior approx.
Each hit generates ~5 rage and each crit generas ~11 rage
This might be caused due to a similiar issue mentioned in regards of warrior melee hits being absorbed by the dummies. This requires verification.
Other bugs that play a part in this issue:
-ARPN not increasing rage gained

Rage could get upto almost 100 within 2 crit swings, much unlike the dummy which would generage not more than 20 rage.

Hash 37abe2528c8efa4a99feca0bd0a8e0b5e6fa3efc
Tdb: 335.11.43
Addons: wg(not tc) / ac1 / tc2 / armory / pvprank
OS Linux.

Thanks in advance.
##

**Comment by Keader** [comment]
No news? Hacks? Nothing? :(

**Comment by tkrokli** [comment]
Well, a new and documented confirmation on recent source could be useful too, just to be sure.

**Comment by Keader** [comment]
wow ! very nice ariel !

**Comment by Noryad** [comment]
i was not the only one to miss "the madness" of @ariel- ariel. Good Job
