### ISSUE TITLE
[Core/Mechanics/Spells] Spells that cause visual movement

### ISSUE THREAD

**Issue by Ric101** [TrinityCore/TrinityCore#3862]
Every spell that causes the NPC in question to move, either it is Vampiric Bite from BQL, Well of Souls on Devourer of Souls (http://www.wowhead.com/spell=68820) numerous charge, leap, and other mechanics that do not change the NPC's target, visual bug him

Its a general issue i believe, probably from the lack of packages sent to the client, since in reality (Ignoring Visual) every NPC that does these effects never leaves his place, you can melee him on his inicial pos, even if you see him somewhere else

BQL is probably the best quick example of this, to *unbug* her, she has to be moved

**Comment by Aokromes** [comment]
@Treeston this was fixed already? or still no?

**Comment by Treeston** [comment]
No idea, hard to tell from OP description, but I'd assume yes (even before spell facing).

**Comment by Aokromes** [comment]
Well, if this bug is still valid open a new ticket with one updated core and readable description.
