### ISSUE TITLE
{NPC} Gordawg

### ISSUE THREAD

**Issue by durrrr** [TrinityCore/TrinityCore#3941]
Hello,
I have encountered a problem while questing in "Nagrand" zone. 

How to reproduce the bug: 
1. Get any quest from "Gordawg".
2. Try to complete any of his quests.

What should happen, what happens instead:
You should get any of "Gordawg" quests, and just be able to complete them. (notice the quest data) instead, you try and interact with "Gordawg" after completing a quest, and you just cant you cant click him while he is with a "Yellow question mark". (After going back and forward from his zone, i was able to interact with him but it shouldn't work like that :o).

Some links:
http://www.wowhead.com/quest=9853 --> Example for a quest.
http://www.wowhead.com/npc=18099 --> The NPC
http://www.wowhead.com/zone=3518 --> The Nagrand zone

I'm running Unix on hash: 37abe2528c8efa4a99feca0bd0a8e0b5e6fa3efc , TDB 43+
Addons: AH bot and WG.

**Comment by Aokromes** [comment]
A lot of months after i asked feedback, closing. If this bug is still valid open a new ticket.
