### ISSUE TITLE
{Talent, core spells}Improved Health Funnel

### ISSUE THREAD

**Issue by Justiciar** [TrinityCore/TrinityCore#3961]
Dear Sir or Madam,
I have encountered a problem with the talent "Improved Health Funnel" while using the spell:"Health Funnel".
The problem is that there wasn't any damage reducing effect of 30% rank 2 "Improved Health Funnel" talent which should   enhance ths spell:"Health Funnel" I used on my minion while my minion has been attacked.
If this talent would have worked properly, the minion should got the 30% immunity to damage while the channeling was in process.
Any of the following not occurred.
Sincerely yours, 
                            Justiciar.
wowhead talent link: http://www.wowhead.com/spell=18704

wowhead ability link: http://www.wowhead.com/spell=755

Hash:37abe2528c8efa4a99feca0bd0a8e0b5e6fa3efc

Tdb: 335.11.43+

Addons: wg(not tc) / ac1 / tc2 / armory / pvprank

on Linux

**Comment by Keader** [comment]
Last time i checked, this talent is working (in recent revs)
