### ISSUE TITLE
DB/Waypoints: Argent Peacekeeper (Flying Dalaran Guards)

### ISSUE THREAD

**Issue by ndrut** [TrinityCore/TrinityCore#3967]
I noticed these particularly awkward moving NPC's. 

http://i.imgur.com/Jv0co.jpg
http://i.imgur.com/Fd2k2.jpg

DB GUID: 78187, current GUID: 78187.
Faction: 2072.
npcFlags: 0.
Entry: 35587.

And

DB GUID: 78186, current GUID: 78186.
Faction: 2072.
npcFlags: 0.
Entry: 35587.

Located in creature:

Confirmed after server restart. No commands or changes have been made to these NPC's. They continue to get stuck on the trees and land on invisible planes.
##

**Comment by danlapps** [comment]
@Killyana is this ready to ship ?

**Comment by Rushor** [comment]
:ship:  xD

**Comment by Killyana** [comment]
Yes it works correctly, my be I will add a permanent active grid for this npcs.

**Comment by ccrs** [comment]
@Killyana tested your fix and got these
````note
 WaypointMovementGenerator::LoadPath: creature Arelas Brightstar (Entry: 35604 GUID: 364100 DB GUID: 364100) doesn't have waypoint path id: 0
 WaypointMovementGenerator::LoadPath: creature Jaeren Sunsworn (Entry: 35589 GUID: 364101 DB GUID: 364101) doesn't have waypoint path id: 0
````

**Comment by Killyana** [comment]
DB error fixed and permanent Active grid added.

**Comment by ccrs** [comment]
how is the "permanent Active grid" functionality done? :)

**Comment by Killyana** [comment]
It made the npcs always active even if there's no player on their range.

**Comment by ccrs** [comment]
Sure, but how? Is it a sai action?

**Comment by Killyana** [comment]
Yes SMART_ACTION_SET_ACTIVE= 48 with param1= 0 or 1

**Comment by Kittnz** [comment]
I guess this will never be added because of the set active.

**Comment by Kittnz** [comment]
Well.. not if we make them despawn at some point and let them respawn again at the next point. Like d3ebb79d78b9d914c1c782e3824060d4fdb91893
What do you think @Killyana

**Comment by Killyana** [comment]
We need a summoner in this case, also using an active spawn in Dalaran is a bad Idea as all grids in the city will turn active if I'm not wrong.

**Comment by Kittnz** [comment]
only if the npc visits that area, also thats temporary once the whole path is done. It's the same as the transporters. those grids get activated to when it flys thru the space. Not an issue. maybe there is an summoner npc somewhere, i haven't checked.
