### ISSUE TITLE
{Quest} Mounting Up

### ISSUE THREAD

**Issue by durrrr** [TrinityCore/TrinityCore#3977]
Hello,
I have encountered a problem while questing in "Grizzly Hills" zone. 

How to reproduce the bug: 
1. Get quest from "Squire Percy".
2. Collect "Wild Carrots".
3. Try and use the "Stick" on the "Highland Mustang"s.

What should happen, what happens instead:
You should equip the "Stick", Collect 5 "Wild Carrots" than use them to lure the "Highland Mustangs" and get ticks for every mustang. (notice the quest data) instead, you collect the carrots, equip the stick, and when you try to lure the mustangs, nothing happens. you click on the item ("Stick") and it doesnt lure, or give a tick.

Some links:
http://old.wowhead.com/quest=12414 --> The quest
http://old.wowhead.com/object=189983 --> The object #1 
http://old.wowhead.com/item=37708 --> The object #2
http://old.wowhead.com/npc=26377 --> The NPC #1
http://old.wowhead.com/npc=26472 --> The NPC #2
http://old.wowhead.com/zone=394 --> The Grizzly Hills zone

I'm running Unix on hash: 37abe25 , TDB 43+
Addons: AH bot and WG.

**Comment by danlapps** [comment]
Was this ever pushed ? Is this still an issue or is it fixed ?

**Comment by Rushor** [comment]
well nope we need a new pr with a fitting sql file xD

**Comment by MitchesD** [comment]
https://github.com/TrinityCore/TrinityCore/commit/7d3668b0b91eb60149d88842248a0a54195f1da4
