### ISSUE TITLE
[Pilgrims Bounty] Food buffs

### ISSUE THREAD

**Issue by lynxzor** [TrinityCore/TrinityCore#3991]
You don't acquire the food buffs from eating the following foods:

Candied Sweet Potato 44839 
Cranberry Chutney 44830
Pumpkin Pie 44836
Slow-Roasted Turkey	44838
Spice Bread Stuffing 44837

You also can't eat from a Bountiful Feast 46887 to receive that food buff either and it disappears too fast.

up 43
c0c237f

**Comment by thomas33** [comment]
close?

**Comment by Killyana** [comment]
Bountiful Feast 46887 still cannot be used.

**Comment by Killyana** [comment]
Script for Bountiful Feast from Sniffs:

``` sql 
DELETE FROM `spell_scripts` WHERE `id`= 66477;
INSERT INTO `spell_scripts` (`id`, `effIndex`, `delay`, `command`, `datalong`, `datalong2`, `dataint`, `x`, `y`, `z`, `o`) VALUES 
(66477, 0, 0, 15, 66622, 2, 1, 0, 0, 0, 0),
(66477, 0, 0, 15, 66478, 2, 1, 0, 0, 0, 0),
(66477, 0, 0, 15, 66041, 2, 1, 0, 0, 0, 0);
