### ISSUE TITLE
[Pilgrims Bounty] bountiful tables

### ISSUE THREAD

**Issue by lynxzor** [TrinityCore/TrinityCore#3998]
http://www.wowhead.com/npc=32823 -- table
http://www.wowhead.com/npc=34823 -- cranberry chair
http://www.wowhead.com/npc=34822 -- pie chair
http://www.wowhead.com/npc=34824 -- potato chair
http://www.wowhead.com/npc=34819 -- stuffing chair
http://www.wowhead.com/npc=34812 -- turkey chair

The tables are not working at all.
Each table should have the 5 chairs, there's about 3 tables at each of the locations.
Each of the chairs is a vehicle and when you sit in one you get the vehicle actions bars of 6 skills of: feast on #food, pass the #food. Abilities depend on which you sit. These are the stuffing chair abilities:
1 pass the stuffing http://www.wowhead.com/spell=66259
2 feast on turkey http://www.wowhead.com/spell=61784
3 feast on cranberries http://www.wowhead.com/spell=61785
4 feast on stuffing http://www.wowhead.com/spell=61788
5 feast on sweet potatoes http://www.wowhead.com/spell=61786
6 feast on pie http://www.wowhead.com/spell=61787
Since its the stuffing chair the feast on stuffing option is always available and you can only feast on the other food if its passed to you.
If you eat a food you get 1 stack of its buff, eating it x5 times gives you the well fed buff also if you eat each of the 5x different foods x5 times then you get the sharing buff http://www.wowhead.com/spell=61849 
Passing can also result in a miss where instead you the throw the food at someone.
Depending on the location of the tables you can also get some other achievements listed here:
http://www.wowhead.com/achievement=3579 -- food fight 
http://www.wowhead.com/achievement=3557 -- pilgrims Paunch
http://www.wowhead.com/achievement=3581 -- pilgrims peril
http://www.wowhead.com/achievement=3558 -- sharing is caring

up 43
c0c237f
##

**Comment by BahDumbBugs** [comment]
As of 9633c8c it was still not working. Tested during Pilgrim's Bounty World Event.

**Comment by Kittnz** [comment]
it just needs to be scripted

**Comment by Keader** [comment]
87510f3be51c2fe4542da9607f679baa8c293124

**Comment by BahDumbBugs** [comment]
Dang..... now we have to wait til Thanksgiving 2017 to test. LOL

**Comment by BahDumbBugs** [comment]
Question though, was that just fixed for 335 or Master?

**Comment by Keader** [comment]
3.3.5
Need cherrypick to Master

**Comment by Strazhnik** [comment]
3.3.5 
Feast On Sweet Potatoes - don't use.

**Comment by Azmaeus** [comment]
The vehicles and spells seem to work. The vehicles have the correct "pass the x" spell, but not "feast on x", and none of the chairs have "feast on sweet potatoes". The chairs should have both "pass the x" and "feast on x" with x being the type of chair (e.g. The Sweet Potato Chair would have "Pass the Sweet Potatoes" and "Feast on Sweet Potatoes" available).

Currently on TrinityCore rev 42bc12ddb6b2; World DB: TDB 335.63

**Comment by sirikfoll** [comment]
Update your core, this was already fixed in https://github.com/TrinityCore/TrinityCore/commit/1a638b39e374fd4733be7d13bd9e4d4052412596

**Comment by Azmaeus** [comment]
Thanks!

**Comment by ChiefMcClane** [comment]
Hey

I have just noticed that the food goes but you can't sit down in Orgrimmar. There are benches. 

In Ironforge there are chairs, you can also sit down but the achievement is not updated, Ironforge remains greyed out. Nothing else happens when you sit down. 

I have updated the core.

Can anyone confirm this?

**Comment by illfated** [comment]
Tested this yesterday on TrinityCore rev. d163735abdf3 2020-09-29 17:31:50 +0200 (3.3.5 branch) (Win64, Release, Static).
The only 2 things you can do is 1) pick up the seasonal quest (visit the Hero's grave) from the nearby NPC, and 2) pick up food & drink.

The fish plate is sometimes hidden by 1 or 2 other dishes, though, depending on which table you look at (multiple spawns in 1 spot).

Notice that this is not [Pilgrim's Bounty](https://www.wowhead.com/pilgrims-bounty) (2020-11-23 - 2020-11-30).
This is the [Harvest Festival](https://www.wowhead.com/harvest-festival) (2020-09-29 - 2020-10-06).
(https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?event=11)

See also the Holiday Calendar: https://www.wowhead.com/events/holidays
(https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?events=1)

**Comment by ChiefMcClane** [comment]
> Notice that this is not [Pilgrim's Bounty](https://www.wowhead.com/pilgrims-bounty) (2020-11-23 - 2020-11-30).
> This is the [Harvest Festival](https://www.wowhead.com/harvest-festival) (2020-09-29 - 2020-10-06).
> (https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?event=11)
> 
> See also the Holiday Calendar: https://www.wowhead.com/events/holidays
> (https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?events=1)

Now this is embarrassing. That was the problem, I mixed up the festivals. Whops... Thanks for the quick answer @illfated
