### ISSUE TITLE
[Warlocks] Pet CD After Summon

### ISSUE THREAD

**Issue by Authority** [TrinityCore/TrinityCore#4005]
Hi
When you summon a Pet with warlock it suppose to Reset her CD even if you use Fel Domination or Regular summon
http://www.wowhead.com/spell=691
http://www.wowhead.com/spell=697
http://www.wowhead.com/spell=688
http://www.wowhead.com/spell=712
http://www.wowhead.com/spell=30146
 Fel Domination >> http://www.wowhead.com/spell=18708
Hash:37abe25
 TDB: 335.11.43+
 On Linux

**Comment by PaulHellCore** [comment]
From d9b59efecffaabeb172868be5bc73b27c68ba7aa Mon Sep 17 00:00:00 2001
From: PaulHellCore <pashka2030@bk.ru>
Date: Sat, 7 Feb 2015 17:21:47 +0300
Subject: [PATCH] Core/Spell: Fix Pets Unsummon

---
 src/server/game/Spells/SpellEffects.cpp | 8 ++++++++
 1 file changed, 8 insertions(+)

diff --git a/src/server/game/Spells/SpellEffects.cpp b/src/server/game/Spells/SpellEffects.cpp
index 6d3a4cd..e7ad3ad 100644
--- a/src/server/game/Spells/SpellEffects.cpp
+++ b/src/server/game/Spells/SpellEffects.cpp
@@ -3027,6 +3027,14 @@ void Spell::EffectSummonPet(SpellEffIndex effIndex)
             //OldSummon->Relocate(px, py, pz, OldSummon->GetOrientation());
             //OldSummon->SetMap(owner->GetMap());
             //owner->GetMap()->Add(OldSummon->ToCreature());
+			if (OldSummon->getPetType() == SUMMON_PET)
+			{
+				OldSummon->SetHealth(OldSummon->GetMaxHealth());
+				OldSummon->SetPower(POWER_MANA, OldSummon->GetMaxPower(POWER_MANA));
+				OldSummon->SetPower(POWER_ENERGY, OldSummon->GetMaxPower(POWER_ENERGY));
+				OldSummon->m_CreatureSpellCooldowns.clear();
+				OldSummon->m_CreatureCategoryCooldowns.clear();
+			}
 
             if (owner->GetTypeId() == TYPEID_PLAYER && OldSummon->isControlled())
                 owner->ToPlayer()->PetSpellInitialize();
-- 
1.8.3.msysgit.0

**Comment by PaulHellCore** [comment]
[GitHub](https://gist.github.com/PaulHellCore/0526d0eccd63b851b221) 
tested and works

**Comment by Keader** [comment]
OldSummon->m_CreatureSpellCooldowns.clear();

Error	1	error C2039: 'm_CreatureSpellCooldowns' : is not a member of 'Pet'	C:\TrinityCore\src\server\game\Spells\SpellEffects.cpp	3004	1	game

**Comment by tkrokli** [comment]
@Keader : your error message is correct, `m_CreatureSpellCooldowns` does not exist in the source, meaning that it is not defined. `CreatureSpellCooldowns` existed in https://github.com/TrinityCore/TrinityCore/blob/8aa55a0b570cfee0445cd841f86baa5ca433a803/src/server/game/Entities/Creature/Creature.h#L451 (6.x) around August 1., but seems to have been removed later (uncertain if that is related). You need to define it somewhere in the source code before it will work.

**Comment by Keader** [comment]
OldSummon->GetSpellHistory()->ResetAllCooldowns();

**Comment by Rushor** [comment]
@Keader: this stuff is still working?

**Comment by Keader** [comment]
Until the last time I tested, pets still on cooldown
i´m still using ```cpp OldSummon->GetSpellHistory()->ResetAllCooldowns(); ``` on ```cpp Spell::EffectSummonPet ``` function

**Comment by Rushor** [comment]
but if i remember right, not all pets should reset their cooldown no?

**Comment by Keader** [comment]
I confess that despite being using, I'm not sure if it blizzlike

**Comment by Shauren** [comment]
Not valid. See https://github.com/TrinityCore/TrinityCore/pull/16551#issuecomment-220298203
