### ISSUE TITLE
Problem with email and deleted characters

### ISSUE THREAD

**Issue by DarkS1de** [TrinityCore/TrinityCore#4022]
If I send a mail with money and items (boa) from my PG to another into my account.
and I delete this PG before read this mail.

happens that I receve a mail from <non existing character> and many items are lost.

TC: cab3def3a4f81a9763f9bea84864e7aa9ae6f794
DB: TDB 11.43
Patch: AC1
##

**Comment by mik1893** [comment]
this doesn't happen unless you are running a server which deletes immediatly characters.
You need to setup 
CharDelete.Method = 0
and a number of days in CharDelete.KeepDays = 30

**Comment by Shauren** [comment]
It should work regardless of config values

**Comment by Treeston** [comment]
Cannot reproduce on 250e8d9. Mail appears as sent from "Unknown", but can be interacted with normally.
