### ISSUE TITLE
[Boss] Blackheart the Inciter

### ISSUE THREAD

**Issue by TheMaaster** [TrinityCore/TrinityCore#4047]
as we tried to work our way into Shadow Labyrith we ran in to some trouble with 
Blackheart the Inciter (http://old.wowhead.com/npc=18667)
each time he did his Incite he would kinda reset...
now i think i found the problem, but don't ask me on a  technical lvl.

according to wowhead he should do:
   Incite Chaos (http://old.wowhead.com/spell=33676) 
   "Incites chaos in the minds of all enemies, causing them to randomly attack each other."
but judging by the icon, he actually did:
   Incite Chaos (http://old.wowhead.com/spell=33684) 
   "Drives the target into a chaotic rage, attacking anyone nearby."
that last one also has a charm aura, and that causes all to assist, and him loosing agro thus resetting.
(also see http://old.wowhead.com/spell=35120 for char)

so in my humble opinion changing 33684 to 33676 would fix him.

**Comment by Aokromes** [comment]
Generic bug: #4723

**Comment by xStarfall** [comment]
This persists on 60d1c0e20d3f8f32de81bff047531b927e586a97 even if it might be marked as closed in #4723 by 4e4b2b9a138650ebe6087e18dc392f08dafe4e37

**Comment by tkrokli** [comment]
Hmm. Maybe open a new issue with renewed documentation & checking if there are any open PRs for this?
