### ISSUE TITLE
[Bug/Spell]Anti-Air Rocket

### ISSUE THREAD

**Issue by Crysicle** [TrinityCore/TrinityCore#4078]
Bug:
Anti-Air Rocket spell witch is used by Salvaged Siege Engine's passenger damages not only enemies but also friendly raid members whenever they're not mounted on a vehicle.

Links:
Anti-Air Rocket - http://old.wowhead.com/spell=62359
Salvaged Siege Engine - http://old.wowhead.com/npc=33060

Core revision: Trinity Core 4f738fe75a89+
Database revision: TDB 335.11.44
Addons: Anticheat1

**Comment by joschiwald** [comment]
fix provided in #15080
