### ISSUE TITLE
[Bug]Risen Drakkari Bat Rider

### ISSUE THREAD

**Issue by Crysicle** [TrinityCore/TrinityCore#4104]
Bug:
When Risen Drakkari Bat Rider is aggroed, he deals damage while you cannot deal the damage back because he is untargetable.

Link:
Risen Drakkari Bat Rider - http://old.wowhead.com/npc=26638

Screen:
http://img265.imageshack.us/img265/4041/wowscrnshot112711161345.jpg

Core revision: Trinity Core 4f738fe75a89+
Database revision: TDB 335.11.44
Addons: Anticheat1

**Comment by Rushor** [comment]
on retail they only fly around and don't react at all to player:

fix:

```sql
UPDATE `creature_template` SET `flags_extra`=2 WHERE  `entry` IN (26638, 31351);
```

**Comment by MitchesD** [comment]
already fixed in https://github.com/TrinityCore/TrinityCore/commit/e90d18af31d992a8d0ef87ae2f5f2f91ccf1295d
