### ISSUE TITLE
Ethereal Soul-Trader not working as intended

### ISSUE THREAD

**Issue by tippythop** [TrinityCore/TrinityCore#4152]
Upon learning the item and summoning him he should :

1: Should emote "I have arrived. Shall we set to work, then?
2: He follows and absorbs souls from slain mobs in return for Ethereal Credits http://www.wowhead.com/item=38186
also to earn the credit mobs must be capable of giving experience / honor, i.e. green or harder, and character must have the killing blow
3: He acts as a vendor where the items he sells are traded for Ethereal Credits http://www.wowhead.com/item=38186

Also this screenshot http://www.wowhead.com/npc=27914#screenshots:id=87517 shows that he also has gossip flags as well

I have seen as well that you cannot sell anything to him.

This first link is for some of the items he sells : http://www.wowhead.com/search?q=soul-trader%27s#
http://www.wowhead.com/item=38308
http://www.wowhead.com/item=38294
http://www.wowhead.com/item=38291
http://www.wowhead.com/item=38300

I am using revision: df3f11dc805a
##

**Comment by Aokromes** [comment]
@mik1893 can you convert https://github.com/TrinityCore/TrinityCore/issues/4152#issuecomment-49161738 to spell_scripts if possible?

**Comment by mik1893** [comment]
aokromes - i eventually had this workign with a set of awful hacks.
It requires quite some work to be properly fixed.

**Comment by Aokromes** [comment]
@Keader any idea on this?

**Comment by Aokromes** [comment]
"I have seen as well that you cannot sell anything to him." this part now is implemented.

**Comment by DanVS** [comment]
I think there is need of passing Object GUID from spell script to Creature AI Script. Is this even possible?

**Comment by DanVS** [comment]
OK, I have implemented more or less working solution, but it does use `UpdateAI(uint32 diff)` calls instead of Events system. Would that be acceptable, @Aokromes?

**Comment by Keader** [comment]
I looked around some days ago, and you dont need make a big CreatureScript to fix it.
Just SpellScripts can handle with all Soul Trader stuffs.
Spells here (https://github.com/TrinityCore/TrinityCore/issues/4152#issuecomment-54674954) and here (https://github.com/TrinityCore/TrinityCore/issues/4152#issuecomment-55532832) need be scripted.
If i remember right, you just need a little CreatureScript to make owner (player) has ProcAura

**Comment by DanVS** [comment]
But how about Talk?

**Comment by Keader** [comment]
If i remember right he need talk "3 times"

1 - On spawn (can be inside of JustAppeared hook, together with cast proc spell on player)
2 - When player kill someone (can be inside of AuraScript of Proc Effect)
3 - When he send token to owner (can be inside of SpellScript too)

inside of Spell/AuraScript you can use: (remember to change GetTarget/GetCaster, need check what is the soul trader)
```cpp
if (Creature* soulTrader = GetTarget()->ToCreature())
    soulTrader->AI()->Talk(XXXXX);
```

**Comment by Aokromes** [comment]
ba9943d
