### ISSUE TITLE
{Zone/NPC} Caverns of Time / Time Watcher

### ISSUE THREAD

**Issue by durrrr** [TrinityCore/TrinityCore#4167]
Hello,
I have encountered a problem while roaming in "Caverns of Time" zone. 

How to reproduce the bug: 
1. Go to Caverns of Time.

What should happen, what happens instead:
You should go to "Caverns of Time" and see the dragons (Time Watchers) roaming arround / flying arround. (notice the quest data) instead, you see wierd floating arround dragons  in the air that moving arround like tetris.

An image that will explain a little better:
http://img546.imageshack.us/img546/9269/dragonswithaids.jpg

A link:
http://old.wowhead.com/npc=19918 --> The NPC 

I'm running Unix on hash: 10444a1 , TDB 43+
Addons: AH bot and WG.

**Comment by Killyana** [comment]
I will add on this ticket all events an visual stuff on Caverns of Time:
``` sql
UPDATE `creature_template` SET `InhabitType`=4 WHERE `entry` IN (20142, 19918, 20069);
UPDATE `creature_addon` SET `bytes2`=4097 WHERE `guid` IN (23472, 23473);

**Comment by Aokromes** [comment]
http://www.wowhead.com/npc=19918/time-watcher#comments

**Comment by SQLfix** [comment]
@Killyana  very nice work
