### ISSUE TITLE
[Bugged Quest]Flight of the Wintergarde Defende

### ISSUE THREAD

**Issue by SimulationWow** [TrinityCore/TrinityCore#4175]
Hello,
I have encountered a problem With the spell of Wintergarde Gryphon Whistle.

How to reproduce the bug:
1. Get the quest Flight of the Wintergarde Defender.
2. Use the item Wintergarde Gryphon Whistle.
3. Get up on the Gryphon.

What should happen, what happens instead:
Skill 1 Should Grab someone on the Gryphon, Skill 2 Should Drop off someone and skill 3 Increase the flight speed by 350%.
Skill 1+2 Doesnt work, when you cast skill 1 "Rescue Villager" nothin happend.

Links :
Quest -> http://old.wowhead.com/quest=12237
Quest Item -> http://old.wowhead.com/item=37287#comments
Video -> http://www.youtube.com/watch?v=3MHyoWDaLJQ

I'm running Unix on hash: 367122dd62785a413bfb80d33359c67dba59cded , TDB 43+
Addons: AH bot and WG.

**Comment by alein** [comment]
Hello again.

The quest is work to the part when you should use [Rescue Villager](http://www.wowhead.com/spell=48363/rescue-villager). When I try to use it close to some villager, I get message "You can't do that yet"

[Screenshot](http://s22.postimg.org/j37h2smmn/werwrwer.png)

Another thing is that if you kill undead mobs around villagers, they say something like: Finally! A hero has come..."  then run a bit an despawn.

Trinity Core: 8197da7
Database: TDB_full_335.57_2014_10_19 + updates to the core above.

Regards.

**Comment by Aokromes** [comment]
Working as intended on fa7663a9bcde, be sure you rescue Helpless Wintergarde Villager not trapped Wintergarde Villager.
