### ISSUE TITLE
CC/stunned NPCs (mobs) often flee ignoring the stun effect

### ISSUE THREAD

**Issue by Loginisalreadytaken** [TrinityCore/TrinityCore#4193]
If the NPC is stunned by Frost Nova or Kidney Shot and then loses health below the fleeing limit, it **kind of** runs away anyway - it runs away and stands still at the same time.

What happens is that it looks like it's running away, but to hit it in melee, one must remain where the NPC was stunned. If one tries to run after it, the error "You are facing the wrong way" appears - if one stands still, it's quite possible to continue hitting the air and hurting the enemy.
When the stun breaks, the NPC's actual position gets updated to where it *ran* and activates an ally, so the running part only occurs graphically, not "physically".

This is hard to notice with Frost Nova since the mage is just about always in range and facing the right way anyway, but with a melee character, it's obvious.

Version: 3.3.5a (12340)
Core revision: Trinity Core 86f6d73d6aed+
Database revision: TDB 335.11.44

For searching: crowd control.

**Comment by Aokromes** [comment]
b0e7b458408b85e44734b0e876e83fc4473cc3ec
