### ISSUE TITLE
{Quest} Shoot 'Em Up

### ISSUE THREAD

**Issue by durrrr** [TrinityCore/TrinityCore#4207]
Hello,
I have encountered a problem while questing in "Icecrown" zone.

How to reproduce the bug: 
1. Get quest "Shoot 'Em Up".
2. Try and kill 15 "Jotunheim Proto-Drakes" and their riders.

What should happen, what happens instead:
You should take the quest and try to kill 15 "Jotunheim Proto-Drakes" and their riders on the "Jotunheim Rapid-Fire Harpoon". (notice the quest data) instead, you try to aim and kill them and it doesnt hit anything. like hitting air.

Some links:
http://www.wowhead.com/npc=30330 --> The NPC
http://www.wowhead.com/npc=30337 --> The NPC #2
http://www.wowhead.com/quest=13069 --> The quest 
http://www.wowhead.com/zone=210 --> The "Icecrown" zone

I'm running Unix on hash: 367122d , TDB 43+
Addons: AH bot and WG.
##

**Comment by dr-j** [comment]
Looks like the same spell is used on the harpoons used for skadi in Upgarde keep or conditions suggest it.

Adding the following with different else group fixes the issue and damages and gives credit for quest when hit by harpoons.

~~~sql
    DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=13 AND `SourceEntry`=56578 AND `ElseGroup`=1;
    INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
    (13, 3, 56578, 0, 1, 31, 0, 3, 30330, 0, 0, 0, 0, '', 'Spell Rapid-Fire Harpoon targets only Jotunheim Proto-Drake');

**Comment by JunkyBulgaria** [comment]
npc sai sai

`
DELETE FROM `smart_scripts` WHERE `entry` = 30330;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (30330, 0, 1, 0, 6, 0, 100, 0, 0, 0, 0, 0, 33, 30330, 0, 0, 0, 0, 0, 18, 40, 0, 0, 0, 0, 0, 0, 'On Death - Kill Credit');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (30330, 0, 0, 0, 25, 0, 100, 0, 0, 0, 0, 0, 48, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Jotunheim Proto-Drake - On Reset - Set Active');

`

**Comment by Aokromes** [comment]
Anything here can be pushed?

**Comment by JunkyBulgaria** [comment]
the smartai and conditions are working great so far, you can kill them and quest is doable so i guess it's ok to push them

last issue is the spell cooldown from the cannon because it doesnt have any

**Comment by Killyana** [comment]
Why the set active_action?

**Comment by JunkyBulgaria** [comment]
was there already, from old ytdb i'm using and i haven't deleted it, i think it works without it too
