### ISSUE TITLE
Item D.I.S.C.O. does not cast spell for dance

### ISSUE THREAD

**Issue by duhow** [TrinityCore/TrinityCore#4214]
Item D.I.S.C.O. (38301) summons creature 27989. When you right-click the NPC, it should cast spell 50317 (the spell works fine), but it doesn't work.
Rev: eb190eb0bc99+

**Comment by lainimer** [comment]
no't work last revision

**Comment by Nyeriah** [comment]
There isn't such a thing as latest revision, it works fine on 3x. If you're trying it at 6x then I can think of several reasons why it wouldn't be working

**Comment by lainimer** [comment]
im use 3.3.5 branch,no't work

**Comment by Killyana** [comment]
It 's just a missing  spell_click on object=190351, once a player click, the spell 50493 will be casted and he will start listening to the music and dancing.

**Comment by Killyana** [comment]
``` sql
SET @Disco         :=190351;
UPDATE `gameobject_template` SET `AIName`='SmartGameObjectAI' WHERE `entry` IN (@Disco);
DELETE FROM `smart_scripts` WHERE `entryorguid`=@Disco AND `source_type`=1;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES 
(@Disco, 1, 0, 0, 64, 0, 100, 0, 0, 0, 0, 0, 85, 50493 , 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'Disco - On gossip hello - cast Listening to Music');

**Comment by lainimer** [comment]
testet,dance work,not music

**Comment by Killyana** [comment]
How to test it:
1- use the item to spawn the Disco Ball
2- remove the aura, and wait until the music stops (it's just for test purpose)
3- click on the Disco Ball, the character will start dancing and the music starts
Any other player from your faction can use the Disco Ball.

**Comment by Killyana** [comment]
test 7ee61140bf72
