### ISSUE TITLE
[Bug/Spawn]Chromie

### ISSUE THREAD

**Issue by Crysicle** [TrinityCore/TrinityCore#4222]
Bug:
The 3rd version of Chromie inside Culling of Stratholme is missing. He's needed to complete A Royal Escort.

Link:
Chromie - http://old.wowhead.com/npc=30997
A Royal Escort - http://old.wowhead.com/quest=13151

Core revision: Trinity Core 86f6d73d6aed+
Database revision: TDB 335.11.44
Addons: Anticheat1

**Comment by Aokromes** [comment]
Fixed long time ago.
