### ISSUE TITLE
[QUEST] Covert Ops - Beta (#1080)

### ISSUE THREAD

**Issue by Vavehl** [TrinityCore/TrinityCore#4246]
Quest Info: http://www.wowhead.com/quest=1080/covert-ops-beta

The red remote detonator (http://www.wowhead.com/item=5692) does not function. Although you can properly plant the red explosive charges (http://www.wowhead.com/item=5694) adjacent to the lumber mill wagon, clicking on the detonator does not cause ensuing mayhem. Note that the quest is still able to completed by stealth or brute force, but it would be nice to do it the proper way.

TC: af08693
OS: Windows 7 64bit
DB: TDB 335.11.44
##

**Comment by Killyana** [comment]
Merged with #4245
