### ISSUE TITLE
[BUG] Book "Evil Soothsaying for Dummies" not work

### ISSUE THREAD

**Issue by SignFinder** [TrinityCore/TrinityCore#4425]
This book
http://www.wowhead.com/object=177226#comments
works for switching profession specialization, learn and unlearn. Gnomish, goblin Engineering, Leatherworking specialty like Elemental or Dragonscale, alchemy specialization.

Item not work :-(

**Comment by Exodius** [comment]
Close as per dbf9f58351ea1f80c5e892d062904f9f73b92568?
