### ISSUE TITLE
[The Lich King] Summoning effect of adds

### ISSUE THREAD

**Issue by Aristoo** [TrinityCore/TrinityCore#4427]
Summoning effect of adds (Ghouls, Horrors) is broken. When adds climb out of the ground and they have some pet around themself, they skip summoning effect and instantly attack nearby pet. After ~3 seconds (so after time when summoning effect should end) they attack players. During this ~3sec they can not be pulled (pull does not have any effect.. they still attack pet and after it attack players) and they also ignore aggro from attacks.
It is very unpleasant for tanks who try tank them, because they have big melee DMG so they easily kill healer or any cloth class.
##

**Comment by Runico** [comment]
Confirm this one just for Raging Spirits ( Entrys 36701,39302,39303,39304 )

**Comment by dixanackmad** [comment]
confirmed on: http://dithub.com/TrinityCore/TrinityCore/commit/b1d0855624d1c83850fc36f524237d7f7c1336b

**Comment by SQLfix** [comment]
Confirm this one just for Raging Spirits ( Entrys 36701,39302,39303,39304 ) 
should attacks player after 3sec delay

https://github.com/TrinityCore/TrinityCore/commit/0be0606593cf6ce8a08735b070e64efa6b6f1667

**Comment by Keader** [comment]
2792046dc7a229180d27dfdc4ce37ccfb84c8a27
