### ISSUE TITLE
[Core/Spells] Magic Absorption Calculation

### ISSUE THREAD

**Issue by maxxx** [TrinityCore/TrinityCore#4524]
http://www.wowhead.com/spell=29444#comments
Increases all resistances by 1 per level 
now it gives "level-1" resistance (79 on level 80). Yes it' small difference, but may be in other place importance will be higher.
wrong calculation here (not sure at 100%):
SpellEffectInfo::CalcValue
...
level -= int32(_spellInfo->SpellLevel);

f283a7b116d7bdcf1b35361df85b2d07927107f2

**Comment by Rushor** [comment]
https://github.com/TrinityCore/TrinityCore/pull/16494

**Comment by mik1893** [comment]
mmh this should be closed... fixed by #16494

**Comment by Rushor** [comment]
Reference:

https://github.com/TrinityCore/TrinityCore/commit/343c2fbf526a279964ca7d1927a2e245821607c3
https://github.com/TrinityCore/TrinityCore/commit/07bb3037dec38b6e5bb8672e3dd03683d4702db1
