### ISSUE TITLE
Go rotation

### ISSUE THREAD

**Issue by malcrom** [TrinityCore/TrinityCore#4543]
I have noticed many go's not rotated properly. Wondering if anyone else has the same issue?

**Comment by Treeston** [comment]
Why the close? Is this issue resolved @Killyana?

**Comment by Killyana** [comment]
Yes by https://github.com/TrinityCore/TrinityCore/commit/2967bf59b4a47837b85c995b732a6761c9c35f7e

**Comment by Treeston** [comment]
Awesome :+1:
Tagging PR #14146
