### ISSUE TITLE
[SPELL] Gem Perfection

### ISSUE THREAD

**Issue by jokerstar** [TrinityCore/TrinityCore#4688]
Spell - Gem Perfection ID 55534 http://www.wowhead.com/spell=55534
 When you finish quest you will gain Gem perfection. http://www.wowhead.com/quest=12918
 Problem is when you producing jewels you have chance to make a perfection gem, but it doesn´t work, you still produce normal jewels

**Comment by Aokromes** [comment]
15cafba
