### ISSUE TITLE
[Bug]Reliquary of Souls spam

### ISSUE THREAD

**Issue by Crysicle** [TrinityCore/TrinityCore#4703]
Bug:
After one of the phases of Reliquary of Souls is done, the boss spams the log by yelling "I don't want to go back", it says it in less than a second about 4-10 times.

Links:
Reliquary of Souls - http://www.wowwiki.com/Reliquary_of_Souls
-Essence of Suffering - http://www.wowhead.com/npc=23418
-Essence of Desire - http://www.wowhead.com/npc=23419
-Essence of Anger - http://www.wowhead.com/npc=23420

Proof:
How it is - http://img830.imageshack.us/img830/3631/wowscrnshot010712205914.jpg
How it should be (08:16) - http://www.youtube.com/watch?v=ueHzTag9GBA&hd=1

Core revision: Trinity Core 991934911edb+
Database revision: TDB 335.11.44
Addons: Anticheat1

**Comment by Killyana** [comment]
Cannot reproduce on rev. 5b5c0938da0f

**Comment by Aokromes** [comment]
This was fixed long time ago.
