### ISSUE TITLE
[Item] Argent Squire , Argent Pony Bridle

### ISSUE THREAD

**Issue by BlackangelWow** [TrinityCore/TrinityCore#4710]
The item "Argent Pony Bridle" is bugged , when you click on it you should get option of:
- Bank
- Trader (vendor)
- Mailbox

But you can't see that list , 
You just see 
"Greetings name" 

In addtion there is item which call "Argent Pony Bridle" that should give mount for this companion what doesn't work as well

Related IDs:
http://old.wowhead.com/item=44998
http://old.wowhead.com/item=47541

Server info:
Hash: 090bb5a45e4b7608b57577c525a16416986a0b3e
Tdb: 335.11.43+

**Comment by Killyana** [comment]
Gossip options on retail: https://youtu.be/7Vectgmyto4?t=22s

**Comment by Xanvial** [comment]
Anyone tried gecko patch? It looks good

**Comment by sirikfoll** [comment]
I had it scripted(except the mailbox part) in SAI, but the cooldown debuffs doesn't get saved, so everytime you ressumon the pet, you can reuse the options

**Comment by Kittnz** [comment]
https://github.com/Kittnz/Sunwell/blob/master/src/server/scripts/Pet/pet_generic.cpp#L217
Sunwell did it like this, not sure if it is good or not. Just putting it here if anyone wants to test and pr it

**Comment by Xanvial** [comment]
@sirikfoll 
From wowhead, it seems there's 3 aura related to cooldown debuff
With educated guess
http://www.wowhead.com/spell=67334/tired it's given to the player (it's persistent through death and logout)
Both http://www.wowhead.com/spell=67401/tired and http://www.wowhead.com/spell=68852/tired used for the pet, one for horde the other for alliance (not sure which).

So maybe, when you summon the pet, you cast 67334 to the player then cast respective tired buff to the pet. For subsequent summon, first check the player for aura 67334, if it's there cast the tired buff for pet and disable the gossip.

**Comment by sirikfoll** [comment]
Fixed in https://github.com/TrinityCore/TrinityCore/commit/989aaaa8b5284bc707c94c62e6c50e9df3cbfc84
