### ISSUE TITLE
[QUEST] Dead Man's Plea (8945)

### ISSUE THREAD

**Issue by nelegalno** [TrinityCore/TrinityCore#4722]
You are supposed to free Ysida Harmon  ( http://old.wowhead.com/npc=16031 ) but instead currently you have to kill her in order to get quest credit and then run the whole instance again in order to return it to here.

**Comment by Killyana** [comment]
Ysida spawns if you kill Baron Rivendare on 45min after you enter the donjon and the quest is completed once the baron dies. Tested on rev. 5b5c0938da0f
