### ISSUE TITLE
[Bug]Domination makes the player "stick to one place"

### ISSUE THREAD

**Issue by Crysicle** [TrinityCore/TrinityCore#4723]
Bug:
Whenever a mob successfully casts Domination on a player, the character "gets stuck in one place" while still being able to move, but whenever the player uses a abilities like Prowl or Bear Form he comes back to the same place(the video will explain a lot more). I've tested this only on Harbinger Skyriss and Dark Rune Controller, but i think this accounts for all spells of the same name and perhaps all "mind control" spells as well.

Info:
Domination - http://old.wowhead.com/spell=51503
Video of the bug - http://www.dailymotion.com/video/xnj0dp_bug-report-domination_videogames

Core revision: Trinity Core 991934911edb+
Database revision: TDB 335.11.45
Addons: Anticheat1

**Comment by Expecto** [comment]
GetMotionMaster->Claer(); Solve Problem

**Comment by sirikfoll** [comment]
The above correction by Expecto is a hack ? It works for me.
Here it is, in diff
```diff
diff --git a/src/server/game/Entities/Unit/Unit.cpp b/src/server/game/Entities/Unit/Unit.cpp
index 653426e..9705703 100644
--- a/src/server/game/Entities/Unit/Unit.cpp
+++ b/src/server/game/Entities/Unit/Unit.cpp
@@ -9543,6 +9543,7 @@ void Unit::SetCharm(Unit* charm, bool apply)
             || charm->GetOwnerGUID() != GetGUID())
         {
             m_Controlled.erase(charm);
+            charm->GetMotionMaster()->Clear();
         }
     }
 }

**Comment by GeneralSaurfang** [comment]
Any news?

**Comment by Aokromes** [comment]
No.

**Comment by Tauriella** [comment]
Please Dev's fix this Bad Bug

**Comment by tkrokli** [comment]
Soon™

**Comment by Rushor** [comment]
the fix from @Expecto works very well.

**Comment by tkrokli** [comment]
@Expecto : would you like to post a Pull Request for your suggested fix?

**Comment by tkrokli** [comment]
In case anybody else want to try out Expecto's suggested fix, here is a diff for it:
```diff
diff --git a/src/server/game/Entities/Unit/Unit.cpp b/src/server/game/Entities/Unit/Unit.cpp
index f8810c9..7451efc 100644
--- a/src/server/game/Entities/Unit/Unit.cpp
+++ b/src/server/game/Entities/Unit/Unit.cpp
@@ -9569,12 +9569,13 @@ void Unit::SetCharm(Unit* charm, bool apply)
 
         if (charm->GetTypeId() == TYPEID_PLAYER
             || !charm->ToCreature()->HasUnitTypeMask(UNIT_MASK_MINION)
             || charm->GetOwnerGUID() != GetGUID())
         {
             m_Controlled.erase(charm);
+            charm->GetMotionMaster()->Clear();
         }
     }
 }
 
 int32 Unit::DealHeal(Unit* victim, uint32 addhealth)
 {

```
Why doesn't anybody make a PR out of this 1-liner? Is it because nobody wants to defend the code?

**Comment by Rushor** [comment]
hm this fix does not work all the time.

after applying this patch you will get a new problem:
1) player a in arean casts charm on player b
2) player b is affected by charm
3) charm on player b fades
3) player b gets somekinds stuck and runs straight in one direction without having the option to change the direction

some people say this has something to do with the activation / deactivation of autorun

personally i cannot reproduce this

**Comment by tkrokli** [comment]
Thanks for the explanation. I see what you mean (I think). Maybe `GetMotionMaster()->Clear()` is
not correctly applied in the suggested code, that it can cause incorrect MotionMaster behaviour?

**Comment by Expecto** [comment]
Another solution I have not yet found ...

**Comment by Rushor** [comment]
the better way would be to find out the actual reason for this bug first

**Comment by Aokromes** [comment]
4e4b2b9
