### ISSUE TITLE
[3.3.5] Core/Spell: Magma totem threat

### ISSUE THREAD

**Issue by lynxzor** [TrinityCore/TrinityCore#4728]
Currently mobs like to hunt out these totems and kill them when they are not meant to create any threat

"Magma Totem: The damage and scaling has been increased and no longer generates threat."

source: http://us.battle.net/wow/en/game/patch-notes/3-0-8

f283a7b
##

**Comment by Rushor** [comment]
but what happens if the player does not attack the creature and the totem casts it's spell on the creature? after some time the totem dealed more damage than the player.

in this case the creature should also NOT attack the totem?

**Comment by mik1893** [comment]
@Rushor  latest retail behaviour, afaik, the totems were just never getting harmed unless they were the only thing left to attack from an NPC

**Comment by Killyana** [comment]
https://github.com/TrinityCore/TrinityCore/issues/21178
