### ISSUE TITLE
[QUEST] The road to Falcon Watch 9375

### ISSUE THREAD

**Issue by phantomdl** [TrinityCore/TrinityCore#4769]
Core 528a9a6
DB 335.11.44
NO ADDONS

http://old.wowhead.com/quest=9375 The quest is able to be completed the problem is while you are escorting her there is mobs that are to spawn to attack her. They do spawn, then de-spawn with in a few seconds. They don't move or attack the npc you are protecting / escorting.

**Comment by dr-j** [comment]
Actually I may know something to do with this, there are several escort quests on tc where the escortee npc will walk straight past mobs which are meant to attack it.

If the player who is escorting the npc agros the npc(s) then the escort npc will attack but unless the escorting player enters into combat the escort npc walks straight past mobs.

and thats the ones where the creature does actually attack,

There are other escort quests where escortee does not even attack if the player does but continues walking, have found on some of these that cpp script changes faction on quest accept and then it wont attack any of the mobs which are meant to attack it but if faction is changed back to the original faction from db while the escort is running then it does attack mobs (cant remember name of quest(s) where found this off the top of my head

**Comment by Killyana** [comment]
In this case the npc change on the correct faction and get the correct react, his attacked and attack all hostile npcs.
