### ISSUE TITLE
After summoning with portal visual bug

### ISSUE THREAD

**Issue by Trista** [TrinityCore/TrinityCore#4779]
[http://www.wowhead.com/spell=698 - is affected also] - when the player who summon other player finish casting and the ritual is complete the visualisation of a portal who needs to be clicked doesn't dissapear /even if u click it after it stays and don't interract by any means/ , this continue till the summoner move from his position. I'm not sure when this got bugged, but it was not long ago /4-5 months or smth max/.

Sys: Windows 7
DB: 335.11.44

**Comment by Killyana** [comment]
This is still valid?
