### ISSUE TITLE
{NPC} Pustulent Horror

### ISSUE THREAD

**Issue by durrrr** [TrinityCore/TrinityCore#4869]
Hello,
I have encountered a problem in "Icecrown" zone.

How to reproduce the bug:
1. Attack "Pustulent Horrors".

What should happen, what happens instead:
You should try and kill these NPC .(notice the quest data) instead, there are a few of these NPC's that wont fight back, i have encountered only 1 that attacked me back, and some of them are not even letting you attack.
(These NPC's are a part of Horde/Alliance quest's so people might encounter that issue for a few times)

Some links:
www.wowhead.com/npc=31139 --> The NPC
http://old.wowhead.com/zone=210 --> The "Icecrown" zone

I'm running Unix on hash: 090bb5a , TDB 43+
Addons: AH bot and WG.

**Comment by Aokromes** [comment]
Fixed long time ago.
