### ISSUE TITLE
[Ulduar] Chopper's Tar vs Demolisher's Pyrite

### ISSUE THREAD

**Issue by angelovopsan** [TrinityCore/TrinityCore#4946]
After some tests I realised a majour bug, when you cast pyrite on slowed by tar effect  FL, he doesn't get the dot effect, which lead to losing your stacks. When you do cast it without one you get the stack, tested and 100% confirmed. So basicly each casted pyrite on slowed by tar state = miss for the dot.
Tar - http://www.wowhead.com/spell=62287 and Pyrite - http://www.wowhead.com/spell=62489, I'm not sure if you actualy even hit with the spellfire 60-70k damage or miss it also, I need someone to test that out. One more thing the tar don't remove the already ticking dot and applied on him, for example if your have 2 stacks he gets slowed and get out of slow and you manage to reapply it stack to next level, so it dosn't clear it or smth.
## 

Bump. I realised this only occur if the pyrite and the tar get applied at the same time or smth else comming from the tar.

TDB 48/Win 7
##

**Comment by Killyana** [comment]
Cannot reproduce on rev. 6efdcd3ea8bf
