### ISSUE TITLE
[Bugged Quest] Forging a Head

### ISSUE THREAD

**Issue by SimulationWow** [TrinityCore/TrinityCore#4975]
Hello,
I have encountered a problem with the quest "Forging a Head".

How to reproduce the bug:
1. Go to Storm Peaks.
2. Get the quest "Forging a Head".
3. Use "Diamond Tipped Pick" on "Dead Iron Giants".

What should happen, what happens instead:
You should find 8 "Dead Iron Giants" and use "Diamond Tipped Pick" on them and get 8x Stormforged Eyes for complete the quest, Instead when you use "Diamond Tipped Pick" on Dead Iron Giant Corpse Nothin happen and you cant finish the quest.

Links:
Quest --> http://old.wowhead.com/quest=12985/forging-a-head
Diamond Tipped Pick -->  http://old.wowhead.com/item=42424
Stormforged Eyes --> http://old.wowhead.com/item=42423
Video --> http://www.youtube.com/watch?v=kgHlDznPXlY

Hash : 87761580aacf8b8d96a878a8a2de2ea5a245549c
Tdb: 335.11.43+
Addons: wg(not tc) / ac1 / tc2 / armory / pvprank
on Linux

**Comment by Treeston** [comment]
Still an issue on 3f3ff8b36b05

**Comment by Killyana** [comment]
Some spell requires cast_flag=2 if the npc has the aura Permanent Feign Death.
``` sql
UPDATE `smart_scripts` SET `action_param2`=2 WHERE `entryorguid` IN (2991401) AND `source_type`=9 AND `id`=0;
