### ISSUE TITLE
{Zone / NPC's} Molten Core / Molten Destroyer / Molten Giant

### ISSUE THREAD

**Issue by durrrr** [TrinityCore/TrinityCore#4991]
Hello,
I have encountered a problem while raiding in "Molten Core" zone.

How to reproduce the bug:
1. Go to Molten Core.
2. Try and kill some adds including "Molten Destroyer" / "Molten Giant".

What should happen, what happens instead:
You should go to "Molten Core" and enjoy doing the raid, in a normal way :). (notice the zone data) instead, When attacking "Molten Destroyer" and "Molten Giant" sometimes get's them stuck in their place, not moving, and you cannot attack them and you are still in combat with them. sometimes when you move away from them, just getting you out of combat, which should not happen in a raid, with elites, but still, they are stuck when you come back to them, and you still cant attack them.

A link:
old.wowhead.com/zone=2717 --> The "Molten Core" zone
http://old.wowhead.com/npc=11659 --> The NPC #1 (Molten Destroyer)
http://old.wowhead.com/npc=11658 --> The NPC #2 (Molten Giant)

I'm running Unix on hash: 6c1815d , TDB 43+
Addons: AH bot and WG.

Regards,
durrrr

**Comment by Killyana** [comment]
Cannot reproduce this issues on rev. 5b5c0938da0f or in rev. 95084bf54e85
