### ISSUE TITLE
{Zone/Encounter} Naxxaramas / Gluth

### ISSUE THREAD

**Issue by durrrr** [TrinityCore/TrinityCore#5005]
Hello,
I have encountered a problem while raiding in "Naxxaramas" zone.

How to reproduce the bug:
1. Go to "Naxxaramas" zone.
2. Start "Gluth" Encounter.

What should happen, what happens instead:
You should go to "Naxxaramas", start "Gluth" encounter and when the "Adds" phase start, kite them when they are running towards you. (notice the zone data) instead, They are not getting summoned sometimes, and when they are getting summoned they are not running towards you, they are just stuck in their place.

A link:
http://old.wowhead.com/zone=3456 --> The "Naxxaramas" zone
http://old.wowhead.com/npc=15932 --> The NPC

I'm running Unix on hash: 6c1815d , TDB 43+
Addons: AH bot and WG.

Regards,
durrrr

**Comment by chaodhib** [comment]
fixed in #14865
