### ISSUE TITLE
{Achievement} The Traitor King (10/25)

### ISSUE THREAD

**Issue by durrrr** [TrinityCore/TrinityCore#5006]
Hello,
I have encountered a problem while raiding in "Trial of the Crusader" zone.

How to reproduce the bug:
1. Start Anubarak encounter.
2. kill 40 adds (Swarm Scarabs) within 30 seconds.

What should happen, what happens instead:
You should go to "Trial of the Crusader" zone and kill 40 Swarm Scarabs withing 30 seconds. (notice the zone data) instead, the scarabs do not give you ticks towards the achievement.

A link:
http://old.wowhead.com/zone=4722 --> The "Trial of the Crusader" zone
http://old.wowhead.com/npc=34564 --> The NPC #1 (Anub'arak)
http://old.wowhead.com/npc=34605 --> The NPC #2 (Swarm Scarab)
http://old.wowhead.com/achievement=3800 --> The Achievement (10 Man Version)
http://old.wowhead.com/achievement=3816 --> The Achievement (25 Man Version)

I'm running Unix on hash: 6c1815d , TDB 43+
Addons: AH bot and WG.

Regards,
durrrr
##

**Comment by w5860363** [comment]
check 
https://github.com/TrinityCore/TrinityCore/blob/c75fcbe20b07fd7518be58bf02ba30d903133449/src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheCrusader/instance_trial_of_the_crusader.cpp#L240

**Comment by w5860363** [comment]
spell 68515 not find Achievement does not work

**Comment by Killyana** [comment]
I get the achievement on 10 and 25,  the kill count is correct and npcs keep always spawning when Anub is underground.
rev. 24cf532557b0
