### ISSUE TITLE
{Zone/Encounter} Black Temple / Illidan Stormrage

### ISSUE THREAD

**Issue by durrrr** [TrinityCore/TrinityCore#5018]
Hello,
I have encountered a problem while raiding in "Black Temple" zone.

How to reproduce the bug:
1. Go to "Black Temple" zone.
2. Start "Illidan Stormrage" Encounter.
3. Get to phase 3.

What should happen, what happens instead:
You should go to "Black Temple", start "Illidan Stormrage" encounter and when phase 3 starts he should become a demon. (notice the zone data) instead, he does not become a demon, he just continues the encounter in his normal shape.

A link:
http://old.wowhead.com/zone=3959 --> The "Black Temple" zone
http://old.wowhead.com/npc=22917 --> The NPC

I'm running Unix on hash: 6c1815d , TDB 43+
Addons: AH bot and WG.

Regards,
durrrr
##

**Comment by Kittnz** [comment]
Well the counter and the npc illidan needs updating and fixing however you can complete this encounter without any crashes!

**Comment by Keader** [comment]
some "triggers" of spells, attack players too xD

**Comment by Kittnz** [comment]
Yes, a lot of changes have to be made, akama is bad too.

**Comment by Keader** [comment]
Rewrite in progress
