### ISSUE TITLE
[Bug]Kruban Darkblade

### ISSUE THREAD

**Issue by Crysicle** [TrinityCore/TrinityCore#5079]
Bug:
Kruban Darkblade stays in one place and doesn't walk around the Valley of Strength in Orgrimmar as he is supposed to.

Link:
http://old.wowhead.com/npc=14843

Core revision: Trinity Core c9762b0e3852+
Database revision: TDB 335.11.45
Addons: Anticheat1

**Comment by Rushor** [comment]
@MrSmite: researched already some wps for really old npcs back in the days. maybe he will be successfully here too :)

**Comment by Rushor** [comment]
@malcrom wrote:
> If he ever had a path it would no longer be obtainable.

we will trade this issue like https://github.com/TrinityCore/TrinityCore/issues/12844
