### ISSUE TITLE
{Spell} Garrote

### ISSUE THREAD

**Issue by durrrr** [TrinityCore/TrinityCore#5101]
Hello,
I have encountered a problem while playing in any of the game zones.

How to reproduce the bug:
1. Use "Garrote" on bosses.

What should happen, what happens instead:
You should use "Garrote" and have the following effect: "Garrote the enemy, silencing them for 3 sec and causing ((119 + AP \* 1 \* 0.07) \* 6) damage over 18 sec, increased by your attack power.  Must be stealthed and behind the target.  Awards 1 combo point." (notice the spell data) instead, the spell in the last period of time is being evaded on bosses, many many times. I do not know what is the issue, but lately it happens a lot, specially on boss NPC's.

A link:
http://www.wowhead.com/spell=703 --> The spell

P.S,
If needed, video example will be given.

I'm running Unix on hash: 1a41d8e , TDB 43+
Addons: AH bot and WG.

Regards,
durrrr
##

**Comment by Killyana** [comment]
Cannot reproduce on rev. 24cf532557b0
