### ISSUE TITLE
[Ach] Love is in the Air - Lonely /gameobject needs script/

### ISSUE THREAD

**Issue by Trista** [TrinityCore/TrinityCore#5116]
When you use http://www.wowhead.com/item=34480 and click on www.wowhead.com/object=187267 you should sit and receive www.wowhead.com/spell=45123 5 sec after it has been triggered, if a person sits to you and click it 2 and receive buff, you use the delight and get achievement asap. I made some researchs and the basket does not dissapear.
Here when click on basket nothing happens and it dissapear after the 5th sec, when should apply the buff. It need to be scripted/updated to trigger the spell mentioned on user.
On manual cast on yourself + the person you get the achievement, after eating.
http://www.youtube.com/watch?v=wlnX6Dm-c78
Win 7
TDB 11.45
##

**Comment by D4R4** [comment]
Confrim, no heart for me :((((

**Comment by Killyana** [comment]
Same issue as Naxxramas portals https://github.com/TrinityCore/TrinityCore/issues/13255

**Comment by Killyana** [comment]
Generic issue
