### ISSUE TITLE
[Bug]Echeyakee

### ISSUE THREAD

**Issue by Crysicle** [TrinityCore/TrinityCore#5143]
How it should work:
Go to around (65:16) in The Barrens, summon the mob by blowing the provided horn, then kill the mob and loot him.

Bug:
The radius of where the horn can be blown is really small, you need to be really in the middle of the 2 kodo skeletons to be able to use it. This should not happen, you should be able to blow it while around 10 yards away from those 2 skeletons. Also, this may or may not be a bug, but Echeyakee in the videos below, except the first one, seems to spawn closer if not completely in the middle of the bones, while at the moment he spawns about 10 yards to the Southeast of them.

Links:
Quest - http://old.wowhead.com/quest=881
Echeyakee - http://old.wowhead.com/npc=3475
Echeyakee's current spawn - http://img832.imageshack.us/img832/698/wowscrnshot020812195328.jpg
(3:15) - http://www.youtube.com/watch?v=2I44x52znso
(2:00) - http://www.youtube.com/watch?v=8kYmRMOkzbQ
(3:00) - http://www.youtube.com/watch?v=9YsrSZdJuso

Core revision: Trinity Core 7a117dd42966+
Database revision: TDB 335.11.45
Addons: Anticheat1

**Comment by Rushor** [comment]
```sql
UPDATE `event_scripts` SET `x`=443.264038, `y`=-3049.477539, `z`=92.263039 WHERE `id`=2980;
UPDATE `gameobject_template` SET `data1`=70 WHERE  `entry`=164651;
```

well this is not sniffed and only an adaption to https://www.youtube.com/watch?v=2I44x52znso&feature=player_detailpage#t=204

this cannot be sniffed on retail, because the summonpoint and the summonaction for this npc changed with 4.x

**Comment by Killyana** [comment]
This will update the spawn position as on the videos, for the item range maybe there's more than 1 spellfocus
``` sql
UPDATE `event_scripts` SET `x`=453.896027, `y`=-3039.76147, `z`=91.785370 WHERE `id`=2980;
