### ISSUE TITLE
[Instances] Ahn'Kahet - Jedoga Shadowseeker

### ISSUE THREAD

**Issue by Trista** [TrinityCore/TrinityCore#5182]
Boss id - http://www.wowhead.com/npc=29310
Issues:
0. The trigger that stays near the water infront of boss or in other words NPC_JEDOGA_CONTROLLER = 30181 is visible to regular players, when it shouldn't.
I. After clearing the 15 Twilight Initiates http://www.wowhead.com/npc=30114 boss should descend and activate /that part works/, the problem is after it 15 Twilight Volunteers should spawn http://www.wowhead.com/npc=30385 in not active state just kneeling and waiting for her to call them for sacrifice mentioned on point II. The problem is in the script there is only mentioned the ID of the  Initiates and it use them instead of the Volunteers /in simple words it is scripted right, but wrong npc is being used/. So after boss gets activated 15 Initiates should be replaced by 15 Volunteers.
II. Once that is done the sacrifice itself use Initiates so the id and npc should be changed to Volunteer /not sure if there must be some npc state changes, when I tried it I got it not atackable just running./
III. Since 3.3.2 this encounter has been nerfed, still Trinity's script is staying at boss old state. What should be changed - boss should only 1 time fly up above the ground at 50% of her hp /and this is the change/ in not targetable state and use http://www.wowhead.com/spell=56150 on Twilight Volunteer to get http://www.wowhead.com/spell=56219, if the party doesn't kill the npc before that. Atm she use the old boss script and do it many times.
IV. Here I will mention the achievement part for http://www.wowhead.com/achievement=2056. The script is working 50% atm, the conditions are set /though id of initate should be changed with volunteer/ and atm the thing that is bugged is that it caunt boss sacrifice as failing the achievement, there should be set extra condition that if volunteer get sacrificed http://www.wowhead.com/spell=56150 -> achievement return true.
Connected with issue - https://github.com/TrinityCore/TrinityCore/issues/3276, just mentioning the ach part to have it here 2.
V. In case of wipe the 15 Initiates that trigger boss activate should respawn-reset, currently only 2 do.

TDB: 11.45
Win 7
a3e739e7261da501d1b901c2c738a7231b570eae
##

**Comment by Killyana** [comment]
All issues are fixed except Twilight Initiates are used for sacrifice instead of Twilight Volunteers

**Comment by Nyeriah** [comment]
Boss needs script update, also some parts of the code are in german https://github.com/TrinityCore/TrinityCore/blob/6.x/src/server/scripts/Northrend/AzjolNerub/Ahnkahet/boss_jedoga_shadowseeker.cpp#L502-L510

**Comment by sirikfoll** [comment]
Closed in https://github.com/TrinityCore/TrinityCore/commit/f1ff7e642f8feb027d668a53adc39ecaa7488cc2
