### ISSUE TITLE
[Achievement] Hadronox Denied

### ISSUE THREAD

**Issue by Trista** [TrinityCore/TrinityCore#5183]
I removed the problems I mentioned, because fixed them, though others arrised concering core, will submit them when I post the c++ script.

The achievement itself I scripted at the start, but is nothing without the whole encounter.
c++ -> http://www.trinitycore.org/f/topic/7543-wip-hadronox-azjol-nerub/
Here is what I've done concerning the db, any help improving is welcome, if done and not said, since don't have much time.
http://www.trinitycore.org/f/topic/7542-wip-hadronox-event-mechanic-completed/

TDB: 11.49
Win XP

**Comment by Rushor** [comment]
joschi pr'd a fix here https://github.com/TrinityCore/TrinityCore/pull/13184

i cannot see any fix in this issue

**Comment by Aokromes** [comment]
Test #17118

**Comment by Keader** [comment]
still valid @Treeston ?

**Comment by Treeston** [comment]
Fixed by Hadronox PR.

**Comment by Treeston** [comment]
#17118 #18012
