### ISSUE TITLE
Equip spells aren't reapplied after death / Lovely Charm Collector's Kit

### ISSUE THREAD

**Issue by milotic** [TrinityCore/TrinityCore#5184]
http://www.wowhead.com/item=49661 

This item is required in the players bags in order to obtain http://www.wowhead.com/item=49655 The charms are not looted but appear within your inventory automatically upon the death of a creature that grants experience for your level. 
http://www.wowwiki.com/Lovely_Charm_Collector%27s_Kit

Bug: Only obtain http://www.wowhead.com/item=49655 by higher level creatures that the player.

Example 80 player kill http://es.wowhead.com/npc=32255 about 100 times and 0 charms but go to ramdom heroic and get many charms

revision: https://github.com/TrinityCore/TrinityCore/commit/5365bd25fae59a6ae225534b779bd6c14779599a
##

**Comment by Aokromes** [comment]
Bug still present on bbcf8f58e69d

**Comment by Killyana** [comment]
Tested on rev. 5b5c0938da0f
- For the aura, if the item is moved in the inventory the player will get the aura again
- Just killed 6 npcs level (73, 74) with level 80 character and get 3 Lovely Charms
