### ISSUE TITLE
[BUG] MoveInLineOfSight don't called for worldtriggers (flag_extra | 128)

### ISSUE THREAD

**Issue by SignFinder** [TrinityCore/TrinityCore#5194]
TC today, TDB45+updates

In this quest http://www.wowhead.com/quest=24849 have triggers 38342 
https://github.com/TrinityCore/TrinityCore/commit/c6f8f23616d468d9a761d7f5f6762fdca208e66f

Need porting this commit for fix
https://github.com/mangos/mangos/commit/6ad98e2806f1044317ccf0cfcf751191f1a433b9

**Comment by Aokromes** [comment]
This bug is still valid?

**Comment by Nyeriah** [comment]
Yes it is (for a clear example see yog saron's trigger)

**Comment by w5860363** [comment]
@Aokromes @Nyeriah  Dear sir NPC 33280 set to 1 can make Sara work, I do not know Is it right? 

Please excuse my English.

**Comment by Frytiks** [comment]
Ye, it will make it work.

**Comment by akrom23** [comment]
inline void CreatureUnitRelocationWorker(Creature* c, Unit* u)
vs
void Creature::InitializeReactState()

MoveInLineOfSight is called only for creatures with aggressive react. Triggers have passive.

**Comment by w5860363** [comment]
Restore the code to work before February 128

**Comment by Keader** [comment]
This bug is still hurting Start Fight of Yogg Saron b574c99549bb8cf1d95bd4bc0c319548a678799a

**Comment by digz6666** [comment]
I set flags_extra = 1 and the phase transition works after Sara dies but Yogg Saron phase 3 transformation not works, he just disappears after phase 2 (his shadowy barrier disapperars).

**Comment by Keader** [comment]
@digz6666 For the fight to happens Sara must not die. It gets 1 / 200k but can not die. It has a small problem in the code, remove the "if" of damage taken Sara the condition of being first phase. Because at the time of transition has left some live ADD and you kill him during the transition this will make Sarah dies and lock the whole script.

**Comment by digz6666** [comment]
@Keader oh yes, the Sara is dead.
![sara_dead](https://cloud.githubusercontent.com/assets/1736110/9561931/8563fb2c-4e96-11e5-8c2b-824b544a4aab.jpg)

**Comment by digz6666** [comment]
@Keader you mean this part?
```c++
void DamageTaken(Unit* /*attacker*/, uint32& damage) override
{
    if (_events.IsInPhase(PHASE_ONE) && damage >= me->GetHealth())
    {
        damage = 0;

        if (Creature* voice = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(DATA_VOICE_OF_YOGG_SARON)))
            voice->AI()->DoAction(ACTION_PHASE_TRANSFORM);

        Talk(SAY_SARA_TRANSFORM_1);
        _events.SetPhase(PHASE_TRANSFORM);
        _events.ScheduleEvent(EVENT_TRANSFORM_1, 4700, 0, PHASE_TRANSFORM);
        _events.ScheduleEvent(EVENT_TRANSFORM_2, 9500, 0, PHASE_TRANSFORM);
        _events.ScheduleEvent(EVENT_TRANSFORM_3, 14300, 0, PHASE_TRANSFORM);
        _events.ScheduleEvent(EVENT_TRANSFORM_4, 14500, 0, PHASE_TRANSFORM);
    }
}
```

**Comment by digz6666** [comment]
@Keader maybe this will fix right?
```c++
void DamageTaken(Unit* /*attacker*/, uint32& damage) override
{
    if (_events.IsInPhase(PHASE_ONE) && damage >= me->GetHealth())
    {
        damage = 0;

        if (Creature* voice = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(DATA_VOICE_OF_YOGG_SARON)))
            voice->AI()->DoAction(ACTION_PHASE_TRANSFORM);

        Talk(SAY_SARA_TRANSFORM_1);
        _events.SetPhase(PHASE_TRANSFORM);
        _events.ScheduleEvent(EVENT_TRANSFORM_1, 4700, 0, PHASE_TRANSFORM);
        _events.ScheduleEvent(EVENT_TRANSFORM_2, 9500, 0, PHASE_TRANSFORM);
        _events.ScheduleEvent(EVENT_TRANSFORM_3, 14300, 0, PHASE_TRANSFORM);
        _events.ScheduleEvent(EVENT_TRANSFORM_4, 14500, 0, PHASE_TRANSFORM);
    }
    else if (damage >= me->GetHealth())
    {
        damage = 0;
    }
}
```

**Comment by Keader** [comment]
Yeap. But Joschi fix (https://github.com/TrinityCore/TrinityCore/commit/2b21fbb58e6b213cf26706dd0dd368b2ea4a92b3)

**Comment by Killyana** [comment]
Please don't talk about a different issues in the same ticket.

**Comment by sirikfoll** [comment]
I think this was fixed by https://github.com/TrinityCore/TrinityCore/commit/165c6a4d8c972ba5b44f59f5b65e5caca360e14c

**Comment by tkrokli** [comment]
Does that include http://www.wowhead.com/event=335/love-is-in-the-air ,
http://www.wowhead.com/quest=24849/hot-on-the-trail and Snivel Rustrocket (several NPC entries)?

http://www.wowhead.com/npc=38334/snivel-rustrocket#comments (Alliance bank)
http://www.wowhead.com/npc=38335/snivel-rustrocket#comments (Alliance auction house)
http://www.wowhead.com/npc=38336/snivel-rustrocket#comments (Alliance barbershop)

http://www.wowhead.com/npc=38337/snivel-rustrocket#comments (Horde bank)
http://www.wowhead.com/npc=38338/snivel-rustrocket#comments (Horde auction house)
http://www.wowhead.com/npc=38339/snivel-rustrocket#comments (Horde barbershop)

http://www.wowhead.com/npc=37715/snivel-rustrocket#comments (quest target, [A Friendly Chat...](http://www.wowhead.com/search?q=A+Friendly+Chat))
http://www.wowhead.com/quest=24657/a-friendly-chat (Alliance)
http://www.wowhead.com/quest=24576/a-friendly-chat (Horde)

**Comment by sirikfoll** [comment]
Yes, the generic issue was fixed by https://github.com/TrinityCore/TrinityCore/commit/165c6a4d8c972ba5b44f59f5b65e5caca360e14c
and consequently quests above works too.

**Comment by tkrokli** [comment]
Thanks for confirming, I suppose we can ask for this issue to be closed by one of the TC collaborators.
