### ISSUE TITLE
{Forge of Souls, Instance, npc-script}Corrupted Soul Fragment

### ISSUE THREAD

**Issue by Justiciar** [TrinityCore/TrinityCore#5215]
Hello,
I have encountered a problem with the npc "Corrupted Soul Fragment" after killing the boss which summoned it, "Bronjahm".
"Bronjahm" summoned this npc by Corrupt Soul ability on a player as well other "Corrupted Soul Fragments".
The problem is that one of the "Corrupted Soul Fragments" is left after killing the boss and it's not attacking anything, just remains in it's place.
If this npc would have been working properly, it would attack the players but more trying to move toward Bronjahm in order to heal him for a large amount, it did none of those actions.
Only one npc from the entire "Corrupted Soul Fragments" group suffered from this issue.
I didn't add any guid or ID, I might provide it later.
if there is a need please inform me.
Another issue which I'm not certain is occuring is that all Corrupted Soul Fragments not trying to move toward the boss and  to heal him, therefore he is not healed.
Sincerely yours,
Justiciar

wowhead Corrupted Soul Fragment npc link:http://www.wowhead.com/npc=36535

wowhead Boss link: http://www.wowhead.com/npc=36497

wowhead summoning spell link:http://www.wowhead.com/spell=68839

wowwiki Corrupted Soul Fragment link:http://www.wowwiki.com/Corrupted_Soul_Fragment

Hash:1a41d8e

Tdb: 335.11.43+

Addons: wg(not tc) / ac1 / tc2 / armory / pvprank

 on Linux

**Comment by Aokromes** [comment]
Fixed few days ago.

**Comment by joschiwald** [comment]
this issue wasn't fixed

**Comment by Runico** [comment]
Corrupted Soul Fragment will do nothing
