### ISSUE TITLE
[Raid]Ulduar 10 Kologarn

### ISSUE THREAD

**Issue by cover25** [TrinityCore/TrinityCore#5220]
in Ulduar 10 on the boss Kologarn when the boss picks a raid member up it is impossible to get him down. My raid DPSed  the hand until it broke Just to get the raid member down. The Hand is supposed to release when it takes X amount of damage (Idk the amount). When you die (If you die) You fall between his legs. Now i'm not sure if this is intended or bugged but it makes it impossible to res you. 

The encounter starts the second someone crosses the second line of the entrance.
The Armor de-buff doesn't stack, it just reapplies. http://old.wowhead.com/spell=64002#comments
                                          
Also in the video seen below V he mentions that the Hands are essentially share HP and DPSing it affects the bosses HP. That however doesn't happen here. It doesn't Deal damage to the boss for the Damage dealt to the hands

http://www.youtube.com/watch?v=PSkUlEvZdww&feature=player_embedded

Trinity Core a3e739e7261d+
TDB 335.11.45
3.3.5a

**Comment by Aokromes** [comment]
Fixed long time ago, if any bug is still valid open a new ticket for each bug.
