### ISSUE TITLE
[Pathing] Strand of the Ancients Emissary

### ISSUE THREAD

**Issue by Ve3xar** [TrinityCore/TrinityCore#5230]
Hash:  84268be882e79ee7633323502ce83f2e4bfcf3a9
Database: TDB_full_335.11.46_2012_02_13

The two NPCs Strand of the Ancients Emissary in Darnassus walk on top of each other as they make their walk from the gate to the city. Their guides are: 207936 and 207931. They also do the bounce jumping walking thing as they start reaching the city.

**Comment by Killyana** [comment]
There's only one PathId 2079310 the second npc follow the first one (creature_formations), it looks fine for me, just general minor behaviors.
