### ISSUE TITLE
Core/Spells Charmed creatures stay linked after hearth

### ISSUE THREAD

**Issue by Kline-** [TrinityCore/TrinityCore#5288]
During this quest http://old.wowhead.com/quest=6082 and similar you receive an item to temporarily tame a creature as a quest objective. If you hearth while the creature is tamed you lose it as a pet (displays in pet slot below character frame but with 0 stats) and retain an invisible buff preventing you from completing subsequent quests in the series until the buff is cleared by time or relogging.

Buff generated from item during the quest: http://old.wowhead.com/spell=19697

Core vers: https://github.com/TrinityCore/TrinityCore/commit/41d99a474ca1c210e0f6730dc8808700ba2705a2
TDB TDB_full_335.11.46_2012_02_13.rar
Debian Linux x64

**Comment by Aokromes** [comment]
Near 1 year since feedback request, if this bug is still valid open a new ticket.
