### ISSUE TITLE
[Hellfire Ramparts]Encounter does not reset properly on Nazan and Vazruden

### ISSUE THREAD

**Issue by blackcat2** [TrinityCore/TrinityCore#5298]
Hi,

When you wipe while doing the Nazan and Vazruden encounter, they fly back to the air and can't be pulled down. The error message says, "Target is not in Line of Sight". This makes the encounter not re-doable.

If I remember correctly, Nazan and Vazruden stays on the ground after the initial event where Nazan fly down to start encounter. so when you wipe, they stay on the ground.

I'm using TDB 335.11.45 with updates all the way until rev 8c2526e7d0f8 and same revision for the core..

Cheers..
BC

**Comment by Aokromes** [comment]
Fixed few days ago.

**Comment by DDuarte** [comment]
866eff64aa90974e2b1a774b8fd6ea4856346635
