### ISSUE TITLE
Player auras are only applying to one Spirit Wolf/Treant.

### ISSUE THREAD

**Issue by Vasago** [TrinityCore/TrinityCore#5302]
Core: https://github.com/TrinityCore/TrinityCore/commit/cd3ed111c95503f0802f1763651ca35ee7bdf9d9
TDB: 46

After this https://github.com/TrinityCore/TrinityCore/commit/cd3ed111c95503f0802f1763651ca35ee7bdf9d9 it summons more NPC but auras are applied only on one still.
##

**Comment by Killyana** [comment]
This is a 4.3.4 issue and I cannot reproduce it on TrinityCore rev. 4b48d0dfdccd
