### ISSUE TITLE
Sidnragosa Spell Unchained Magic

### ISSUE THREAD

**Issue by Ussmaan** [TrinityCore/TrinityCore#5401]
Hi, I play a restoration shaman, and Sindragosa's unchained magic ability seems to be bugged, based on what i have read about the encounter. Unchained Magic is a debuff that is cast on magic users, causing them to gain stacks of instability for the spells they cast. On WOWWIKI it says that they gain 1 stack of instability per spell cast, resulting in 2k dmg per spell cast when the instability stacks reset. Chain Heal is only 1 spell, hitting 4 targets. So in theory I should only receive 1 stack of instability for the 1 chain heal cast. This is not the case however, as I receive 4 stacks of instability every time I cast this spell. Is this a bug, or is the wording of the debuff on wowwiki wrong? Please Help.

Thank
author:  Doon.

using latest rev no patches

**Comment by Rushor** [comment]
we could use:
bool Check(ProcEventInfo& eventInfo)

in the spellscript of spell_sindragosa_unchained_magic

but should all channeled stuff completely not trigger the other debuff?

**Comment by Rushor** [comment]
something like this:

```c++
bool Check(ProcEventInfo& eventInfo)
{
        if (!eventInfo.GetSpellInfo())
            return false;

        // check for channeled spells
         if (eventInfo.GetSpellInfo()->AttributesEx & SPELL_ATTR1_CHANNELED_1)
             return false;

         if (eventInfo.GetSpellInfo()->AttributesEx3 & SPELL_ATTR3_TRIGGERED_CAN_TRIGGER_PROC_2)
                    return false;

             return true;
}
```

**Comment by P-Kito** [comment]
Channeled Spells should trigger it once AFAIK

**Comment by Kittnz** [comment]
What about this?
https://github.com/Effec7/Effec7Core/commit/a3a5cd7f0055f41a9f32bf5446c1b524e847b80d

**Comment by Keader** [comment]
Still present on rev cb8f64cb63c9262717c7a019a581bd284579583c
And https://github.com/TrinityCore/TrinityCore/issues/5401#issuecomment-98175002 this link dont work anymore :(

**Comment by Rushor** [comment]
the fix was a costumcooldown for the proccaura in in spell_proc_event

**Comment by Keader** [comment]
like https://github.com/TrinityCore/TrinityCore/issues/5401#issuecomment-6990976 ?

**Comment by Aokromes** [comment]
If anything here is valid anyone can open a PR for it?

**Comment by Shauren** [comment]
No to ALL OF IT.
