### ISSUE TITLE
UnitAI::AttackStart(Unit* victim)

### ISSUE THREAD

**Issue by pointerxr** [TrinityCore/TrinityCore#5403]
The function posted above seemed to be bugged, many quest scripts and other creature scripts use this like me->AI()->AttackStart(target); 
But this seems to be not working in many cases, not all, but many.

Especially in Functions like JustSummoned(Unit* summoned)
summoned->AI()->AttackStart(me)

This doesn't work as intended and is therefore bugged in my opinion.

REV: Newest

**Comment by Killyana** [comment]
This issue is still valid?

**Comment by tkrokli** [comment]
1) The OP has neither documented core rev. hash nor any specific examples. I vote for closing this issue.

2) http://wowhead.com/quest=8488 - Unexpected Results - has worked for me for more than 8 months (issue closed in https://github.com/TrinityCore/TrinityCore/commit/c5394842bb17e30535e0b65eb9f429a2529c6c94 by dr-j on 30 Jul 2014) so I don't see the need for this badly documented issue to be kept open. I recommend closing this issue and for other users to open a new issue if the specific code referred to by the OP produces any kind of bugs.

**Comment by Aokromes** [comment]
1 year without answer, if this bug is still valid open a new ticket.
