### ISSUE TITLE
[Bug]Some npcs don't respond to aggro if player is in water

### ISSUE THREAD

**Issue by Crysicle** [TrinityCore/TrinityCore#5405]
Bug:
Some humanoid mobs sometimes don't get aggroed when you aggro them while being in water. However, if you aggro them while on the land and when they're close enough you go into the water, they still chase you. But you lose aggro on the mob which you aggroed on the land if you go into the water right after aggoring.

I could only reproduce this in Kalimdor -> Stonetalon Mountains -> Windshear Crag on the mobs near the lake. Northrend(Borean)/EK(STV) humanoid mobs worked just fine.

Link:
Video - http://www.dailymotion.com/video/xp173a_my-movie2

Core revision: Trinity Core 2f37e8209770+
Database revision: TDB 335.11.46
Addons: Anticheat1

**Comment by Killyana** [comment]
``` sql
UPDATE `creature_template` SET `InhabitType`=3 WHERE `entry` IN (5931, 3989, 3988, 3991, 3999, 4004, 4003);
