### ISSUE TITLE
[Spells] Spells projectiles with missile destination don't stop when encountering an enemy.

### ISSUE THREAD

**Issue by joshwhedon** [TrinityCore/TrinityCore#5439]
Current revision : https://github.com/TrinityCore/TrinityCore/commit/7be89c89b0e6782590f92261a554eb23110b9954

It's a little hard to explain, but take spell 48766 for example. When you target a enemy, the target circle correctly appear on the enemy, but the projectile go through the enemy until it reachs the map, while it should stop on the enemy. It's not a big problem for classic spells, but when you have to hunt flying enemies it becomes a problem, because you have to bring them on the floor to fight them.

**Comment by Killyana** [comment]
Fixed.
