### ISSUE TITLE
[GO] Strange Fruited Plant - quest accept radius very small

### ISSUE THREAD

**Issue by MrSmite** [TrinityCore/TrinityCore#5452]
Rev: c15f7bfc193a2f9e05e999e3ade588002df366e2
OS: XP SP3
DB: 46 + updates

<b>Description</b>

The quest: The Glowing Fruit (930) offered by the "Strange Fruited Plant" (GOid: 6751, GPS: X: 9254.704102 Y: 1641.605469 Z: 1303.050293 Map: 1) in Teldrassil does nothing when you click "Accept" unless you're practically standing inside the GO.

<b>Details</b>

When the quest cursor lights up and you right-click the GO, the quest dialog appears but if you click "Accept" it simply closes. In order to accept the quest you must practically move into the GO.

Also, after you manage to accept the quest, the icon changes to a gear indicating you can interact with the GO but you can't. It simply says "Hello".

**Comment by Aokromes** [comment]
1 year since request, closing. If this bug is still valid open a new ticket.
