### ISSUE TITLE
[Bug] Saves in RDF

### ISSUE THREAD

**Issue by Yoni140** [TrinityCore/TrinityCore#5487]
Hello , after I did a RDF and got saved in it , I qued for another RDF and got into the same one I did befor ,and then I got into my old save instead of a new one and the rest of the group who wasnt saved got into a new save .

What should happen:
If i was saved in a dungon I did through the RDF system and im doing another RDF and getting into the same one , i should get into a new save and not into my old one. 

Thanks ahead . 
Hash:86537a1  TDB : 355.11.46+

**Comment by Killyana** [comment]
If this issue still happen in the current revision reopen it.

**Comment by Frytiks** [comment]
It's hard to say if it happens, cause player can't queue into RDF

**Comment by Killyana** [comment]
Why can't?

**Comment by Frytiks** [comment]
Cause last player all time missing. https://github.com/TrinityCore/TrinityCore/issues/14331
