### ISSUE TITLE
[ICC/Lady Deathwhisperer] Reanimated Adherent/Reanimated Fanatic

### ISSUE THREAD

**Issue by Amit86** [TrinityCore/TrinityCore#5549]
Using clean trinitycore with clean tdb

Bug: The NPC's `Reanimated Adherent` and `Reanimated Fanatic` does not get spawned at all by script

The only NPCs that gets spawned are these:
- Deformed Fanatic
- Cult Adherent
- Empowered Adherent
- Cult Fanatic

Bug 2:
After Cult Fanatic transform into Deformed Fanatic he does not melee attack anyone and just follow players around.

Hash: cbee39a

**Comment by Aokromes** [comment]
This bug is still valid?

**Comment by Runico** [comment]
2 months ago this bug was valid, but recently i saw a commit about dark_martyrdom

**Comment by Aokromes** [comment]
Yeah, that's why i ask.

**Comment by Runico** [comment]
Lemme test this right now

**Comment by Runico** [comment]
Nope, still don't work

**Comment by Killyana** [comment]
Confirm on rev. 5b5c0938da0f

**Comment by Aokromes** [comment]
If https://github.com/TrinityCore/TrinityCore/issues/5549#issuecomment-4308742 is valid anyone can create a pr for it?

**Comment by Keader** [comment]
For references, fixed by : https://github.com/TrinityCore/TrinityCore/commit/8e82d8a9e79ba95fbd780fa093416ebe7431a1c0
