### ISSUE TITLE
backslash/clearcasting/nightfall

### ISSUE THREAD

**Issue by Azryel** [TrinityCore/TrinityCore#5592]
We've got a problem on our server,
When someone gets one of these buffs (backslash/clearcasting/nightfall ...) the buff is removed  when the target gets hit but  the problem with that system is that if you are far enough of your target, you can cast a second one with the same bonuses as the first ...
For example, a warlock can cast 2 instant shadowBolts if he's far enough :/

Is there a way to fix this ??

**Comment by Keader** [comment]
still present in current revs?

**Comment by ariel-** [comment]
No, those procs have charge drop proc at phase cast now.
