### ISSUE TITLE
[PetAI] Pet LOS should not apply to command attack

### ISSUE THREAD

**Issue by MrSmite** [TrinityCore/TrinityCore#5613]
Rev: 9f93681625f16b4a118df755eccb8ac80f713c16
OS: XP Sp3
DB: 46 + updates

<b>Details</b>

When a player clicks 'attack', pet LOS should not apply, pets should attack the target. This allows the player to target a creature in an instance (while behind a wall, etc.) and use the pet to pull by clicking "attack" and then "follow" after initial aggro.

Pet LOS should only apply for the AI automatic target selection to prevent pets from picking targets on different Z axis or behind walls.

<b>Patch</b>

Removed by MrSmite - issue still needs review and other things in the core fixed first (see discussion below)
##

**Comment by Killyana** [comment]
Cannot reproduce on rev. 24cf532557b0
Summon an Imp and focus a target not in los, if you use the attack action it will move to the target then start casting the fireball.
If you try to cast the fireball when the pet is not in LOS you will get target not in LOS.
