### ISSUE TITLE
[Quest] Dr. Boom!

### ISSUE THREAD

**Issue by Zaranthos** [TrinityCore/TrinityCore#5629]
http://www.wowhead.com/quest=10221/dr-boom

Seems like posted strategies for killing him don't work. As far as I can tell he is able to target you no matter where you stand making it impossible to solo this quest at lower levels at least.

1ebdc5c19cc871ab2e00e75c3e477972151c8e7f
TDB_full_335.11.46_2012_02_13

All vmaps options enabled. I don't think he should be able to target you from above and behind where he stands but he was able to roast me even though I couldn't see him. This might be something mmaps would fix?

**Comment by Aokromes** [comment]
No word after months, closing, if this bug is still valid open a new ticket.
