### ISSUE TITLE
[Quest] [11690] Bring 'Em Back Alive

### ISSUE THREAD

**Issue by alein** [TrinityCore/TrinityCore#5646]
TrinityCore rev. 4f5f148e8cf3
TDB 335.11.46+

Quest: Bring 'Em Back Alive - http://old.wowhead.com/quest=11690
Quest item: Torp's Kodo Snaffle - http://old.wowhead.com/item=34954

You need to rescue 8 Kodo, but when you use the quest item Torp's Kodo Snaffle ( http://old.wowhead.com/item=34954 ) the Kodo's doesn't follow you. You just get one buff and nothing happens.

**Comment by Killyana** [comment]
Fixed.

**Comment by KarrokDC** [comment]
Issue can be reproduced in the following 6.x revision:

TrinityCore: 6c48066a6f24ccbcb4aa527d5241a411691e3173
Trinity DB : d00ba9587d5d604a60827de2f49a74a1f7fd3455 (TDB 6.03)

Apparently, an action bar should be presented to the user, see this movie:
https://www.youtube.com/watch?v=Z1JMkmIvtb0 (CataQuests.com - Bring'Em Back Alive)

Question: with this particular release I've had more problems with action bars, particularly in the DK starter area, so its seems like a more global issue.

**Comment by Rushor** [comment]
the quest itself works, one missing thing are general features in 6.x

**Comment by KarrokDC** [comment]
Allrighty, thanks for the update :)
