### ISSUE TITLE
[Spell] Scent of Blood

### ISSUE THREAD

**Issue by Macavity** [TrinityCore/TrinityCore#5673]
http://www.wowhead.com/spell=72769
Scent of Blood should slow enemies near to the caster but doesn't.

This spell is used by the blood beasts in the Deathbringer Saurfang encounter.

Core: https://github.com/TrinityCore/TrinityCore/commit/a48216e1226601817a76605b12ee7bafbaf66a78
##

**Comment by Killyana** [comment]
.npc add temp 38508 and .cast back 72769 : the player will get Scent of Blood with -80% speed and the blood beast get id: 72771 [Scent of Blood], may be on the script the spell is not casted correctly.
Also if someone can confirm if this still valid.

**Comment by Killyana** [comment]
Cannot reproduce on rev. 24cf532557b0
