### ISSUE TITLE
felmyst

### ISSUE THREAD

**Issue by gnomepunter** [TrinityCore/TrinityCore#5680]
ok i am using 
win7 32 bit and core  
84268be882e79ee763 335.11.46
no custom updates.
ok the problem here is that when i kill brut in sunwell that felmyst shows up but only as a round invisible circle here is a screenshot.
http://i1134.photobucket.com/albums/m618/gnomepunter1/WoWScrnShot_031212_122748.jpg.
i havent gotten into dbc fixes yet but if someone would point me in the right direction ill try to fix it myself to help out.
##

**Comment by sova-bogdan** [comment]
how to fix?

**Comment by w5860363** [comment]
@sov

**Comment by w5860363** [comment]
@sova-bogdan NO
But I think this is because the felmyst flags_extra = 128 Only GM visible
hack flags_extra = 1 You can temporarily let him work but in some cases the client crashes

**Comment by w5860363** [comment]
maybe UPDATE creature_template SET flags_extra=33 WHERE entry=25038;

**Comment by L30m4nc3r** [comment]
Now felmyst not spawn.

**Comment by w5860363** [comment]
@L30m4nc3r felmyst  

There have been no chance. This is another problem https://github.com/TrinityCore/TrinityCore/issues/12238

respawn brutallusRepeatedly kill but not what meaning

**Comment by L30m4nc3r** [comment]
@w5860363 thanks. I see. :+1:

**Comment by w5860363** [comment]
@L30m4nc3r In fact, our idea is to convert from 128-model2 a visible model1 but it does not work

**Comment by chovie23q** [comment]
most sunwell is working on the mangosone tbc/2.4.3 version here is the link to their scripts,

https://github.com/cmangos/mangos-tbc/blob/master/src/scriptdev2/scripts/eastern_kingdoms/sunwell_plateau/boss_kiljaeden.cpp

https://github.com/cmangos/mangos-tbc/blob/master/src/scriptdev2/scripts/eastern_kingdoms/sunwell_plateau/boss_kalecgos.cpp

https://github.com/cmangos/mangos-tbc/blob/master/src/scriptdev2/scripts/eastern_kingdoms/sunwell_plateau/boss_brutallus.cpp

https://github.com/cmangos/mangos-tbc/blob/master/src/scriptdev2/scripts/eastern_kingdoms/sunwell_plateau/boss_felmyst.cpp

hoping someone can can grab stuff from here and apply it to TC

**Comment by sirikfoll** [comment]
I do intend to do some work on this intance, but time is against me :/
Initial work on Kalecgos is here https://github.com/sirikfoll/TrinityCore/tree/Kalecgos

**Comment by Aokromes** [comment]
@sirikfoll can't that be merged since it's better than current code? :)

**Comment by Rushor** [comment]
very basic fix: https://github.com/Rushor/TrinityCore/commit/93f1b1e11f354d2ee0460295275e065e8022bed6

**Comment by Freeman256** [comment]
I have detailed the boss issue in this https://github.com/TrinityCore/TrinityCore/issues/26597 post. So, I tried testing this event again. As I wrote in my post, Felmyst appears, but it's not clear where. So, after killing the Brutallus, I used the command **.gm on**, and suddenly I saw the boss. It turns out that Felmyst is simply not in the phase that should change after the death of Brutallus. I hope my observations will help you fix the problem faster.

**Comment by CraftedRO** [comment]
From my quick tests this somehow I think that got fixed too by : https://github.com/TrinityCore/TrinityCore/commit/46560070ae610e4c85dfbbe37b24d2b4b4071405

![Uploading WoWScrnShot_092422_124639.jpg…]()

**Comment by CraftedRO** [comment]
From my quick tests this somehow I think that got fixed too by : https://github.com/TrinityCore/TrinityCore/commit/46560070ae610e4c85dfbbe37b24d2b4b4071405

![WoWScrnShot_092422_124639](https://user-images.githubusercontent.com/24683355/192091621-84c7d4bd-aefc-4399-8328-99c98a00645c.jpg)
