### ISSUE TITLE
[Bug] Halaa Battle token 

### ISSUE THREAD

**Issue by Yoni140** [TrinityCore/TrinityCore#5709]
Hello, You should get this token after killing an member of the opiset faction or get a killing blow over him , but as it seems you dont get anything. 

link to the tokens : http://www.wowhead.com/item=26045

Hash: c443b03  TDB: 335.11.46+

**Comment by tkrokli** [comment]
TrinityCore rev. 3e588acfe9ec 2015-04-25 09:15:27 +0200 (3.3.5 branch) (Win64, Release)

Verified once again that item 26045, [[Halaa Battle Token](http://wotlk.openwow.com/item=26045)], appears in the bag inventory upon a successful PvP player kill.

Please close this issue, it has not been an issue for at least half a year now.
