### ISSUE TITLE
[Bug] Naxxramas Feugen and Stalagg 

### ISSUE THREAD

**Issue by Yoni140** [TrinityCore/TrinityCore#5713]
Feugen and Stalagg suppose to switch between the tanks (switch between the tanks platforms ) but sometimes they throw you to the acid below isntad of the other ramp .
happened to me after the second throw. 

Hash: c443b03 TDB: 335.11.46+

**Comment by Aokromes** [comment]
This bug is still valid @Treeston ?

**Comment by Treeston** [comment]
No.
