### ISSUE TITLE
Distraction at the dead scar & The Air Strikes Must Continue (same issues)

### ISSUE THREAD

**Issue by jnorris1977** [TrinityCore/TrinityCore#5749]
Distraction At The Dead Scar ( Quest ID 11532 )
The Air Strikes Must Continue ( Quest ID 11533 )

Battlemage Arynna wants you to speak to Ayren Cloudbreaker when you're ready to fly over the Dead Scar. Once there, use the Arcane Charges to kill 2 Pit Overlords, 3 Eredar Sorcerers and 12 Wrath Enforcers.

Pit Overlord slain (2)

Eredar Sorcerer slain (3)

Wrath Enforcer slain (12)

Provided item:
Arcane Charges

Issue

Seems on second pass (flying lower) you are to close to the ground to get credit. Actually you get a to close to the ground warning.
Also, get The Air Strikes Must Continue at the same npc at the same time. It also has the same issues.

**Comment by Rushor** [comment]
cannot confirm this on https://github.com/TrinityCore/TrinityCore/commit/a75b651e93b1e17186e90266289008fa6670e183

you only get the warning if you are too close to an builing, but the spell is not meant to work on that.
