### ISSUE TITLE
[Quest] Borrowed Technology, Volatility + the dailies

### ISSUE THREAD

**Issue by Trista** [TrinityCore/TrinityCore#5757]
There are 4 main core problems with this quest that left:
1) Enter vehicle of 31578 is being overriding the vehicle aura of the accessory so it kicks it out. (both get applied to 1, but instead decoy should be to 0).
2) Even if mentioned above get fixed the accessory is supposed to implicitly hit another passenger with explosion
and no seat flags for it even unknown.
3) Armored Decoy doesn't keep emote from freeze mechanic when enter vehicle connected with a not supported flag.
4) Vehicle speed seems too fast (there is some general vehicle not correct speed problem with spline being involved).

TDB: .51
Hash: c41b53605c22d07d2127558a2137fe7f4212588a - and milestone to for main quest commit for better orientation in future, if someone decides to fix. I'm lifting my hands from it for now.

**Comment by sirikfoll** [comment]
From @Nevadas's change, 
```sql
 UPDATE `vehicle_template_accessory` SET `seat_id`=0 WHERE `entry`=31583 and accessory_entry=31630 and `seat_id`=1;
```
it fixes the bunny issue, but quest credit still don't work.

**Comment by tkrokli** [comment]
@sirikfoll, just a minor detail: add back ticks ( ` ) around the column name accessory_entry like this:
```sql
UPDATE `vehicle_template_accessory` SET `seat_id`=0 WHERE `entry`=31583 and `accessory_entry`= 31630 and `seat_id`= 1;
```
(maybe the missing back ticks are not essential to make it work, but it is a codestyle detail)

How about testing @Nevada's suggested change in the `smart_scripts` section with something like this:
```sql
UPDATE `smart_scripts` SET `action_type`= 85 WHERE `entryorguid`= 31578 AND `source_type`= 0;
```
Like @Nevada said, I don't know if this is considered to be a hack or not. I will test this and see if it works.

**Comment by Jenkyins** [comment]
Confirmed on  b1d0855624d1c83850fc36f5242437d7f7c1336b

**Comment by Aokromes** [comment]
d1a053e4f5a29f96b3300397e16d3e63a1cf9bae
