### ISSUE TITLE
[BUG] Jeevs falls underground - every time

### ISSUE THREAD

**Issue by Amit86** [TrinityCore/TrinityCore#5777]
hash 41cc704

When Jeevs is spawned (ItemID: 49040)
he keeps falling underground..
I even tried spawning it when i was in air (gm fly on) but he spawned on the ground under me and fell straight threw..

using `npc add` does the same thing when spawned on the ground, if i fly a bit above ground he doesn't fall

**Comment by Aokromes** [comment]
Fixed who knows when.
