### ISSUE TITLE
[Core] WORLD_TRIGGER and LOS check

### ISSUE THREAD

**Issue by Toshik** [TrinityCore/TrinityCore#5795]
I've run into some weird issue: when we have game object type 10 (goober) and it should cast spell on use core spawns WORLD_TRIGGER to be caster unit. The position of summon is exact GO position (other words - inside of it), so, for some spells WORLD_TRIGGER can't cast spell because of not in LOS cast error.

Example: GO #191609, it should cast spell 51888 wich can't be cast because LOS issue.

Any ideas how to avoid such behavior but not to break other cases, when LOS is important for GO (is there are any)?
##

**Comment by Aokromes** [comment]
This bug is still valid after SnapperRy's changes to gameobjects?

**Comment by Killyana** [comment]
There's also: https://github.com/TrinityCore/TrinityCore/issues/18752 and https://github.com/TrinityCore/TrinityCore/pull/18885

**Comment by Aokromes** [comment]
maybe master lacks @SnapperRy 's changes

**Comment by Aokromes** [comment]
No answer after months, closing, if this bug is still valid open a new ticket on one updated core.

**Comment by Killyana** [comment]
Looks to be fixed.
