### ISSUE TITLE
Ulduar ( Flame Leviathan) and vehicles

### ISSUE THREAD

**Issue by click** [TrinityCore/TrinityCore#581]
Vehicles:
Salvaged Chopper:
Does not have the spell: Grab Pyrite

Salvaged Demolisher:
Drivers / Passengers can be damaged by other players witch drive others vehicles
Demolisher Gunner – feed the driver's gun with pyrite, and shoot things from the sky. Can also load himself into the gun to be launched on the Flame Leviathan( those options aren't there
Throw Passenger does not work.
Anti-Air Rocket does not work.
Grab crate aint bound to action bar, so unusable

Salvaged Siege Engine:
Siege Engine Gunner – shoot things from the sky and fire at ground targets( siege engine don't have an option to load the guner, only driver can go with it)
Using the spell "Steam Rush" might get u driven through the map, only way to get back is get out of the vehicle, and wait for the teleport.

Going under map with any vehicles means you will lose the vehicle.

Flame Leviathan:

There are 4 towers to increase his damage and HP.
Tower of Storms
Tower of Flames
Tower of Frost
Tower of Life
After killing all 4 towers, the boss should have 23M HP, which he has till he goes into combat mode, and gains the buff of the all towers.

Players can not shoot the boxes from the sky when they are up the vehicles as they should be able to. THis is needed to keep the pyrite buff on the boss to kill him fast, so you dont run out of health.

**Comment by Aokromes** [comment]
Most of the bugs are already fixed, open a new ticket for each bugged thing.
