### ISSUE TITLE
Core/Liquids: Doesn't check for target typemask

### ISSUE THREAD

**Issue by Warpten** [TrinityCore/TrinityCore#5815]
Spells cast on players by liquids WMO don't check target typemasks, the best example is the wintergrasp lakes, just swim there  a bit.

Windows 7 64bits, clean core & TDB.
Rev : 568e524c456098c8adae806a26bdcb6913eccc22
##

**Comment by Killyana** [comment]
@Warpten this issue is still valid?

**Comment by Warpten** [comment]
idk

**Comment by Warpten** [comment]
Yes
