### ISSUE TITLE
[wintergrasp] Vehicle teleporter doesnt work

### ISSUE THREAD

**Issue by Amit86** [TrinityCore/TrinityCore#5831]
on hash 1fb07dc and earlier

The vehicle teleporter that should teleport the vehicles out of the caste doesnt work

included picture
http://img842.imageshack.us/img842/5532/wowscrnshot032112183031.jpg

**Comment by WoWErrorDev** [comment]
Provate questo.

class go_wg_vehicle_teleporter : public GameObjectScript
{
    public:
        go_wg_vehicle_teleporter() : GameObjectScript("go_wg_vehicle_teleporter") { }

        struct go_wg_vehicle_teleporterAI : public GameObjectAI
        {
            go_wg_vehicle_teleporterAI(GameObject* gameObject) : GameObjectAI(gameObject),
                _checkTimer(0)
            {
			}

			bool IsFriendly(Unit* passenger)
			{
				return ((go->GetUInt32Value(GAMEOBJECT_FACTION) == WintergraspFaction[TEAM_HORDE] && passenger->getRaceMask() & RACEMASK_HORDE) ||
						(go->GetUInt32Value(GAMEOBJECT_FACTION) == WintergraspFaction[TEAM_ALLIANCE] && passenger->getRaceMask() & RACEMASK_ALLIANCE));
			}


			Creature* IsValidVehicle(Creature* cVeh)
			{
				if (!cVeh->HasAura(SPELL_VEHICLE_TELEPORT))
                    if (Vehicle* vehicle = cVeh->GetVehicleKit())
                        if (Unit* passenger = vehicle->GetPassenger(0))
                            if (IsFriendly(passenger))
                                if (Creature* teleportTrigger = passenger->SummonTrigger(go->GetPositionX()-60.0f, go->GetPositionY(), go->GetPositionZ()+1.0f, cVeh->GetOrientation(), 1000))
									return teleportTrigger;
                    
				return NULL;
			}

            void UpdateAI(uint32 diff)
            {
				_checkTimer += diff;
                if (_checkTimer >= 1000)
                {
                    for (uint8 i = 0; i < MAX_WINTERGRASP_VEHICLES; i++)
                        if (Creature* vehicleCreature = go->FindNearestCreature(vehiclesList[i], 3.0f, true))
							if (Creature* teleportTrigger = IsValidVehicle(vehicleCreature))
								teleportTrigger->CastSpell(vehicleCreature, SPELL_VEHICLE_TELEPORT, true);

                    _checkTimer = 0;
                }
            }
          private:
              uint32 _checkTimer;
        };

        GameObjectAI* GetAI(GameObject* go) const
        {
            return new go_wg_vehicle_teleporterAI(go);
        }
};


void AddSC_wintergrasp()
{
	// GOs
	new go_wg_vehicle_teleporter();

**Comment by Aokromes** [comment]
If this is valid, plz create a PR for it.
