### ISSUE TITLE
[Druid quest] The Ward of Wakening  

### ISSUE THREAD

**Issue by Yoni140** [TrinityCore/TrinityCore#5922]
Hello, when i try to loot the item Bogblossom it does not do anything,there for i cant complete the quest .

http://old.wowhead.com/quest=10961/the-ward-of-wakening

hash: b23ff22 TDB 335.11.46+

**Comment by Rushor** [comment]
the endevent here is missing http://wow.gamepedia.com/Quest:The_Ward_of_Wakening

going to add it...

**Comment by offl** [comment]
Here's no reason to reopen the issue. He already opened a new one for the end event.

**Comment by Keader** [comment]
#18581
