### ISSUE TITLE
Core/Spells: druid talent Primal Precision

### ISSUE THREAD

**Issue by durrrr** [TrinityCore/TrinityCore#5954]
Hello,
I have encountered a problem while playing in any of the game zones.

How to reproduce the bug:
1. Use "Primal Precision" in your talent tree.

What should happen, what happens instead:
"Increases your expertise by X, and you are refunded Y% of the energy cost of a finishing move if it fails to land." (notice the spell data) instead, the 2nd part of the talent is not working. when failing to land a finishing move, does not refund energy.

A link:
http://www.wowwiki.com/Primal_Precision --> The spell

I'm running Unix on hash: b23ff22 , TDB 335.11.46+
Addons: AH bot and WG.

Regards,
durrrr
##

**Comment by Killyana** [comment]
Still happen on rev. 24cf532557b0

**Comment by tkrokli** [comment]
(The subject of this article was removed from World of Warcraft in patch 4.0.1.)
- https://wow.gamepedia.com/Primal_Precision
- https://wow.gamepedia.com/Patch_4.0.1_(class_changes)#Feral

**Comment by ariel-** [comment]
Actually talent is working, but found some code which made it so caster gets removed even less energy than what it should
