### ISSUE TITLE
Lich King outro doesn't work correctly.

### ISSUE THREAD

**Issue by klocklimek** [TrinityCore/TrinityCore#5970]
When Boss's HP is under 10%, script starts. This is correct. But when Highlord Tirion Fordring destroys Frostmourne, Arthas flying without ghosts around him. 

Core: https://github.com/TrinityCore/TrinityCore/commit/7efb63725853b7c2221a800bf6204dcf5635c63c
DB: TDB 335.11.46
Updates: All to 2012_03_30_00

**Comment by Killyana** [comment]
Fixed
