### ISSUE TITLE
[Quest] A meeting with the Magister/An Audience With the Arcanist

### ISSUE THREAD

**Issue by Miroslav1993** [TrinityCore/TrinityCore#5976]
Rev : ec3d3782ce87575e3d685085ba3f30d943f38fd9
Using TDB from Tuesday, march 20th

Can't cast spells Sunreaver Disguise/Silver Covenant Disguise , reports "You are in the Wrong Zone" , thus making the quests undoable.

**Comment by Killyana** [comment]
Fixed
