### ISSUE TITLE
[Bugged Skills] Warlock Fear + Death coil

### ISSUE THREAD

**Issue by SimulationWow** [TrinityCore/TrinityCore#5995]
Hello,
I have encountered a problem with the skills of warlock : Fear + Death coil

How to reproduce the bug:
1. Open warlock
2. Use the skill Death coil / Fear on someone 
3. Watch the duration of the time you can control the other char.

What should happen, what happens instead:
When you fear someone or Death coil him he have duration which he cant control his char (Example: Fear = 10s Duration), The problem is that after the fear ends you cant control the char more 1 sec and one sec in pvp = very critical.
In this sec that you cant control the char you can die.

Links:
Fear --> http://www.wowhead.com/spell=5782/fear
Death Coil --> http://www.wowhead.com/spell=6789/death-coil 

Hash : b23ff22
Tdb: 335.11.43+
on Linux
##

**Comment by Killyana** [comment]
Cannot reproduce on rev. 24cf532557b0
