### ISSUE TITLE
{General} Death / After spirit releasing

### ISSUE THREAD

**Issue by durrrr** [TrinityCore/TrinityCore#6051]
Hello,
I have encountered a problem while playing in any of the game zones.

How to reproduce the bug:
1. Die, and release spirit

What should happen, what happens instead:
After you release your spirit you should fly to your original death place and be able to take your body back (notice the info) instead, after you release your spirit you are sometimes stuck (unable to move, at all) or moving very very slowly (On a flying mount usually) which takes you a very long time  to get to your original death place which is really really annoying (By the way, ALT+F4, usually fixes these bugs, but not a 100% of the times).

A link:
http://www.wowwiki.com/Death --> The info (Wowwiki)

I'm running Unix on hash: b23ff22 , TDB 335.11.46+
Addons: AH bot and WG.

Regards,
durrrr

**Comment by Aokromes** [comment]
I don't have seen this bug for a lot of time, closing, if this bug is still valid open a new ticket.
