### ISSUE TITLE
Vampiric Blood & Improved Blood Presence

### ISSUE THREAD

**Issue by Kengur** [TrinityCore/TrinityCore#6067]
Vampiric blood gives 35% increased heal and Improved Blood Presence 10% increased heal, but they dont stack and will be 35% increased heal when you use Vampiric Blood.

I cant find exact tooltip from Vampiric Blood and Improved Blood Presence

TrinityCore rev. 2012-03-28 15:56:25 +0200 (75fef39+) (Unix, Release)

TDB 335.11.46
##

**Comment by ariel-** [comment]
Healing bonus don't stack, only max positive and max negative bonus count, being as vampiric blood is a cd and the rest of the time you have the imp. BP bonus.
