### ISSUE TITLE
Priest Martyrdom vs interrupt

### ISSUE THREAD

**Issue by Paralyzed** [TrinityCore/TrinityCore#6115]
http://www.wowwiki.com/Martyrdom decreases duration of Interrupt effects by 20%, but not work.

rev .https://github.com/TrinityCore/TrinityCore/commit/e231cf9462dc3f8568ac5f0a4112b8aefc4041c4
##

**Comment by Keader** [comment]
Working in 4fe5a167d298ad6fcb9a5f130035abcb98fa5eae
