### ISSUE TITLE
[wintergrasp] Missing Workshop guards

### ISSUE THREAD

**Issue by Amit86** [TrinityCore/TrinityCore#6131]
tested on hash 0f1e96f

Most of the workshops are missing their guards, if its Westpark workshop who doesnt have guards at all or Eastpark workshop that has only alliance guards

There should be guards available at all workshops
##

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/64935-wintergrasp-missing-workshop-guards?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github).

**Comment by Aokromes** [comment]
This is valid after the latest changes from @SnapperRy ?

**Comment by Aokromes** [comment]
no answer after 13d, closing, if this bug is still valid open a new ticket on one updated core.
