### ISSUE TITLE
[wintergrasp] Game Over - prematurely 

### ISSUE THREAD

**Issue by Amit86** [TrinityCore/TrinityCore#6132]
Tested on 0f1e96f

While playing WG the battle sometimes end prematurely for no reason. the walls havent been breached and the relic was never taken, also the timer showed 12 minutes left, there was nothing special in the logs to confirm why this happens.
##

**Comment by Aokromes** [comment]
this is still valid?

**Comment by Aokromes** [comment]
no answer after 2 years, if this bug is still valid post results with updated core.
