### ISSUE TITLE
{Item} Shard of Azzinoth

### ISSUE THREAD

**Issue by durrrr** [TrinityCore/TrinityCore#6143]
Hello,
I have encountered a problem while playing in any of the game zones.

How to reproduce the bug:
1. Use "Shard of Azzinoth"

What should happen, what happens instead:
You use "Shard of Azzinoth" and enjoy the proc normally (notice the zone info) instead, when the proc is open and you summon your minion he is not attacking unless you move him from his current location, which is wasting time because the proc only lasts a few seconds anyway.

Some links:
http://www.wowwiki.com/Shard_of_Azzinoth --> The item (Wowwiki)
http://old.wowhead.com/item=32471 --> The item (Old Wowhead)

I'm running Unix on hash: e636531 , TDB 335.11.46+
Addons: AH bot and WG.

Regards,
durrrr

**Comment by Killyana** [comment]
Fixed.
