### ISSUE TITLE
Core/Spells: [DB Saurfang] Rune Of Blood

### ISSUE THREAD

**Issue by omridahan** [TrinityCore/TrinityCore#6146]
Hello, 
I would like to report about new bug in Deathbringer's skill "Rune Of Blood".

How to reproduce the bug:
1)Go Icc (10/25).
2)Go to the boss "Deathbringer".
3)Start the boss and wait for the skill "Rune Of Blood"

What happens:
The skill "Rune Of Blood" does less damage on the raid players, much less than he should.

Links:
1-http://www.wowhead.com/spell=72410#see-also-other
2-http://www.wowhead.com/spell=72408
3-http://www.wowhead.com/spell=72449
4-http://www.wowhead.com/spell=72447

IDs:
1-72410
2-72408
3-72449
4-72447

TDB:  335.11.46+
Hash : e636531

**Comment by Killyana** [comment]
10nm: Leeches 5100 - 6900 health
10hm: Leeches 5950 - 8050 health
25nm: Leeches 5100 - 6900 health
25hm: Leeches 5950 - 8050 health
Recount (10nm): 1. Hit 16 (100%) (Min: 5002 Moy: 6229 Max: 7930)
Looks fine for me.
