### ISSUE TITLE
Creature/Movements: Creature with Flight States: "CanFly" falling to the ground

### ISSUE THREAD

**Issue by shlomi1515** [TrinityCore/TrinityCore#6148]
Hey Guys

many of creatures using InhabitType 7 are falling down to the ground 
but they not on the ground you cant interact with them
its a visual issue please fix it

thanks

core info:
lastest
##

**Comment by Killyana** [comment]
I recently update some npcs with unhabittype 7: https://github.com/TrinityCore/TrinityCore/issues/14656 and this issue doesn't happen.

**Comment by tkrokli** [comment]
Does it make a difference if the flying creature has got a flying aura in `creature_template_addon` or not?

**Comment by Kittnz** [comment]
Might be a conflict somewhere

**Comment by Rushor** [comment]
moreover: creatures which are attackable with inhabittype 4 also fall to the ground instead of attacking the unit in the air.

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by Shauren** [comment]
anything related to inhabittype isnt valid anymore as that field was removed

**Comment by Killyana** [comment]
The issue changed since Inhabittype was removed, now the issue happen for any npc using Flight States: "CanFly" regarding ground/swim movements.
Example: .go c 112970 (move far form the npc and go back) you will see the npc falling to the ground for some seconds and go back flying with bouncing movements, on server side the npc is not falling or bouncing you can see that with .gps, but on client side it looks like a movement flag  is not sent correctly.

**Comment by HelloKitty** [comment]
@Killyana I think it's in an even worse state now.

**Comment by Killyana** [comment]
Could be observed in this area: .go c 112972

**Comment by Rushor** [comment]
in current state - if we set Flight = 1 in creature_template_movement it seems to work fine

**Comment by Aokromes** [comment]
https://mega.nz/#!53ZRFKoB!ehvFCASfAA28k9bd4P5ccjd20aYl8zNMAjNd4kfGqnc

**Comment by Rushor** [comment]
@Ovahlord added adjustment for some. maybe we should apply it for all creatures in wotlk with flying type?

and: @Aokromes they will not always stay in the ground right? sometimes they move up again( if they have wander_distance or waypointmovement)

**Comment by Ovahlord** [comment]
To clear things up for volunteers: CanFly is NOT what you wanna use to make units actually fly. What you want is DisableGravity which is being applied by using Flight = 1 in creature_template_movement and creature_movement_override.

**Comment by nerc0487** [comment]
> https://mega.nz/#!53ZRFKoB!ehvFCASfAA28k9bd4P5ccjd20aYl8zNMAjNd4kfGqnc

Has this been fixed?

**Comment by Faq** [comment]
> 
> 
> > https://mega.nz/#!53ZRFKoB!ehvFCASfAA28k9bd4P5ccjd20aYl8zNMAjNd4kfGqnc
> 
> The issue still stands

You didnt provide rev.

Was not able to reproduce on 0d152e932cdd986f62ae22bd9fc40569892a2453
https://mega.nz/#!53ZRFKoB!ehvFCASfAA28k9bd4P5ccjd20aYl8zNMAjNd4kfGqnc
and
Could be observed in this area: .go c 112972

**Comment by nerc0487** [comment]
> > > https://mega.nz/#!53ZRFKoB!ehvFCASfAA28k9bd4P5ccjd20aYl8zNMAjNd4kfGqnc
> > 
> > 
> > The issue still stands
> 
> You didnt provide rev.
> 
> Was not able to reproduce on [0d152e9](https://github.com/TrinityCore/TrinityCore/commit/0d152e932cdd986f62ae22bd9fc40569892a2453)
> https://mega.nz/#!53ZRFKoB!ehvFCASfAA28k9bd4P5ccjd20aYl8zNMAjNd4kfGqnc
> and
> Could be observed in this area: .go c 112972

Currently running on TrinityCore rev. 450dbd32b68a+
If you walk slowly towards that area (towards creature 112972 & co., you'll see them slowly fall from the sky unto the ground.

**Comment by Faq** [comment]
Can't find your mentioned rev hash.

**Comment by nerc0487** [comment]
It is this commit - approximately around mid March

Killyana
    
40acf3c
    
DB/Creature: Fix some creatures position in Sholazar Closes #24305
    2020‑03‑16

**Comment by nerc0487** [comment]
> Can't find your mentioned rev hash.

It is this commit - approximately around mid March

Killyana

40acf3c

DB/Creature: Fix some creatures position in Sholazar Closes #24305
2020‑03‑16

**Comment by Aokromes** [comment]
"The issue still stands" and using a 6 months old core doesn't match.

**Comment by nerc0487** [comment]
I am aware, the issue is still open however, this is the main reason for checking up with this issue. I'm unsure if the changes mentioned here would do the job. Pulling latest TC rev will cause major merge conflicts.

**Comment by nerc0487** [comment]
I'm still confused as to what the conclusion of this issue is. It's still open with no clear answers as to what the solution might have been. Any insights would be greatly appreciated. Apologies for bringing this up again, I've been struggling to figure out what is wrong.

**Comment by Aokromes** [comment]
the issue is still open because there are still some bugged mobs, unless you have a prof of all mobs are fixed.

**Comment by Faq** [comment]
@Aokromes "some" doesn't tell nothing (it is the same as stating using latest rev.), he asked what still left, that means providing some ids or other info.

**Comment by nerc0487** [comment]
I just need to know what the issue existing is at the moment, if anyone could provide me with some insight I could give this a try and share the fix. 

Almost all flying northrend mobs are still broken on my revision which dates back to March 13:

Killyana
#40acf3c
DB/Creature: Fix some creatures position in Sholazar Closes #24305
2020‑03‑16

**Comment by ccrs** [comment]
IIRC this is all related to the creature model, the client does not process correctly one flag or the other depending on the... model? of the creature.
NOTE: Not 100% sure it depends on the model, but well its somewhat consistent between different cases..

BTW sniffs _should_ point out which movementflag must be used, just saying...

In my experience, CanFly is rarely the correct one, almost always its DisableGravity, but there are cases in which it is CanFly.
Try and error, or sniffs, your choice.

**Comment by ccrs** [comment]
BTW, as far as I know, the creature's position should be ok, its 100% a visual bug clientside.
Though since some spell range is validated clientside it can be annoying, even gamebreaking, Lich King's Valkyrs are the prime example.

**Comment by Aokromes** [comment]
> I just need to know what the issue existing is at the moment, if anyone could provide me with some insight I could give this a try and share the fix.
> 
> Almost all flying northrend mobs are still broken on my revision which dates back to March 13:
> 
> Killyana
> [40acf3c](https://github.com/TrinityCore/TrinityCore/commit/40acf3c56b833d987a2d46fe163cf4d75c31d10f)
> DB/Creature: Fix some creatures position in Sholazar Closes #24305
> 2020‑03‑16
> 
> I'm running a customized core, for this reason I won't be able to merge as tons of conflicts will emerge, I am cherry-picking fixes and implementing them with time. I will hopefully be able to provide TC fixes in return.

again, a report from march is useless, if the mobs where fixed and you don't update you will continue to be bugged.

**Comment by offl** [comment]
>Almost all flying northrend mobs are still broken on my revision which dates back to March 13
I just need to know what the issue existing is at the moment, if anyone could provide me with some insight I could give this a try and share the fix.

They are broken only on your revision

Try to set Flight to 1, example here https://github.com/TrinityCore/TrinityCore/commit/2a7181b49406fb3a861b6306f3d2043b1bf0312d

**Comment by Ovahlord** [comment]
and most importantly: update for fking core. There is no point in complaining about broken flight movement when you are over a half year behind in which in fact, some fixups happened already. Like your video for example is 100% invalid because I literally fixed that myself months ago.

**Comment by nerc0487** [comment]
> 
> 
> @Ovahlord added adjustment for some. maybe we should apply it for all creatures in wotlk with flying type?
> 
> and: @Aokromes they will not always stay in the ground right? sometimes they move up again( if they have wander_distance or waypointmovement)

They "seem" to be on the ground (only visual).
They  move back up to their intended location if you engage combat with them & discard before killing them (.gm on) or exiting combat range.

**Comment by Aokromes** [comment]
stop reporting bugs here till you update to recent builds

**Comment by jackpoz** [comment]
> I have noticed some creatures have odd movements in water

water and flying are 2 totally different unrelated things. For the water bit, see https://github.com/TrinityCore/TrinityCore/pull/24020 and https://github.com/TrinityCore/TrinityCore/issues/21872

**Comment by Killyana** [comment]
This issue is fixed, if there's other flying npcs that doesn't have the correct movement set in the DB, new specific issues must be created for each one.
