### ISSUE TITLE
[PitOfSaron] Missing Gauntlet (Ice Cave)

### ISSUE THREAD

**Issue by Amit86** [TrinityCore/TrinityCore#6155]
Hash a998e9e 

Taken from random pastebin on the net, tested and works fine, I dont know about blizzlike level

```diff
diff --git a/src/server/scripts/Northrend/FrozenHalls/PitOfSaron/boss_scourgelord_tyrannus.cpp b/src/server/scripts/Northrend/FrozenHalls/PitOfSaron/boss_scourgelord_tyrannus.cpp
index 7a6aefe..d08ac0a 100644
--- a/src/server/scripts/Northrend/FrozenHalls/PitOfSaron/boss_scourgelord_tyrannus.cpp
+++ b/src/server/scripts/Northrend/FrozenHalls/PitOfSaron/boss_scourgelord_tyrannus.cpp
@@ -56,6 +56,11 @@ enum Spells
     SPELL_MARK_OF_RIMEFANG          = 69275,
     SPELL_HOARFROST                 = 69246,
 
+    //cave
+    SPELL_ICICLE_FALL               = 69428,
+    SPELL_FALL_DAMAGE               = 62236,
+    SPELL_ICICLE                    = 62234,
+
     SPELL_ICY_BLAST                 = 69232,
     SPELL_ICY_BLAST_AURA            = 69238,
 
@@ -509,6 +514,54 @@ class at_tyrannus_event_starter : public AreaTriggerScript
         }
 };
 
+class npc_tyrannus_icicle : public CreatureScript
+{
+	public:
+		npc_tyrannus_icicle() : CreatureScript("npc_tyrannus_icicle") { }
+
+		CreatureAI* GetAI(Creature* pCreature) const
+		{
+			return new npc_tyrannus_icicleAI(pCreature);
+		}
+
+		struct npc_tyrannus_icicleAI : public ScriptedAI
+		{
+			npc_tyrannus_icicleAI(Creature *c) : ScriptedAI(c)
+			{
+				pInstance = c->GetInstanceScript();
+				me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_DISABLE_MOVE | UNIT_FLAG_NON_ATTACKABLE | UNIT_FLAG_NOT_SELECTABLE | UNIT_FLAG_PACIFIED);
+				me->SetReactState(REACT_PASSIVE);
+			}
+
+			void Reset()
+			{
+				IcicleTimer = urand(8000, 14000);
+				me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_DISABLE_MOVE | UNIT_FLAG_NON_ATTACKABLE | UNIT_FLAG_NOT_SELECTABLE | UNIT_FLAG_PACIFIED);
+				me->SetReactState(REACT_PASSIVE);
+			}
+
+			void UpdateAI(const uint32 diff)
+			{
+				if(pInstance->GetData(DATA_TYRANNUS_EVENT) == NOT_STARTED)
+				{
+					if (IcicleTimer <= uint32(diff))
+					{
+						DoCast(me, SPELL_ICICLE);
+						IcicleTimer = urand(8000, 14000);
+					} else IcicleTimer -= diff;
+				}
+
+				//Return since we have no target
+				if (!UpdateVictim())
+					return;
+			}
+		private:
+			InstanceScript* pInstance;
+			uint32 IcicleTimer;
+    };
+
+};
+
 void AddSC_boss_tyrannus()
 {
     new boss_tyrannus();
@@ -516,4 +569,5 @@ void AddSC_boss_tyrannus()
     new spell_tyrannus_overlord_brand();
     new spell_tyrannus_mark_of_rimefang();
     new at_tyrannus_event_starter();
+    new npc_tyrannus_icicle();
 }
```

Video:
http://www.youtube.com/watch?v=FEsIRJYNVbw

**Comment by yvomsx** [comment]
Got the snow to fall, and the damage to be done.
Just the ice falling isn't working.

**Comment by joschiwald** [comment]
https://gist.github.com/joschiwald/b25aa530e391bf3e0c1f written long time ago

**Comment by Rushor** [comment]
/// @todo: fix snowfall visual after collapse

the most important part of this event! :D

**Comment by yvomsx** [comment]
//cave
	SPELL_ICICLE_FALL_TRIGGER		= 69428,
	SPELL_FALL_DAMAGE				= 62236,
	SPELL_ICICLE_SUMMON			= 62234,
	//tests
	SPELL_ICICLE_FALL_VISUAL		= 62234,	
	DATA_ICE_SHARDS_HIT			= 62236,

Anyone happens to know these?

**Comment by Keader** [comment]
Fix by @joschiwald  dont compile here :(
Same erros : https://gist.github.com/joschiwald/b25aa530e391bf3e0c1f#gistcomment-1439210

**Comment by Rushor** [comment]
update the guid structure, he created this stuff long time before the ObjectGUID change in oktober 2014

**Comment by Keader** [comment]
The Achiev Dont Look Up (http://wotlk.openwow.com/achievement=4525) seems not to work (I used to test the script @zabustak).

Little Vid About the Achiev: https://www.youtube.com/watch?t=69&v=yQ3agrSMtwg

**Comment by ariel-** [comment]
@Keader check table achievement_criteria_data, this needs to be scripted to work

Also there is no use of areatriggers, the cave is full of them.

**Comment by ShinDarth** [comment]
please can you open a PR? (with WIP in the title if it is not yet ready to be merged)

**Comment by Laintime** [comment]
any news?(Meybe hack fo this

**Comment by Rushor** [comment]
joschis fix just works fine https://gist.github.com/joschiwald/b25aa530e391bf3e0c1f#gistcomment-1439210 remember to add the missing datas in the instancescript

**Comment by Laintime** [comment]
@Rushor I'm test this,no work((((meybe help me?

**Comment by sirikfoll** [comment]
not really right, but something like that works https://gist.github.com/sirikfoll/c3674a475cf8e6393be7

**Comment by DevRival** [comment]
It's an old script, but there is a bug effect falling icicles, and as seen Trigger(NPC).

**Comment by Aokromes** [comment]
If anything here is valid plz open a pr for it, if needed i can supply sniffs for it.

**Comment by ConradBunton** [comment]
While the compil :

Warning C4373: 'npc_tyrannus_icicle::npc_tyrannus_icicleAI::UpdateAI' on line 598
error C2065: 'UNIT_FLAG_DISABLE_MOVE' on line 587
error C2660: 'Object::SetFlag' on line 587
error C2065: 'UNIT_FLAG_DISABLE_MOVE' on line 594
error C2660: 'Object::SetFlag' on line 594

**Comment by Aokromes** [comment]
@sirikfoll can you create one PR of that? maybe someone can help improving it.

**Comment by sirikfoll** [comment]
https://gist.github.com/sirikfoll/666ff7f685628c1f4cf984e55b5da256

**Comment by sirikfoll** [comment]
Fixed in https://github.com/TrinityCore/TrinityCore/commit/b459c6607f80701945cb822d8c7519998cad205f
