### ISSUE TITLE
Nobblegarden Chocolate Eggs - no Well Fed buff

### ISSUE THREAD

**Issue by Faq** [TrinityCore/TrinityCore#6184]
rev 5dd75d91c51653a9307c994a0aaa3bc9bf0d32b2

"When you eat Chocolate egg you dont get Well Fed buff, even if it says that you should in description of item."
http://www.wowhead.com/item=44791
http://www.wowhead.com/spell=61874#comments

fix:
44953ec0a4d797d1ed51778056bc74bc478553cf

**Comment by Killyana** [comment]
Fixed.
TrinityCore rev. 5b5c0938da0f
