### ISSUE TITLE
Ship Icon and Vehicles not showing up on map

### ISSUE THREAD

**Issue by jaredjones** [TrinityCore/TrinityCore#6186]
In retail wow, the ship in Icecrown is suppose to show up as a moving icon on the main map and the minimap.

Commit: Latest from 04/12/2012

The Ship in Question:
http://i42.tinypic.com/10hllw7.png

The Map lacking the ship icon
http://i42.tinypic.com/nn38nr.png
##

**Comment by Killyana** [comment]
Npcs:
horde
Entry: 30342.
DB GUID: 134846, current GUID: 134846.
Alliance
Entry: 30343.
DB GUID: 134847, current GUID: 134847.
And they are not on the ship, for his just following the ship

**Comment by Killyana** [comment]
Set these tow npc's active seems to be a good idea as nps on the ship will be visible even if the player is not on it.

``` sql
UPDATE `creature_template` SET `AIName`='SmartAI' WHERE `entry` IN (30342, 30343);
DELETE FROM `smart_scripts` WHERE `entryorguid` IN (30342, 30343) AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(30343, 0, 0, 0, 25, 0, 100, 0, 0, 0, 0, 0, 48, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,0,'The Skybreaker- On Reset - Set active'),
(30342, 0, 0, 0, 25, 0, 100, 0, 0, 0, 0, 0, 48, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,0,'Orgrim''s Hammer- On Reset - Set active');

**Comment by Shauren** [comment]
how about no. keeping that grid permanently active is NOT a good idea.

**Comment by Killyana** [comment]
If you say so.

**Comment by NorthStrider** [comment]
The only solution I would say then is setting that unit as active permanently.

**Comment by tkrokli** [comment]
> The only solution I would say then is setting that unit as active permanently.

Shauren commented on 9 Jan 2013 :
> "Active" objects are evil and should not be used if not needed (not needed here) - what we need is allowing customization of visibility distance.

**Comment by Killyana** [comment]
Both npcs have visibilityDistanceType=5 infinite
We need just to get ride of the grid system and it will works correctly.
