### ISSUE TITLE
Core/SpellEffects: Id 86: ACTIVATE_OBJECT

### ISSUE THREAD

**Issue by angelovopsan** [TrinityCore/TrinityCore#6200]
So there is a gameobject that has specific animation /go - 181288/ and there is Art Kit in goartkit.dbc for this specific gobject. There are 2 values one for turning animation on/activate/ and one for turning animation off/deactivate/. There is a spell that is supposed to stamp the fires out /to remove the burning animation from the go/. Here is the spell below:
The spell is ID - 46903 Stamp Out Bonfire (Art Kit)

```
Effect 0: Id 86 (SPELL_EFFECT_ACTIVATE_OBJECT)
BasePoints = 1
Targets (40, 0) (TARGET_GAMEOBJECT_NEARBY_ENTRY, NO_TARGET)
EffectMiscValueA = 20
```

--> When I cast/npc do it on the object nothing happens. If I'm doing something wrong please tell me how to use it properly, if not here is what I understood so far.  The spell effect script is incomplete imo and it doesn't use the Art Kit listed in the dbc at all. The only thing it can from what I can see is to activate the speicific object and not to disable it. It is more like a activate directly instead of using the art kit? Or atleast it doesn't use this dbc at all?
The values 121 is for \SummerFest_Bonfire_ON.mdx and 122 \SummerFest_Bonfire_OFF..mdx. The spell should trigger the 2nd one, though tbh I don't see anywhere in the spell dbc the values I mentioned, nor the gameojbect. And from what I understood this effect should atleast\* also handle what I mentioned. Or there a specific way to use this effect and I don't understand it?

```
void Spell::EffectActivateObject(SpellEffIndex /*effIndex*/)
{
if (effectHandleMode != SPELL_EFFECT_HANDLE_HIT_TARGET)
return;

if (!gameObjTarget)
return;

ScriptInfo activateCommand;
activateCommand.command = SCRIPT_COMMAND_ACTIVATE_OBJECT;

// int32 unk = m_spellInfo->Effects[effIndex].MiscValue; // This is set for EffectActivateObject spells; needs research

gameObjTarget->GetMap()->ScriptCommandStart(activateCommand, 0, m_caster, gameObjTarget);
}
```

TDB: 11.46
Hash: 4f14693ef29402c6cfdab38879f9722235e4e1a9
OS: XP
##

**Comment by Killyana** [comment]
There's a missing trap: (with spell http://wotlk.openwow.com/spell=28784)
Also some related spell:
wowhead.com/spell=46904
wowhead.com/spell=29831
wowhead.com/spell=45443
wowhead.com/spell=45437
wowhead.com/spell=46903

``` sql
DELETE FROM `gameobject_template` WHERE `entry` IN (181290);
INSERT INTO `gameobject_template` (`entry`, `type`, `displayId`, `name`, `IconName`, `castBarCaption`, `unk1`, `faction`, `flags`, `size`, `data0`, `data1`, `data2`, `data3`, `data4`, `data5`, `data6`, `data7`, `data8`, `data9`, `data10`, `data11`, `data12`, `AIName`, `ScriptName`, `VerifiedBuild`) VALUES
(181290,6,0,'Midsummer Bonfire Spawn Trap','','','',0,0,1,0,0,0,28784,0,0,-1,0,0,0,0,0,0,'','',0);

**Comment by Aokromes** [comment]
This can be pushed?

**Comment by Killyana** [comment]
Push the template but don't close the issue.

**Comment by sirikfoll** [comment]
GameObjectArtKit.dbc seems to be currently unused, no idea on how to fix tho

**Comment by Killyana** [comment]
There's 2 wrong conditions, as this 2 spells are supposed to target all midsummer fires:
``` sql
DELETE FROM conditions WHERE SourceTypeOrReferenceId=13 AND SourceEntry IN (46904, 46903);

**Comment by Killyana** [comment]
This spell effects:  	Activate Object (15)  Activate Object (20)  still not activating objects
example: http://wotlk.openwow.com/spell=44422
We are using this conditions, but the object is never activated when the spell is casted:
``` 
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId` IN(13,17) AND `SourceEntry`=44422;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`,`SourceGroup`,`SourceEntry`,`SourceId`,`ElseGroup`,`ConditionTypeOrReference`,`ConditionTarget`,`ConditionValue1`,`ConditionValue2`,`ConditionValue3`,`NegativeCondition`,`ErrorType`,`ErrorTextId`,`ScriptName`,`Comment`) VALUES
(17,0,44422,0,0,30,0,186946,5,0,0,0,0,'',"Spell 'Scavenge' target GameObject 'Fjord Hawk Egg'"),
(13,1,44422,0,0,31,0,5,186946,0,0,0,0,'',"Spell 'Scavenge' target GameObject 'Fjord Hawk Egg'");

**Comment by Killyana** [comment]
dup https://github.com/TrinityCore/TrinityCore/issues/21078
