### ISSUE TITLE
[Ability][Hunter] Disengage works sporadically

### ISSUE THREAD

**Issue by Marforius** [TrinityCore/TrinityCore#6209]
Disengage works, pushes the target back properly however the casting hunter has to spam it to work correctly, otherwise the icon is greyed out and he receives a message saying "can't use that right now".

Tested on: 2012-04-11 17:41:36 -0500 (397ee8c) (Win64, Release)
Patches: None
TDB: TDB 335.11.45 Full for TC hash 84268be (2012/02/13) (with all updates at time of compile)

**Comment by Killyana** [comment]
Cannot reproduce on TrinityCore rev. 5b5c0938da0f , if this still happen reopen the issue.
