### ISSUE TITLE
[Quest] On Nethery Wings

### ISSUE THREAD

**Issue by Zaranthos** [TrinityCore/TrinityCore#6210]
Using the quest item uses charges but doesn't destroy the mana conduit. Unable to complete quest.
http://www.wowhead.com/quest=10438

2012-04-15 17:41:37 +0200 (39b3589dcb54+) (Win64, Release)
TDB_full_335.11.46_2012_02_13 (+updates)
##

**Comment by Aokromes** [comment]
This bug was fixed no?

**Comment by Killyana** [comment]
Still bugued on rev. 68c4ea314443

**Comment by Killyana** [comment]
According to the spell description 35734 the Range=100 yards (Tower), on the spell focus the range is  50 yards and the fly will never be too close to the gob. Also on respawn the npc falls to the ground, I cannot find find how to fix it.
``` sql
UPDATE `gameobject_template` SET `data1`=100 WHERE `entry` = 184643;

**Comment by dr-j** [comment]
maybe spell focus should be moved rather than changing wdb data on go since spell focus positions cant be sniffed.

**Comment by Killyana** [comment]
``` sql
UPDATE `gameobject` SET `position_z`=402.410004 WHERE `guid`=99956;

**Comment by ikir83** [comment]
This still happens on Trinity Core: d82534a7bbd4 DB: 335.61

I can try to apply Killyana query

**Comment by tkrokli** [comment]
it has been part of the TDB since 2015-03-02 (commit https://github.com/TrinityCore/TrinityCore/commit/32b792915fb494eefb9275a6cc55dabaa6d46db4) so it won't change the game object, unless you have modified those data yourself before you got the issue.

**Comment by jerbookins** [comment]
f909d4f1957b

Still unable to complete using only the Netherdrake. Using ones own flying mount works.

**Comment by dr-j** [comment]
This is due to combat range on tc this is much lower than on retail and when you get out of range npc evades and resets

**Comment by Wyrserth** [comment]
Issue still exists as of ba8d3254c22c271e69f10ee6b87d51e36d680451, range should be 100 yards but because data1=50 the core only allows casting within 25 yards.

The path of the Netherdrake also looks a bit wrong compared to [retail](https://www.youtube.com/watch?v=wBuyWjfI9_k). The dragon clips through a map object on the way, and goes through the crystal two times instead of just cycling around it.

**Comment by Killyana** [comment]
``` sql
DELETE FROM `gameobject` WHERE `guid` IN (99956,9381,9385,9386);
INSERT INTO `gameobject` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `position_x`, `position_y`, `position_z`, `orientation`, `rotation0`, `rotation1`, `rotation2`, `rotation3`, `spawntimesecs`, `animprogress`, `state`, `VerifiedBuild`) VALUES
(99956, 184643, 530, 0, 0, 1, 1, 3964.10376, 2008.44445, 381.94104, 0.176697, 0, 0, 0, 1, 180, 0, 1, 15595),
(9381, 184643, 530, 0, 0, 1, 1, 3930.18457, 2038.26062, 383.50134, 1.720004, 0, 0, 0, 1, 180, 0, 1, 15595),
(9385, 184643, 530, 0, 0, 1, 1, 3902.93530, 1996.42260, 385.64352, 3.275094, 0, 0, 0, 1, 180, 0, 1, 15595),
(9386, 184643, 530, 0, 0, 1, 1, 3942.99975, 1970.09973, 386.32125, 5.105074, 0, 0, 0, 1, 180, 0, 1, 15595);
