### ISSUE TITLE
Opening a game object(banner) under absorb effects in battlegrounds should result an interupt

### ISSUE THREAD

**Issue by baudejas** [TrinityCore/TrinityCore#6222]
If you're opening a banner for example at arathi basin and got hit by an enemy player, your current opening should be interupted. Problem is that it doesn't work on players with absorbing shields (like Ice barrier and so on)

TrinityCore rev. 2012-04-12 23:58:10 +0300 (296de924f108+) (Unix, Release)
TDB 335.11.46

**Comment by Aokromes** [comment]
If the fix here is valid, plz open a PR.
