### ISSUE TITLE
Obsi Bug Tornadoes

### ISSUE THREAD

**Issue by SkyAngel** [TrinityCore/TrinityCore#6226]
And again I
I'm sorry that I trouble you again but in obsidian are the tornadoes in the lava when it comes to a close and constant kicking off track
Once you fight the boss is too close to them, than one can no longer take part in the fight

I would like to take out but they are not getting into the target, anyone happen to know the ID?

**Comment by Killyana** [comment]
Fixed
TrinityCore rev. 5b5c0938da0f
