### ISSUE TITLE
bullets in ToCr

### ISSUE THREAD

**Issue by telsamat** [TrinityCore/TrinityCore#6258]
rev 9231f04d0f 
tdb 46

according this commit https://github.com/TrinityCore/TrinityCore/commit/e8c3cb1c10f8c7cb8edcddeb6b7b0705563c161c#-P0

for me now after going into the instance bullets are flying around before starting event with valkyr

works fine only with ally characters

on horde char it is bugged

**Comment by Aokromes** [comment]
This bug is fixed no?

**Comment by Killyana** [comment]
Yes fixed.
