### ISSUE TITLE
[Quest] Corki's Gone Missing Again!

### ISSUE THREAD

**Issue by Exodius** [TrinityCore/TrinityCore#6281]
Quest: http://www.wowhead.com/quest=9924
Corki: http://www.wowhead.com/npc=20812

Problem: Upon unlocking the cage, Corki does not leave it and quest can't be completed.

How it should work:
1. Take quest and head to Northwind Cleft cave;
2. Kill Ogres in the cage to get the key;
3. When you get the key, go to Corki's cage in the cave;
4. Open the cage with the key, Corki thanks you, quest counts and you turn it in.

Revision: a28742bffeca3764468b3f307a86c14e2f3e3607
TDB: DB: 335.11.46 + Repository Updates

**Comment by Killyana** [comment]
The quest was scripted, just the creature_text is wrong:
``` sql
UPDATE `creature_text` SET `text`= "This is the last time I get caught! I promise! Bye!", `BroadcastTextId`=15308, `Language`=0 WHERE `entry`=20812;
