### ISSUE TITLE
[Object] Nether Drake Egg

### ISSUE THREAD

**Issue by Exodius** [TrinityCore/TrinityCore#6284]
Object ID: http://www.wowhead.com/object=184867
Nether Whelp: http://www.wowhead.com/npc=20021

Problem:
When you "open" it, it does not hatch.

How should it work:
When you "open" it, it should hatch a Nether Whelp and despawn..

Related with quest "[What Came First, the Drake or the Egg?](http://www.wowhead.com/quest=10609)"
Revision: a28742bffeca3764468b3f307a86c14e2f3e3607
TDB: DB: 335.11.46 + Repository Updates

**Comment by fvicaria** [comment]
This is still a problem. Same description given by Exodius about 3 years ago.

**Comment by Killyana** [comment]
``` sql
DELETE FROM `spell_linked_spell` WHERE `spell_trigger` = 37639 AND `spell_effect` = 36326;
INSERT INTO `spell_linked_spell` (`spell_trigger`,`spell_effect`,`type`,`comment`) VALUES
( 37639, 36326, 0, 'Nether Whelp');
