### ISSUE TITLE
[Rotface] Slime Spray

### ISSUE THREAD

**Issue by BlackangelWow** [TrinityCore/TrinityCore#6328]
Hello :D 
The spell "Slime Spray" shouldnt be kickable  , but you can interrput it
what make it abuseable

Related IDs:
http://www.wowhead.com/npc=36627
http://www.wowhead.com/spell=69508

Server info:
hash : fb787ae
Tdb: 335.11.46+

**Comment by SQLfix** [comment]
confirm still bugged

**Comment by danlapps** [comment]
I think i submitted a full ICC sniff some weeks ago, might this help ?

**Comment by Aokromes** [comment]
we have more :P we lack c++ guys fixing scripts or spells on 3.3.5a :&

**Comment by danlapps** [comment]
Same as https://github.com/TrinityCore/TrinityCore/issues/11835 ?  And is it good fix if same ?

**Comment by SQLfix** [comment]
@danlapps  Not work . mechanic_immune_mask dont work on this Bug

**Comment by Rushor** [comment]
kickable or intruptable while using taunts?

**Comment by Runico** [comment]
@Rushor, Both

**Comment by Killyana** [comment]
It's a general issue related to; https://github.com/TrinityCore/TrinityCore/issues/12020

**Comment by Aokromes** [comment]
#12020
