### ISSUE TITLE
[Item] Nibelung

### ISSUE THREAD

**Issue by JudgeGM** [TrinityCore/TrinityCore#6337]
Hello , 
There are 2 bugs:
1.It can't proc from damage over time effects 
2.It can't proc inside arenas

What should happen instead
1.The Valkyr should be summon from every kind of damage ,  including DOTS.
2.The Valkyr should be able to appear in arenas as well, yet at the moment this spell doesn't appear to work inside arenas.

Related IDs:
http://www.wowhead.com/spell=71845 - Item - Icecrown 25 Normal Caster Weapon Proc

Server info :
hash : fb787ae
Tdb: 335.11.46+
##

**Comment by lainimer** [comment]
confirm

**Comment by ariel-** [comment]
Is the issue valid? https://github.com/TrinityCore/TrinityCore/issues/6337#issuecomment-5357798

**Comment by Keader** [comment]
No answers in 26 days and links posted in https://github.com/TrinityCore/TrinityCore/issues/6337#issuecomment-5372113 not work anymore... so closing.
