### ISSUE TITLE
[Quest] Craftsman's Writ - Goblin Sapper Charge

### ISSUE THREAD

**Issue by Zaranthos** [TrinityCore/TrinityCore#6343]
http://old.wowhead.com/quest=9195

You can acquire the items but can't turn them in to complete the quest.

There are 24 quests in this "chain" and probably none of them work. The comments for this quest links all the other quests in this chain.

2012-04-15 17:41:37 +0200 (39b3589dcb54+) (Win64, Release)
TDB_full_335.11.46_2012_02_13 (+updates)

**Comment by Killyana** [comment]
Fixed TrinityCore rev. 5b5c0938da0f
PS: In some cases Quests requires items cannot be completed event if you have all requirements, in this case you must put the items in the bank and get them back or use a vendor or just exchange the items with an other player, this happen if you keep the items a long tie in your inventory
