### ISSUE TITLE
[Bug Spells] Visual and Sound Resurrection Bug

### ISSUE THREAD

**Issue by Expecto** [TrinityCore/TrinityCore#6355]
When using self-reviving spells
(the visual and sound effect doesn't work)
Example:Shaman Spell Reincarnation

Rev Hash 778afa11ac80837c877d043c6146e18c1aab89aa

**Comment by Killyana** [comment]
There's a visual for the reincarnation and also a sound, my be fixed long time ago.
https://youtu.be/8maAExPsCBU?t=43s
TrinityCore rev. 5b5c0938da0f
