### ISSUE TITLE
Gameobject not exist and not created at spell

### ISSUE THREAD

**Issue by Expecto** [TrinityCore/TrinityCore#6366]
Spells ID 

http://old.wowhead.com/spell=61063
http://old.wowhead.com/spell=61067

Gameobject (Entry: 193977) not exist and not created at spell (ID: 61063) cast
Gameobject (Entry: 193978) not exist and not created at spell (ID: 61067) cast

don't summon object because not in DB

TDB 11.46

Rev Hash 272351594642eb239ff4d0342cc1e0cdc9815015

**Comment by Aokromes** [comment]
Note to self: get gameobjects from tdb 4.3.4
