### ISSUE TITLE
[Warrior][Talent] Titan's Grip - Damage Reduction

### ISSUE THREAD

**Issue by telsamat** [TrinityCore/TrinityCore#6375]
rev.: b53485e053 
tdb 46

wiki says: Patch 3.1.0 (2009-04-14): 10% damage decrease 

Reduction part of this talent does not work anymore.

**Comment by D4R4** [comment]
Is this still considered a valid issue? I can't find the aura 49152 on my toon when dual-wielding two-hand weps atm with Titan's Grip

**Comment by Killyana** [comment]
Still not fixed on rev. 5b5c0938da0f
If you .aura 49152 you will  see on your stats "damage" will turn red with x90% instead of 100%

**Comment by ccrs** [comment]
Ive tested this, and damage reduction seems to be huge O.o (like 3k less dps)
I'm wondering if there is samething in core or db that also applies the reduction.

@robinsch do you know anything about this?

**Comment by robinsch** [comment]
Do some testing first, if this is really not working as it should I can check and fix it.

**Comment by ccrs** [comment]
Like I said, I already tested it :)

Aura/unaura works fine.
The only matter here is if it's a double damage reduction or not:
results show big dps loss (around 3k)

**Comment by ccrs** [comment]
Maybe its a matter of spell damage calculation with that damage reduction (just wondering)

**Comment by ccrs** [comment]
dealed:
![image](https://cloud.githubusercontent.com/assets/4329612/8623742/6df8cd12-2733-11e5-86a0-475540ee93a3.png)

expected:
![image](https://cloud.githubusercontent.com/assets/4329612/8623762/8b4bfa06-2733-11e5-8f35-cde05d96c89a.png)


dealed:
![image](https://cloud.githubusercontent.com/assets/4329612/8623788/c7e79a74-2733-11e5-9e14-44565599226d.png)

expected:
![image](https://cloud.githubusercontent.com/assets/4329612/8623793/cd59a4fc-2733-11e5-97bb-fef57ba72e5a.png)

dealed:
![image](https://cloud.githubusercontent.com/assets/4329612/8623835/0cbbd28c-2734-11e5-8c2b-b234239c574f.png)

expected:
![image](https://cloud.githubusercontent.com/assets/4329612/8623842/13121c68-2734-11e5-95c6-79d9e81e61f4.png)



(soz for spanish locales :P)

**Comment by ccrs** [comment]
more info:
http://wowwiki.wikia.com/Attack_power_coefficient

**Comment by Keader** [comment]
Fix by @Vincent-Michael work here :+1:

**Comment by Keader** [comment]
Fix by: @Vincent-Michael It has one small problem. Relog after the damage reduction is removed.

**Comment by Keader** [comment]
Hey @Vincent-Michael Divine Intervetion (spell id: 19752) of Paladins, remove reduction.

**Comment by Aokromes** [comment]
If anything here is valid plz open a PR for it.

**Comment by Aokromes** [comment]
@Vincent-Michael can you merge this?

**Comment by Keader** [comment]
I'm using Vincent-Michael fix, and works fine
But need a spellmgrfix:
```cpp
case 49152:
                spellInfo->Attributes |= SPELL_ATTR0_UNAFFECTED_BY_INVULNERABILITY;
                break;
```

**Comment by robinsch** [comment]
Same for other immunity effects, such as Hand of Protection

**Comment by joschiwald** [comment]
how is this possible titan's grip has SPELL_ATTR0_PASSIVE

**Comment by Poli93** [comment]
Is there any progress with this spell? It's literally been three years. Don't misunderstand me I do not complain but I'm confused, I see a lot of inputs and someone even suggested a possible fix.
