### ISSUE TITLE
[NPC/GO] Baron Rivendare - Doors remain closed

### ISSUE THREAD

**Issue by Zaranthos** [TrinityCore/TrinityCore#6377]
http://old.wowhead.com/npc=10440

You enter the room he's in and the doors close and when you kill him and his mobs the doors should open again but do not. End up trapped inside and have to HS, teleport or portal out.

Update: If you go just inside the doors of the room he is in, range attack him, and quickly back up outside the room and up the stairs to the closed outside door and kill him there the doors will open and you can leave as intended. The GO range that detects his death must be too small an area.

2012-04-28 15:10:52 +0200 (b53485e05326+) (Win64, Release)
b53485e05326f9ed6562aa78fee282f255eac339
TDB_full_335.11.46_2012_02_13 (+updates)

**Comment by cr4st** [comment]
```diff
diff --git a/src/server/scripts/EasternKingdoms/Stratholme/boss_baron_rivendare.cpp b/src/server/scripts/EasternKingdoms/Stratholme/boss_baron_rivendare.cpp
index 8d7d430..237a82c 100644
--- a/src/server/scripts/EasternKingdoms/Stratholme/boss_baron_rivendare.cpp
+++ b/src/server/scripts/EasternKingdoms/Stratholme/boss_baron_rivendare.cpp
@@ -106,7 +106,8 @@ class boss_baron_rivendare : public CreatureScript
         void AttackStart(Unit* who) override
         {
             //can't use entercombat(), boss' dmg aura sets near players in combat, before entering the room's door
-            instance->SetData(TYPE_BARON, IN_PROGRESS);
+            if (instance && instance->GetData(TYPE_BARON) == NOT_STARTED)
+                instance->SetData(TYPE_BARON, IN_PROGRESS);
             ScriptedAI::AttackStart(who);
         }
```
Should resolve this issue. :ice_cream:

**Comment by StormBytePP** [comment]
I created a PR with @cr4st changes #15257
