### ISSUE TITLE
Professor Putricide - Gas Cloud

### ISSUE THREAD

**Issue by kakakon** [TrinityCore/TrinityCore#6396]
Greetings.

In Professor Putricide 25 and 10 normal mode his skill "Unstable Experiment" summon two kinds of mobs, one by one. one of them green named  "Volatile Ooze" and the secoud orange named "Gas Cloud". The Orange (Gas Cloud) mob choosing a target and start run to her, befor the mob hit the target he does 1950 - 2050 damage (damage school- Nature / Shadow) every two seconds.
In addition the orange mob put on his target 10 stacks, those stacks set the damage that the target will take if the mob will hit his target, every two seconds one stack fall from the target, more stacks the damage will be higher, less stacks the damage will be lower. the damage that the target takes will be given to the whole raid. afther 20 seconds the target wont have stacks and the mob will choose new target.

What happens instead, when the orange mob hit the target while the target have less then 10 stacks the damage gained will be equal to the damage gained from 10 stacks on the target.

Gas Cloud - http://old.wowhead.com/npc=37562#abilities:mode=normal25
Gaseous Bloat - http://old.wowhead.com/spell=72858

Hash : fb787ae Tdb: 335.11.46+

**Comment by Rushor** [comment]
to clarify it for these who do not want to read the large text:

10 stacks of spell 72858 -> 11k Damage
9 stacks of spell 72858 -> 11k Damage
8 of spell 72858 -> 11k Damage

and so on.

**Comment by danlapps** [comment]
Im not a good c programmer, but is it possible spell 72858 is not in  https://github.com/TrinityCore/TrinityCore/blob/e6f26cfb1f75d21a166cc3fd371f9c5f1641625e/src/server/scripts/Northrend/IcecrownCitadel/boss_professor_putricide.cpp but SPELL_GASEOUS_BLOAT                     = 70672, is instead ?

**Comment by Rushor** [comment]
The CastCustomSpell seems to beak the mechanic, that the damage will be reduced with less stacks.

i used this https://gist.github.com/Rushor/e06d0ca59a047d4ee332 (also with the regist of the spellscript(forgot that in gist)) and it didn't changed the amount of damage :(

**Comment by Rushor** [comment]
maybe 
```diff
diff --git a/src/server/scripts/RG/Northrend/IcecrownCitadel/boss_professor_putricide.cpp b/src/server/scripts/RG/Northrend/IcecrownCitadel/boss_professor_putricide.cpp
index 50feaf5..8703bf4 100644
--- a/src/server/scripts/RG/Northrend/IcecrownCitadel/boss_professor_putricide.cpp
+++ b/src/server/scripts/RG/Northrend/IcecrownCitadel/boss_professor_putricide.cpp
@@ -1348,10 +1348,12 @@ class spell_putricide_gaseous_bloat : public SpellScriptLoader
 
             void HandleExtraEffect(AuraEffect const* /*aurEff*/)
             {
+                PreventDefaultAction();
+                uint32 bloat = sSpellMgr->GetSpellIdForDifficulty(uint32(SPELL_GASEOUS_BLOAT), GetCaster());
                 Unit* target = GetTarget();
                 if (Unit* caster = GetCaster())
                 {
-                    target->RemoveAuraFromStack(GetSpellInfo()->Id, GetCasterGUID());
+                    target->RemoveAuraFromStack(bloat, GetCasterGUID());
                     if (!target->HasAura(GetId()))
                     {
                         caster->GetMotionMaster()->MovementExpired();
@@ -1363,6 +1365,12 @@ class spell_putricide_gaseous_bloat : public SpellScriptLoader
                         caster->CastCustomSpell(SPELL_GASEOUS_BLOAT, SPELLVALUE_AURA_STACK, 10, caster, false);
                     }
                 }
+                if (Aura const* aura = GetTarget()->GetAura(bloat))
+                {
+                    uint32 stack = aura->GetStackAmount();
+                    uint32 basepoints = aura->GetSpellInfo()->GetBasePoints(EFFECT_0);
+                    GetCaster()->DealDamage(target, stack * basepoints, NULL, DIRECT_DAMAGE, SPELL_SCHOOL_MASK_NORMAL, NULL, false);
+                }
             }
 
             void Register()
```

**Comment by Rushor** [comment]
the problem itself is that RemoveAuraFromStack() does not update the damage of the periodic ticks

Spell difficulty Ids:
Normal 10: 70672
Normal 25: 72455
Heroic 10: 72832
Heroic 25: 72833

**Comment by ccrs** [comment]
AFAIK periodic damage should always be the same, regardless of aura stack amount

**Comment by Rushor** [comment]
bte someone know how do deal spelldamage which appears in the combatlog?
```diff
GetCaster()->DealDamage(..) 
```
only deals direct damage, it is not reducable with mods and it does not appear in the combatlog :/

**Comment by Nyeriah** [comment]
That's a hack. Modify the damage value from the spell that should deal the damage instead

**Comment by ccrs** [comment]
working on it :)

**Comment by ccrs** [comment]
Ok, this isnt as easy as it seems.

There is no aura hook to update tick damage (thats the reason for all the hacks in SpellAuraEffects)

The only thing I found is a hook on Unitscripts: "ModifyPeriodicDamageAurasTick".
I'll try to use it on gas cloud script.

**Comment by ccrs** [comment]
try this @Rushor : 

````c++
class npc_gas_cloud : public CreatureScript
{
    public:
        npc_gas_cloud() : CreatureScript("npc_gas_cloud") { }

        struct npc_gas_cloudAI : public npc_putricide_oozeAI
        {
            npc_gas_cloudAI(Creature* creature) : npc_putricide_oozeAI(creature, SPELL_EXPUNGED_GAS)
            {
            }

            void CastMainSpell()
            {
                me->CastCustomSpell(SPELL_GASEOUS_BLOAT, SPELLVALUE_AURA_STACK, 10, me, false);
            }
        };

        void ModifyPeriodicDamageAurasTick(Unit* target, Unit* /*attacker*/, uint32& damage) override
        {
            if (Aura* aura = target->GetAura(SPELL_GASEOUS_BLOAT))
                damage *= aura->GetStackAmount();
        }

        CreatureAI* GetAI(Creature* creature) const override
        {
            return GetIcecrownCitadelAI<npc_gas_cloudAI>(creature);
        }
};
````

**Comment by Nyeriah** [comment]
Maybe an aurascript like https://github.com/TrinityCore/TrinityCore/blob/6.x/src/server/scripts/Northrend/IcecrownCitadel/boss_the_lich_king.cpp#L2818-L2882

**Comment by Rushor** [comment]
@ccrs: sadly no changes :/ http://i.imgur.com/22ApKDx.jpg maxdmg with a few stacks

i will try the lkstuff

**Comment by ccrs** [comment]
@Rushor another try:

````c++
class spell_putricide_gaseous_bloat : public SpellScriptLoader
{
    public:
        spell_putricide_gaseous_bloat() : SpellScriptLoader("spell_putricide_gaseous_bloat") { }

        class spell_putricide_gaseous_bloat_AuraScript : public AuraScript
        {
            PrepareAuraScript(spell_putricide_gaseous_bloat_AuraScript);

            void HandleExtraEffect(AuraEffect const* /*aurEff*/)
            {
                Unit* target = GetTarget();
                if (Unit* caster = GetCaster())
                {
                    if (AuraEffect* effect = GetAura()->GetEffect(EFFECT_0))
                        effect->RecalculateAmount(caster);

                    target->RemoveAuraFromStack(GetSpellInfo()->Id, GetCasterGUID());
                    if (!target->HasAura(GetId()))
                        caster->CastCustomSpell(SPELL_GASEOUS_BLOAT, SPELLVALUE_AURA_STACK, 10, caster, false);
                }
            }

            void OnProc(AuraEffect const* aurEff, ProcEventInfo& eventInfo)
            {
                PreventDefaultAction();

                uint8 stack = GetStackAmount();
                int32 const mod = (GetTarget()->GetMap()->GetSpawnMode() & 1) ? 1500 : 1250;
                int32 dmg = 0;
                for (uint8 i = 1; i < stack; ++i)
                    dmg += mod * stack;
                if (Unit* caster = GetCaster())
                    caster->CastCustomSpell(SPELL_EXPUNGED_GAS, SPELLVALUE_BASE_POINT0, dmg);
            }

            void CalculateBonus(AuraEffect const* aurEff, int32& amount, bool& canBeRecalculated)
            {
                canBeRecalculated = true;
                amount = 0;
                amount = aurEff->GetBaseAmount() * (GetStackAmount() - 1);
            }

            void Register() override
            {
                OnEffectPeriodic += AuraEffectPeriodicFn(spell_putricide_gaseous_bloat_AuraScript::HandleExtraEffect, EFFECT_0, SPELL_AURA_PERIODIC_DAMAGE);
                OnEffectProc += AuraEffectProcFn(spell_putricide_gaseous_bloat_AuraScript::OnProc, EFFECT_0, SPELL_AURA_PERIODIC_DAMAGE);
                DoEffectCalcAmount += AuraEffectCalcAmountFn(spell_putricide_gaseous_bloat_AuraScript::CalculateBonus, EFFECT_0, SPELL_AURA_MOD_DAMAGE_PERCENT_DONE);
            }
        };

        AuraScript* GetAuraScript() const override
        {
            return new spell_putricide_gaseous_bloat_AuraScript();
        }
};
````

in uint.cpp at ````
bool Unit::HandleAuraProc(Unit* victim, uint32 damage, Aura* triggeredByAura, SpellInfo const* procSpell, uint32 /*procFlag*/, uint32 procEx, uint32 cooldown, bool * handled) ````
````diff
-                // Gaseous Bloat
-                case 70672:
-                case 72455:
-                case 72832:
-                case 72833:
-                {
-                    *handled = true;
-                    uint32 stack = triggeredByAura->GetStackAmount();
-                    int32 const mod = (GetMap()->GetSpawnMode() & 1) ? 1500 : 1250;
-                    int32 dmg = 0;
-                    for (uint8 i = 1; i < stack; ++i)
-                        dmg += mod * stack;
-                    if (Unit* caster = triggeredByAura->GetCaster())
-                        caster->CastCustomSpell(70701, SPELLVALUE_BASE_POINT0, dmg);
-                    break;
-                }
````
erase my previous workaround

**Comment by Rushor** [comment]
@ccrs  -thx, but somehow this fucks up everything xD

a) the periodicdmg is now way to high and does not get reduced if the stacks get lower
b) the proc and the the explode works nicely :)

http://i.imgur.com/LpXsibA.jpg
http://i.imgur.com/LdAZqVm.jpg

**Comment by ccrs** [comment]
updated

**Comment by Rushor** [comment]
:+1:

**Comment by ccrs** [comment]
tested and working :)

**Comment by Rushor** [comment]
no decrease for me :/ http://i.imgur.com/ixlHxOt.jpg http://i.imgur.com/mQYXEge.jpg shure that it's working for you? :D

**Comment by ccrs** [comment]
O.o yes it does. 

Try to erase any other change and use only the last one i posted

**Comment by Rushor** [comment]
concerning

```cpp
for (uint8 i = 1; i <= stacks; ++i)
                    dmg += mod * stacks;
                if (Unit* caster = GetCaster())
                    caster->CastCustomSpell(SPELL_EXPUNGED_GAS, SPELLVALUE_BASE_POINT0, dmg);
```

we must remove the for (uint8 i = 1; i <= stacks; ++i) because corrently the damage for the explode is calculated like this:
(in case of 9 stacks in 25er man mode)
1500 * 9 * 9 
xD

**Comment by Shauren** [comment]
FYI: The scaling on retail is NOT linear

**Comment by Rushor** [comment]
:o interesting http://wowwiki.wikia.com/wiki/Professor_Putricide?file=Putricide-gas-cloud-calculation.jpg

**Comment by Shauren** [comment]
yeeeep, thats it.
now then - is the issue of always doing damage as if the target had max stacks still valid?

**Comment by ccrs** [comment]
@Shauren nice, I didnt see that typo. The spellscript works as intended, there isn't much left to do.

**Comment by Kittnz** [comment]
PR it then =)

**Comment by ccrs** [comment]
at least use the spellscript to erase the hack :P

**Comment by ccrs** [comment]
oh and the periodic tic damage is bugged wihout it too.

**Comment by Rushor** [comment]
i will open up a new issue tomorrow for it

**Comment by Shauren** [comment]
hack? you call the entire old proc system a hack?

**Comment by ccrs** [comment]
wut? isnt that a hack?
````
                // Gaseous Bloat
                case 70672:
                case 72455:
                case 72832:
                case 72833:
                {
                    *handled = true;
                    uint32 stack = triggeredByAura->GetStackAmount();
                    int32 const mod = (GetMap()->GetSpawnMode() & 1) ? 1500 : 1250;
                    int32 dmg = 0;
                    for (uint8 i = 1; i < stack; ++i)
                        dmg += mod * stack;
                    if (Unit* caster = triggeredByAura->GetCaster())
                        caster->CastCustomSpell(70701, SPELLVALUE_BASE_POINT0, dmg);
                    break;
                }
````

**Comment by Shauren** [comment]
No, it is not. Also I have zero issues with periodic damage of this aura - see 
![bloat](https://cloud.githubusercontent.com/assets/297439/11511494/b894fb50-9869-11e5-9989-41bca610034b.PNG)
