### ISSUE TITLE
Mirror image should switch target

### ISSUE THREAD

**Issue by johndays** [TrinityCore/TrinityCore#6400]
If you cast mirror image, they only attack the first target.

Example : You have 2 targets, and now you must spawn mirror image, now cc target 1 and swicth to target 2. The mirror's stopping to attack target 1 but they don't switch to target 2.

**So, mirrors image must attack same target as you, and follow you always!**

**Comment by Killyana** [comment]
Tested on rev. 5b5c0938da0f they switch target and always attacks npcs on range.
