### ISSUE TITLE
Item - Heartpierce

### ISSUE THREAD

**Issue by Loginisalreadytaken** [TrinityCore/TrinityCore#6421]
Don't know about normal version, but ilvl277 Heartpierce's **Item - Icecrown 25 Heroic Dagger Proc** (spell 71892) only triggers on the hits of Heartpierce itself, never the other weapon when dual wielding. (see http://old.wowhead.com/item=49982#comments:id=919413)

Core revision: Trinity Core b72617a77be6+
Database revision: TDB 335.11.46

**Comment by Killyana** [comment]
Fixed, just .aura 71892 and use some melee attacks without Heartpierce and the buff will proc.
rev. 5b5c0938da0f
