### ISSUE TITLE
[Quest] Libram of Focus

### ISSUE THREAD

**Issue by Zaranthos** [TrinityCore/TrinityCore#6424]
http://old.wowhead.com/quest=7484

You gather all the required items but can't click the continue button to complete the quest. Quest ? is also grey instead of yellow.

2012-04-28 15:10:52 +0200 (b53485e05326+) (Win64, Release) AHbot
b53485e05326f9ed6562aa78fee282f255eac339
TDB_full_335.11.46_2012_02_13 (+updates)

**Comment by Killyana** [comment]
on rev. 5b5c0938da0f it works fine, probably fixed long time ago.
