### ISSUE TITLE
[QUEST] Now, When I Grow Up... (11975)

### ISSUE THREAD

**Issue by nelegalno** [TrinityCore/TrinityCore#6425]
This is currently (as of d8e4e164c6b54444a233db9613f4564085410c7d ) the only not working quest for the Blood Elf Orphan.
It should be marked as complete when you are around 76,81 in Silvermoon City.

P.S. The only other problem is that you can see all quests when you summon the orphan.
##

**Comment by Killyana** [comment]
Seems easy to fix : https://github.com/TrinityCore/TrinityCore/blob/41e2b0046dc73ab2adf9c15442d70a7b769013f9/src/server/scripts/Events/childrens_week.cpp#L1023

**Comment by tkrokli** [comment]
Same line as above in the 3.3.5 branch version of the file:
https://github.com/TrinityCore/TrinityCore/blob/011b8847d1bb657137fe593fdb0b62a232b523e8/src/server/scripts/Events/childrens_week.cpp#L1040

**Comment by Killyana** [comment]
Works fine in rev. 6efdcd3ea8bf
