### ISSUE TITLE
Alterac Valley. Missing Reputation

### ISSUE THREAD

**Issue by milotic** [TrinityCore/TrinityCore#6426]
Alterac Valley have many bugs in quest and reputation.

List of mising or incorrect reputation.

Killing Enemy General (389 Rep) :http://www.wowhead.com/npc=11948 http://www.wowhead.com/npc=11946
Killing Enemy Captain (125 rep)  http://www.wowhead.com/npc=11947 http://www.wowhead.com/npc=11949
Killing an Enemy Air Master (5 rep) http://www.wowhead.com/npc=13438 http://www.wowhead.com/npc=13439 http://www.wowhead.com/npc=13437 http://www.wowhead.com/npc=13179 http://www.wowhead.com/npc=13180 http://www.wowhead.com/npc=13181
Killing any Enemy Guard (5 rep) *NOTE: This is capped through honored and does not give rep in revered* http://old.wowhead.com/npcs?filter=na=guar;cr=6;crs=2597;crv=0
Killing an Enemy Player(+1 Rep+HK+CP).
Killing Ivus the Forest Lord or Lokholar the Ice Lord (125 rep) http://www.wowhead.com/npc=13256 http://www.wowhead.com/npc=13419
Destroying an Enemy Tower (64 rep) 

At the end of the game, extra rep is gained for each of the following conditions:

    Enemy Captain Killed (36 rep)
    Allied Captain Still Alive (125 rep)
    Enemy Towers Destroyed (24 rep each)
    Controlled Intact Tower (12 rep each)
    Controlled Graveyards (12 rep each)
    Controlled Mines (12 rep each) 

Source: http://www.wowwiki.com/Alterac_Valley

Core revision: all

**Comment by Killyana** [comment]
I tested all npcs listed here and the reputation amounts are correct, probably fixed long time ago.
rev. 5b5c0938da0f
