### ISSUE TITLE
[33.5][Hunter] Explosive Trap

### ISSUE THREAD

**Issue by cover25** [TrinityCore/TrinityCore#6464]
Other than it missing the initial burst of damage (see https://github.com/TrinityCore/TrinityCore/issues/5740) It can be used in places such as dalaran, or frozen halls as a way to damage a player of the opposite faction. 

To replicate, Walk up to a opposite member of your faction, place the trap and watch it explode. It should do 900ish damage (It does initial damage when on a player in sanctuaries but not in normal combat? Odd...)

http://old.wowhead.com/spell=13813

Version: 3.3.5a (12340)
Core revision: Trinity Core b72617a77be6+
Database revision: TDB 335.11.46
##

**Comment by Rushor** [comment]
Furthermore you can target neutral creatures in dalaran with this (not only palyers)

**Comment by Eliminationzx** [comment]
```diff
 src/server/game/Spells/SpellMgr.cpp | 4 ++++
 1 file changed, 4 insertions(+)

diff --git a/src/server/game/Spells/SpellMgr.cpp b/src/server/game/Spells/SpellMgr.cpp
index ff8fc45..61da3f0 100644
--- a/src/server/game/Spells/SpellMgr.cpp
+++ b/src/server/game/Spells/SpellMgr.cpp
@@ -3227,6 +3227,10 @@ void SpellMgr::LoadSpellInfoCorrections()
                 spellInfo->Effects[EFFECT_0].TargetB = SpellImplicitTargetInfo(TARGET_UNIT_SRC_AREA_ALLY);
                 spellInfo->Effects[EFFECT_1].TargetB = SpellImplicitTargetInfo(TARGET_UNIT_SRC_AREA_ALLY);
                 break;
+            case 49065: // Explosive Trap
+                spellInfo->Effects[EFFECT_0].TargetA = TARGET_UNIT_TARGET_ENEMY;
+                spellInfo->Effects[EFFECT_0].TargetB = TARGET_UNIT_DEST_AREA_ENTRY;
+                break;
 ```

**Comment by Keader** [comment]
is a hack i think
trap still is active but dont take damage

**Comment by noryad** [comment]
@ariel- Explosive Trap not work, only disappears, maybe a mask problem.
Confirmed in f5d3343
