### ISSUE TITLE
[Skill/Enchanting] Abyssal Shatter

### ISSUE THREAD

**Issue by Zaranthos** [TrinityCore/TrinityCore#6469]
This doesn't seem to give skill points. Used it 11 times and got no skill points at 445 enchanting.
http://www.wowhead.com/spell=69412

2012-04-28 15:10:52 +0200 (b53485e05326+) (Win64, Release) AHbot
b53485e05326f9ed6562aa78fee282f255eac339
TDB_full_335.11.46_2012_02_13 (+updates)

**Comment by Rushor** [comment]
so this bug is offically confimred from everyone?

**Comment by Aokromes** [comment]
0d91ccf
