### ISSUE TITLE
[Spell] Spellsteal

### ISSUE THREAD

**Issue by Loginisalreadytaken** [TrinityCore/TrinityCore#6496]
*[Blind Faith](http://old.wowhead.com/spell=56410)* - mistook this one for all crit, not just melee & ranged
[Storm Cloud](http://old.wowhead.com/spell=57408)

The above spells can be acquired from NPCs but they have no effect on the player character - no increased crit chance or damage to attackers.

[Revitalizing Rune](http://www.wowhead.com/spell=52714), however, works properly.

Core revision: Trinity Core b72617a77be6+
Database revision: TDB 335.11.46

**Comment by Killyana** [comment]
Fixed
rev. 5b5c0938da0f
