### ISSUE TITLE
[Food Buff] Slippery Eel

### ISSUE THREAD

**Issue by cover25** [TrinityCore/TrinityCore#6504]
When you attempt to eat Slippery Eel, it gives the error "you're too full to eat that right now". It should give you the buff that increases your dodge by 40 rating. instead, the item is consumed and you get no hp/buff.

http://www.wowhead.com/item=43652/slippery-eel
http://www.wowhead.com/spell=59230/well-fed

Trinity Core b72617a+
TDB 335.11.46
3.3.5a
##

**Comment by Rushor** [comment]
.list aura shows also, that you get the buff:

[21:04:36]id: 59227 [Erfrischung] effmask: 4 charges: 0 stack: 1 slot 0 duration: 26400 maxduration: 30000   caster: player guid: 5

but it is not displayed in the aurabar.

**Comment by Killyana** [comment]
Actually the buff is applied and visible on the buff bar, the problem is the effect1 trigger 2 spells in the same time, the second one (the buff) is already triggered on effect2 http://wotlk.openwow.com/spell=59227 (for this reason the effect1 fails and you get the error)

**Comment by Killyana** [comment]
Cannot reproduce on rev. 24cf532557b0
