### ISSUE TITLE
Spell (mainly channeled) errors trigger global cooldown

### ISSUE THREAD

**Issue by Loginisalreadytaken** [TrinityCore/TrinityCore#6512]
https://github.com/TrinityCore/TrinityCore/issues/4074

Also goes for [Arcane Missiles](http://old.wowhead.com/spell=5143) and [Conjure Mana Gem](http://old.wowhead.com/spell=759) (error: Item already has the maximum number of charges).

Core revision: Trinity Core b72617a77be6+
Database revision: TDB 335.11.46

**Comment by Killyana** [comment]
Conjure Mana Gem is unique you can only get one in your inventory for  Arcane Missiles it's fixed.

rev. 5b5c0938da0f
