### ISSUE TITLE
NEUTRAL FACTION NPC ATTACKED IN VEHICLE

### ISSUE THREAD

**Issue by Expecto** [TrinityCore/TrinityCore#6519]
Enter Ulduar
Seat in vehicle
Use Spells for neutral npcs

TDB 11.46 and YTDB 620

Rev Hash 06c4917568a43cd85a40b07eb82f273af2053050

Screen  http://www.imageup.ru/img203/945767/wowscrnshot_051412_231339.jpg

**Comment by Killyana** [comment]
Cannot reproduce on rev. 5b5c0938da0f
