### ISSUE TITLE
[3.3.5][Priest] - Shadowform

### ISSUE THREAD

**Issue by click** [TrinityCore/TrinityCore#657]
Spell: [http://old.wowhead.com/spell=15473]

Error: Cast any spell, and put shadowform before end global CD, not apply shadowform, and no longer lets you get Shadowform.

Core: https://github.com/TrinityCore/TrinityCore/commit/790086ea2f06a659d3995811bb42212771b5b3ce

**Comment by Raydor** [comment]
Still bugged https://github.com/TrinityCore/TrinityCore/commit/48fa7fa992c02d7c17c39c08cb78c6457d034f49

**Comment by cguliver** [comment]
when was  posted first time was  on [ May 17, 2011 ] so i think is required 10 more  years to fix this LOL :"

**Comment by sirikfoll** [comment]
Reopen?
Still bugged  0148832

**Comment by Aokromes** [comment]
I am using https://github.com/TrinityCore/TrinityCore/issues/657#issuecomment-8433390 for years.

**Comment by mik1893** [comment]
note also that the same should be applied to tricks of the trade and misdirection
```
    if (strict && !(_triggeredCastFlags & TRIGGERED_IGNORE_GCD) && HasGlobalCooldown()) 
    {
        switch (m_spellInfo->Id)
        {
            case 15473: // Shadowform
            case 34477: // Misdirection
            case 57934: // Tricks of the Trade
                return SPELL_FAILED_FIZZLE; // !Hack - Returning "Not ready" bugs Shadowform client side
            default:
                return SPELL_FAILED_NOT_READY;
        }
    }

**Comment by Keader** [comment]
Dont work for MD and Tricks of the Trade (https://github.com/TrinityCore/TrinityCore/issues/657#issuecomment-226107058)
Already using this fix, and still bug sometimes.
Shadowform works well :)

**Comment by mik1893** [comment]
mmmh to me MD and tricks of the trade work...
not entirely sure I did anything different from this to make it work
