### ISSUE TITLE
The Blood Princes 2 Buggs

### ISSUE THREAD

**Issue by SkyAngel** [TrinityCore/TrinityCore#6578]
Hello,

in the Phase change from 2 to 3 Phase, can not sruvive

In the Phase Change should be of Dark Nucleus (http://www.wowhead.com/npc=38369) the Spell Shadow Resonance (http://www.wowhead.com/spell=71822) get, this is Buggy

The Kinetic Bomb (http://www.wowhead.com/npc=38454) fly too fast down about 10 times faster than normal

**Comment by Killyana** [comment]
First issue fixed second one here https://github.com/TrinityCore/TrinityCore/issues/7150
rev. 5b5c0938da0f
