### ISSUE TITLE
Harvest soul

### ISSUE THREAD

**Issue by telsamat** [TrinityCore/TrinityCore#6601]
tc 39a609ce5c
tdb 47

There is a bug with HS debuff on heroic mode of ICC, which deals 2000 shadow damage per second. It must to be active only when the players are inside the frostmourne room, not after they leave this room - now BUG.

Another bug is with wicked spirits inside the room, they appear later than they should and the spirit bombs are dropped from them, now if the players enter the room, they explode even there are no wicked spirits - bug.

reference: http://www.youtube.com/watch?v=W5Tloy9Xroo&feature=fvst
another:http://www.youtube.com/watch?v=qog5PgpBUQY

**Comment by Keader** [comment]
Still bugged on TrinityCore rev. 694398d6621b+ 2015-07-07 09:30:40 -0300 (3.3.5 branch) (Win64, Release)

**Comment by wowcamper** [comment]
Confirm.
Correct damage is 2000, the applied damage is approximately 30% higher 2589.

**Comment by Killyana** [comment]
Duplicate: https://github.com/TrinityCore/TrinityCore/issues/13287
