### ISSUE TITLE
{NPC/General} Blood Queen Lana'thel / General Threat / Biting

### ISSUE THREAD

**Issue by durrrr** [TrinityCore/TrinityCore#6616]
Hello,
I have encountered a problem while playing in "Icecrown Citadle" zone.

How to reproduce the bug:
1. Start "Blood Queen Lana'thel" encounter

What should happen, what happens instead:
You should start the boss, and the biting by "Blood Queen Lana'thel" should be given to the highes threat producer [Other than the tanks] (Notice the zone data), what happens instead is it does not always work like that. Sometimes healers with no threat visible get bit, sometimes people who dont even have 0.1% threat on the NPC, sometimes tank and so on.

In another issue, the NPC has threat issues all over the place.
Sometimes the NPC decides he just turns arround with no regards to the threat and give somebody 8k+8k+3k+3k+5k in a matter of 0.5% seconds (>_<?).

Some links:
http://www.wowwiki.com/Blood-Queen_Lana%27thel --> The NPC (Wowwiki)
http://old.wowhead.com/zone=4812 --> The Zone (Old Wowhead)
http://www.wowwiki.com/Icecrown_Citadel --> The Zone (Wowwiki)

I'm running Unix on hash: 7e62c34 , TDB 335.11.46+
Addons: AH bot and WG.

Regards,
durrrr

**Comment by Killyana** [comment]
Cannot reproduce on rev. 5b5c0938da0f
