### ISSUE TITLE
[Caverns Of Time] [Battle For Mount Hyjal] [Errors]

### ISSUE THREAD

**Issue by Expecto** [TrinityCore/TrinityCore#6659]
After Starting event in Instance Hyjal (Thrall Event) in Console Spam Errors

ERROR: TSCR ERROR: EscortAI reached waypoint out of order 0, expected 2, creature entry 17906
ERROR: TSCR ERROR: EscortAI reached waypoint out of order 0, expected 2, creature entry 17907
ERROR: TSCR ERROR: EscortAI (script: mob_giant_infernal, creature entry: 17908) attempts to Start while in combat
ERROR: CastSpell: unknown spell id 0 by caster: creature (Entry: 18036)

TDB 11.48

Hash 7d4d296e2f60b2d42fe51b92b666238d4513bbd1
##

**Comment by Rushor** [comment]
is this still valid? i could not see the spam for a long time now
