### ISSUE TITLE
[Bug/Spell]Uncontrollable Frenzy

### ISSUE THREAD

**Issue by Crysicle** [TrinityCore/TrinityCore#6663]
Bug:
If you gain Uncontrollable Frenzy while fighting Blood-Queen Lana'thel, you will lose control of your character and start attacking your raid members as well gain some really high stats. If you relog while under this debuff, you will regain full control of your character though the debuff will remain intact. This leaves you to rampage the boss with 100%+dmg, 5000%+health and 1000%+healing.

Uncontrollable Frenzy - http://old.wowhead.com/spell=70923
Blood-Queen Lana'thel - http://old.wowhead.com/npc=37955

Core revision: Trinity Core d98f36194bc2+
Database revision: TDB 335.11.47
Addons: Anticheat1

**Comment by Aokromes** [comment]
near 2 years without answer, if this bug is still valid open a new ticket.
