### ISSUE TITLE
Ghoul ap coefficient

### ISSUE THREAD

**Issue by Kengur** [TrinityCore/TrinityCore#6693]
Ghouls should only get attack power from their own strenght and buffs. But instead they get bonus attack power from Owners attack power too.

http://www.wowwiki.com/Risen_Ghoul

TDB 335.11.47
TrinityCore rev. 2012-06-01 20:29:23 +0100 (6bffb472523b) (Unix, Release)

**Comment by Aokromes** [comment]
f82f06e29e6bb0d1747541c9831875782bbe4270
