### ISSUE TITLE
[Core/Pooling System] ICC weekly quests

### ISSUE THREAD

**Issue by PKX** [TrinityCore/TrinityCore#6701]
**Revision** b72617a77be6966bbd347e85939f28f411c2ab42

**What should happen:**
The server should pick a random quest from the pool, save it in char db and keep spawning the same quest every time the server is restarted for a week, then start all over again by picking another quest.

**What happens instead:**
The server picks a random quest every time it's restarted, ignoring what is saved in char db.

**Why this happens:**
We have this in db:

```
pool_quest
entry	pool_entry	description
24871	5685	Securing the Ramparts ALLY (10)
24870	5685	Securing the Ramparts HORDE (10)
24872	5684	Respite for a Tormented Soul (10)
24873	5683	Residue Rendezvous (10)
24869	5682	Deprogramming (10)
24874	5681	Blood Quickening (10)

pool_pool
pool_id	mother_pool	chance	description
5683	5679	0	Residue Rendezvous (10)
5682	5679	0	Deprogramming (10)
5681	5679	0	Blood Quickening (10)
5684	5679	0	Respite for a Tormented Soul (10)
5685	5679	0	Securing the Ramparts (10)

pool_template
entry	max_limit	description
5679	1	General ICC 10man pool
5680	1	General ICC 25man pool
5681	1	Blood Quickening (10)
5682	1	Deprogramming (10)
5683	1	Residue Rendezvous (10)
5684	1	Respite for a Tormented Soul (10)
5685	2	Securing the Ramparts (10)
```
At server start, the pool 5679 is spawned: since is a pool of pools, `SpawnPool<Pool>` is called, which calls `PoolGroup<T>::SpawnObject`; this funcion immediately spawns an object from the pool without checking table pool_quest_save: here is the bug

**How to fix this**
We should add some check in `SpawnPool<Pool>` to call `PoolGroup<Quest>::SpawnObject` instead, when the pool has a pool of quest as a child. Probably also the function that saves the quests in db will have to be modified.

**Comment by Aokromes** [comment]
No answer after a lot of months, if this bug is still valid open a new ticket.

**Comment by Runico** [comment]
this issue still happens

**Comment by tkrokli** [comment]
"No answer after a lot of months, if this bug is still valid open a new ticket." - Aokromes
