### ISSUE TITLE
[Creature] Pit Commander SAI (Dark Portal Misc)

### ISSUE THREAD

**Issue by warriorpoetex** [TrinityCore/TrinityCore#6710]
The event between the Horde/Alliance NPCs and the Burning Legion NPCs doesn't work right ... 

The Fel Soldiers, Wrath Masters and Siegebreakers spawns and their attack waves appear incomplete. Lack of SAI?

Pit Commander is also not scripted, needs SAI ... I may try and toss up a SAI for him to help.
##

**Comment by Kittnz** [comment]
Anyone interested in scripting this "event"?

**Comment by Kittnz** [comment]
Apparently the 'sunwell core' has this scripted in SAI, just an FYI.

**Comment by Aokromes** [comment]
If it's needed i can sniff this.

**Comment by Killyana** [comment]
Closed by https://github.com/TrinityCore/TrinityCore/commit/bf5799fce5da19a78af6805e29ee75da4d147f12
