### ISSUE TITLE
[NPC] Sister Svalna

### ISSUE THREAD

**Issue by Exodius** [TrinityCore/TrinityCore#6722]
ID: http://www.wowhead.com/npc=37126
HC Diff entry: 38258

Problem: Not scripted. Does not drop anything.

How should it work: [Source](http://www.wowhead.com/npc=37126#comments:id=963735)
Sister Svalna is a Val'kyr mini-boss in the room before the first boss of the Frostwing Halls, Valithria Dreamwalker.
Kill the trash up to her, which is essentially a gauntlet that you fight with other crusaders. As you are doing this, she will kill your crusader helpers.

The fight with her is simple, and much akin to the [High Warlord Naj'entus](http://www.wowhead.com/?npc=22887) encounter in Black Temple, where she will throw her spear at a player in the raid, immobilizing the player. Another player must them loot the spear and throw the spear back at her when she tosses up her immunity bubble. A few times throughout the fight she will resurrect the crusaders she killed. They do not have much health and are easily tanked and spanked.
Rinse and repeat using the spear to break the bubble and you have yourself a mini boss downed!
In ten man she dropped approx. ~75g and one [Emblem of Frost](http://www.wowhead.com/?item=49426).

For all this time, I've never seen her using any ability except the part where she resurrects the dead Crusaders.
Some entries from WoWhead suggest that she has same loot as Trash mobs in ICC.

Revision: faaf22d628b538511478a579ef1d95eb61251176
TDB 335.11.47 + Repo updates
##

**Comment by tkrokli** [comment]
@Expecto : the ICC thrash mobs were moved to SQL SAI in commit 0cba1013150888cf690c5fab1b08ef2a30879192 on January 3, 2013.

**Comment by Aokromes** [comment]
If the fix here is valid, plz open a PR.

**Comment by tkrokli** [comment]
1. This page does not show when labels got added. Don't know what [Feedback-PatchFix] refers to.
2. Expecto's linked pastebin script is not a solution, only an example (nothing about Svalna in it).
3. Nothing is suggested for Sister Svalna's missing abilities (I don't know the status of this issue).
4. Only the SQL mingold/maxgold update is a suggested solution here, nothing else.

**Comment by Aokromes** [comment]
If it's needed i can sniff this.

**Comment by Killyana** [comment]
The ncp is scripted, the script issue has is own ticket here  https://github.com/TrinityCore/TrinityCore/issues/19985
