### ISSUE TITLE
Pet abilities have all less damage

### ISSUE THREAD

**Issue by Vasago** [TrinityCore/TrinityCore#6727]
Hello,
There is problem after some "damage fixes revision" in past which cause all pet abilities to degrease like -50% than they should deal

Server info : WG patch
https://github.com/TrinityCore/TrinityCore/commit/8c841d12b3e00c6f4e50a72113dbaac03a6158f4
Tdb: 335.11.47+

Possible revisions which could have cause it (not have computer strong enough to test them all hope devs will see the mistake without doing revision by revision.

https://github.com/TrinityCore/TrinityCore/commit/1037f96e4f9a788cc450fd429ce5f2b0fcc29790
https://github.com/TrinityCore/TrinityCore/commit/63010fe77b4eea4461c01ffd8a3f2a0841bdd220
https://github.com/TrinityCore/TrinityCore/commit/c6aa41cc1050bf637669c633024cd82270bd64a7
https://github.com/TrinityCore/TrinityCore/commit/619fdd185b2b59d886697d1cdbf71ac843982f66
https://github.com/TrinityCore/TrinityCore/commit/ea4815b52806aa41ad015b314c8caff9ff2e2a6f
https://github.com/TrinityCore/TrinityCore/commit/b90cb5878de2afc621c0b9ebc86066c2b827f428

And all revision around this date concerning changes in damage.
##

**Comment by Killyana** [comment]
This issue cannot be tested, a lot of changes were made on pets since 2012 and a lot of issues about pets are already opened.

**Comment by tje3d** [comment]
ROFL, Now Pets doing +50% than they should deal
