### ISSUE TITLE
[Quest]The Emissary

### ISSUE THREAD

**Issue by Justiciar** [TrinityCore/TrinityCore#6734]
Greetings,
I have encountered a problem with this quest's item which made it impossible to complete this quest.
The quest's item "Trident of Naz'jan" which is supposed to impale the npc  "Leviroth", reducing it's HP to 6.5k and give a kill credit after the player has slain it is not working as it should be.
The quest's item is just killing the npc instantly without giving a kill credit to the player which is necessary in order to complete the quest's objective.
If this quest's item would have been working as it should be, it would also been giving the player the kill credit after reducing the HP of the npc to 6.5k(if the player kills the npc after it's been reduced) and not only killing the npc on the spot which is the status right now.
Thanks in Advance.
Hash: 1b77fd4
 Tdb: 335.11.47+
wowhead quest's link:http://old.wowhead.com/quest=11626
wowhead npc Leviroth link: http://old.wowhead.com/npc=26452
wowhead quest's item:http://old.wowhead.com/item=35850

**Comment by Killyana** [comment]
Fixed 
rev. 5b5c0938da0f
