### ISSUE TITLE
[Quest] An Ambitious Plan

### ISSUE THREAD

**Issue by lordofthedread** [TrinityCore/TrinityCore#6739]
The quest An Ambitious Plan (http://old.wowhead.com/quest=9383) in Hellfire Peninsula is bugged.

How it should work :

Fight a Ucontrolled Voidwalker and use the Sanctified Cristal when its life is low to get a Glowing Sanctified Cristal.

How it is working :

When you use the Sanctified Cristal on the wounded voidwalker the item disappear and you dont get the Glowing Sanctified Cristal.

On rev : 7b5bdc2+ and TDB 11.47+

**Comment by Killyana** [comment]
Fixed
rev. 5b5c0938da0f
