### ISSUE TITLE
[Quest] Recharging the batteries

### ISSUE THREAD

**Issue by lordofthedread** [TrinityCore/TrinityCore#6761]
The quest Recharging the Batteries in Netherstorm is bugged (http://old.wowhead.com/quest=10190).

How it should work :

Use the Battery Charger Blaster on 10 Phase Hunters.

How it is working :

Server hangs with the following message when you try to use the item on the creature :

CreatureEventAI : EventMap for creature 2293 is empty but creaure uses CreatureEventAI.
CreatureEventAI : EventMap for creature 2293 is empty but creaure uses CreatureEventAI.
CreatureEventAI : EventMap for creature 2293 is empty but creaure uses CreatureEventAI.
World Thread Hangs, kicking out server!

C\....\src\server\worldserver\Master.ccp:106 in FreezeDetectorRunnable::run ASSERTION FAILED :
false
[0x350bff]
?invoke@ACE_OS_Thread_Adapter@@UEAAKXZ90+0x55 [0x61ad5]
_endthreadex()+0x43 [0x1652d]
_endthreadex()+0xdf [0x21e3b]
BaseThreadInitThunk()+0xd [0x1562d]
RtUserThreadStart()0x21 [0x2c521]

On rev : 7b5bdc2+ and TDB 11.47+

**Comment by Killyana** [comment]
Fixed
rev. 5b5c0938da0f
