### ISSUE TITLE
[Quest] Finish Me!

### ISSUE THREAD

**Issue by Zaranthos** [TrinityCore/TrinityCore#6814]
http://old.wowhead.com/quest=13232

When trying to do this quest it's not possible to attack the dying soldiers. May be related to this quest not working. https://github.com/TrinityCore/TrinityCore/issues/3223 since I had both at the same time which seems impossible. How can you talk to them and attack them at the same time?

2012-06-14 20:41:28 -0230 (8962b8842584+) (Win64, Release) AHbot
8962b8842584610a3597e9e691267b5aaa1c436e
TDB_full_335.11.47_2012_05_19 (+updates)

**Comment by fvicaria** [comment]
Sorry I didn't see any other on this quest so just checking here..
I don't seem to get any credit when I speak to NPC and execute him.

I can speak to NPC and kill it but no credit.

Can anyone confirm...

I am using

TDB 335.58 + plus updates.

**Comment by Killyana** [comment]
The SAI is ugly, this will fix the credit, but still need to check some conditions:
``` sql
UPDATE `smart_scripts` SET `event_type`=8, `event_param1`=59226, `event_param2`=0, `Comment`="Dying Soldier - On Spellhit - Cast 'Alliance Quest Aura'" WHERE `entryorguid`=31304 AND `source_type`=0 AND `id`=0;
