### ISSUE TITLE
Daily quests missing XP rewards

### ISSUE THREAD

**Issue by Zaranthos** [TrinityCore/TrinityCore#6818]
http://old.wowhead.com/quest=14074/a-leg-up

Doesn't give XP reward upon completion. Should be a simple fix.

2012-06-14 20:41:28 -0230 (8962b8842584+) (Win64, Release) AHbot
8962b8842584610a3597e9e691267b5aaa1c436e
TDB_full_335.11.47_2012_05_19 (+updates)

**Comment by Killyana** [comment]
Daily quests  gives xp only the first time (tested many quests from this list and it works as intended as you get xp only once)
rev. 5b5c0938da0f

**Comment by Rushor** [comment]
we need new bugs :D http://pokit.org/get/?f207394db0d3c369c522b71b2313c113.jpg
