### ISSUE TITLE
[Quest] Two Wrongs

### ISSUE THREAD

**Issue by lordofthedread** [TrinityCore/TrinityCore#6849]
The quest Two Wrongs (http://old.wowhead.com/quest=11188) in howling fjord is bugged.

How it should work :

Use the provided item to pull a Proto Drake in ember clutch

How it does work :

The item is working but the creature dont turn agressive and / or does not get in combat, since there is no other way to pull the drakes you cant complete the quest.

Using GM command "die" on creature correctly gives credit for the quest.

On rev : 225d264 TDB 11.47+

**Comment by Killyana** [comment]
Fixed
rev. 5b5c0938da0f
