### ISSUE TITLE
Scripts/Spells: Burning Hot Pole Dance  achievement

### ISSUE THREAD

**Issue by asdyy** [TrinityCore/TrinityCore#6876]
http://http://old.wowhead.com/achievement=271

achievement don't work ..after i put the set on me i clicked on Ribbon Pole (http://old.wowhead.com/object=181605) and not working.
##

**Comment by danlapps** [comment]
Anything valid in here ? https://github.com/darkman1983/TrinityCore/commit/a897035d60f0390a839b38a638cbe607bf853003 a valid fix ?

**Comment by Aokromes** [comment]
If anything here is valid, plz create a PR for it.

**Comment by BahDumbBugs** [comment]
So.....this doesn't work? I click on the ribbon pole for 60 seconds, player spins seemingly the entire time and nothing happens. Am I doing it wrong?

**Comment by Keader** [comment]
Last time i checked looks like :

```cpp
if (!target->FindNearestGameObject(GO_RIBBON_POLE, 20.0f) || !target->HasUnitState(UNIT_STATE_CASTING))
```
This Unit State Casting is falling. (And i cant see the reason of this be there)
And looks like ```SPELL_BURNING_HOT_POLE_DANCE``` is not working (Achiev Spell)

**Comment by BahDumbBugs** [comment]
@Keader - Thanks. I'll be watching this and will help test if needed. Even if I have to adjust start / end dates of Midsummer.

**Comment by sirikfoll** [comment]
Delete this: ` || !target->HasUnitState(UNIT_STATE_CASTING)` from this line: https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Spells/spell_holiday.cpp#L1571
and run the code bellow, should fix the problem
```sql
UPDATE `spell_dbc` SET `Effect1`=3, `EffectImplicitTargetA1`=1 WHERE `Id`=58934;

**Comment by Aokromes** [comment]
@sirikfoll push it xd
