### ISSUE TITLE
Midsummer Celebrant

### ISSUE THREAD

**Issue by Shadowfang** [TrinityCore/TrinityCore#6881]
Greetings,
I have encountered a problem with the npcs called "Midsummer Celebrant" that are related to the event "Midsummer Festival".
For the alliance side, the npcs are friendly but for the horde side, the npcs are unfriendly and attack them when they get close.
If the npcs would have been working properly, they were friendly both for alliance and horde side.

Thanks in advance,
Shadowfang

Hash: c430b45
Tdb: 335.11.47+

http://old.wowhead.com/npc=16781

**Comment by sirikfoll** [comment]
Confirm on rev. 6e1113a81034
The Midsummer Celebrant (http://wotlk.openwow.com/npc=16781) still are hostile to horde's players.
They have faction 1733

**Comment by Aokromes** [comment]
What's missing here to push this?

**Comment by SnapperRy** [comment]
Solved with recent Midsummer changes.
