### ISSUE TITLE
Thaddius- naxx

### ISSUE THREAD

**Issue by milotic** [TrinityCore/TrinityCore#6888]
http://www.wowhead.com/npc=15928/thaddius

Wipe in this boss and no reset event :/

Core revision: All

**Comment by Killyana** [comment]
Need confirmation if the 2 boss http://www.wowwiki.com/Feugen and http://www.wowwiki.com/Stalagg  must respawn if there's a wipe on Thaddius, or just he must stay attackable

**Comment by Kittnz** [comment]
@Killyana Yes, they must respawn.

**Comment by Exodius** [comment]
@Aokromes Close as per #15523?
