### ISSUE TITLE
[Talent] Hack and Slash

### ISSUE THREAD

**Issue by Shadowfang** [TrinityCore/TrinityCore#6892]
Greetings,
I have encountered a problem with the rogue talent "Hack and Slash".
This talent says "You have a chance of 5% to get an extra attack while hitting a target with an axe or sword.
The problem is that the chances are way lower.
If the talent would have working properly, you could get a 5% chance to get an extra attack while hitting a target with an axe or sword.

Thanks in advance,
Shadowfang

Hash: a057525
Tdb: 335.11.47+

http://old.wowhead.com/spell=66923

**Comment by Rushor** [comment]
like @LuqJensen said, the issue is still there in 3.3.5. it would be a shame to copy all dates from this issue in a new one :)

**Comment by ariel-** [comment]
Is this still valid?

https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Entities/Unit/Unit.cpp#L2024-L2031
Extra attacks are mainhand only.
