### ISSUE TITLE
[Chain Quest] King of the Fire Festival

### ISSUE THREAD

**Issue by Shadowfang** [TrinityCore/TrinityCore#6904]
Greetings,
I have encountered a problem while doing the achievement "King of the Fire Festival".
In this achievement you are supposed to steal the flames from each of the opposing faction's main cities, when you take each of the fires you get a quest "Flames of...(the name of the city)", you can complete all the quests but you can't get the next quest which awards you with the achievement- "A Thief's Reward".
If this chain quest would have working properly, you could get the last quest which awards you with the achievement after you finish stealing the flames from the opposing side's main cities.

Thanks in advance,
Shadowfang

Hash: a057525
Tdb: 335.11.47+

Last quest of chain: http://www.wowhead.com/quest=9365
http://www.wowhead.com/quest=9339

**Comment by Aokromes** [comment]
This can be pushed?

**Comment by Killyana** [comment]
Fixed on https://github.com/TrinityCore/TrinityCore/commit/81bb03b00de4126a0bab93e4e7ee99d8725a0fe3
