### ISSUE TITLE
Gushing Wound

### ISSUE THREAD

**Issue by Yoni140** [TrinityCore/TrinityCore#6913]
Hello, While fighting the blood queen and using Shadow's Edge you gain the debuff Gushing Wound which is a part of the quest Blood Infusion, but you gain this debuff even if you dont have the quest which shouldnt happen

Blood Infusion - http://www.wowhead.com/quest=24756

Gushing Wound -http://www.wowhead.com/spell=72132 

Hash : a057525

**Comment by Killyana** [comment]
Cannot reproduce on rev. 5b5c0938da0f
