### ISSUE TITLE
[Quest] The Heart of the Mountain

### ISSUE THREAD

**Issue by Zaranthos** [TrinityCore/TrinityCore#6914]
http://old.wowhead.com/quest=4123

Opening all the coffers should spawn 5 elites, 4 golems and Watchman Doomgrip. Nothing happens when you open all the coffers.
http://old.wowhead.com/npc=9476
http://old.wowhead.com/item=11309
http://old.wowhead.com/item=11078 - opens the coffers which contain chests that you should be able to loot but those also don't work.
http://old.wowhead.com/object=160845

Quest is currently not working.

2012-06-14 20:41:28 -0230 (8962b8842584+) (Win64, Release) AHbot
8962b8842584610a3597e9e691267b5aaa1c436e
TDB_full_335.11.47_2012_05_19 (+updates)

**Comment by RedSonja** [comment]
any news on this one?

**Comment by Rushor** [comment]
some detailed infos which show what should happen step by step would be nice.

the info in the first post does not seem to be enough.

**Comment by danlapps** [comment]
If I remember right, you loot relic keys here and there in the dungeon.  You then use those keys to open the relic chests.  Once the last chest is open, the named will appear.  Not sure if he drops the heart or another key for final chest tho, been quite a while since I did that quest.

**Comment by Killyana** [comment]
WIP
``` sql
SET @cover  := 164819;
SET @Portrait :=164825;
UPDATE `gameobject_template` SET `AIName`='SmartGameObjectAI' WHERE `entry` IN (@cover, @Portrait);
DELETE FROM `smart_scripts` WHERE `entryorguid` IN (@Portrait, @cover);
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES 
(@cover, 1, 0, 0, 64, 0, 100, 0, 0, 0, 0, 0, 106, 16, 0, 0, 0, 0, 0, 20, @Portrait, 5, 0, 0, 0, 0, 0, 'Cover - On gossip hello - Remove flags');

**Comment by tkrokli** [comment]
:+1: Cool. Perhaps it will make sense to visit BRD again after this is pushed. :smiling_imp:
