### ISSUE TITLE
Spell SPELL_CHARGE_DEFEND not working properly

### ISSUE THREAD

**Issue by Vasago** [TrinityCore/TrinityCore#6944]
SPELL_CHARGE_DEFEND       = 64100,
http://www.wowhead.com/spell=64100
Related to quests:
http://www.wowhead.com/quest=13625
http://www.wowhead.com/quest=13677

Spell is casted by NPC_CHARGE_TARGET = 33272, but when it is casted there is no effect of shields and quest is not working on this npc. Other NPC and effect shield are ok

Core: https://github.com/TrinityCore/TrinityCore/commit/d014f7fcedce79165d63f2796c6ea64285d74ac6
TDB_full_335.11.47

**Comment by Aokromes** [comment]
This bug is still valid?

**Comment by tkrokli** [comment]
No, at least not on 3.3.5 / TDB 335.61 - the quests can be completed normally (I did it 2-3 days ago).
Have not tested the 6.x versions yet.
