### ISSUE TITLE
[Quest] The Struggle Persists

### ISSUE THREAD

**Issue by Zaranthos** [TrinityCore/TrinityCore#6948]
http://old.wowhead.com/quest=13124
NPC Drako - http://old.wowhead.com/npc=27654
Quest completion NPC - Belgaristrasz - http://old.wowhead.com/npc=27658

You're supposed to be able to sneak around the edge and talk to the quest completion guy in the cage to complete this without a fight. The problem is Drako aggo's before you can get dialog with the guy in the cage or there is a problem not being able to talk to the guy while Drako is alive. Can't complete this with level 80 characters.

2012-06-14 20:41:28 -0230 (8962b8842584+) (Win64, Release) AHbot
8962b8842584610a3597e9e691267b5aaa1c436e
TDB_full_335.11.47_2012_05_19 (+updates)

**Comment by Killyana** [comment]
Fixed
rev. 5b5c0938da0f
