### ISSUE TITLE
[Quest Bug] Battling the Elements

### ISSUE THREAD

**Issue by BladeFight** [TrinityCore/TrinityCore#6969]
http://www.wowhead.com/quest=12967

You can access snoorir up and kill the elements but the elements do not count the one who killed her.

**Comment by w5860363** [comment]
The 30125 is the goal but it is visible GM flip flop

**Comment by Killyana** [comment]
You must use Snorri to kill Seething Revenants, tested twice and it works correctly.

**Comment by w5860363** [comment]
@Killyana Confirmation of the work

**Comment by Killyana** [comment]
http://i.imgur.com/hm81zl9.jpg
