### ISSUE TITLE
[bug/ICC] - Lich King

### ISSUE THREAD

**Issue by kakakon** [TrinityCore/TrinityCore#6987]
Hello

In phase 2 Lich king summon mobs name Val'kyr Shadowguard, the NPC pick up one party member, stun him and start push him to the end of the stage, when it get to the end of the stage, both of them falling down. the whole party melle + caster need to attack the valkyr it in order to kill it before both of the targets falling down.

The problem is the Val'kyr fly to high and to fast what prevents from the melle dps to attack the Valkyr.

Valkyr - http://old.wowhead.com/npc=36609

Hash: a057525 , Tdb: 335.11.47+

**Comment by Killyana** [comment]
As there's already an issue for this npc I will close this one https://github.com/TrinityCore/TrinityCore/issues/7266
