### ISSUE TITLE
[Evade Bug] HP Regen is Too slow

### ISSUE THREAD

**Issue by Butterfly69** [TrinityCore/TrinityCore#6991]
Seems something wrong with Evade Mode.
The problem is when we put somthing like basic Campfire or Hunter Traps on the Default Position of Boss,like Lord Marrowgar or Rotface and then someone else taunt Lord marrowgar out of the room,boss Enter to Evade mode and Return to Default position,But befor he get to Full HP,he enter to combat with same HP and again ...
or on Sindragosa,If Everyone get in Ice Tomb in Air phase Exactly Where Sindragosa landing and when she come down everyone taunt her immediately,she will not gain any HP and Return to combat...
Easy way for icc bosses :D
Any confirm?

**Comment by Aokromes** [comment]
fdd78d20772701b3e0fd7caf0da2cd5a2e6b6354
