### ISSUE TITLE
[Warlock] Felguard Demon

### ISSUE THREAD

**Issue by Divisioner** [TrinityCore/TrinityCore#7005]
Greetings,
I know that this issue allready has been reported long time ago, But i would like to try again and get appropriate answer to this bug.
The warlock Demon "Felguard" Has much lower stats then he should have, the reason is that his stasts are not affected by his warlock stats, whats make his damage much lower then it should be. 
That makes him be totally useless for the Demon spec warlocks, and force them to use Imp as main Demon.

Many people will be really happy if the issue will get fixed.

Hash : 5b24fb
Tdb: 335.11.47+

Thanks in advance,
Division

**Comment by Aokromes** [comment]
#5136
