### ISSUE TITLE
Playercreateinfo table initial spawn-in

### ISSUE THREAD

**Issue by henhouse** [TrinityCore/TrinityCore#7009]
If you have a custom playercreateinfo location to spawn in when you first create your character you login to a massive empty space that is just blue. It will take several seconds depending on the speed of your computer to finally load the area. It is literally as if the game loads a different zone (original starting zones?) then quickly realizes, you're not there at all and struggles to load that area, except... without a loading screen. So you're stuck in limbo for like 10-15 seconds while it finally loads the area.

During this time you can run around aimlessly, miss a lot of things, etc.
##

**Comment by Killyana** [comment]
TC don't support custom changes.

**Comment by Killyana** [comment]
Cannot reproduce on rev. 42c9289be36
