### ISSUE TITLE
[Quest] What Do You Feed a Yeti, Anyway?

### ISSUE THREAD

**Issue by Zaranthos** [TrinityCore/TrinityCore#7019]
http://old.wowhead.com/quest=14112

Creatures affected:
http://old.wowhead.com/npc=35061
http://old.wowhead.com/npc=35060
http://old.wowhead.com/npc=35071

This quest worked in my previous version but now seems to suffer from some evade bug. You attack the sharks and they aggro for a second and then exit combat and return to position. I'm unable to kill them before they exit combat, heal, and eventually despawn.

Worked in version: 2012-06-14 20:41:28 -0230 (8962b8842584+) (Win64, Release) AHbot

Not working:
2012-07-03 16:51:25 -0700 (c3cb82b92633+) (Win64, Release) AHbot VASAutoBalance
c3cb82b9263331ceaf68ebf69638ce3162b4a934
TDB_full_335.11.47_2012_05_19 (+updates)

Edit: Hmm, you used to be able to kill the sharks where they spawned which was usually on the ship. If you jump in the water and aggro them with a ranged attack they will enter combat and not evade. Quest behavior changed but it still works.

**Comment by Killyana** [comment]
The only remained issue is that the item can be used outside water, as we don't have a condition for that this cannot be fixed, also summoned npcs  must attack the player "on_just_summoned" but as there's a general issue they will aggro only if the player moves

**Comment by Kittnz** [comment]
Or you can make them move 1 step and the update will work too. Ill check tonight if i can add another condition for is in water

**Comment by dr-j** [comment]
the only issue I know of with this quest is when you use the chum in water the sharks or angry vrykul will always spawn at the bottom and never attack, regardless of how deep in the water player is the mobs always spawn at the bottom.

**Comment by Kittnz** [comment]
@Killyana So you need a condition if the unit is in water?

**Comment by Killyana** [comment]
(Yes as actually the item can be used in icecrown even at earth.

**Comment by Kittnz** [comment]
I'll push a in water condition in a few hours.

**Comment by Killyana** [comment]
Thanks for the condition, the remained issue will be fixed with https://github.com/TrinityCore/TrinityCore/issues/1031
``` sql
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=17 AND `SourceEntry`=66741;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`,`SourceGroup`,`SourceEntry`,`SourceId`,`ElseGroup`,`ConditionTypeOrReference`,`ConditionTarget`,`ConditionValue1`,`ConditionValue2`,`ConditionValue3`,`NegativeCondition`,`ErrorType`,`ErrorTextId`,`ScriptName`,`Comment`) VALUES
(17,0,66741,0,0,40,0,0,0,0,0,0,0,'','Chum the Water can only be used in water');

**Comment by joschiwald** [comment]
there is already a `spell_q14112_14145_chum_the_water` spellscript, which is a better place to implement a is in water check
