### ISSUE TITLE
[QUEST] #6001 Body and Heart

### ISSUE THREAD

**Issue by phantomdl** [TrinityCore/TrinityCore#7049]
Rev 26c36ba
No addons
335a

http://old.wowhead.com/quest=6001

You do not receive http://old.wowhead.com/spell=5487  ID number 19179

There is other reports regarding this quest but are closed 

https://github.com/TrinityCore/TrinityCore/issues/2759
https://github.com/TrinityCore/TrinityCore/issues/6139

**Comment by Aokromes** [comment]
Fixed months ago.
