### ISSUE TITLE
Achievement distribution distance

### ISSUE THREAD

**Issue by BlackangelWow** [TrinityCore/TrinityCore#7075]
Hello,
There is bug with those achievements "The Frozen Throne (10 player)" "The Frozen Throne (25 player)"

What happen?
If there is some player that the lichking move him with "Harvest Soul" to the room of the frostmourne he won't get achievement + the title of killing the lich king

What should happen? 
He should get the achievement and the title even that he was in this room

Related IDs:
http://www.wowhead.com/achievement=4530
http://www.wowhead.com/achievement=4597
http://www.wowhead.com/title=175
http://www.wowhead.com/spell=68980
http://www.wowhead.com/spell=74325
http://www.wowhead.com/spell=74297
http://www.wowhead.com/spell=74296

Server info:
Hash : 6a83cd4
Tdb : Tdb: 335.11.47+

**Comment by Aokromes** [comment]
This is a generic bug of players being to far from boss.

**Comment by Aokromes** [comment]
cb4d157
