### ISSUE TITLE
[ICC] LICH KING Tiron jump and souls graphics

### ISSUE THREAD

**Issue by mackov** [TrinityCore/TrinityCore#7091]
Trinity Core revision. (799b2c146b)
Trinity Database revision. (335.11.47)

Problem:
When LK use Fury of Frostmourne and he is talking, tirion is releasing from his ice trap and run too LK destroy frostmourne he should jump but he goes through LK, and break frostmourne disappeared there is no souls visuals which release from frostmourne, Tirion should say''THE LICH KING MUST FALL'' when player is revive but he doesnt say this.pls fix this:)
##

**Comment by Keader** [comment]
Jump part and visual effects is working in current revs.
But text "The Lich King Must Fall" still appear.

**Comment by Shauren** [comment]
No such text is ever said during The Lich King fight on retail, if jump works then that is all for this issue.

**Comment by Keader** [comment]
Hmm.
Lich King in current revs Jump, but searching in youtube... he jumps wrong.
https://youtu.be/RSeVCw3hVgQ?t=18m41s
https://youtu.be/3agPbq8F0S8?t=16m28s

Current Rev: He jump in point A and Fall in Point C.
On Retail: He should jump in point A, fall in point B, and "take a knockback" for point C.

**Comment by Keader** [comment]
2792046dc7a229180d27dfdc4ce37ccfb84c8a27
