### ISSUE TITLE
[Spell]Spell with multiple auras vs hand of freedom and similiar effects

### ISSUE THREAD

**Issue by diton** [TrinityCore/TrinityCore#7146]
Most know spell of that type is Frostfirebolt (http://www.wowhead.com/spell=44614) some other is Infected Wounds (http://www.wowhead.com/spell=48483) - both spells affect target with debuff with 2 effects: DoT/AS debuff and snare (mod speed).

Spells trat removes/grant immunity on snares should only remove 1 component of aura - snare effect - dot should stay on target
spells that remove(at last should) snare: hand of freedom, vanish, shapeshift(druid), warlock's portal, masters call etc

Now some more usefull info: using any of spell removing snare effect - removes whole aura - doesnt grant immunity on snare componnent only - as it should - so for eg when u use vanish u still should have debuff aura on rogue w/o snare effect
When u use aura like hand of freedom/masters call and debuff is aplied during snare immune aura u're affected by debuff with 1 full effect(dot/attack speed debuff) - ure imune to snare component - works as intended!

Server info:
rev:https://github.com/TrinityCore/TrinityCore/commit/8ffafdc859a1d591bc5d29674b4576c2d32bf29c
db: 335.11.47
##

**Comment by Rushor** [comment]
vanish spellid: spell=26889

**Comment by P-Kito** [comment]
SPELL_EFFECT_SANCTUARY: Does this trigger the removal of slows?

**Comment by robinsch** [comment]
Are there more spells like this? Just my two cents, instead of call RemoveAura we can check each spellEffect for mechanics etc and call ChangeAmount(0);

**Comment by Aokromes** [comment]
Anything here is valid? if yes create a PR for it.

**Comment by Shauren** [comment]
Nothing is

**Comment by Keader** [comment]
93746e8c4a79c8256cd4896533315683f143508c
