### ISSUE TITLE
[ICC] Blood Prince Council - Kinetic Bomb

### ISSUE THREAD

**Issue by Butterfly69** [TrinityCore/TrinityCore#7150]
1. When Kinetic Bomb Take Damage From Any Spell ,it started Flying to Sky and dont fall again,it Should go a little Higher and again Start Falling to Ground !
2. The Kinetic Bomb Falling too FAST!
3. They shouldn't be Root\Stun ...

http://www.wowhead.com/npc=38454
Rev: 395994c707f2cb1cc5a6022d9f9fc729df64b1dc
##

**Comment by Aokromes** [comment]
Anything here is valid? if yes, create a PR for it.

**Comment by Aokromes** [comment]
@Shauren anything here is valid?
