### ISSUE TITLE
pvp racial won't shares CD with pvp cooldowns

### ISSUE THREAD

**Issue by Bloodx** [TrinityCore/TrinityCore#7151]
Will of the Forsaken             -            http://www.wowhead.com/spell=7744
Medallion of the Horde        -            http://www.wowhead.com/item=51378

After wotf the cd on an accessory isn't imposed

**Comment by selenir** [comment]
Any news guys? Diff not working now, after adding SpellHistory to TC.

**Comment by Laintime** [comment]
Confirm last reva bagged

**Comment by Laintime** [comment]
Fix on spell history
http://pastebin.com/8rzGS3pz

**Comment by Trisjdc** [comment]
@Laintime: BAD BAD BAD BAD BAD BAD. Very bad, should never need to manually send packets in a spellscript like that.

My suggestion:
```
enum PvPTrinketTriggeredSpells
{
    SPELL_WILL_OF_THE_FORSAKEN_COOLDOWN_TRIGGER         = 72752,
    SPELL_WILL_OF_THE_FORSAKEN_COOLDOWN_TRIGGER_WOTF    = 72757,
};

class spell_pvp_trinket_wotf : public SpellScriptLoader
{
    public:
        spell_pvp_trinket_wotf() : SpellScriptLoader("spell_pvp_trinket_wotf") {}

        class spell_pvp_trinket_wotf_shared_cd_SpellScript : public SpellScript
        {
            PrepareSpellScript(spell_pvp_trinket_wotf_shared_cd_SpellScript);

            void HandleCast()
            {
                // cooldown spells, they can't be triggered and thus we can't use linked spells
                GetCaster()->CastSpell(GetCaster(), SPELL_WILL_OF_THE_FORSAKEN_COOLDOWN_TRIGGER);
                GetCaster()->CastSpell(GetCaster(), SPELL_WILL_OF_THE_FORSAKEN_COOLDOWN_TRIGGER_WOTF);
            }

            void Register()
            {
                OnCast += SpellCastFn(spell_pvp_trinket_wotf_shared_cd_SpellScript::HandleCast);
            }
        };

        SpellScript* GetSpellScript() const
        {
            return new spell_pvp_trinket_wotf_shared_cd_SpellScript();
        }
};
```

**Comment by Laintime** [comment]
@Trisjdc I help to users,no't use.

**Comment by lineagedr** [comment]
@Trisjdc Don't work.

**Comment by Killyana** [comment]
Can you check after Core/Spells: Improved spell category cooldown handling ?

**Comment by tkrokli** [comment]
True, a confirmation of if it works better now after commit https://github.com/TrinityCore/TrinityCore/commit/7dcddd9 would be nice. Just notice that there are 2 semicolon error in the current file [/sql/base/characters_database.sql](https://github.com/TrinityCore/TrinityCore/blob/7dcddd9/sql/base/characters_database.sql), but it is safe to use the update on an existing `characters` DB: [/sql/updates/characters/2015_10_29_00_characters_335.sql](https://github.com/TrinityCore/TrinityCore/tree/7dcddd9/sql/updates/characters/2015_10_29_00_characters_335.sql)

**Comment by Aokromes** [comment]
Anything here is valid? if yes create a PR for it.
