### ISSUE TITLE
Starfall aoe hitting also the main target

### ISSUE THREAD

**Issue by robyfow85** [TrinityCore/TrinityCore#7203]
Hello
Rev: f7a085e2dc47758c80273a2c84d741a1c77c234f

Starfall's main target is hit by both the star effect and the aoe effect
As a reference https://github.com/TrinityCore/TrinityCore/issues/1186 but that fix is not working properly.

Any suggestions ?
##

**Comment by Killyana** [comment]
@ariel-  this issue is still valid?

**Comment by ariel-** [comment]
Cannot reproduce on 1acfefb973895b0e3df3c8d9b43b920d2a1b5392
