### ISSUE TITLE
Core/Spells: Hand of Freedom while in CC.

### ISSUE THREAD

**Issue by Demonid** [TrinityCore/TrinityCore#7206]
How it SHOULD work: Hand of Freedom should be usable  on a Friendly Target. while the Paladin is in Sap and some others CC's.

How it DOES work: When Paladin is in CC it cannot cast Hand of Freedom on a Friendly Target.

Spell: http://www.wowhead.com/spell=1044

Videos: http://www.youtube.com/watch?v=pS_1d7X2GHM&t=5m7s

Info Source:
http://www.wowhead.com/forums&topic=50290/blessing-of-freedom-help-pleezz
http://www.threadmeters.com/tU9jeC/Hand_of_Freedom_is_absolutely_useless_in_PvP/
http://www.skill-capped.com/content/3985/holy-paladin-spells-and-abilities
http://www.skill-capped.com/content/3790/retribution-paladin-pvp-abilities

**Comment by Raydor** [comment]
Any news about this?

**Comment by Keader** [comment]
Still valid in 3.3.5 branch

**Comment by ariel-** [comment]
So, is the issue valid?

**Comment by tkrokli** [comment]
The PR was closed because the suggested PR would allow an incapacitated paladin to release self from stun/sap etc. and that is not blizzlike. Paladins should still be able to use Hand of Freedom on other friendly targets while incapacitated, although it is unclear if this should be possible under all forms of physical CC.

**Comment by Keader** [comment]
Yeap, like tkrokli say, issue still valid.
My fix is not clean. Paladins only should use Hand of Freedom (in SAP) in friendly targets

**Comment by CraftedRO** [comment]
> (But i'm still confused about it, because a lot of people complain about can use Hand of Freedom in self now... and in current version has no talent to remove stun when use hand of freedom.)

Sigh: https://www.wowhead.com/wotlk/spell=31872/divine-purpose

**Comment by CraftedRO** [comment]
As of b6bb35bb9af9ae75463edd52bfbe5af0f46cd900 it looks like paladin can self-cast HoF while stunned and freed from stun effects (if spec in [divine-purpose](https://www.wowhead.com/wotlk/spell=31872/divine-purpose)) not sure if blizzlike, probably not.

**Comment by CraftedRO** [comment]
OK after watching [some videos](https://youtu.be/7oDf_rL4SzM?t=251) and read [some forums](https://www.mmo-champion.com/threads/1779192-Hand-of-Freedom-is-no-longer-usable-while-stunned-REALLY?p=33787980&viewfull=1#post33787980) looks like it works as intended and [warpten was wrong here](https://github.com/TrinityCore/TrinityCore/pull/19783#issuecomment-303139366) and this can be closed.
