### ISSUE TITLE
[Bug/ICC]Val'kyr Herald

### ISSUE THREAD

**Issue by Crysicle** [TrinityCore/TrinityCore#7209]
Bug:
The 2 Val'kyr Heralds that are circling around the round room, where the teleporter to the Litch King is, do not have any abilities. They should cast Severed Essence which would spawn raid member clones by the name of "Severed Essence" that would dps the raid down. If it was a healer on whom this spell was casted, the clone would not kill the raid members, but heal the Val'kyr Herald instead.

Links:
Val'kyr Herald - http://old.wowhead.com/npc=37098
Severed Essence(Npc) - http://old.wowhead.com/npc=38410
Severed Essence(10-man) - http://old.wowhead.com/spell=71906
Severed Essence(25-man) - http://old.wowhead.com/spell=71942
1st Video of the encounter - http://www.youtube.com/watch?v=5N-dT6BZbaY
2nd Video of the encounter - http://www.youtube.com/watch?v=QCYXNsHRTng

Core revision: Trinity Core 5b24fbf2f4b7+
Database revision: TDB 335.11.47
Addons: Anticheat1
##

**Comment by Keader** [comment]
More generic issue #7209

**Comment by Rushor** [comment]
you linked the same issue :)

**Comment by Keader** [comment]
updated xd
