### ISSUE TITLE
[3.3.5] Magtheridon's Lair: Magtheridon can be pulled out of his lair

### ISSUE THREAD

**Issue by Crysicle** [TrinityCore/TrinityCore#7230]
Bug:
You are able to pull Magtheridon outside of the big chamber. Hellfire Channeler and Burning Abyssal may need to have the same boundaries as the boss because they're part of the encounter.

Links:
Magtheridon - http://www.wowhead.com/npc=17257
Hellfire Channeler - http://old.wowhead.com/npc=17256
Burning Abyssal - http://old.wowhead.com/npc=17454
Screen - http://i.imgur.com/VLTzN.jpg

Core revision: Trinity Core 5b24fbf2f4b7+
Database revision: TDB 335.11.47
Addons: Anticheat1
##

**Comment by Aokromes** [comment]
This can be fixed after Treeston's boundaries implementation.

**Comment by Keader** [comment]
i have boundary ready for this creature... but he need a full rewrite.
If someone can provide me sniffs, i can rewrite him

**Comment by Keader** [comment]
@Crysicle idk if you still here, but test with #18330 💃

**Comment by Keader** [comment]
891551e845a6d7f023511abcc1795e77d2f5f1bd
