### ISSUE TITLE
[Bug]Vorsha the Lasher

### ISSUE THREAD

**Issue by Crysicle** [TrinityCore/TrinityCore#7240]
Bug:
1 - Add waves should spawn 5 seconds apart from each other after the previous was killed. Same goes when Vorsha spawns, she should spawn only 5 seconds after the 2nd wave is done. At the moment waves are set to a time limit and spawn after a certain amount of time, no matter if the previous wave is not yet killed. **_Note: the wave timer may not be exactly true, it's taken from wowhead comments._**
2 - If you wait long enough on the island, the quest completes on it's own and the adds despawn while it should complete only when Vorsha is killed.
3 - The adds and Vorsha don't move from their place when spawned. They should instantly go towards the middle of the island and start attacking the player and the quest giver.

Links:
Vorsha the Lasher(quest) - http://old.wowhead.com/quest=6641
Vorsha the Lasher(npc) - http://old.wowhead.com/npc=12940
Muglash - http://old.wowhead.com/npc=12717
Proof - http://www.youtube.com/watch?v=MEBjvnJT5sA

Similar bugs to Nr. 2 and 4:
https://github.com/TrinityCore/TrinityCore/issues/7213
https://github.com/TrinityCore/TrinityCore/issues/7300

Core revision: Trinity Core 5b24fbf2f4b7+
Database revision: TDB 335.11.47
Addons: Anticheat1

**Comment by Killyana** [comment]
Fixed.
rev. 5b5c0938da0f
