### ISSUE TITLE
[Bug]Freedom to Ruul

### ISSUE THREAD

**Issue by Crysicle** [TrinityCore/TrinityCore#7262]
Bug:
The escort ends mid way out of the camp, somewhat after exiting the cave from where you accept the quest, Ruul just disappears and you get "Quest Completed". This should not be so, Ruul should be still going down the cliff, then take a left turn and go out through the gate. When the escort is done, he should transform into a tauren, say "Thank you for freeing me. Speak with my sister in Splintertree. I... I must find a place to rest." and then disappear.

Links:
Freedom to Ruul - http://www.wowhead.com/quest=6482
Ruul Snowhoof - http://www.wowhead.com/npc=12818
Video(4:02) - http://www.youtube.com/watch?v=Ck8DPMExGE8

Unfortunately, after a few hours of searching, this is the only video i could find of the quest that shows at least some parts of the escort.

Core revision: Trinity Core 5b24fbf2f4b7+
Database revision: TDB 335.11.47
Addons: Anticheat1
##

**Comment by Aokromes** [comment]
If needed i can supply sniff for this.
