### ISSUE TITLE
[Bug]Sentinel Onaeya

### ISSUE THREAD

**Issue by Crysicle** [TrinityCore/TrinityCore#7304]
Bug:
She should be red for horde, not yellow.

Links:
Sentinel Onaeya - http://www.wowhead.com/npc=11806
Current - http://i.imgur.com/q3WaL.jpg

Core revision: Trinity Core 0b98656b2878+
Database revision: TDB 335.11.48
Addons: Anticheat1
##

**Comment by Killyana** [comment]
Seems like the faction was changed on 4.x as on 4.3.4 the faction is 1076

**Comment by Killyana** [comment]
On 3.3.5 she was neutral https://youtu.be/aPmuvh8daGk?t=43s
