### ISSUE TITLE
[Bug]Blight Falconer

### ISSUE THREAD

**Issue by Crysicle** [TrinityCore/TrinityCore#7320]
Bug:
1 - Blight Falconer doesn't run after you, she doesn't attack you or use her shoot ability and doesn't even notice you, only the bird on her shoulder does.
2 - The bird, Carrion Hunter, does all of the damage if you are close to Blight Falconer, however looking at the video below it seems that he should dismount from the Falconer and help her kill the enemy, but instead he stays on her.
3 - Blight Falconer doesn't say nor shout anything once engaged.

Links:
Carrion Hunter - http://old.wowhead.com/npc=31263
Blight Falconer - http://old.wowhead.com/npc=31262
Video(2:32+) - http://www.youtube.com/watch?v=n2qj11k5LoI
How it is now - http://www.youtube.com/watch?v=1hhXXYNHpOs

Core revision: Trinity Core 0b98656b2878+
Database revision: TDB 335.11.48
Addons: Anticheat1

**Comment by Killyana** [comment]
Fixed
rev. 5b5c0938da0f
