### ISSUE TITLE
[Bug]Shapeshifting Npcs

### ISSUE THREAD

**Issue by Crysicle** [TrinityCore/TrinityCore#7337]
Bug:
There are npcs which, after taking bear form, do not have a model to correspond their change(Could be all of them). They either stay in their previous form while the shapeshift buff is active or are already set to the form that they should take only when they have the buff.

Links:
Cenarion Caretaker - http://old.wowhead.com/npc=4050
http://i.imgur.com/Oggyt.jpg
http://i.imgur.com/KPxQM.jpg
http://i.imgur.com/LFuuE.jpg

Cenarion Protector - http://old.wowhead.com/npc=3797
http://i.imgur.com/mX5hH.jpg
http://i.imgur.com/LFdEe.jpg
http://i.imgur.com/XkTvW.jpg

Brother Ravenoak - http://old.wowhead.com/npc=5915
http://i.imgur.com/Fvdyd.jpg
http://i.imgur.com/iv52e.jpg

Core revision: Trinity Core 0b98656b2878+
Database revision: TDB 335.11.48
Addons: Anticheat1
##

**Comment by Killyana** [comment]
For some reason the effect Shapeshift is not applied when the server start, but on respawn or reset it works fine, also once the aura expired is not recasted as added with creature_addon. May be it's better to add the aura to the SAI.
