### ISSUE TITLE
[Bugged Quest] Words for Delivery.

### ISSUE THREAD

**Issue by SimulationWow** [TrinityCore/TrinityCore#7348]
Hello,
I have encountered a problem with the quest "Words for Delivery".

First there is prob with the npc "Toby Zeigear" he give the quest "Words for Delivery"(Id: 25500) instead of the quest "Words of Delivery" (Id: 25286).

The second prob is in the right quest (id: 25286), the prob is that when you go to give the speech to "Captain Tread Sparknozzle" there is no option to talk with him or complete the quest.

Links:
The wrong quest -->http://old.wowhead.com/quest=25500
The right quest --> http://old.wowhead.com/quest=25286
Npc: Toby Zeigear --> http://old.wowhead.com/npc=39678
Npc: Captain Tread Sparknozzle --> http://old.wowhead.com/npc=39675

Hash : f523192
Tdb: 335.11.47+
on Linux

**Comment by Killyana** [comment]
There's two version of "Words for Delivery" depending on the player level, also I tested the two version and you can complete both of them.
rev. 5b5c0938da0f
