### ISSUE TITLE
[3.3.5][Paladin] Core/Spell: Sacred Cleansing

### ISSUE THREAD

**Issue by Oriden** [TrinityCore/TrinityCore#7406]
Since the other bug reports got closed for some reason, i will open a new one.

http://wotlk.openwow.com/?spell=53551

Sacred Cleansing should only give 30% resistance to Disease, Magic and Potion.
Currently, i think it is giving resistance to everything. When SC is up, the attacker has a high chance to miss the target or to have his spells resisted which isvery annoying.

 Core: a306d39bb4
TDB: 335.11.48 + updates

**Comment by Runico** [comment]
this issue still exist, please reopen it

**Comment by P-Kito** [comment]
we check for .IsAura() - Why does it take out damage?

**Comment by L30m4nc3r** [comment]
Summon @greymane
http://dev.eternal-wow.com:3000/issues/5150

**Comment by Noryad** [comment]
@ariel- can you take a look at this?

**Comment by ariel-** [comment]
Indeed check is duplicated
