### ISSUE TITLE
loot bug shadow shard 

### ISSUE THREAD

**Issue by MMRm** [TrinityCore/TrinityCore#7412]
hi

all player in raid can loot shadow shard if add quest 24548 

1-  10 player add  quest=24548

2- boss kill 

3 - 10 player Simultaneous loot shadow shard :)

**Comment by Killyana** [comment]
The Shadowfrost Shard can be seen by all players but only ones having the quest can rand it or loot it, I will not add conditions as in the case if the raid lead distribute loots he will not see the shard and it will be a problem. Actually there's no error shown if someone want loot it and don't have the quest, He just can't.
rev. 5b5c0938da0f
