### ISSUE TITLE
[Quest] 9561 Nolkai's Words

### ISSUE THREAD

**Issue by Tolbin** [TrinityCore/TrinityCore#7442]
Upon finishing quest you don't get the expected quest reward Nolkai's Box. Clicking on the Mound of Dirt [181758] yields "Greetings name".

Not sure if you're supposed to get it from completing the quest or clicking on the Mound of Dirt after you've completed the quest.

http://old.wowhead.com/quest=9561
http://old.wowhead.com/object=181758
http://old.wowhead.com/item=23846

TrinityCore rev. 2012-07-12 00:16:13 +0100 (da9865b6833f) (Win32, Release)
TDB 335.11.47

**Comment by Killyana** [comment]
Fixed
rev. 5b5c0938da0f
