### ISSUE TITLE
Dual spec phasing

### ISSUE THREAD

**Issue by Nastrand** [TrinityCore/TrinityCore#7447]
How to reproduce this bugs

1 Complete any quest or chain of quests who changes your phase (Example: Son of hodir quest chain)

2 Then you can see the NPCs and gob in that phase

3 Change talent spect

When you change the spec, you cant see the NPCs and you must return to the spec where you complete the quest, because the change of phase only affect the talent spec you have active.

Sorry for my bad english

Core: 19cec23f396c0ab8cb6a574eea5665c73e5ce5a2
DB: TDB 335.11.48 hash da9865b (2012/07/12)

**Comment by Killyana** [comment]
Cannot reproduce on rev. 5b5c0938da0f
