### ISSUE TITLE
[3.3.5.][6.x][Core/SAI] Vehicles attack and act as regular mobs

### ISSUE THREAD

**Issue by Trista** [TrinityCore/TrinityCore#7450]
If a player controlled vehicle gets a SAI, it responds to aggro and movement of the victim. This is very old bug, jus that I finaly realised the cause. We need some exception for player controlled vehicles.

-

TDB: 11.48
Hash: 3a25fdeadec8449b6627854630ac16c8840fb3f6
OS: WinXP

**Comment by Killyana** [comment]
If someone can have a look on this issue as many quests are broken cause of it.

**Comment by Nyeriah** [comment]
Not only quests, but there are several vehicles that should have no AI response at all, but somehow, for example, they store combat info (i.e if you hit a SotA demolisher you'll be in combat forever). I think controllable vehicles should be void of any AI reactions

**Comment by Killyana** [comment]
Also CONDITION_SOURCE_TYPE_CREATURE_TEMPLATE_VEHICLE don't work if the vehicle have a SAI.

**Comment by Rushor** [comment]
there is a AI for such 0 react behaviour called NullCreatureAI, probably someone could implement the function of attackstart and update to SmartAI :)

**Comment by Kittnz** [comment]
wait, why do vehicles have SmartAI and not VehicleAI?

**Comment by MitchesD** [comment]
provide some IDs where it's in conflict

**Comment by Rushor** [comment]
example:
the horse vehicle for this quest: https://github.com/TrinityCore/TrinityCore/commit/e23b6436c5f84aa229af92c57e0ebc5fb04ec6c6

if a creature attacks the horse, the horse wants to react to the creature

**Comment by Rushor** [comment]
another example:

@Treeston wrote:
> Branch 3.3.5, rev. 8a0bbc386982

> [Quest: Sniffing Out the Perpetrator](http://www.wowhead.com/quest=12855/sniffing-out-the-perpetrator)

> Waypoints are messed up and drop you below the ground. Visual issue only.

@Killyana  wrote:
> Not related to waypoints, it's the vehicle behavior when it enter combat mode then evade it return to the last waypoint with a direct path ignoring mmaps, it must be fixed with this issue:  https://github.com/TrinityCore/TrinityCore/issues/7450
To be sure about the diagnostic just do the quest with gm on to avoid aggroing mobs.

**Comment by Rushor** [comment]
update by Treeston in https://github.com/TrinityCore/TrinityCore/pull/16020

**Comment by Rushor** [comment]
another example:

@Treeston wrote:
> Branch 3.3.5, rev. 8a0bbc386982
[Quest: A Mammoth Undertaking](http://www.wowhead.com/quest=12607/a-mammoth-undertaking)
Mounted [Shattertusk Mammoth](http://www.wowhead.com/npc=28379/shattertusk-mammoth) keeps its AI, chasing mobs and fighting against the player's control.

**Comment by Treeston** [comment]
#16020 has its own issues, as mentioned; it breaks a ton of quests that require vehicles or pets to do something scripted.

SmartAI needs to properly abide player control and not override movement in those cases.

**Comment by Killyana** [comment]
@Treeston This was fixed If I'm not wrong.

**Comment by Treeston** [comment]
yes.

**Comment by Treeston** [comment]
@kilyana link the commit please, it's one of my most recent ones to 3.3.5

**Comment by Treeston** [comment]
@killyana the above (mobile github sucks)

**Comment by Killyana** [comment]
Closed by https://github.com/TrinityCore/TrinityCore/commit/96f90381e3ed696861354ea4ddf4ac0c495031c5

**Comment by Treeston** [comment]
PR in question was #17738, looked it up for another issue.
