### ISSUE TITLE
[BUG] The Black Knight's Order

### ISSUE THREAD

**Issue by DoctorHR** [TrinityCore/TrinityCore#7468]
The quest [The Black Knight's Order] is bugged.
after you use the quest item, Enchanted Bridle, the black gryphon apears, a chat box opens but you cant get on the gryphon himself, which makes it impossible to complete.

Useful links:

Quest:
http://www.wowhead.com/quest=13663

Quest item:
http://www.wowhead.com/item=45083

thanks, DoctorHR

Hash: 3c42401

**Comment by Killyana** [comment]
The hole  quest is already scripted the problem is https://github.com/TrinityCore/TrinityCore/issues/8195 if you use another vehicleid for http://www.wowhead.com/npc=33519 it works, but ti's a hack.

**Comment by StormBytePP** [comment]
Fixed by rev ac2845ee77d0f3e838267ad424fbcf4894040333
