### ISSUE TITLE
[Bug]Enslaved Proto-Drakes in Utgarde Keep

### ISSUE THREAD

**Issue by Crysicle** [TrinityCore/TrinityCore#7475]
Bug:
1 - There is 1 Enslaved Proto-Drake inside Utgarde Keep, Dragonflayer Pens, that is unattackable. It seems as if it's below the ground thus cannot be reached because of LoS.

2 - There are about 20 Enslaved Proto-Drakes without waypoints in Tyr's Terrace, including the ones that should fly away from the last boss once he is aggroed.

3 - There is 1 Enslaved Proto-Drake in Tyr's Terrace that should go down from the top of the bridge and engage the party which is doing the instance when they're close enough to it. Furthermore, that drake should be mounted by a Proto-Drake Rider.

Links:
Enslaved Proto-Drake - http://old.wowhead.com/npc=24083
Proto-Drake Rider - http://old.wowhead.com/npc=24849
1 - http://i.imgur.com/7PuHa.jpg
2:
http://i.imgur.com/LpXQr.jpg
http://i.imgur.com/6sXG5.jpg
http://i.imgur.com/uQ0Et.jpg
http://i.imgur.com/v1NjT.jpg
3 - http://i.imgur.com/RkhiV.jpg

Video of issue 3(9:45) - http://www.youtube.com/watch?v=VIHU4DhdI_0

Core revision: Trinity Core 0b98656b2878+
Database revision: TDB 335.11.48
Addons: Anticheat1

**Comment by Rushor** [comment]
fixed like 3 weeks ago in the update for the wps of utrgarde
