### ISSUE TITLE
[Core/Vehicles] VehicleId 241

### ISSUE THREAD

**Issue by Trista** [TrinityCore/TrinityCore#7485]
Connected with #1084:
`vehicleId`=241 gives immunity to knockback effects and is sniffed value from a npc that must be affected by knockback.
I couldn't find anything related and maybe this guy needs an exception, not sure about core issues atm. I suppose is general vehicle thing and relates to all vehicles, if that is the case sorry:
NPC = 30388 /land npc/
Spell effect from spell ID - 61663 Gust of Wind (Effect 1 is damage and it is applied correctly, I tested without the VehicleId and all was okay):
Effect 0: Id 98 (SPELL_EFFECT_KNOCK_BACK)
BasePoints = 120
Targets (6, 0) (TARGET_UNIT_TARGET_ENEMY, NO_TARGET)
EffectMiscValueA = 120

-

TDB: 11.48
Hash: 85ed0e32a9b2b029c1db3cf1a914b3940cf72b9b
OS: XP

**Comment by Killyana** [comment]
Fixed
rev. 5b5c0938da0f
