### ISSUE TITLE
[NPC] Twilight Corrupter (15625)

### ISSUE THREAD

**Issue by nelegalno** [TrinityCore/TrinityCore#7529]
You need to kill him for The Nightmare's Corruption ( http://www.wowhead.com/quest=8735 ).
This NPC should be soloable at lvl80: https://www.youtube.com/watch?v=Q-yWGgN1Sa4

He falls underground and you can't attack him unless you stay in the pool.
Once he casts his mind control you fall underground and then are stuck to a few yards of the position besides him.
When he trows you back he usually resets (too small aggro range) and as you can see from the video he should follow you anywhere in the Twilight Grove zone.

P.S. You must have the quest and enter the zone where the NPC is located on foot in order to see it.

Videos:
https://www.youtube.com/watch?v=d9VTiu14bVs#t=88s
https://www.youtube.com/watch?v=Q-yWGgN1Sa4

Tested on TDB48  up to 13aa00d5f216 and TDB49 up to 2dc72ec7c85790c5f9bb0e0cbf408de1b6260ff2
##

**Comment by Aokromes** [comment]
This bug is still valid?

**Comment by Rushor** [comment]
Yes the small aggrorange is confirmed

If you try to solo this creature, it will simply throw you away and resets after it.
The dropping below the texture because of mind controle is a general problem with all mind controle spells

**Comment by Killyana** [comment]
Cannot reproduce on TrinityCore rev. 9614f9d8cf29
