### ISSUE TITLE
BattleField/Wintergrasp: Horde mobs in alliance controlled fortress

### ISSUE THREAD

**Issue by Chrisnetika** [TrinityCore/TrinityCore#7593]
Warsong Champions keep spawning by doorways in the fortress that is under alliance control
Using commit 4070f5ac842be931561caa07ad2f5334f622a9b8
Windows 7 Enterprise x64

**Comment by fvicaria** [comment]
Do we have any more news on this one?

**Comment by Frytiks** [comment]
Wintergrasp is in state - absolutly non-working.

**Comment by fvicaria** [comment]
I am still seeing double of all npcs and portal at Dalaran doesn't work among other little things. 
Could anyone suggest a way to go about it?
I am learning my way around the code so any pointers will be very welcome.
Thanks.

**Comment by ExHunter** [comment]
@fvicaria I have no idea if it is a proper fix.. but npcs are already in the database spawned with the right phases, so I don't see why https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Battlefield/Zones/BattlefieldWG.cpp#L127 from line 127 to 140 is done. Commenting it out will fix duplicated NPCs.

**Comment by fvicaria** [comment]
Just commenting out from 127 to 135 will do the trick.Although I am still struggling with both factions inside the keep and the double banners everywhere.

Regards, 
fvicaria

Date: Sat, 4 Apr 2015 12:52:43 -0700

**Comment by fvicaria** [comment]
Still looks like we are in a between stages here...
Half is coming from DB and half is coming from code.
Getting rid of the duplicates is easy but you still end up in a messed up state with hordes inside alliance controlled keep.  
Can anyone suggest the correct way to go here? I have see suggestion that it should be in DB but it looks (from my newbie point of view) a little easier given where we are and how long this is going for to do it in code.

**Comment by PaulHellCore** [comment]
Any news?

**Comment by Aokromes** [comment]
No.

**Comment by SnapperRy** [comment]
Please report unrelated bugs in different issues, if still valid.
