### ISSUE TITLE
[NPC] Greatfather Aldrimus (19698)

### ISSUE THREAD

**Issue by nelegalno** [TrinityCore/TrinityCore#7605]
Greatfather Aldrimus should be visible once the player finishes the quest chain starting with I See Dead Draenei ( http://www.wowhead.com/quest=10227 ), but it doesn't become visible and player can't get the Everything Will Be Alright ( http://old.wowhead.com/quest=10164 ) quest.

TDB up to c0d4ca8af120d3c23363d1e7dee08ba24283fe9f
TDB49 up to 2dc72ec7c85790c5f9bb0e0cbf408de1b6260ff2
##

**Comment by Killyana** [comment]
The npc is always visible (without invisibility aura) on rev. 5b5c0938da0f

**Comment by dr-j** [comment]
Ye I spawned from sniff but did not have any auras

**Comment by dr-j** [comment]
oh maybe wrong npc but did spawn a missing npc which is meant to be only visible once x quest is done but had no invis auras in sniff but dont think it was this npc.

**Comment by Gerhood** [comment]
`UPDATE creature SET phaseMask = 3 WHERE areaid = 3688;
UPDATE creature SET phaseMask = 2 WHERE id IN (19879, 19698);
DELETE FROM spell_area WHERE spell = 59073 AND AREA = 3688;
INSERT INTO spell_area(spell, AREA, quest_start, quest_end, aura_spell, racemask, gender, autocast, quest_start_status, quest_end_status) VALUES
(59073, 3688, 10253, 0, 0, 0, 2, 1, 64, 0);`

**Comment by Aokromes** [comment]
I really doub they used phasemasks on bc.

**Comment by Gerhood** [comment]
They didnt: http://www.gamasutra.com/php-bin/news_index.php?story=25192
But why should we neither?

**Comment by Aokromes** [comment]
Because if blizzard don't use phasemasks the fix is incorrect.

**Comment by Gerhood** [comment]
The phasing system is a server thing and we dont know how exactly blizzards phasing system worked in bc. But I dont see why you would not just use the system already in place with trinity.

**Comment by Aokromes** [comment]
phasemasks where added on wotlk, so, if this quest was added onBC using phasemasks is INCORRECT.

**Comment by dr-j** [comment]
well this could be a number of things, some invis aura on npc and see invis aura on player but have never been able to find in sniff but there are still other things that dont work from tbc too like forced rep (none player reps) to for example make hostile creatures neutral (ie ogres in nagrand) for which no signs of spells for that in sniff either

**Comment by Rushor** [comment]
phasemask hack was also already used here https://github.com/TrinityCore/TrinityCore/commit/0f6515750dc882185135a5ef31165e14d7a2c304 in bc :/

**Comment by Grz3s** [comment]
from sniff:
```code
ServerToClient: SMSG_AURA_UPDATE (0x2C22) 
UpdateAll: True
AurasCount: 1
[0] Slot: 0
[0] HasAura: True
[0] SpellID: 32648 (32648)
[0] SpellXSpellVisualID: 0
[0] Flags: NoCaster (1)
[0] ActiveFlags: 1
[0] CastLevel: 70
UnitGUID: Full: 0x2030F84240133C8000005D00001092AF Creature/0 R3134/S93 Map: 530 Entry: 19698 Low: 1086127
```

**Comment by offl** [comment]
So 32649 should be on the player?

**Comment by offl** [comment]
Hm, [quite possible](http://www.wowhead.com/spell=32649/commune-with-the-ancestors#comments).

**Comment by Killyana** [comment]
It's possible that other npc turn visible with the same conditions as 19698
``` sql
UPDATE `creature_template_addon` SET `auras`=32648 WHERE `entry` IN(19698);
DELETE FROM `spell_area` WHERE `spell`=32649 AND `area`=3688;
INSERT INTO `spell_area` (`spell`,`area`,`quest_start`, `quest_end`,`aura_spell`,`racemask`,`gender`,`autocast`,quest_start_status) VALUES
(32649,3688,10252,0,0,0,2,1,64);
