### ISSUE TITLE
Water Elemental + other minions

### ISSUE THREAD

**Issue by Valcorb** [TrinityCore/TrinityCore#7621]
Water Elemental + other minions that do not despawn when you mount up, should gain the speed from the mount from his summoner.

At the moment, the minion stays at walking speed and gets left behind when you mount up and run away.

Core: 
46852a3808

TDB: 335.11.48 + sql/updates/world
##

**Comment by Saben65** [comment]
https://github.com/TrinityCore/TrinityCore/pull/15749

**Comment by Rushor** [comment]
well this https://github.com/TrinityCore/TrinityCore/pull/15749 does not solve the issue, that the creature despawns after mounting. Code for this can be found in Unit::DoMount

**Comment by Saben65** [comment]
Unless I am miss-reading it, the issue being reported is that minions that do not despawn when mounted (such as the water elemental, which is correct) do not inherit the owner's speed, which I believe the PR addresses.

**Comment by Killyana** [comment]
https://github.com/TrinityCore/TrinityCore/commit/2a84562dc85516f432bb1e5de9add23c28b26ce4
