### ISSUE TITLE
[Core/warden] : Not checked The Hitchhiker's Hack (35$ bounty)

### ISSUE THREAD

**Issue by Kingswow** [TrinityCore/TrinityCore#7639]
revision :  a47ad2f5e1

db version : TDB 335.11.48

Hitchhiker's Hack Download link : (removed to protect the innocent)

(im not sure)MD5 Hash : 0F84359C5BA5A737EF25E836729F7870

Edited by Nay
##

**Comment by Raydor** [comment]
Confirm

Rev: https://github.com/TrinityCore/TrinityCore/commit/97d415d1b2a429557f667f9c30e8577ab89e6434

TDB: TDB 335.57

**Comment by lainimer** [comment]
Confirm and very critical!

**Comment by pravietis** [comment]
Confirm still have this problem :) need some solution  Thanks!

**Comment by lashia** [comment]
confirm fb895cc99bffa668715b02b41fdf78038b2f0dfa

**Comment by mik1893** [comment]
this cant be checked by the warden - the only to check this is to have an active anticheat running on the server that check player position every x ms and tries to understand if the new position is valid compared to the last one, given any teleport and auras on the player. There is a massive amount of false positives that needs to be handled....

**Comment by tje3d** [comment]
Isn't this a wont fix issue?

**Comment by tkrokli** [comment]
Good point. If this specific hack is too difficult for Blizzard to solve, why should TrinityCore keep the issue open for 10 years to see if it gets solved?

**Comment by Kittnz** [comment]
Just to note it's still an issue i guess? :dancer:

**Comment by tkrokli** [comment]
Sure, I get that. I just don't see any solution for this in the next year or so.

**Comment by tje3d** [comment]
@tkrokli Similar to #13660 which is stated as won't fix

**Comment by tkrokli** [comment]
Thanks for the tip. I leave it up to the owners/main TC devs to decide if that will be the case here.

**Comment by FireEmerald** [comment]
That kind of detection is called a **passive anti-cheat** which is in fact able to detect any speedhack e.g.
But it has various negative effects which are maybe the reason why never such a feature was implemented. The two main reasons which i would think of are:

1. It isn't that easy to calculate the correct speed and in fact it will take extra resources (cpu e.g.)
2. It may detect players with a high-ping/lags as cheater so there are various cases where false-detection could happen and therefore a GM must check every player.

**Comment by Seyden** [comment]
@Killyana i can look if i always have the code for it.

@FireEmerald i can't remember.. but i think i thought about point 2 when i did the anti cheat.. but have to look..

**Comment by Igorinus** [comment]
try this https://github.com/WoWSource/WoWSource434/tree/dcb2fec245b3b2ab4a8f6f4f8cd77a51c80bfb68/src/server/game/Anticheat i remember there was no hacks to work  in that core, all was  detected right away and auto banned all attempts and options can be modify from worldserver.conf, i'm sure its required a  few adjustments to fit with actually tc

**Comment by Aokromes** [comment]
news is this will continue to be the same.
https://github.com/TrinityCore/TrinityCore/issues/7639#issuecomment-224385035
(use passive anticheat and check warnings because it has to much false positives)

**Comment by Infernales** [comment]
This is the source code of this cheat. Maybe someone will figure out how to deal with it.
https://github.com/wodim/hitchhiker

**Comment by Aokromes** [comment]
the answer will be the same whatever you write, use passive anticheat.

**Comment by Infernales** [comment]
@Aokromes Are you talking about the anti-cheat that is on the forum? You have to be a sadomasochist to use it. Cheats of this type will never work on the official server, because every player there is processed by the server. Most cheats now use a clumsy implementation of the system of movements. So there is no need for a passive anti-cheat, you need to improve the server-side code.

**Comment by Infernales** [comment]
@Aokromes Well, try to hack the official server through the transport and substitution of MOVEMENTFLAG_ON_TRANSPORT. In Trinity and MaNGOS this is possible.

**Comment by sirikfoll** [comment]
In case anyone wants to check, there are some warden checks here, I can't confirm if any works, but most of them, for sure, does not.
http://www.ac-web.org/forums/showthread.php?227605-Warden-Checks-WoTLK

**Comment by Infernales** [comment]
@sirikfoll I checked it. A lot of false positives. Warden will never recognize The Hitchhiker's Hack or Admin Panel WoW, they do not affect WoW.exe and are aimed at poor synchronization of the server with the client.

**Comment by HelloKitty** [comment]
@tje3d This can be done because move interrupt is only checked on Spell Update and on cancel cast packet. You can send specific MSG_MOVE opcodes after your last movement (like turn). This can be stopped by checking spell casting in movement opcode handler or by tracking the movement flags until next spell update.
