### ISSUE TITLE
[NPC] Ulduar Heart of the Deconstructor - cnt be attacked

### ISSUE THREAD

**Issue by Int007** [TrinityCore/TrinityCore#7648]
XT-002 Deconstructor, Heart of the decontructor - cnt be attacked it is enemy but cnt be attacked {http://www.wowhead.com/npc=33329}

win 7
core commit b4bc78e without any custom things

**Comment by Killyana** [comment]
I made many attempts on different positions and the heart was always attackable.
If someone can confirm we can close the issue.
rev. 5b5c0938da0f

**Comment by Killyana** [comment]
Get confirmations that this issue doesn't happen in recent revisions.
