### ISSUE TITLE
[3.3.5][6.x][Ulduar] Core/Creature: Thorim Encounter

### ISSUE THREAD

**Issue by Int007** [TrinityCore/TrinityCore#7651]
Thorim - after we kill Jurmungar Behemoth and other mobs gate whant to open bar do not work you will se on this video what bar http://youtu.be/WsqT-ntbDOg?t=1m objectID=194264 GUID=55194 and even if i open gate with activate gameobject we cnt kill Thorim it is enemy but in is not attackable and phases do not start

win 7
core commit b4bc78e without any custom things
##

**Comment by dexteerz** [comment]
So we do not have first realm archiv in Ulduar ? :/

**Comment by hellomotow** [comment]
I am surprised this is still not fixed :(

**Comment by Aokromes** [comment]
Test #15008

**Comment by Nikectory** [comment]
Confirmed on rev https://github.com/TrinityCore/TrinityCore/commit/f4e2fb8f79e5a223506d9e514b7adf18c2198bab

**Comment by Aokromes** [comment]
There is no need to confirm when you known a fix is work in progress.

**Comment by Nikectory** [comment]
@Aokromes sorry, i know.
It's just our teamwork protocol, wont happen again.
