### ISSUE TITLE
[Script / Dungeon] The Culling of Stratholme - Arthas Talkable Before Event Finished

### ISSUE THREAD

**Issue by EnteringCombat** [TrinityCore/TrinityCore#7723]
Hello,
There's a problem regarding Arthas in Culling of Stratholme in which you can speak to Arthas before the group plagued 5 crates using the item given by Chromie called "Arcane Disruptor".

The group should only be able to re-meet Chromie after plaguing the 5 crates assigned, right infront of Stratholme village, and only then talk to Arthas.
An alternative script could be plaguing 5 crates and then speak to Arthas and start the event.

Notice, if the group does plague 5 crates and talk to Arthas, the event works.

We're using hash 4bc983d.
##

**Comment by Aokromes** [comment]
Note to self, check this on ptr without doing quest.

**Comment by Aokromes** [comment]
If you don't have quest he is missing.

**Comment by Wyrserth** [comment]
ca6228067507f19db230d415a1d088e5c0b5b808
