### ISSUE TITLE
[Instance] Lady Deathwhisper - Vengeful Shade

### ISSUE THREAD

**Issue by Butterfly69** [TrinityCore/TrinityCore#7737]
H!
Lady Deathwhisper 25HC in secend phase should summon 2 Vengeful Spirit (sometimes 3) ,i didnt find the source in wowhead or wowwiki but as you can see the videos on retail,2 Vengeful shade spawn,not one !

video: http://www.sk-gaming.com/video/259958-Arctica_vs_Lady_Deathwhisper_25_HC
my hash: 0390f9d7085e143b740d6d0c438cf295378d33c4
Thanks.

**Comment by Keader** [comment]
For references, fixed by: https://github.com/TrinityCore/TrinityCore/commit/8e82d8a9e79ba95fbd780fa093416ebe7431a1c0
