### ISSUE TITLE
Enchanted Bridle Should spawn only 1 npc(no huge amount of spawns)

### ISSUE THREAD

**Issue by litr** [TrinityCore/TrinityCore#7786]
Hey all.
Quest: http://www.wowhead.com/quest=13663
Item: http://www.wowhead.com/item=45083
Spell: http://www.wowhead.com/spell=63163
NPC: http://www.wowhead.com/npc=33519
So, this item should spawn only 1 npc(no huge amount of spawns). I looked at https://github.com/TrinityCore/TrinityCore/blob/master/src/server/game/Spells/SpellEffects.cpp#L2305
and if I understand right lines below should fix the problem, but it doesn't. This problem can cause server to completely hang.
http://imageshack.us/a/img840/2228/wowscreenw.png
59e86f8df99da5193c53095a6d9d7ba22aa5d401
DB: TDB 49

**Comment by Aokromes** [comment]
No answer after a lot of months, if this bug is still valid open a new ticket.
