### ISSUE TITLE
[Spell] Icy chill and other Limited to level 60/70 enchants  [$5]

### ISSUE THREAD

**Issue by Exodius** [TrinityCore/TrinityCore#7789]
Icy Chill: http://wotlk.openwow.com/?spell=20029
Learned From: http://wotlk.openwow.com/?item=16223
- Problem 1: Should be dispellable, atm its PHYSICAL
  http://www.wowwiki.com/Enchant_Weapon_-_Icy_Chill
  http://www.wowhead.com/spell=20005#comments
  http://www.wowwiki.com/Chilled ->most prolly the same debuff but applied by NPC.
  ''Can apply a frost debuff on a melee hit that causes target's movement slowed by 30% and time between attacks increased by 25% for 5 sec. ''
  ''It can be dispelled as a Magic type.''
- Problem 2: Should proc ONLY from white attacks NOT special/instant attacks. Atm it procs from everything.
  http://www.wowwiki.com/Enchant_Weapon_-_Icy_Chill
  ''This implies that it cannot proc off of instant attacks (like Battlemaster) ''
  http://www.wowwiki.com/Enchant_Weapon_-_Battlemaster
  '' Unlike most other enchants, battlemaster does not proc more often from ability use or mainhand use. Nothing a player does or equips seems to increase the PPM.\* It either cannot proc from instant attacks (ie procs from autoattack only), or can only proc on white damage attacks.''
- Problem 3: The proc rate is bugged, way too high.
  http://www.twinkinfo.com/sitemap/t-32865.html
  ''well firstly PLEASE don't use icy chill, it's proc rate is horrendous ...''
  http://www.twinkinfo.com/sitemap/t-22838.html
  ''No one uses icey as it's proc rate is supposedly horrible.'
  ''the enchant icy chill is worthless, was nerfed to crap back 4 years ago(icy was hotfixed/stealth nerfed no documentation/notes), it does not have the same proc rate as crusader''..
  Note that Crusader has 1 PPM only ! ..
  http://elitistjerks.com/f31/t15371-tanking_icy_chill_maths/
  ''Within 11682 swings it procced 495 times - every 23,6th swing aka 1.7 ppm .''(found something like this but ...not sure if its after or pre nerf, prolly pre nerf)
  http://www.wowhead.com/spell=20029#comments
  ''this has one of the lowest proc rates of all the enchants. I'd pass unless you want the glow''
  ''Icy procs regularly for me on both my prot warrior and my rogue. The reason you don't see it proc is because your weapon speed is too low - unlike fiery which procs per minute this enchant procs per hit. I put it on my 1.3 offhand dagger and it procs once or twice per combat. The general rule seems to be that damage or buffing enchants (fiery/ crusader) work on a per minute basis while debuffs (icy, unholy) work on a per hit basis.''
- Problem 4: Tooltip Says: Has a reduced effect for players above level 60.
  U still apply this on lvl 80 no problem, but the higher the lvl is the higher the resist should be...
  http://www.wowhead.com/spell=20029#comments
  '' but this seems to proc a lot less often on mobs higher than level 60; I grinded in Bash'ir landing and it proced some 5-6 times in half an hour, while that same day, in Stratholme, it procced about 2 times per one Abomination, fight lasting around 30 seconds. I even managed to keep one of the Abominations permanently chilled until it died.''
  Bashir landing = 65=70 lvl mobs or so...
  ''Has a reduced effect for players above level 60." This obviously includes mobs lvl 60 and up, and its not that it doesn't Proc, its that they Resist it.''
- Problem 5: The proc = Movement slowed by 30% and time between attacks increased by 25%.
  The time between attacks in % should be decreased on lvl 60+.
  http://elitistjerks.com/f31/t15371-tanking_icy_chill_maths/
  ''Seems that vs. a lvl 70 target (player) the attack speed is reduced by 15% (14,8648%).''
  That is on lvl 70, on lvl 80 it should be even more, not sure how much, but currently its 25%.
  Tested on DK, normal speed 3.4, after proc 4.25.
  x=[(4.25/3.4)-1] \* 100 x=25%
- Problem 6: The enchant STACKS with other speed modifying spells/abilities, and thats a BUG.
  http://elitistjerks.com/f31/t15371-tanking_icy_chill_maths/
  ''Well, at least on players it doesn't stack
  without debuffs: 3,6
  Thunderclap: 4,32
  Chilled: 4,14
  TC+Chilled: 4,32''

Currently on testing DK
w/o debuffs :3.4
with TC: 3.74 -->10%
with TC+chilled: 4.68 -->37.7%
##

**Comment by oMadMano** [comment]
Just one example for icy chill enchant
```
DELETE FROM `spell_script_names` WHERE (`spell_id`='16927') AND (`ScriptName`='spell_gen_chilled');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES
('16927', 'spell_gen_chilled');

DELETE FROM `spell_script_names` WHERE (`spell_id`='20005') AND (`ScriptName`='spell_gen_chilled');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES
('20005', 'spell_gen_chilled')
```
```

class spell_gen_chilled : public SpellScriptLoader
{
public:
    spell_gen_chilled() : SpellScriptLoader("spell_gen_chilled") { }

    class spell_gen_chilled_AuraScript : public AuraScript
    {
        PrepareAuraScript(spell_gen_chilled_AuraScript);

        void OnApply(AuraEffect const* aurEff, AuraEffectHandleModes /*mode*/)
        {
            Unit* caster = GetCaster();
            if (Unit* target = GetTarget())
                if (target->GetTypeId() == TYPEID_PLAYER && (target->getLevel()>60))
                if (AuraEffect* aurEff1 = aurEff->GetBase()->GetEffect(EFFECT_1))
                    aurEff1->SetAmount(aurEff->GetAmount() / 2);
        }

        void Register() override
        {
            OnEffectApply += AuraEffectApplyFn(spell_gen_chilled_AuraScript::OnApply, EFFECT_1, SPELL_AURA_MOD_DECREASE_SPEED, AURA_EFFECT_HANDLE_REAL_OR_REAPPLY_MASK);
        }
    };

    AuraScript* GetAuraScript() const override
    {
        return new spell_gen_chilled_AuraScript();
    }
};
```

**Comment by joschiwald** [comment]
CalculateAmount hook is a better way

**Comment by Keader** [comment]
Deathfrost still give slow in level 80...
Fix by @untaught (https://github.com/TrinityCore/TrinityCore/issues/4951#issuecomment-37126867) works
```sql
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=17 AND `SourceEntry`=46629;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
(17,0,46629,0,0,27,1,74,2,0,0,0,0,'','Deathfrost hits only targets below lvl 74');
```

**Comment by Aokromes** [comment]
Can't https://github.com/TrinityCore/TrinityCore/issues/7789#issuecomment-202098308 be adapted to all the spells listed on this ticket?

**Comment by ariel-** [comment]
> Problem 1: Should be dispellable, atm its PHYSICAL

Not true
```
ID - 20005 Chilled
=================================================
Description: Target's movement slowed by $s2% and time between attacks increased by $s1% for $d.
ToolTip: Movement slowed by $s2% and time between attacks increased by $s1%.
Category = 0, SpellIconID = 143, activeIconID = 0, SpellVisual = (675,0)
Family SPELLFAMILY_GENERIC, flag [0] 0x00000000 [1] 0x00000000 [2] 0x00000000

SpellSchoolMask = 16 (SPELL_SCHOOL_MASK_FROST)
```
