### ISSUE TITLE
Quests: Do Your Worst

### ISSUE THREAD

**Issue by mweinelt** [TrinityCore/TrinityCore#7800]
http://www.wowhead.com/quest=13305 Horde
http://www.wowhead.com/quest=13394 Alliance

Matthias Lehner (http://wowhead.com/npc=32408) is not spawned and as such you cannot get the quest.

The Refurbished Demolisher also cannot be boarded.

Matthias Lehner (http://wowhead.com/npc=32404) is also not spawned, so the quest cannot be turned in either.

TDB49, 6ebc6b9a76d0a4576306d777b35ec1a37d3ec5da

**Comment by Killyana** [comment]
Fixed
rev. 5b5c0938da0f
