### ISSUE TITLE
Quest: Army of the Damned

### ISSUE THREAD

**Issue by mweinelt** [TrinityCore/TrinityCore#7801]
http://www.wowhead.com/quest=13236

Quest StartScript for phasing and entering the vehicle is missing.

Video:
http://www.youtube.com/watch?v=Ew2efBLJVjs

TDB49, 6ebc6b9a76d0a4576306d777b35ec1a37d3ec5da

**Comment by GeneralSaurfang** [comment]
Deathstorm can target the player himself if he is close enough to the original target, resulting in death.
Soul Cleave doesn't work and says "No target" although I do have a proper target.

Without Soul Cleave, it is impossible to extract enough mana to complete the quest.

**Comment by Killyana** [comment]
The 2 spells need conditions, try to do it, it's not hard.

**Comment by GeneralSaurfang** [comment]
'''SET @DEATHSTORM := 58912;
SET @SOULCLEAVE := 58913;

DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId` = 13 AND `SourceEntry` = @DEATHSTORM;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`)
VALUES (13, 1, @DEATHSTORM, 0, 0, 33, 0, 1, 1, 0, 1, 0, 0, '', 'Deathstorm cannot hit self');

DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId` = 17 AND `SourceEntry` = @SOULCLEAVE;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`)
VALUES (17, 1, @SOULCLEAVE, 0, 0, 32, 0, 8, 0, 0, 0, 0, 0, '', 'Soul Cleave can target units');'''

I tried this but it didn't change anything. What am I doing wrong? Can you hint me in the right direction?

**Comment by Killyana** [comment]
This must be done by cpp as all effects doesn't support conditions

**Comment by Rushor** [comment]
```c++
enum Deathstormmisc
{
    NPC_LORDAERON_FOOTSOLDIER = 31254
};

class DeathstormTargets
{   
    public:
        bool operator()(WorldObject* object) const
        {
            return object->GetEntry() != NPC_LORDAERON_FOOTSOLDIER;
        }
};

// - 58912 Deathstorm
class spell_icecrown_deathstorm : public SpellScriptLoader
{
    public:
        spell_icecrown_deathstorm() : SpellScriptLoader("spell_icecrown_deathstorm") { }

        class spell_icecrown_deathstorm_SpellScript : public SpellScript
        {
            PrepareSpellScript(spell_icecrown_deathstorm_SpellScript);

            void FilterTargets(std::list<WorldObject*>& unitList)
            {
                unitList.remove_if(DeathstormTargets());
            }

            void Register()
            {
                OnObjectAreaTargetSelect += SpellObjectAreaTargetSelectFn(spell_icecrown_deathstorm_SpellScript::FilterTargets, EFFECT_0, TARGET_UNIT_TARGET_ENEMY);
            }
        };

        SpellScript* GetSpellScript() const
        {
            return new spell_icecrown_deathstorm_SpellScript();
        }
};
```

**Comment by Killyana** [comment]
@Rushor Need you on IRC.

**Comment by ccrs** [comment]
no need for that, use oncheck hook instead :)

**Comment by sirikfoll** [comment]
This should be reopened?
Spell [58913](https://wotlk.openwow.com/spell=58913) doesn't work, it says "No target"
Spell [58912](https://wotlk.openwow.com/spell=58912) remains the same, hitting the vehicle and  the player

**Comment by sirikfoll** [comment]
Spell 58912 only hit the vehicle and the player if none target is selected, so, adding a condition for explicit target solve that issue
```sql
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=17 AND `SourceEntry`=58912;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
(17,0,58912,0,0,31,1,3,31254,0,0,0,0,'','Spell \'Deathstorm\' requires target Lordaeron Footsoldier');
```

**Comment by sirikfoll** [comment]
Now that conditions work for chain targets, this sql is enough to fix the issue.
Spell 58913 still bugged, but that's another issue(#17205)
```sql
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId` IN(13,17) AND `SourceEntry`=58912;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`,`SourceGroup`,`SourceEntry`,`SourceId`,`ElseGroup`,`ConditionTypeOrReference`,`ConditionTarget`,`ConditionValue1`,`ConditionValue2`,`ConditionValue3`,`NegativeCondition`,`ErrorType`,`ErrorTextId`,`ScriptName`,`Comment`) VALUES 
(17,0,58912,0,0,31,1,3,31254,0,0,0,0,'','Deathstorm requires target Lordaeron Footsoldier'),
(17,0,58912,0,1,31,1,3,32414,0,0,0,0,'','Deathstorm requires target Lordaeron Captain'),
(13,1,58912,0,0,31,0,3,31254,0,0,0,0,'','Deathstorm can hit Lordaeron Footsoldier'),
(13,1,58912,0,1,31,0,3,32414,0,0,0,0,'','Deathstorm can hit Lordaeron Captain');

**Comment by tkrokli** [comment]
Something is bugged on this page, I don't see when the labels were added (after which comment post).

**Comment by Rushor** [comment]
github bugs :o

**Comment by Aokromes** [comment]
Old labels don't have addition date. Not a bug, simply non-implemented feature.
