### ISSUE TITLE
you get kicked from the group if you get disconected

### ISSUE THREAD

**Issue by robin1741** [TrinityCore/TrinityCore#7843]
if you are in a group, and log out, you get kicked from the group. THAT must be a bug? it's very annoying if you are playing a instance or a raid and you get dc and you get be with your group only becaseu you get dc and you are kicked form the group. this must be a bug right? in real wow you woud not be kicked if you get dc or relog or whatever
##

**Comment by Aokromes** [comment]
This was fixed few months ago no?

**Comment by Rushor** [comment]
hm maybe this issue still happens in lfg groups

**Comment by Killyana** [comment]
Cannot reproduce on rev. fa3eb754cbe1
