### ISSUE TITLE
[Bug]Double spawn of a Stratholme Resident and Citizen

### ISSUE THREAD

**Issue by Crysicle** [TrinityCore/TrinityCore#7898]
Bug:
When Arthas rushes into Stratholme in CoS he kills 2 npcs - Stratholme Resident and Stratholme Citizen. However, instead of them being killed, another npc of each spawns and those are killed instead.

Note: sometimes these clones don't even spawn, so arthas just waves his hammer into the air.

Links:
Stratholme Citizen - http://www.wowhead.com/npc=28167
Stratholme Resident - http://old.wowhead.com/npc=28169
Video of the bug - http://www.youtube.com/watch?v=erZJf4gIunM

Core revision: Trinity Core 8fc42b16ecfe+
Database revision: TDB 335.49
Addons: Anticheat1, AHbot

**Comment by Killyana** [comment]
Fixed.
rev. 5b5c0938da0f
