### ISSUE TITLE
[Bug]Skinning Chrono-Lord Epoch

### ISSUE THREAD

**Issue by Crysicle** [TrinityCore/TrinityCore#7899]
Bug:
When you try to skin Chrono-Lord Epoch, instead of starting to skin him, the cursor becomes a grey hand.

Link:
Chrono-Lord Epoch - http://www.wowhead.com/npc=26532

Core revision: Trinity Core 8fc42b16ecfe+
Database revision: TDB 335.49
Addons: Anticheat1
##

**Comment by Riztazz** [comment]
Its caused by dynamicflag on this boss, if you remove it then you're able to skin it, current set dynamicflag in db is UNIT_DYNFLAG_TAPPED_BY_PLAYER for whatever reason - this is probably not a fix, just letting you know whats up :P

**Comment by Killyana** [comment]
To be tested after https://github.com/TrinityCore/TrinityCore/pull/23388

**Comment by Killyana** [comment]
Fixed by https://github.com/TrinityCore/TrinityCore/pull/23388
