### ISSUE TITLE
[Bug]CoS - Infinite dragonflight 2nd wave

### ISSUE THREAD

**Issue by Crysicle** [TrinityCore/TrinityCore#7901]
Bug:
When the the 2nd Infinite dragonflight wave spawns in CoS, players are not able to kill them until Arthas kills 1 of the mobs.

Links:
Video of the bug - http://www.youtube.com/watch?v=D4PLW8D62m8

Core revision: Trinity Core 8fc42b1+
Database revision: TDB 335.49
Addons: Anticheat1, AHbot

**Comment by Aokromes** [comment]
I think this was fixed long time ago.

**Comment by Killyana** [comment]
yes.
