### ISSUE TITLE
Invisibility & Threat Reducing abilities

### ISSUE THREAD

**Issue by LordUsagi** [TrinityCore/TrinityCore#7912]
Currently, when using Invisibility, or any kind of spell or ability that reduces aggro as seen on the item
Hypnotist's Watch - http://old.wowhead.com/item=25786

you'll actually pulse, and pull all surrounding enemies, whether they're neutral or not causing you to engage in combat with a very wide spread area.

**Comment by Aokromes** [comment]
dc1a015
