### ISSUE TITLE
[Bug]Spectral Citizen

### ISSUE THREAD

**Issue by Crysicle** [TrinityCore/TrinityCore#7921]
How it should work:
1. If you /rude them from a distance, they'll /rude back, however, if you are close enough, they will "Slap!" you, but not engage in combat.
2. If you /kiss them, they will /kiss you back.
3. If you /wave at them, they'll /wave back.
4. If you /dance with them, they will stop attacking and /dance. Atm, they just drop all threat when you /dance.

Links:
Spectral Citizen - http://www.wowwiki.com/Spectral_Citizen
Spectral Citizen - http://www.wowhead.com/npc=10384
Slap! - http://www.wowhead.com/spell=6754
Proof of the dance/wave(2:50) - http://www.youtube.com/watch?v=dgupcdA1pl0

Core revision: 0f0cea1
Database version: TDB 335.53
Addons: Anticheat1

**Comment by Killyana** [comment]
Fixed.
rev. 5b5c0938da0f
