### ISSUE TITLE
Hellscream Warsong and Strength of Wrynn on pets

### ISSUE THREAD

**Issue by lvalladares** [TrinityCore/TrinityCore#7940]
these auras (http://www.wowhead.com/spell=73822 and http://www.wowhead.com/?spell=73828) aren't affecting pets

How to reproduce

1 Enter in icc

2 Call your pet

What happens?

Err... nothing special

What should happen?

The pet should gain the buff, exactly as the players gains the buff

Source: http://bigredrhino.wordpress.com/2010/04/08/pet-feat-icecrown-citadel-25-lord-marrowgar-mt/

"The fight was done with 10% Hellscream’s Warsong buffing HP, damage, and healing by 10%."

Hash: d44ec4b7dabb5a43bf8161b0a6118b209a49b5d1
DB: TDB_full_335.49
##

**Comment by Nefertumm** [comment]
Progress? Still bug

**Comment by Staleness89** [comment]
There's a fix for this in Sunwell Core's Pet.cpp if any experts want to look at it.

https://github.com/Staleness89/Sunwell/blob/master/src/server/game/Entities/Pet/Pet.cpp#L75

https://github.com/Staleness89/Sunwell/blob/master/src/server/game/Entities/Pet/Pet.cpp#L1170

Also requires a few defines from their PetDefines.h. Works for me, though.

**Comment by Keader** [comment]
94b60ff0ef7ee908e9ab4660f6dce0dcfe3f13e8
