### ISSUE TITLE
Wintergrasp quests not completed

### ISSUE THREAD

**Issue by digz6666** [TrinityCore/TrinityCore#7953]
Following 8 quests not completed even I do it:
1. Victory in Wintergrasp (horde) - http://www.wowhead.com/quest=13183
2. Victory in Wintergrasp (alliance) - http://www.wowhead.com/quest=13181
3. Stop the Siege (horde) - http://www.wowhead.com/quest=13185
4. Stop the Siege (alliance) - http://www.wowhead.com/quest=13186
5. Defend the Siege (horde) - http://www.wowhead.com/quest=13223
6. Defend the Siege (alliance) - http://www.wowhead.com/quest=13222
7. Toppling the Towers - http://www.wowhead.com/quest=13539
8. Southern Sabotage - http://www.wowhead.com/quest=13538

Source: https://github.com/TrinityCore/TrinityCore/commit/94b2f90a5a821db38cb5c8430bc029423557cd2f
Database: TDB.335.49

**Comment by zamalaev** [comment]
Latest rev 3.3.5a
Quest Flags = 32842 =(
32768 QUEST_FLAGS_WEEKLY +
64       QUEST_FLAGS_RAID +    // does not work?
8         QUEST_FLAGS_SHARABLE +
2         QUEST_FLAGS_PARTY_ACCEPT)

**Comment by Rushor** [comment]
addition:
1. Victory in Wintergrasp (horde) - http://www.wowhead.com/quest=13183
2. Victory in Wintergrasp (alliance) - http://www.wowhead.com/quest=13181

these quests can be accapted mutiple times in a week. you can also complete it mutiple times in a week, but you can only reward it once in a week.

normally you should not be able to accapt the quest mutiple times

**Comment by el-druida** [comment]
This issue still persists

**Comment by Aokromes** [comment]
test  #17535

**Comment by tkrokli** [comment]
[Core/Quest: implement usage of QUEST_FLAGS_RAID to allow a quest to be completed while in raid] #17535 is now merged into 3.3.5 so you can just update your sources to see if things have improved.

**Comment by SnapperRy** [comment]
Aaaaand we can finally forget about this :P
