### ISSUE TITLE
[ICC]Professor Putricide - Tear Gas Don't Work

### ISSUE THREAD

**Issue by Flameshot** [TrinityCore/TrinityCore#7972]
Hi.At Professor Putricide in tranzition phase tear gas don't work.I searched a fix but i didn't find it/

rev: https://github.com/TrinityCore/TrinityCore/commit/74707a08d3d63dc66e7b6943431c91f50258b0f9
DB: TDB_335.49.
##

**Comment by Aokromes** [comment]
If the fix here is valid, plz open a PR.

**Comment by Aokromes** [comment]
973f6b04ed082d4a7c7743021eb16b7304764e40
