### ISSUE TITLE
[BUG] Sweeping Strikes

### ISSUE THREAD

**Issue by kasimtim** [TrinityCore/TrinityCore#7995]
Hi guys!
1. Warrior: uses sweeping strike+bladestorm
2. Hunter: uses deterrence
3. Warrior: target hunter pet
4. Hunter using deterrence takes damage from sweeping strikes.
Core revision: 3aa5869
Database revision: TDB 335.49

**Comment by Re3os** [comment]
Confirm https://github.com/TrinityCore/TrinityCore/commits/3.3.5

**Comment by DevRival** [comment]
Any news?

**Comment by fat4l** [comment]
Sweeping stikes cant be dodged, blocked or parried.
Deterrence = parry
U cant parry an un-parryable attack.

**Comment by Aokromes** [comment]
So, invalid report?

**Comment by Rushor** [comment]
yes

http://us.battle.net/wow/en/forum/topic/6520713188
• You can hit hunters through deterrence with Sweeping Strikes. Target their pet when beside both of them to keep doing some damage. This works because deterrence works off misses, and sweeping strikes can never miss/dodge/block/parry.
