### ISSUE TITLE
NPC [Razormane Hunter] [3265] should have pet [Razormane Wolf] [3939]

### ISSUE THREAD

**Issue by kldxzzhc3** [TrinityCore/TrinityCore#8003]
Hi, I use the latest version code and the latest TDB.

I found that :
THE NPC [Razormane Hunter] [3265] should have pet [Razormane Wolf] [3939],
but in TrinityCore, 3265 doesn't have any pet. I think it's a bug.

By the way, I want to know how to add a pet for a npc(using database sql).

Thanks!

**Comment by Killyana** [comment]
``` sql
DELETE FROM `creature` WHERE `id`=3939;
UPDATE `creature_template` SET `AIName`='SmartAI' WHERE `entry`=3939;
DELETE FROM `smart_scripts` WHERE `entryorguid`=3939 AND `source_type`=0;
DELETE FROM `smart_scripts` WHERE `entryorguid`=3265 AND `source_type`=0 AND `id`=2;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(3265, 0, 2, 0, 25, 0, 100, 0, 0, 0, 0, 0, 11, 6479, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,0,'Razormane Hunter- On Reset - Cast to summon Razormane Wolf'),
(3939, 0, 0, 0, 0, 0, 100, 0, 3000, 7000, 8000, 12000, 11, 16828, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0,0,'Razormane Wolf - IC - Cast Claw'),
(3939, 0, 1, 0, 0, 0, 100, 0, 5000, 10000, 10000, 150000, 11, 59881, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0,0,'Razormane Wolf- IC - Cast Rake');

**Comment by tkrokli** [comment]
@Killyana : as much as I applaud your tenacity and stamina working on the issues and writing solutions, I need to comment on using Cat abilities on a Wolf. The basic ability for a wolf is not Claw, it is Bite. Regarding the Rake ability, I am less sure about the equivalent ability, since I can't find an "Abilities" column for the Razormane Wolf on WowHead. From a hunter's perspective, it should be Furious Howl.

Source: Petopia - Patch 4.0 Ability Changes: http://www.wow-petopia.com/guides/patch40abilities.html

**Comment by Killyana** [comment]
Cannot find any spell used by this  npc so I keep the ones used in a previous script.

**Comment by tkrokli** [comment]
OK, fair enough. Should you decide to modify it at a later time, the spell with matching damage is :

http://wotlk.openwow.com/spell=16828 < `action_param1` (Claw rank 2 - basic ability)
Claw Rank 2, 25 mana, 5 yd range, Instant, Claw the enemy, causing 8 - 12 damage
: Bite Rank 2, 25 mana, 5 yd range, Instant, Bite the enemy, causing 8 - 12 damage.
http://wotlk.openwow.com/spell=17255 < `action_param1` (Bite rank 2 - basic ability)
***
http://wotlk.openwow.com/spell=59881 < `action_param1` (Rake rank 1 - special ability)
Rake rank 1, 20 mana, 5 yd range, Instant, 10 sec cooldown
Rake the target for 1 - 3 bleed damage and an additional 1 damage every 5 seconds.

*Not as easy to find a spell with the same damage description, but if going with the animal's abilities ;*

Furious Howl rank 1, 20 mana, Instant, 40 sec cooldown
Increases melee and ranged attack power by 18 for the wolf and its master for 20 sec.
http://wotlk.openwow.com/spell=24604 < `action_param1` (Furious Howl rank 1 - special ability)
