### ISSUE TITLE
[Dual Spec] Triggered spell bug

### ISSUE THREAD

**Issue by click** [TrinityCore/TrinityCore#806]
commit  2c7ca195d178beca4975
I found 2 bug: Focus magic (mage) and Master of subtlety (rogue)
How to reproduce:

Mage
Spec arcane
- Put focus magig on a party member
- Change spec to fire or frost
  focus magic remain active on your friend increasing his and your crit

Rogue
Spec subtlety
go in stealth (you gain master of subtlety buff)
respec assassination
go in steath
you now have a 20% more damage until death or relog.
##

**Comment by danlapps** [comment]
Anything in here either valid fix or still an issue ?

**Comment by Rushor** [comment]
there are a lot of spells which should be removed /updated on speccchange...

**Comment by Demonid** [comment]
Yep, Warlock Armor, some Rogue Buffs like Overkill (At least some years ago), and some Spells from mages.

**Comment by tkrokli** [comment]
For a complete overview, it could be necessary to find all spells learned from talents on all classes and then see if they can be handled in one PR or if they should be separated. I hope a more generic solution can be found, but the suggested solution only focused on 1 spell/class.

**Comment by Keader** [comment]
Vigilance (Prot Warrior) too
Bug still persist on rev e6afebd1502fcea1f883a7761a62d158f94eb5c2

**Comment by tkrokli** [comment]
Looks like those changes should be worth testing, for those who know the mage or warrior class well.
Do you think it is worth putting those changes into a PR yet, Keader?

**Comment by Keader** [comment]
@tkrokli nop, is a hack i think
those should removed when mage/warrior change build.
This fix remove when spell proc... this is not blizzlike

**Comment by Aokromes** [comment]
@ariel- any idea on this?

**Comment by ariel-** [comment]
These are two different bugs: Vigilance/Focus Magic are single target auras, they should be removed if player doesn't have that spell in Player::ActivateSpec

Master of Subtlety, on the other hand, there is a logical fail in Aura::HandleAuraSpecificMods that is recasting the infinite duration aura when stealth is applied
