### ISSUE TITLE
Blade Tempest (75125)

### ISSUE THREAD

**Issue by Nastrand** [TrinityCore/TrinityCore#8062]
The skill Blade Tempest used by Baltharus the warborn (http://www.wowhead.com/spell=75125) is impossible to dodge or parry, considering it does 8 to 9 k damage every 0.5 sec for 4 secs, it does almost 70k... in 4 secs.

I've been searching in google and guides about this boss and dont mention anything about its impossible to dodge or parry.

Hash: b06e9cfd41e11b8efed8c1e8abb7899b91897b8d
DB: TDB_full_335.49

**Comment by Killyana** [comment]
You cannot dodge or parry this spell.
