### ISSUE TITLE
Twilight Precision dont work

### ISSUE THREAD

**Issue by Nastrand** [TrinityCore/TrinityCore#8063]
The aura Twilight Precision used by Halion in Ruby Sanctum (http://www.wowhead.com/spell=78243) don't work, i've been searching and exist a column that adds the aura, but the problem is the aura does nothing, you can even learn the spell ussing the command .learn 78243 or use the command .aura 78243 and NOTHING happens.

I think is a missing script or something like that.

Hash: b06e9cfd41e11b8efed8c1e8abb7899b91897b8d
DB: TDB_full_335.49

**Comment by Killyana** [comment]
You can test Halion in normal condition and after unaura 78243, you will see a difference on dodge stats.
