### ISSUE TITLE
Boss Text Emotes [%s]

### ISSUE THREAD

**Issue by Expecto** [TrinityCore/TrinityCore#8110]
Does not work Boss Text Emote in Quest http://www.wowhead.com/quest=753

After accepting Quest Text Emote does not work

Screen: http://www.imageup.ru/img296/1074697/wowscrnshot_101712_143326.jpg

Text  (%s gestures to the pitcher of water sitting on the edge of the well.', '16', '0', '100', '0', '0', '0', 'Greatmother Hawkwind)

TDB 11.49 Rev Hash 27f091806a6f52f406837d188dd4171019bfa59b

**Comment by Aokromes** [comment]
A bug related to this was fixed few days ago, can you try on head?

**Comment by Rushor** [comment]
http://pokit.org/get/?90c0b263c5078a5f6930e8b76b0e6a00.jpg

works great on current rev

https://github.com/TrinityCore/TrinityCore/commit/89a7026898af8da7a24486795cbbbf6eb9777693
