### ISSUE TITLE
[4.3.4] PvP Bug

### ISSUE THREAD

**Issue by Remix99** [TrinityCore/TrinityCore#8150]
Branch : 4.3.4
Core Revision : TrinityCore rev. 2012-10-20 00:02:32 +0200 (c40e9e2) (Unix, Release)

Details : When you attack NPCS such as target dummies, damage is working but on players all the damage just keeps saying "Miss" whether its spell damage or melee damage on both it just keeps saying "Miss" .

EDIT : **UPDATE OF ISSUE**  if you equip any item more than level 60 , like if u equip level 70-85 armor/weapons & then someone attacks you it will cause that bug , tested it 5-10 times confirmed 200%  (that means the items with resillence are causing this bug) means resillence is bugged

**Comment by Aokromes** [comment]
This issue is valid on 6.x?

**Comment by Shauren** [comment]
no
