### ISSUE TITLE
[Core/Vehicles] Not working vehicles

### ISSUE THREAD

**Issue by Pitcrawler** [TrinityCore/TrinityCore#8195]
There are some vehicles that cant be mounted. After some research I am quite convinced this is due to their seat flags. All of them that I checked were missing VEHICLE_SEAT_FLAG_CAN_ENTER_OR_EXIT. That were vehicleIds 240, 127 and 90 for example.

From a logical point of view it wouldnt make much sense to have a seat that cant be mounted...
In DBCEnums.h that flag has comment Lua_CanExitVehicle which makes much more sense to me. Maybe core handling must be changed and this flag should make the core decide wether to display the exit button when mounted or not.

Something more I noticed is that those vehicles are all flying and taking you on some kind of tour. So it'd make even more sense to be not able to exit voluntairily... So you wouldnt be able to fall to death when accidentally clicking the exit button.

Hash: ca276292dcce939d65649d434a08796269789901

**Comment by dr-j** [comment]
https://github.com/TrinityCore/TrinityCore/issues/13298

**Comment by StormBytePP** [comment]
Fixed by rev ac2845ee77d0f3e838267ad424fbcf4894040333
