### ISSUE TITLE
[DK] Raise Ally

### ISSUE THREAD

**Issue by click** [TrinityCore/TrinityCore#82]
1.Party up with someone
2.Let him die
3.Cast Raise Ally on him

What is the expected output? What do you see instead?
Dead friendly grouped target is supposed to raise as a kewl and strong 
ghoul for 5 minutes under HIS control. Instead, nothing happens. The skill 
goes in Cooldown, but the target remains dead and nothing really happens.

http://www.wowhead.com/spell=61999
Raises the corpse of a raid or party member to fight by your side.  The 
player will have control over the Ghoul for 5 min.

fix Mangos
https://github.com/rsa/mangos/commit/7cbb2fcb3fc0b51139a2cad557ba2d58e4b5d6df
https://github.com/rsa/scriptdev2/commit/ff1db75e8716b04b7aee8b5da807a84919b43569

for part 2
https://github.com/rsa/mangos/commit/96ec786b4071ce1ce6b9415e07aa5c4facd91b11

for part 3
https://github.com/rsa/mangos/commit/3e89e2633b68e39dae9a174d6c7b93e8373ae305

**Comment by Raydor** [comment]
Still bugged https://github.com/TrinityCore/TrinityCore/commit/8197da743cd5a9a2c4df73e53b9f9dc44cbec1d5
