### ISSUE TITLE
Tortured Skeleton - Shadow Labyrinth

### ISSUE THREAD

**Issue by Failed-** [TrinityCore/TrinityCore#8219]
In Shadow Labyrinth you got the Tortured Skeleton's (http://www.wowhead.com/npc=18797) that lay dormant on the ground and they will get up and attack when someone is getting close. 

There are several packs within the instance, the ones that "play dead" are not standing up when moving in on the group. Instead they will move in while they still lie on the ground.

Rev: f2e92b81a30d

**Comment by Aokromes** [comment]
#14367
