### ISSUE TITLE
Channeled spells crit chance reduction on targets with resilience

### ISSUE THREAD

**Issue by diton** [TrinityCore/TrinityCore#8225]
All channeled spells (mind fly, arcane missiles etc) ignore resilience - crit chance reduction. Each "tick" can be critical strike if spell allow u to crit and u have at last 0.01% crit chance.

Tested on target with 10% resilience rating with mage/priest with 0% crit, 9% crit and 20% crit.
Each test contained at last 500 casts - each time spell crit chance was equal to number of crits from channeled spells in this case 0% then ~9% and ~20%.

With direct spells, melee attack(autoattack) and dots(damage over time) crit chance is reduced correctly - also tested.

Core: TrinityCore/TrinityCore@a664a35

TDB: TDB 335.49+

**Comment by Aokromes** [comment]
So, incorrect report?

**Comment by Killyana** [comment]
Need confirmation as cannot reproduce.

**Comment by Killyana** [comment]
If the issue is still valid explain how to reproduce it.
