### ISSUE TITLE
Arena bug [Fear]

### ISSUE THREAD

**Issue by iconskater** [TrinityCore/TrinityCore#8266]
How to reproduce:  Have 2 players queue for arena, when the queue pops duel each other. Let the priest fear his partner, when he is feared enter arena. The partner who was feared will spawn in the middle of the arena.

Revision: 4e22731467
##

**Comment by Aokromes** [comment]
If this fix is valid, plz open a PR for it.

**Comment by Killyana** [comment]
Cannot reproduce on rev. 41982aa30026
