### ISSUE TITLE
[4.3.4] PvP Flag not working

### ISSUE THREAD

**Issue by Persephone** [TrinityCore/TrinityCore#8326]
It seems as the PVP flag aint working, neither setting config to gameype: 16 does nothing

gurubashi arena does not apply pvp flags and nobody can attack eachother.

SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_PVP_ATTACKABLE);

seems as it doesnt communicate /:
##

**Comment by Aokromes** [comment]
This bug exists on 6.x?

**Comment by Killyana** [comment]
Fixed on 4.3.4 and probably on Master.
