### ISSUE TITLE
[Quest] Imprisoned in the Citadel

### ISSUE THREAD

**Issue by TheMaaster** [TrinityCore/TrinityCore#8331]
I went in to Heroic [Shattered Halls] (http://old.wowhead.com/zone=3714) to go do [Imprisoned in the Citadel] (http://old.wowhead.com/quest=9524)
But i couldn't find [Randy Whizzlesprocket] (http://old.wowhead.com/npc=17288)
(and i wonder if he was there if the rest would work, because it looks like it needs some scripting)

Core revision: Trinity Core 85f5a189decf+ 
Database revision: TDB 335.49

**Comment by msoky** [comment]
close by https://github.com/TrinityCore/TrinityCore/pull/14157?
