### ISSUE TITLE
[3.3.5][6.x][Ice Crown Citadel Boss] The Lich King 25 heroic

### ISSUE THREAD

**Issue by Shadowfang** [TrinityCore/TrinityCore#8335]
Greetings,
There is a problem while facing The Lich King in Ice crown citadel in 25 heroic mode.
In the 3rd phase, The Lich King uses an ability called "Harvest Soul" which pulls the entire raid into the Frostmourne dimension.

While you are inside this dimension you are supposed to dodge the Vile spirits that bomb you from the sky, when a player gets hit and die while in the frostmourne dimension the Lich King will get enrage and will get a huge demage buff to himself.

**Problems:**
- [ ] the Vile spirits throw at you are way too fast and are nearly impossible to dodge which cause you to die and enrage the Lich King and make you wipe almost instantly due to his Enrage buff.
  If it would have working properly the bombs would have been thrown in a speed which is possible to dodge and make that phase possible.
- [ ] wicked spirits aggroing Terenas (npc)
- [ ] There are vile spirits that can't be targeted and other with 0 hp.
  This make this phase impossible to do.

Hash: ba20aa8
TDB: 335.11.47+

http://old.wowhead.com/npc=36597
http://old.wowhead.com/spell=74297
http://old.wowhead.com/spell=70498
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/63819-ice-crown-citadel-boss-the-lich-king-25-heroic?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github).
</bountysource-pl

**Comment by Nikectory** [comment]
Confirmed wicked spirits aggroing Terenas (npc) and bombing too fast, also reporting the presence of some wicked spirits that cannot be targeted during harvest phase in both 10man and 25 man heroic mode https://github.com/TrinityCore/TrinityCore/commit/f4e2fb8f79e5a223506d9e514b7adf18c2198bab

**Comment by Killyana** [comment]
@sirikfoll all this issues are fixed if I'm not wrong.

**Comment by sirikfoll** [comment]
True, if anyone see any of this issues happening again, please open a new issue.
