### ISSUE TITLE
Core/Spells: Cannibalize (Undead)

### ISSUE THREAD

**Issue by Jildor** [TrinityCore/TrinityCore#8354]
Cannibalize: http://www.wowhead.com/spell=20577

When cast Cannibalize on player, if the player has used release spirit, can't cast Cannibalize on dead player.

0a840fc
TDB

**Comment by Rushor** [comment]
issue exists on https://github.com/TrinityCore/TrinityCore/commit/3c4f4356298d974c507fbd4c3fa54c1d4075e091

When cast Cannibalize on player, if the player has used release spirit, can't cast Cannibalize on dead player.

**Comment by Killyana** [comment]
When a player release spirit a corpse is created, if Cannibalize must be used in this corpse the target must updated.

**Comment by Rushor** [comment]
https://www.freakz.ro/forum/FIXED-Multiple-Undead-Cannibalize-vs-released-corpses-t268694.html?blueposts

maybe @Shocker can help us here :)

**Comment by tkrokli** [comment]
https://www.freakz.ro/forum/cine-e-Shocker-asta.html -- nice stats ^_^

**Comment by Keader** [comment]
Nothing news?

**Comment by Aokromes** [comment]
I wonder if it's related to unable to use engineering tools to resurrect people.

**Comment by Rushor** [comment]
spellcondition corpse for this spell is missing here (the spellscript can handle this)

**Comment by Killyana** [comment]
@Langerz82 Your fix works, but you pr it to be discussed.

**Comment by ariel-** [comment]
The SpellInfo correction is unnecessary, the dummy spell triggering this one already has the attribute. This must be fixed on core side at grid searcher logic for spells

**Comment by Langerz82** [comment]
@ariel I removed the spell info fix. It was a code remnant of me trying to fix the issue.

**Comment by Riztazz** [comment]
It probably fails due to this
https://github.com/TrinityCore/TrinityCore/blob/master/src/server/game/Spells/Spell.cpp#L7679

Owner might be anywhere really

**Comment by CraftedRO** [comment]
8ad43140305e8aacd8c27f891d5f701a1452ca61 In my tests this seems no longer valid: https://youtu.be/PmL9BIwMxB4
