### ISSUE TITLE
[Spell / Visual / Cooldown] The spell prowl doesn't display cooldown

### ISSUE THREAD

**Issue by MrSmite** [TrinityCore/TrinityCore#8368]
__Rev:__ https://github.com/TrinityCore/TrinityCore/commit/ced723a53a04b08cc7cafd4dda913108f138c31b

__Details:__

The spell Prowl (24450) used by Hunter cats does not display the 10s cooldown when cancelled. It does however keep saying "that ability isn't ready yet" until the 10 seconds is up so the cooldown is applied, there's just no visual.

**Comment by tkrokli** [comment]
TrinityCore rev. f020f6f51974 2015-05-16 11:52:01 +0100 (3.3.5 branch) (Win64, Release)
Confirmed still present. The prowl button behaves exactly as explained above.

**Comment by Killyana** [comment]
Can you check after Core/Spells: Improved spell category cooldown handling  ?

**Comment by tkrokli** [comment]
OK, I will test and report back. :)

**Comment by Killyana** [comment]
This was fixed if I'm not wrong.

**Comment by tkrokli** [comment]
TrinityCore rev. 02d7df6aa435 2016-04-20 19:44:57 +0200 (3.3.5 branch) (Win64, Release) / TDB 335.61

Tested the Prowl pet bar button and it works as intended with 10 sec. cooldown displaying correcly.
This issue can be closed. As Killyana said, it must have been fixed earlier, but I don't know when.
