### ISSUE TITLE
[Quest] The Halls Of Reflection

### ISSUE THREAD

**Issue by click** [TrinityCore/TrinityCore#838]
Link: http://old.wowhead.com/quest=24561

If you have this quest, when you enter in The Halls Of Reflection and go near Frostmourne, this npc must spawn: http://old.wowhead.com/npc=37158. When you kill it, you can loot the quest item required for the quest. At the moment, nothing happens if you go near Frostmourne when you have the quest. Also the npc has no skin. Maybe it can be useful knowing that if you have the quest, you also have this aura: http://old.wowhead.com/spell=70013. Uther the Lightbringer also attacks the npc, I don0t know if this fact can interfere with the credit and the loot.

Rev: http://www.trinitycore.org/t/trinitycore/changeset/de624adffc7352bf2bfa964990e285c16015cf65

**Comment by Frondor** [comment]
Confirmed. It brokes the chain.

**Comment by Frondor** [comment]
@Aokromes any possibility to add this to any 3.3.5a branch milestone? This is broking one of the most important end-game quest chains

**Comment by Aokromes** [comment]
You think adding it to any milestone will make someone work on it faster?
Also, sunwell quest is broken to and that's way more difficult to fix.

**Comment by Frondor** [comment]
I was no worried about the time, but the importance of this quest chain...
Couldn't test the following quests because couldn't complete this (I'm testing everything as a normal user, too lazy to create GM account yet)

**Comment by MitchesD** [comment]
I have already scripted that quest, but I am not satisfied with some parts of code and I don't have enough time for a few weeks. But I am going to finish it, because its so cool quest

**Comment by Rushor** [comment]
https://bitbucket.org/Rushor/publicscripts/commits/77372d357fab3bc2aa2d8b4b36283390694fd241
for the sunwellstuff, much costum, less blizzlike, but nevertheless a script :D

**Comment by Frondor** [comment]
@Rushor I don't know much about scripting but I think that your script is really approximated to the retail one. I think it's missing the phasing, few speeches (http://www.wowwiki.com/Quest:The_Purification_of_Quel%27Delar) and some NPC's (guards) only.
I love the spanish line "Damas y caballeros..." ♥ I can translate speech lines to spanish if needed.
I'll leave a video taken from retail of that quest and I'm write a better feedback on said quest report: https://www.youtube.com/watch?v=EK4_FPS_SxY

**Comment by MitchesD** [comment]
https://github.com/TrinityCore/TrinityCore/commit/71b53601a3c5701600b3585709e190525e0ae818

**Comment by Frytiks** [comment]
@mitchesd quest again not works, when u hit quel'delar it's just evading

**Comment by Killyana** [comment]
Cannot reproduce on rev. 5b5c093 http://imgur.com/hIpfA0O

**Comment by MitchesD** [comment]
@Frytiks there were no changes in this quest, so it looks like your fail or custom changes or something, there can be only problem with visual of flying, but nothing about evading.

**Comment by Frytiks** [comment]
For me, when i attack, its just say Entering Combat and Leaving combat

**Comment by Frytiks** [comment]
It was working for me fine, until implementation of MoveCirclePath
