### ISSUE TITLE
Core/Calendar: Date of events

### ISSUE THREAD

**Issue by lvalladares** [TrinityCore/TrinityCore#8390]
When you create any event in the calendar, at moment of creation you set the time for the event (Example 14:00) but when you press "create" the event is created at 13:00, one hour less

I tryed seven times with 5 testers and the result is the same, i cant find any refference in web that says this is Blizzlike, so i consider this a bug and reported it

Hash: b0b3c9ffbe84d3c86d6314419d695a44a24ee0dc
DB: TDB_full_335.49
##

**Comment by Golrag** [comment]
While working on calendar packets I noticed this bug too.
Tried this:
```diff
diff --git a/src/server/shared/Packets/ByteBuffer.h b/src/server/shared/Packets/ByteBuffer.h
index 0fa500c..fff1ea6 100644
--- a/src/server/shared/Packets/ByteBuffer.h
+++ b/src/server/shared/Packets/ByteBuffer.h
@@ -562,7 +562,7 @@ class ByteBuffer
             lt.tm_mon = (packedDate >> 20) & 0xF;
             lt.tm_year = ((packedDate >> 24) & 0x1F) + 100;
 
-            return uint32(mktime(&lt));
+            return uint32(_mkgmtime(&lt));
         }
 
         ByteBuffer& ReadPackedTime(uint32& time)
@@ -681,8 +681,8 @@ class ByteBuffer
         void AppendPackedTime(time_t time)
         {
             tm lt;
-            localtime_r(&time, &lt);
-            append<uint32>((lt.tm_year - 100) << 24 | lt.tm_mon  << 20 | (lt.tm_mday - 1) << 14 | lt.tm_wday << 11 | lt.tm_hour << 6 | lt.tm_min);
+            gmtime_s(&lt, &time);
+            append<uint32>((lt.tm_year - 100) << 24 | lt.tm_mon << 20 | (lt.tm_mday - 1) << 14 | lt.tm_wday << 11 | lt.tm_hour << 6 | lt.tm_min);
         }
 
         void put(size_t pos, const uint8 *src, size_t cnt)
```
created event at 12 AM and it didn't change to 1AM ! Not sure if this is a proper way to fix it and not sure if it breaks anything else :s

**Comment by DDuarte** [comment]
_mkgmtime is not available on Linux

**Comment by jackpoz** [comment]
@Golrag did you test that code with clients on different timezones ?

**Comment by Golrag** [comment]
@jackpoz not yet

**Comment by jackpoz** [comment]
after https://github.com/TrinityCore/TrinityCore/commit/23e4472d14bbf24722277d9d49c62ea7e39821c7 creating a Calendar Event at 9 pm with both client and server on CEST timezone actually sets the time to 10 pm. reverting https://github.com/TrinityCore/TrinityCore/commit/23e4472d14bbf24722277d9d49c62ea7e39821c7 creates the event correctly at 9 pm

**Comment by jackpoz** [comment]
Still broken events even localhost server&client

**Comment by jackpoz** [comment]
Still broken and worse than how it was initially

**Comment by jackpoz** [comment]
Some work on this at https://github.com/jackpoz/TrinityCore/commits/3.3.5-timezone

It's not just the creation of an event that has to support timezone, every calendar related action in any CRUD operation. Add to that Guild events while at it.
