### ISSUE TITLE
Bug channels basics + client languaje.

### ISSUE THREAD

**Issue by milotic** [TrinityCore/TrinityCore#8411]
This bug is present only in channels

1. General
2. Trade
3. localDefense
4. looking guild

The channels are separated according to client languaje

Example:

All players have same faction

Player1 have MX client
Player2 have US client
Player3 have ES client
Player4 have MX client
Player5 have GB client
Player6 have MX client
Player7 have RU client
Player8 have MX client
Player9 have MX client
Player10 have ES client

Example 1: Players 1-9 are in dalaran and player 10 go to dalaran and chat show: change chanel: gerenal dalaran, join chanel trade dalaran change chanel local defense.
But player only see in the chanels to player 3 

rev: https://github.com/TrinityCore/TrinityCore/commit/b1ec4b61acd0cd8f19ec96f3452c99fd45ad9362

**Comment by kolyanok** [comment]
Still bugged?

**Comment by Aokromes** [comment]
I think this commit fixes this issue:

https://github.com/Exodius/MistCore/commit/864f923ddea822807f3e47834365c76758fd328b

**Comment by tkrokli** [comment]
Looks quite interesting, but it seems that source still uses ACE. I presume it needs to be adapted for TC, as well as having all the missing translations added in that new table `locales_chat_channel`.

**Comment by kolyanok** [comment]
Aokromes, no. It's my commit for chat channels names localization. Localization is works now, but this bug is still alive on my MistCore fork... I have try to fix it in my free time (and on TC too)...

**Comment by Aokromes** [comment]
This bug is still valid?

**Comment by ariel-** [comment]
Yes
