### ISSUE TITLE
[Skill Bug]Fan of  Knives

### ISSUE THREAD

**Issue by Pumpush** [TrinityCore/TrinityCore#8431]
Hello TC

the skill fan of knives kill the loser in a duel if the weapons has instant poison.
How to reproduce the problem:
1.Make a rogue
2.put the instant poison.
3.duel and kill the target with the skill 

how should it work:
the loser should not die

instant poison-http://www.wowhead.com/item=43230
fan of knives-http://www.wowhead.com/spell=51723

hash: d3c9029
##

**Comment by Keader** [comment]
#19852
