### ISSUE TITLE
Druid restoration tier 10 bugged

### ISSUE THREAD

**Issue by Vn123** [TrinityCore/TrinityCore#8436]
Hi Tc,

bonus of 2 part set druid restoration tier 10 doesn't work it didn't gives the Wild Growth spell reduces 30% less over time it stay the same time.

Wowhead link: http://www.wowhead.com/item=51138#.

Tbd:335.11.47+

Hash:d3c9029

**Comment by Killyana** [comment]
Compare the last hot with and without the T10 bonus (with the same spell power) and you will see there's 30% difference example 121 for the last hot with the bonus and 85 without, so it works correctly.
rev. 5b5c0938da0f

**Comment by tkrokli** [comment]
Good job closing issues, @Killyana ! :+1:
The number of open issues is almost down to 10% of the number of closed ones!  :smiley_cat:
