### ISSUE TITLE
Bugged Quest - Unholy Infusion

### ISSUE THREAD

**Issue by Vn123** [TrinityCore/TrinityCore#8437]
Hi Tc,

Quest link: http://www.wowhead.com/quest=24749

the problem on this quest is the last part when you get the buff from Shadow Infusion after get off from the  Abomination and start kill the boss the buff still on you for the next 6minutes but when you kill the proffesr with the quest buff and weapon on you it just dont complete the quest.

here some video how it should work : http://www.youtube.com/watch?v=gklmHtHK3F8

Tbd:335.11.47+

Hash: d3c9029

**Comment by Rushor** [comment]
i'm currently using this https://gist.github.com/Rushor/47824c2d88aa7984eb92

no fix at all, because it is a dirty hack :/

**Comment by Killyana** [comment]
Tested on rev. 5b5c0938da0f I get the credit and I complete the quest.

**Comment by Killyana** [comment]
If there's an issue explain how to reproduce it.
