### ISSUE TITLE
[Battleground] Supporting auras in BG and invisibility

### ISSUE THREAD

**Issue by Vosicka** [TrinityCore/TrinityCore#8438]
There is a problem with supporting buffs/auras like berserk, speed of heal in battlegrounds:

When you cross through them in invisibility (mage) or stealth (rogue) - you take the aura but it is not in your buffs icon on character and buff is not applied and still the object disappears.

SPEED - Object ID: 179871 + Spell ID: 23451
FOOD/REGEN - Object ID: 179904  + Spell ID: 23493
BERSERK - Object ID: 179905 + Spell ID: 23505

Problem seems to be in function "void Battleground::HandleTriggerBuff(uint64 go_guid)" in Battleground.cpp which seems to not handle invisible players correctly. Thank you for a fix.

Linux 64bit based server
Trinitycore: https://github.com/TrinityCore/TrinityCore/commit/c44c6248ecc52304a76ed5f44575fbf4e90abc80
TDB: TDB_full_335.49_2012_09_16 + updates
Addons/Patches: None - clean core
##

**Comment by ariel-** [comment]
Fixed by b3a4815067d154fb35da87aa8e7365995d6f65f5
