### ISSUE TITLE
[4.3.4] Buffs like Hot strike, Brain freeze, backlash

### ISSUE THREAD

**Issue by saqirmdev** [TrinityCore/TrinityCore#8462]
If you have Hot strike (buff) you can cast pyro (Instant) but when you cast Pyro, you have still buff  and you can cast pyro more times

rev: https://github.com/TrinityCore/TrinityCore/commit/7e69409e65be4da9176ef706f51bcf7ac072e393
##

**Comment by Keader** [comment]
4.x is not supported anymore xD
