### ISSUE TITLE
[Bug]The Eye - final encounter's mini-bosses are respawning

### ISSUE THREAD

**Issue by Crysicle** [TrinityCore/TrinityCore#8479]
Bug:
After the encounter with Kael'thas in The Eye is finished, the 4 mini-bosses that are included in the encounter respawn after some time. This should not be the case, they should only respawn if the raid which was trying to Kael'thas has wiped.

Links:
Kael'thas Sunstrider - http://www.wowhead.com/npc=19622

  Mini bosses:
   -Lord Sanguinar - http://www.wowhead.com/npc=20060
   -Thaladred the Darkener - http://www.wowhead.com/npc=20064
   -Master Engineer Telonicus - http://www.wowhead.com/npc=20063
   -Grand Astromancer Capernian - http://www.wowhead.com/npc=20062

SS after the encounter - http://oi50.tinypic.com/2r6h5eg.jpg

Core revision: Trinity Core 4dffccb93ff0+
Database revision: TDB 335.49
Addons: Anticheat1, AHbot

**Comment by Killyana** [comment]
``` sql
DELETE FROM `linked_respawn` WHERE `guid`=7987;
INSERT INTO `linked_respawn` (`guid`, `linkedGuid`) VALUES
(7987,12570),
(7987,12567),
(7987,12568),
(7987,12569);

**Comment by Nyeriah** [comment]
Actually the issue I find with this is that they don't actually die after Kael'thas is taken down which leaves the raid in combat.
