### ISSUE TITLE
SOTA Vehicle's aura bug

### ISSUE THREAD

**Issue by yashirotcm** [TrinityCore/TrinityCore#8491]
Core: d13ca54ecc991a7312f1584bdfdec32f8e6a0ee3
Db : TDB_full_335.49_2012_09_16

As most of us probably now, whenever you enter a SOTA Demolisher as a passenger you overall stats are boosted, if you manually leave the BG while on a passenger seat this boost is not removed and you retain it until killed on until .unaura all is applied.

Can anyone else confirm?
##

**Comment by Keader** [comment]
It is rare but still occurs. 41e62739942907e1efa2a4656b4717c885873f1d

**Comment by Aokromes** [comment]
Yeah, tried to reproduce, but unable, but got reports of still bugged.

**Comment by Killyana** [comment]
The aura https://woehead.way-of-elendil.fr/?spell=65636 is now removed correctly from the player after dismount and stats are recalculate properly after that.
