### ISSUE TITLE
Officer Van Rossem should take you to flying ship

### ISSUE THREAD

**Issue by click** [TrinityCore/TrinityCore#850]
Officer Van Rossem (Alliance side), gives you a quest for starting in IceCrown zone. But, his gossip option does not do anything, so I assume it is not (well) scripted.

Maybe the horde npc is having same issues.

**Comment by danlapps** [comment]
Is this still an issue ? And if so, on what branch since no rev or info were posted in original post ?

**Comment by Killyana** [comment]
Duplicate https://github.com/TrinityCore/TrinityCore/issues/10422
