### ISSUE TITLE
[CREATURE] All Orgrimmar NPCs ankle-deep in ground (15$ bounty)

### ISSUE THREAD

**Issue by baric** [TrinityCore/TrinityCore#8500]
```sql
--
-- elevate Ogrimmar NPCs out of the ground. This can't be only on my TDB
-- THIS SHOULD ONLY EXECUTE ONE TIME as it increases position_z
--
UPDATE creature SET position_z=position_z+0.15 WHERE guid IN (3371, 3374, 3375, 3376, 3377, 3378, 3379, 3380, 3394, 4770, 4771, 6491, 6501, 6502, 6503, 6506, 6549, 6551, 6552, 6553, 6554, 6555, 6556, 7393, 7394, 7396, 10466, 54395, 88227);
UPDATE creature SET position_z=position_z+0.15 WHERE guid IN (3371, 3374, 3375, 3376, 3377, 3378, 3379, 3380, 3394, 4770, 4771, 6491, 6501, 6502, 6503, 6506, 6549, 6551, 6552, 6553, 6554, 6555, 6556, 7393, 7394, 7396, 88227);
UPDATE creature SET position_z=position_z+0.15 WHERE guid IN (3372, 3373, 3387, 3395, 3418, 4663, 4664, 4665, 6548, 6550, 6557, 6567, 7395);
UPDATE creature SET position_z=position_z+0.15 WHERE guid IN (8521, 8524, 6561, 10299, 3349, 10463, 11790, 3476, 6597, 3472, 3615, 3473, 3613, 3648, 3474, 3471, 3422, 3646);
UPDATE creature SET position_z=position_z+0.15 WHERE guid IN (10347, 3475, 3382, 7950, 1722, 208201, 208202, 7399, 3349, 3384, 10298, 10469);
UPDATE creature SET position_z=position_z+0.30 WHERE guid IN (6611, 125681, 125682, 125683, 125685, 125686, 125687, 10464, 11789);
UPDATE creature SET position_z=position_z+0.15 WHERE guid IN (7948, 6602, 4660, 6563, 7398, 11791, 7442, 6504, 6600, 7943, 4657, 6601, 11796, 4659, 7949, 8530, 4656);
UPDATE creature SET position_z=position_z+0.15 WHERE guid IN (4661, 12325, 709, 708, 710, 706, 711, 707, 10350, 6599, 6605, 4652, 703, 10348, 4655, 6598, 4653, 4769, 6603, 4658, 8528, 7417, 4785, 6500, 10450, 8526, 6565, 10351);
UPDATE creature SET position_z=position_z+0.15 WHERE guid IN (6560, 8522, 3476, 11792, 6564);
UPDATE creature SET position_z=position_z+0.15 WHERE guid IN (6621, 6625, 6623, 4680, 6629, 3421, 7481, 6628, 6631, 4684, 4685, 3467, 34033, 4678, 34045);
UPDATE creature SET position_z=position_z+0.15 WHERE guid IN (8525, 7416, 10462, 6630, 8529, 4666, 4667, 7415);
UPDATE creature SET position_z=position_z+0.15 WHERE guid IN (4679, 6626, 7479, 4687, 6624, 4681, 6566, 11793, 4767, 4766, 7478, 4686, 6622, 4682);
UPDATE creature SET position_z=position_z+0.15 WHERE guid IN (6604, 4654, 3477, 3560, 3571);

UPDATE creature SET position_z=position_z+0.15 WHERE guid IN (10468, 3388, 7451, 4728, 6558, 7971, 6610, 4762, 7443, 202481, 4671, 4668, 7946, 7968, 4672, 7969, 4676, 3426, 3468, 7970, 3430);
UPDATE creature SET position_z=position_z+0.15 WHERE guid IN (3429, 3428, 7463, 3470, 4669, 3469, 4670, 7448, 7973, 7453, 6612, 7446, 4675, 7444, 6613, 4673, 6497, 6492, 6493, 6512, 6516);
UPDATE creature SET position_z=position_z+0.15 WHERE guid IN (10297, 10353, 6608, 7447, 6620, 7449, 7972, 6606);
UPDATE waypoint_data SET position_z=position_z+0.15 WHERE id IN (47600, 104700, 74210, 34660, 33860, 85270, 64960, 104670, 65620, 64940, 33490);
UPDATE waypoint_data SET position_z=position_z+0.15 WHERE id IN (74210, 34660);
```

**Comment by Ajaxhore** [comment]
Confirming that this problem still exist in clean rev. 194fda8a4ed47d968fc3d436ac9b7c8f436eb5b2
2. marts 2015.
Sry for double posting known problem.

**Comment by tkrokli** [comment]
> **[baric](https://github.com/baric)** commented on 29 Nov 2012:
[...] Maybe the ground level on the map is too high?

Anyone got an answer that question, or even have a good educated guess about it? Also: to progress on this issue; is it necessary to set the Z position of the NPCs explicit in the DB, or can an updated variant of the suggested SQL from @baric be used? :smirk_cat:

Off-Topic: the OP has not been active here on github since 2012.

**Comment by baric** [comment]
I'm working on other projects now. Glad I could contribute in some small way to Trinity!

**Comment by Ajaxhore** [comment]
Theres a 15$ bounty on this problem:
https://www.bountysource.com/issues/63631-creature-all-orgrimmar-npcs-ankle-deep-in-ground
This has been annoying me for a loooong time now, would love to see it fixed.
Its the first thing one notices when entering Orgrimmar.
Cords might be "Blizzlike" but that doesent change the fact that NPC's are burried ankle deep, aka not Blizzlike.

**Comment by Aokromes** [comment]
The problem here is to check every afected mob and compare with sniffs. Also, some retail screenshots shows for example thrall afected by that bug.
http://www.wowhead.com/npc=4949/thrall#screenshots:id=181152

**Comment by Ajaxhore** [comment]
Yeah, but i think we can agree that it looks terrible, and its not meant to be like this.
Even if it was on retail, it was not something Blizzard would have done on purpose.

**Comment by baric** [comment]
Why is there a bounty on this problem? I noticed it, fixed it and provided the SQL updates in the OP.

TC didn't want to make it official because it didn't match the official sniffs, but the SQL code to fix it is right up there in the original post.

**Comment by tkrokli** [comment]
I presume that the TC view is based on the fact that Blizzard managed to muck this up themselves in 3.3.5.

**Comment by baric** [comment]
Blizzard is starting on what, 7.x now? Who at TC is being the gatekeeper on retaining what is an obvious bug in the original game from 4 releases ago.

**Comment by Killyana** [comment]
When you sniffs the spawns you can get different coords, the difference doesn't matter on x or y axis, but for z axis you can get this kind of issue, here a sniffed position for npc=3359, the actual z=39.351 in DBTC and z=39.57792 in this sniff:
```
[5] GUID: Full: 0xF130000D1F001AEB Type: Creature Entry: 3359 Low: 6891
[5] Object Type: Unit (3)
[5] Update Flags: Living, StationaryObject (96)
[5] Movement Flags: None (0)
[5] Extra Movement Flags: None (0)
[5] Time: 1424496295
[5] Position: X: 1878.641 Y: -4708.125 Z: 39.57792
[5] Orientation: 0.5235988

**Comment by Ajaxhore** [comment]
@baric 
The update you provided is nice but not complete, there are many NPC's in "The Cleft of Shadow" and "Valley of Honor" who are still burried ankle deep. There are proberbly more other places.
I put this bounty up because I would like to see a beautiful Orgrimmar, with no burried NPC's. And I would like to see this in the core build, and not something that has to be applied afterwards.

**Comment by Ajaxhore** [comment]
Will this stay as it is, cause Blizzard made a mistake on live servers. Or is there a chance it will be fixed permanently?
If there is a chance, can it get a "bounty" label?

**Comment by Killyana** [comment]
There's some npcs that still buried ankle deep, If someone update all affected npcs on orgimmar I will push the fix.

**Comment by DDuarte** [comment]
A [bounty](https://www.bountysource.com/issues/63631-creature-all-orgrimmar-npcs-ankle-deep-in-ground) ($15) has just been posted on this issue by Ajaxhore.

P.S These messages and labelling used to be automatically, I'm not sure what's broken.

**Comment by Saben65** [comment]
255 creatures in total (not the entirety of Orgrimmar, some appeared fine before this)
```SQL
UPDATE `creature` SET `position_z`=position_z+0.15 WHERE `guid` IN (10351,6565,3390,3387,8526,10450,6604,4654,6602,4660,6563,7398,11791,7442,6601,11796,4659,7949,4659,8530,4656,709,708,706,710,4661,707,711,10350,4652,6605,6599,7417,8528,6603,4658,4769,703,91595,6500,10348,4685,4684,6631,3467,34033,7480,34045,4678,4679,6626,7479,4687,6624,4681,702,4766,4767,6630,7478,4686,6622,4682,4680,6629,6623,3421,7481,6628,8529,11793,6566,7415,7420,11794,3452,6596,3461,3456,3419,3457,3455,3460,3389,6458,34037,3415,3451,7942,6593,6594,3370,6595,3454,3458,4662,3420,6561,6600,7943,125694,10463,11790,3648,3616,3474,3471,3422,3646,3472,3473,3615,6597,3475,3382,7950,1722,7399,3384,10469,10298,8521,91610,91593,91608,91609,91611,91615,7395,6548,3373,3395,4663,4664,3418,4665,6550,3372,3371,6555,6491,6553,3375,4771,3379,3376,3380,7393,3374,6506,7394,7396,6501,6503,6502,6556,3378,6551,3394,6552,6549,6560,8522,6564,11792,4666,4667,10462,7416,8525,3388,10468,7451,4728,6558,7443,4762,6610,7971,7946,7968,4672,7969,3426,4676,3468,3430,3429,7970,3428,7463,3470,4669,3469,7973,7448,4670,7446,4675,6609,7444,6613,6612,7453,10297,10353,6608,7447,6618,6614,6615,6616,6619,6617,4677,6606,6620,7972,7449,6607,4668,6516,4673,4674,6497,6492,3459,6493,12325);
UPDATE `creature` SET `position_z`=position_z+0.25 WHERE `guid` IN (6559,10352,8524,125681,125682,125686,125683,125685,125687,4770,6557,10464,6611,202481,6498,4671,3383,7948,3385,6567,54395,10466,4785,4655,6598,4653,11789);
```
The ones set to +.25 were "problem" ones, that the +.15 height didn't fix (the Darkmoon Barker for instance). It should be noted, that if a female orc guard has a leg clipping issue and her GUID is in here, then there is nothing more that can be done. There are female grunts In areas such as the cleft of shadow who have their left leg clipping, but that is because the lowest Z point that seems to be calculated is the right foot. So if the ground under their right foot is lower than their left foot, the left foot will clip. I'm thinking it is because of how small their feet are, and how spread apart they are that makes it so noticeable.

I didn't add the patrolling mobs, as I didn't notice any serious issues with them.

**Comment by Kittnz** [comment]
Indeed thats not the issue ;)

**Comment by Kittnz** [comment]
Actually, i think @Aokromes told me this on IRC, we need to check the sniffs to get the actually real spawn coordinates, adding position_z is just a hack.
