### ISSUE TITLE
[4.3.4] Gain Spell power

### ISSUE THREAD

**Issue by saqirmdev** [TrinityCore/TrinityCore#8520]
Spells Like Fel armor, Totemic Wrath, Trinkets, Blood Fury.. Dont Gain to caster Spell Power.. its Critical

If you have active Fel armor, Totemic Wrath... You dont gain Spellpower 

rev: https://github.com/TrinityCore/TrinityCore/commit/f4602811d5553c2a38e7e986429847611df7e78e

**Comment by Aokromes** [comment]
This bug still exists on 6.x?

**Comment by Shauren** [comment]
no
