### ISSUE TITLE
[Bug] Hunter Pet

### ISSUE THREAD

**Issue by PyromancerWoW** [TrinityCore/TrinityCore#8549]
Hello.

The problem is that if a hunter sends his pet to kill an NPC (creature, animal and so on), and the player doesn't deal any damage to that NPC (100% of the damage to the NPC is dealt by the pet), then the player can't get any drop from the NPC. However, the player do get the experience from the kill.

Thank you.

Hash: a7d8a65 | Tdb: 335.49
##

**Comment by Killyana** [comment]
Players doesn't get XP or loot for the mob if the pet deals 100% of damage.
rev. 0725f608a
