### ISSUE TITLE
Master of Elixirs Quest

### ISSUE THREAD

**Issue by Vn123** [TrinityCore/TrinityCore#8551]
Hi Tc.

this quest http://www.wowhead.com/quest=10902/master-of-elixirs appear to get into bug only in the second time when you want rise again your alchemy profession,when you do it in the second time you cant talk to Lorokeem and complete the quest.

Tbd:335.11.47+

Hash: a7d8a65
##

**Comment by Killyana** [comment]
Fixed by https://github.com/TrinityCore/TrinityCore/pull/20672
