### ISSUE TITLE
Diseased Timber Wolf aggro issues

### ISSUE THREAD

**Issue by czoesq** [TrinityCore/TrinityCore#8561]
This neutral creature (in Human starting area) will sometimes attack the player when the player has selected to auto-attack the creature, is out of melee swing range, but is within the level appropriate hostile aggro radius. That is: sometimes when the player is ~10 yards from the creature and selects auto-attack, the creature will run up and attack the player. 

It happened on a majority of spawns, but not all of them.

**Comment by Killyana** [comment]
Seems fixed.
