### ISSUE TITLE
[Core/Spells] Vehicle spell bars - conditions breaks don't get updated

### ISSUE THREAD

**Issue by angelovopsan** [TrinityCore/TrinityCore#8566]
What I mean by this? -> Have a npc vehicle cast smth that is limited by explicit condition for another entry. What will happen is the spell will remain lighed in yellow as if casted, this is not game breaking, but is not blizzlike (not breaking next casts). Spells should update their status at these cases, all ideas about the problem are greatly appreciated, if noone will fix that, don't have time too look it now, but maybe will do these days.

P.S.: Stil have no idea where to check, CheckCast seems to not be the place.

TDB: 11.49
OS: XP
Hash: c5a38da394a1907858a0fb7e5bd218d8224f1299

**Comment by killradio** [comment]
@joschiwald this issue still persists, tested with vehicle NPC:35905 (King Greymane's Horse) and SPELL:68219 (Rescue Krennan). If casted from vehicle - no msg and button become highlighted. Spell still working, but no cooldown animation or error msgs.

**Comment by Killyana** [comment]
@malcrom did you encounter this issue when scripting https://www.wowhead.com/quest=14293/save-krennan-aranas ?

**Comment by matanshukry** [comment]
Is this still relevant?

I did:
1. `.npc add temp 33060` (spawns Salvaged Siege Engine)
2. Get in it and start moving forward and using the abilities

Spells doesn't remain lighted in yellow and in general seems to be casting correctly.

**Comment by offl** [comment]
Maybe can occur only with the quest above?

**Comment by matanshukry** [comment]
Not even sure how to test it. I tried to summon npc 35905, but you can't "enter" it.
tried to use spell 68219 , but it says you're not close enough to the npc.
Tried to summon the relevant npc, it still said it.

I'm assuming the creature data and the quest isn't scripted, but that still makes the bug invalid?

**Comment by offl** [comment]
https://github.com/TrinityCore/TrinityCore/issues/8566#issuecomment-500777728
I meant by completing the quest normally without spawning something by commands

**Comment by matanshukry** [comment]
I just verified it by creating a new worgen character, and the npcs for the quests aren't there. Only the very first initial quest can be completed, so there isn't any way to test this without spawning things by commands

**Comment by offl** [comment]
> Have a npc vehicle cast smth that is limited by explicit condition for another entry.

> .npc add temp 33060 (spawns Salvaged Siege Engine)

Its spells don't have conditions in DB

**Comment by matanshukry** [comment]
Tested:

1. Added condition for `Steam Rush` spell:
```sql
DELETE FROM conditions where SourceTypeOrReferenceId=17 AND SourceEntry=62346;
insert into conditions (SourceTypeOrReferenceId, SourceEntry, ConditionTypeOrReference, ConditionValue1) VALUES
(17, 62346, 22 /* CONDITION_MAPID */, 0 /* Eastern Kingdoms */);
```

2. `.tele stormwind`, run above commands to add npc 33060 and cast Steam Rush - works great.
3. get out of vehicle
4. `.tele darkshore`, run above commands to add npc 33060 an cast Steam Rush - nothing happens.


3-4th steps are just there to verify the conditions is working as intended.
Step 2 actually verifies casting a spell inside a vehicle with condition works as intended.

**Comment by offl** [comment]
Thanks
