### ISSUE TITLE
[ICC] zone buff.

### ISSUE THREAD

**Issue by L30m4nc3r** [TrinityCore/TrinityCore#8576]
Hi.

Do not hangs zone buff to ICC.
http://www.wowhead.com/spell=73828
http://www.wowhead.com/spell=73822
Buff can be obtained, or off.
He does not hang at the entrance to the dungeon.

http://s018.radikal.ru/i523/1212/9f/13cde3894071.jpg
http://s020.radikal.ru/i702/1212/a8/92e23228f445.jpg
http://s55.radikal.ru/i148/1212/29/62ed187bc1d3.jpg
http://s47.radikal.ru/i116/1212/7c/f62ffd9ddae2.jpg

http://wow.joystiq.com/2010/03/05/ready-check-to-warsong-or-not-to-warsong/#continued

sry my bad english.

Revision: https://github.com/TrinityCore/TrinityCore/commit/2dc72ec7c85790c5f9bb0e0cbf408de1b6260ff2
DB: TDB_full_335.49_2012_09_16.rar 
issue #7940
##

**Comment by sirikfoll** [comment]
Issue about the buff on pets is #7940;

About this ticket, the problem persists on 31b1da4a1485 , players can't choose to do ICC without the buff

**Comment by Keader** [comment]
This buff is handled incorrectly i think.
This is a "spell aura", has some way to "disable" a spell aura if someone talk to a npc?

**Comment by Staleness89** [comment]
There's a fix for this in Sunwell Core's Pet.cpp if any experts want to look at it.

https://github.com/Staleness89/Sunwell/blob/master/src/server/game/Entities/Pet/Pet.cpp#L75

https://github.com/Staleness89/Sunwell/blob/master/src/server/game/Entities/Pet/Pet.cpp#L1170

Also requires a few defines from their PetDefines.h. Works for me, though.

**Comment by Re3os** [comment]
confirm rev https://github.com/TrinityCore/TrinityCore/commit/3a65c706572ea0d0b66b9b79a275f8d230f7991d

**Comment by Laintime** [comment]
Maybe hack this?still baged

**Comment by Killyana** [comment]
Gossips and gossips_options were added to both npcs, what must be done is disabling the buff if a player talk to the npc.

**Comment by Keader** [comment]
94b60ff0ef7ee908e9ab4660f6dce0dcfe3f13e8
