### ISSUE TITLE
[4.3.4][QUEST] Life Savings (14126)

### ISSUE THREAD

**Issue by KalkS** [TrinityCore/TrinityCore#8578]
This quest place an aura on player after completing it.
Player sees everything in dark :S The Aura never expires.
Maybe its a typo error in the database.

www.wowhead.com/quest=14126
##

**Comment by Killyana** [comment]
The spell https://www.wowhead.com/spell=91847/life-savings-quest-complete use to play a movie, it will be scripted properly with the quest.
