### ISSUE TITLE
[4.3.4] [QUEST] Primal Strike (14011)

### ISSUE THREAD

**Issue by KalkS** [TrinityCore/TrinityCore#8579]
[QUEST] Primal Strike (14011) Dosen't meet the requirements.
When shaman does primal strike on the tdummy, the quest doesn't count it.
It wouldn't be completed.

Desc: Speak with Maxx Avalanche and train Primal Strike, then use it 2 times on a Training Dummy.

**Comment by Rushor** [comment]
moved to the todolist from https://github.com/TrinityCore/TrinityCore/issues/15814
