### ISSUE TITLE
Halaa Issue

### ISSUE THREAD

**Issue by daniel1337** [TrinityCore/TrinityCore#8597]
As asked, I want to report this bug which is pretty much annoying and I wish and believe someone can fix it. However, as I said on forums,  the NPCs (guards and vendors) are multiplying by each capture, and then the multipled NPCs do not disappear when opposite faction captures the Halaa. That's when the mess starts to happen, everyone is fighting and there are so many NPCs in it. 

I took the screenshots of  the mentioned situation. 
![WoWScrnShot_120812_110100.jpg](https://f.cloud.github.com/assets/2995213/1720/803edba0-4122-11e2-8ff7-0a3347abbb1d.jpg)
![WoWScrnShot_120812_110128.jpg](https://f.cloud.github.com/assets/2995213/1724/809e22f4-4122-11e2-9b6b-313a1dd16fcf.jpg)
![WoWScrnShot_120812_110137.jpg](https://f.cloud.github.com/assets/2995213/1721/805cbd6e-4122-11e2-9dab-c89169a4cbc5.jpg)
![WoWScrnShot_120812_110323.jpg](https://f.cloud.github.com/assets/2995213/1722/8085199e-4122-11e2-9622-f11d7bfa826b.jpg)
![WoWScrnShot_120812_110344.jpg](https://f.cloud.github.com/assets/2995213/1726/80ba3b9c-4122-11e2-92a5-957294bd8683.jpg)
![WoWScrnShot_120812_110738.jpg](https://f.cloud.github.com/assets/2995213/1725/80aea02a-4122-11e2-9d6d-102f664501e9.jpg)
![WoWScrnShot_120812_110822.jpg](https://f.cloud.github.com/assets/2995213/1723/8091e4da-4122-11e2-9503-e7c45ae262fd.jpg)

**Comment by Treeston** [comment]
Still an issue as of 3f3ff8b36b05

**Comment by joschiwald** [comment]
is halaa present on 6.x like it was in 3.3.5?

**Comment by tkrokli** [comment]
According to Blizzard, it is not present:
http://us.battle.net/wow/en/blog/15091626/warlords-of-draenor-zone-preview-nagrand-8-5-2014

Quote:
**Eric Maloof:** You’ll encounter a lot of new points of interest in this version of Nagrand. There are some things that are no longer there, too—Halaa and Garadar, for example, don’t exist. These were created after Outland became what it did. Highmaul takes up a large portion of the zone, and it houses a Raid instance as well. It’s massive.

**Comment by StormBytePP** [comment]
Not in the "new" nagrand, but the old one still exists :)

**Comment by tkrokli** [comment]
OK, so it depends on which timeline the player is in, if it is Outland or Nagrand in the Draenor timeline.

**Comment by StormBytePP** [comment]
@tkrokli You can always go to the old Outlands ^^, what I was saying is that in the *new* draenor map there is not halaa, but use hearthstone, and go to old one and it's there :)

**Comment by joschiwald** [comment]
try https://github.com/joschiwald/TrinityCore/tree/halaa

**Comment by Aokromes** [comment]
anyone can test https://github.com/TrinityCore/TrinityCore/issues/8597#issuecomment-136161861 ?

**Comment by Treeston** [comment]
TBF, just wait for `dynamic_spawning` to get merged. Once it is, this is really easy to solve.

**Comment by tkrokli** [comment]
There is 1 more issue open regarding Halaa,  **[[3.3.5a][OpenPvP][Halaa] First Spawn of NPCs](13044)** #13044 
Should it be closed as a duplicate?

**Comment by joschiwald** [comment]
@Treeston it isn't an issue of dynamic spawns, it's an issue of shitty opvp code

**Comment by r00ty-tc** [comment]
@joschiwald that's right. Same with Wintergrasp and frankly in terms of creating spawns in c++ code, most BGs.

What @Treeston is saying is that the npc/go group functionality in the dynamic_spawn branch should (and I made it mainly for this reason) allow much easier use of DB NPC/GOs within C++ and SAI scripts.

However, my general thinking is that there's little point doing any work on such scripts using these groups until dynamic_spawns is finalized and committed. Otherwise it's just a commit based on a delta which might well change.
