### ISSUE TITLE
TOC 25 modes have bugs valkyrs name

### ISSUE THREAD

**Issue by milotic** [TrinityCore/TrinityCore#8616]
Hi, in toc 10 work fine but in 25 modes persist old bugs 

http://es.wowhead.com/npc=34497 and http://es.wowhead.com/npc=34496 in 25 modes have wrong name but in 10 modes work fine.

rev: https://github.com/TrinityCore/TrinityCore/commit/7e28938dd0085617e22fbac822f2a1cfe711eb45
##

**Comment by Killyana** [comment]
Cannot reproduce in rev. 12de860b4aef
