### ISSUE TITLE
[ITEM] Meteorite Crystal Trinket

### ISSUE THREAD

**Issue by Earis** [TrinityCore/TrinityCore#8669]
Hello, TC.
The trinket that drops from Algalon at Uldar that fills a place as Best in Slot of few classes and roles
www.wowhead.com/spell=64999

The trinket doesn't work well, it doesn't proc even if the spell cost mana. it sometimes proc when you cast a spell.
seems like there is a chance to trigger but it should be 100%.

What should be done:
When you use it, any spell cast should give you a stack unless it didn't cost any mana. (clear casting, innerfire, free instants etc..)

If anyone here can fix it and confirm a fix ill be thankful.

more information:
http://www.wowhead.com/spell=64999 - Meteoric Inspiration
http://www.wowhead.com/spell=65000 - Meteoric Inspiration Aura

**Comment by digz6666** [comment]
@treak Thanks for the fix :)

**Comment by tkrokli** [comment]
Interesting / funny to see how long it took for this fix to be 1) noticed and confirmed working, 2) labeled as valid fix, 3) re-confiirmed and 4) implemented.
