### ISSUE TITLE
[Bug/ICC] Blood prince encounter.

### ISSUE THREAD

**Issue by PyromancerWoW** [TrinityCore/TrinityCore#8708]
Hello.

The bug is: When raid's group start the encounter, 90% of the time, it teleport all the group to the  Icecrown Citadel Entrance.
It can be happen even when they are about to finish the boss.
and one more problem is that each teleport it wipe for the group.

it happening only on Blood prince

Thank you.

Hash: b9b1465 | Tdb: 335.49

**Comment by Killyana** [comment]
Result of a general issue: https://github.com/TrinityCore/TrinityCore/issues/14120
