### ISSUE TITLE
Fury of frostmourne doesnt kill paladins

### ISSUE THREAD

**Issue by lvalladares** [TrinityCore/TrinityCore#8717]
The skill fury of frostmourne used by the lich king on icc when reachs 5% of his HP doesn't kill tanks paladins because the talent "Ardent Defender" i've been looking youtube guides and as i see, everyone is killed by this skill, so i think is a bug

How to reproduce.

1 Create a paladin and put the talents for the protection tree, need to put the talent ardent defender

2 Do the lich king and wait he reach 5% of hp

3 he cast Fury of frostmourne

What happens:

The ardent defender procs and you "revive" after being hitted by this spells

What should happen:

You should suffer an horrible death :)

Hash: a2832805afb9a8a3434172479c814ca2a729ece1
DB: TDB_full_335.49
##

**Comment by sirikfoll** [comment]
afaik this is blizzlike, there are some comments in Wowhead saying that, like [this](http://www.wowhead.com/spell=72350/fury-of-frostmourne#comments:id=1096079) and [this](http://www.wowhead.com/spell=72350/fury-of-frostmourne#comments:id=2005497)

**Comment by velinath** [comment]
Looks like there's a video [here](https://youtu.be/_-A-B4uh8NU?t=9m30s) from a Prot Paladin POV. According to what I see there, Ardent Defender has not procced yet but the paladin still dies.

**Comment by ariel-** [comment]
Is the issue valid? https://github.com/TrinityCore/TrinityCore/issues/8717#issuecomment-164215812

**Comment by Keader** [comment]
i belive thats not valid :)

**Comment by ariel-** [comment]
Very well. Closing
