### ISSUE TITLE
[Achievement/NPC/FIX] BB King (4437)

### ISSUE THREAD

**Issue by nelegalno** [TrinityCore/TrinityCore#8719]
The player have to pelt the High Tinker Mekkatorque <King of Gnomes> (7937) NPC in order to complete a requirement for the BB King (4437) achievement, unfortunately the NPC's unit_flags is set to IMMUNE_TO_PC which makes it impossible. Can someone check/sniff the value? The other 4 NPC needed for the achievement don't have IMMUNE_TO_PC set.

TDB49 up to 2dc72ec
##

**Comment by Aokromes** [comment]
Anything here can be pushed?

**Comment by tkrokli** [comment]
The only relevant fix suggested is the one from nelegalno in https://github.com/TrinityCore/TrinityCore/issues/8719#issuecomment-11549507 . Compared to the current NPC values in DB for High Tinker Mekkatorque (entry 7937), the suggested changes are listed below:
(based on content in TDB 335.61 + updates up to and including `2016_06_05_12_world.sql`)
```sql
SELECT `entry`,`name`,`subname`,`gossip_menu_id`,`npcflag`,`unit_flags`,`MovementType`,`VerifiedBuild`
 FROM `creature_template` WHERE `entry` = 7937;
```
```
entry  name                     subname         gossip_menu_id  npcflag  unit_flags  MovementType  VerifiedBuild
-----  -----------------------  --------------  --------------  -------  ----------  ------------  -------------
 7937  High Tinker Mekkatorque  King of Gnomes           11390        2         320             0          12340
```
Changing `npcflag` from 2 to 3 seems obvious. He currently has no gossip, only quests like ["The Grand Betrayal" (ID 2929)](http://www.wowhead.com/quest=2929/the-grand-betrayal) and ["A Few Good Gnomes" (ID 25229)](http://www.wowhead.com/quest=25229/a-few-good-gnomes), but should have this greeting gossip:
```sql
SELECT * FROM `gossip_menu` WHERE `entry` = 11390;
```
```
entry  text_id
-----  -------
11390    15863
```
```sql
SELECT `ID`,`text0_0`,`BroadcastTextID0`,`Probability0`,`VerifiedBuild` FROM `npc_text`
 WHERE `ID` = 15863;
```
```
   ID  text0_0                  BroadcastTextID0  Probability0  VerifiedBuild
-----  -----------------------  ----------------  ------------  -------------
15863  Welcome to Tinker Town!             40441             1          12340
```
***
The field `unit_flags` is currently set to 320 (256 + 64)(`UNIT_FLAG_IMMUNE_TO_PC` + `UNIT_FLAG_UNK_6`).

nelegalno's case is that `UNIT_FLAG_IMMUNE_TO_PC` (256) makes the achievement unavailable to players.

trista's first comment says that `unit_flags` = 64 (`UNIT_FLAG_UNK_6`) while Vincent-Michael's sniff shows 80 (64 + 16)(`UNIT_FLAG_UNK_6` + `UNIT_FLAG_RENAME`). Not sure about that "rename" part, but according to trista it could be related to combat of some sort. (Maybe related to the achievement?).
***
`MovementType` : currently set to 0 (Idle; stay in one place). Suggested change: 2 (Waypoint movement). 

This change should only be done when followed up by adding the waypoints in https://github.com/TrinityCore/TrinityCore/issues/8719#issuecomment-11549507 (nelegalno's SQL based on Vincent-Michael's sniff).

**Comment by Aokromes** [comment]
we probably need one sniff made by one horde making achievement.

**Comment by ariel-** [comment]
If sniff says flags = 80 then push them

**Comment by Killyana** [comment]
Fixed long time ago.
