### ISSUE TITLE
[Spell] Shadow's Fate

### ISSUE THREAD

**Issue by Gacko** [TrinityCore/TrinityCore#8723]
Spells:
Shadow's Fate: http://www.wowhead.com/spell=71169
Unholy Infusion Credit: http://www.wowhead.com/spell=71518
Blood Infusiton Credit: http://www.wowhead.com/spell=72934
Frost Infusion Credit: http://www.wowhead.com/spell=72289
Soul Feast: http://www.wowhead.com/spell=71203

Some criterias/improvements/bugs which have to be met/done/fixed:
- When Shadow's Fate triggers, the credit spells should only be casted to players which applied Shadow's Fate to the unit. As many players comment on wowhead it doesnt matter wether you still wear the weapon or not. (All credit spells expect the Soul Feast already have conditions in DBC)
- Linked to the Soul Feast spell a sound should be played.
- Shadow's Fate should only be applied to some NPCs, I think only those giving reputation. So rats, bugs and summons dont count.

Please correct me if you know it better, I read comments for about half an hour now...

**Comment by Killyana** [comment]
The Unholy Infusion gives credit on rev. 5b5c093, I cannot test the blood and frost infusion, if someone can confirm ?

**Comment by Killyana** [comment]
If there's an issue explain how to reproduce it.

**Comment by JunkyBulgaria** [comment]
@Killyana 
    When you're abomination you can't cast 71516 ( Shadow Infusion )
    When you cast 71516 ( Shadow Infusion ) at self, it does not apply the aura(credit) for quest.

**Comment by Killyana** [comment]
It does.
