### ISSUE TITLE
Cannons

### ISSUE THREAD

**Issue by Zedron** [TrinityCore/TrinityCore#8736]
How to reproduce:
1: Teleport to Wintergrasp while it is in progress.
2: Get into a cannon before accepting the invitation to join the battle
3: accept the invitation to join the battle

You're able to move the cannon, and go anywhere you want in wintergrasp with it.

core: 728ee3e
DB: TDB 335.11.49+updates

**Comment by Aokromes** [comment]
Generic issue for all cannons, test https://github.com/TrinityCore/TrinityCore/pull/13642

**Comment by Aokromes** [comment]
cdb16c5
