### ISSUE TITLE
Pets Haste benefit Owner Haste

### ISSUE THREAD

**Issue by click** [TrinityCore/TrinityCore#874]
1.Gargoyle UI is bugged,u should be able to control it by using /petfollow
/petattack macro(works only if u have pet summoned=on retail). Here u can't change it's target.
2.Gargoyle not benefiting from haste(DK pet too not benefiting)
##

**Comment by tkrokli** [comment]
Would this fix from soulfrost, written more than 2 years ago in #9526, be useful to fix the Haste issue?

in /src/server/game/Entities/Pet/Pet.cpp , section `case 27829: // Ebon Gargoyle`
```cpp
            if (Player *owner = m_owner->ToPlayer()) // get 100% of owning player's haste
            {
                float bonus = owner->GetRatingBonusValue(CR_HASTE_MELEE);
                bonus += owner->GetTotalAuraModifier(SPELL_AURA_MOD_MELEE_HASTE) +
                    owner->GetTotalAuraModifier(SPELL_AURA_MOD_MELEE_RANGED_HASTE);
                ApplyCastTimePercentMod(bonus, true);
                SetCreateHealth(uint32(owner->GetMaxHealth()*0.8)); // hp must be 0.8x of DK hp
            }
```
Moreover, would it be valid for the 3.3.5 branch as well as the 4.3.4 branch?

**Comment by Killyana** [comment]
If I'm not wrong this must be done foe all pets.

**Comment by tkrokli** [comment]
OK, does that mean that the above section should be put somewhere else in the file, so it is valid for all pets, or does it need to be completely rewritten to be valid for the script? (Sorry that I don't know this.)

**Comment by ccrs** [comment]
I think most pet scaling stats should be handled with spells. Those spell scripts seem incomplete AFAIK

**Comment by tkrokli** [comment]
"pet scaling stats should be handled with spells" - does you mean it should be changed in the Haste spell script or in the spells to call the pet, based on the class entity calling its pet?

**Comment by ccrs** [comment]
Not really. Those spells i meant are auras added by default on player pets.

**Comment by Killyana** [comment]
Will be closed by https://github.com/TrinityCore/TrinityCore/pull/21016

**Comment by Killyana** [comment]
All kind of scaling are done by auras, here the  ghoul for the DK, it has many scaling auras for almost every stat, wee must maybe close this issue as we have https://github.com/TrinityCore/TrinityCore/issues/5136

```
ServerToClient: SMSG_AURA_UPDATE_ALL (0x0495) Length: 75 ConnIdx: 0 Time: 08/25/2010 14:04:09.000 Number: 44142
GUID: Full: 0xF1xxxxxxxxxx0 Type: Pet Entry: 448xxxxxx Low: 74928
[0] Slot: 0
[0] Spell ID: 67557 (67557)
[0] Flags: 0 (None)
[0] Level: 80
[0] Charges: 0
[0] Caster GUID: Full: 0xF14044609A0124B0 Type: Pet Entry: 448xxxxxx Low: 74928
[1] Slot: 1
[1] Spell ID: 67561 (67561)
[1] Flags: 0 (None)
[1] Level: 80
[1] Charges: 0
[1] Caster GUID: Full: 0xF14044609A0124B0 Type: Pet Entry: 448xxxxxx Low: 74928
[2] Slot: 4
[2] Spell ID: 62137 (62137)
[2] Flags: 15 (EffectIndex0, EffectIndex1, EffectIndex2, NotCaster)
[2] Level: 80
[2] Charges: 0
[3] Slot: 5
[3] Spell ID: 54566 (54566)
[3] Flags: 15 (EffectIndex0, EffectIndex1, EffectIndex2, NotCaster)
[3] Level: 80
[3] Charges: 0
[4] Slot: 6
[4] Spell ID: 51996 (51996)
[4] Flags: 15 (EffectIndex0, EffectIndex1, EffectIndex2, NotCaster)
[4] Level: 80
[4] Charges: 0
[5] Slot: 7
[5] Spell ID: 61697 (61697)
[5] Flags: 15 (EffectIndex0, EffectIndex1, EffectIndex2, NotCaster)
[5] Level: 80
[5] Charges: 0

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/5136
