### ISSUE TITLE
[4.3.4] [Movement] Creature-Formations Z-coord bug

### ISSUE THREAD

**Issue by NorthStrider** [TrinityCore/TrinityCore#8775]
as the title says if you have a flying group for example like i did in stormwind, the formation members dont fly on the same Z-Coord as the leader.

http://www.imagebanana.com/view/796xdp9a/WoWScrnShot_122612_071415.jpg

rev.: b566f544df9fa648039ba2bd615baba9eb27741e

**Comment by Killyana** [comment]
Dup https://github.com/TrinityCore/TrinityCore/issues/15190
