### ISSUE TITLE
Halion crepuscular miss spell ticket version 3

### ISSUE THREAD

**Issue by milotic** [TrinityCore/TrinityCore#8781]
I test this fight many times and this spell http://www.wowhead.com/spell=74792 miss

rev: https://github.com/TrinityCore/TrinityCore/commit/914d3649c4fc5d3f33ca0f673669e414b73d3fb8

**Comment by Aokromes** [comment]
Test #16725

**Comment by Demonid** [comment]
@Aokromes  If i remember correctly, this issue was fixed on https://github.com/TrinityCore/TrinityCore/commit/7fa49c8d62f9284c2a31f939612771ea980246de
