### ISSUE TITLE
Halion 25 hero. Missing npc 

### ISSUE THREAD

**Issue by milotic** [TrinityCore/TrinityCore#8782]
hi when halion summon this npc http://www.wowhead.com/npc=40681 should summon 10 http://www.wowhead.com/npc=40683

rev: https://github.com/TrinityCore/TrinityCore/commit/914d3649c4fc5d3f33ca0f673669e414b73d3fb8

**Comment by Warpten** [comment]
1447875cac0fefd58ae3ad27e6b3fa2134a714c0
