### ISSUE TITLE
[MovementMaps] Sindragosa

### ISSUE THREAD

**Issue by Valcorb** [TrinityCore/TrinityCore#8786]
When you kill Rimefang & Spinestalker, Sindragosa is supposed to fly to the platform. 
At the moment, she doesn't. She stays on a mountain behind the platform.

Screenshot: http://i.imgur.com/JkpYK.jpg

Core: 79b1895223bbf16bfd6484e34e067beea457e4cc
TDB: 335.11.49 + Updates until 2012/12/27 from mmaps branch

**Comment by Killyana** [comment]
Cannot reproduce on rev. 5b5c0938da0f she always lands when the 2 dragons dies (even if with gm on without aggro)
