### ISSUE TITLE
[MovementMaps::Pets] Pet Pathing & Pet LoS

### ISSUE THREAD

**Issue by Valcorb** [TrinityCore/TrinityCore#8789]
It's not working completly. 
Here's a video i recorded & uploaded: http://www.youtube.com/watch?v=dPPJBX8CiRQ

Core: 79b1895223bbf16bfd6484e34e067beea457e4cc
TDB: 335.11.49 + Updates until 2012/12/27 with mmaps branch

**Comment by Aokromes** [comment]
No answer over 6 months, open a new ticket if this bug is still valid.
