### ISSUE TITLE
[ICC/Mutated Transformation]Disease bug

### ISSUE THREAD

**Issue by untaught** [TrinityCore/TrinityCore#8844]
Mutated Transformation ticks refreshes Spirit of Redemption duration so the priest with this talant can never die if there is an abomination alive. Indeed the priest dies from these ticks and come alive in the same second. It is possible to use this mechanic for honorable kills grind if mixed(horde+alliance) raids are enabled.

Mutated Transformation: http://wotlk.openwow.com/?spell=70402
Spirit of Redemption: Spirit of Redemption
##

**Comment by Killyana** [comment]
@ariel-  Can you take a look at this ?

**Comment by kvipka** [comment]
https://dbwotlk.com/?spell=70402 
who should be real caster?
