### ISSUE TITLE
[NPC] Wing Commander Brack - Missing dialog options

### ISSUE THREAD

**Issue by Zaranthos** [TrinityCore/TrinityCore#8851]
Wing Commander Brack
http://www.wowhead.com/npc=19401/wing-commander-brack

Should fly you to Spinebreaker Post as part of a quest. He has no dialog options.
http://www.wowhead.com/spell=34578
http://www.wowhead.com/quest=10242

2012-12-22 09:23:55 -0800 (3f4c6a9d45a5+) (Win64, Release) AHbot
3f4c6a9d45a5994bbf5d1dff42038cd3ab6f3535
TDB_full_335.49_2012_09_16 (+updates)

**Comment by Killyana** [comment]
Fixed.
rev. 5b5c0938da0f
