### ISSUE TITLE
[Quest] Divination: Gorefiend's Truncheon

### ISSUE THREAD

**Issue by Zaranthos** [TrinityCore/TrinityCore#8899]
http://www.wowhead.com/quest=10636
Equipping the spectrecles should allow you to see and kill the mobs. Doesn't work or the mobs aren't spawned or pathing correctly.
http://www.wowhead.com/item=30719

These quests would also not work:
http://www.wowhead.com/quest=10634/divination-gorefiends-armor
http://www.wowhead.com/quest=10635/divination-gorefiends-cloak

Related to this quest which also doesn't work.
https://github.com/TrinityCore/TrinityCore/issues/3950

2012-12-22 09:23:55 -0800 (3f4c6a9d45a5+) (Win64, Release) AHbot
3f4c6a9d45a5994bbf5d1dff42038cd3ab6f3535
TDB_full_335.49_2012_09_16 (+updates)

**Comment by Killyana** [comment]
The aura is wrong it must be 37467 not 37497, for some reason (Apply Aura: Force Reaction (1013) ) is not working. And formation + wp must be done.

**Comment by Killyana** [comment]
``` sql
UPDATE `smart_scripts` SET `event_type`=25, `event_flags`=0 WHERE `entryorguid` IN (21784,21815, 21801) AND `source_type`=0 AND `id`=0;
