### ISSUE TITLE
Mage-Lord Urom - The Oculus

### ISSUE THREAD

**Issue by LordUsagi** [TrinityCore/TrinityCore#8909]
The NPC Mage-Lord Urom, located in the instance The Oculus is currently bugging out.

If you melee, or use a one hit spell then he'll work as intended, but if you use a damage over time ability such as Shadow Word: Pain, it will cancel his spell casting and ruin the encounter basically.

Revision #: 677ed180802541d4bf487eeaa554c01aa3dc5ceb
Running YTDB, I believe.

Can confirm on TDB that it does not work either.

**Comment by Aokromes** [comment]
No answer after near 2 years, closing, if this bug is still valid open a new ticket on one updated version.
