### ISSUE TITLE
[Core / Spell] Mechanical units should be immune poisons, taunts, bleeds

### ISSUE THREAD

**Issue by MrSmite** [TrinityCore/TrinityCore#8937]
**Rev:** All

**Bug:**

Mechanical units should be immune to nature spells such as Serpent Sting, taunts such as Growl and bleeds such as Gouge (yet oddly not a Warrior's rend...)

**Details:**

http://www.wowhead.com/npc=114/harvest-watcher#comments

Specifically the Harvest Watcher in Trinity is not immune to pet Growl and Hunter's Serpent Sting. Don't know if all mechanical units are this way since this is the first one I've encountered.
##

**Comment by danlapps** [comment]
Is this a valid issue or a misunderstanding of the mechanics of the immune criteria ?

**Comment by Killyana** [comment]
This Immunities must be set by npc and not by family.
