### ISSUE TITLE
Looting issue with gameobject type 3 for quest items (cause by players)

### ISSUE THREAD

**Issue by dr-j** [TrinityCore/TrinityCore#8952]
I would like to report an issue which I have encountered with gameobjects (type 3) which contain items which are required for quests,

an example object is http://www.wowhead.com/object=290 which contains http://www.wowhead.com/item=841 which is required for http://www.wowhead.com/quest=64/the-forgotten-heirloom

But have previously encountered this issue with other gameobjects, the issue is if a player opens the gameobject but does not loot the quest item then another player trys to loot the object it will appear empty, if the player who originally opened it goes back and loots the item then it will work again but this wont always happen and object will end up tagged to that player and noone else will be able to loot quest item until server restart unless the player to which it is tagged loots item.
##

**Comment by ariel-** [comment]
Closed by 7011aabb56f061fc889ec42ce32b7605ceb35b53

**Comment by tkrokli** [comment]
Always nice to see such old issues closed, especially those that were opened before I even knew about TrinityCore! 👍 🕺
