### ISSUE TITLE
[Core / Items] Item containers temporarily lose saved items - "You can't do that right now"

### ISSUE THREAD

**Issue by MrSmite** [TrinityCore/TrinityCore#8955]
__Rev:__ fb3245d12533cde3fb0765b114a6132dde836119

__Bug:__

Item containers in the player's inventory can temporarily lose their contents until next player
inventory save if player performs specific actions

Server admins: Please tell your players not to panic, the items aren't permanently lost.

__Details:__

To replicate:

> 1. Get any new container item like Dented Crate (entry 6351)
> 2. Open and close it but don't remove any contents
> 3. Try to move it to a different slot in your bag. It should error with __"You can't do that right now"__
> 4. Open the container and notice it is empty
> 5. Log out and back in and open the container. It might still be empty.
> 6. The player may have to log in and out a few times until the server resaves their inventory. This will allow the contents to be reloaded the next time the item is opened.

It appears the action of trying to move the item removes it from your inventory and does not replace it until the next time the server issues a player inventory save.

Because the item loot loading functionality requires the item to be in a bag, it temporarily can't load the stored contents. After the player's inventory is saved the contents will load.

This isn't a problem with mismatched GUIDs or anything but simply the fact that the item is temporarily not in your inventory as far as the server is concerned.

**Comment by Killyana** [comment]
Fixed.
TrinityCore rev. 5dba91fb0e38
