### ISSUE TITLE
[Core / Spell] Prowl does not apply the bonus to first attack

### ISSUE THREAD

**Issue by MrSmite** [TrinityCore/TrinityCore#8956]
__Rev:__ fb3245d12533cde3fb0765b114a6132dde836119

__Bug:__

The pet ability [Prowl](http://www.wowhead.com/spell=24450/prowl) does not properly apply the bonus % to damage for the first attack.

**Comment by Killyana** [comment]
Fixed.
PS: The first attack from stealth receives a 20% bonus to damage, not 50% as on wod.
rev. 5dba91fb0e38
