### ISSUE TITLE
[Core / NPC] Creature aggro / assist chaining in instances (picture incl.)

### ISSUE THREAD

**Issue by MrSmite** [TrinityCore/TrinityCore#8972]
**Rev:** https://github.com/TrinityCore/TrinityCore/commit/98f502f32f092fe1bcb9e19c32c189d2ea552d19 (though I'd imagine all)

**Bug:**

Creature aggro assist is broken in dungeons. They seem to aggro chain so when you pull one creature you get adds attacking you after the assist delay (CONF) passes.

**Details:**

![deadmines_creature_aggro.jpg](https://gist.github.com/raw/38fc8223656f184fed74/26d89f25808ad0e84633ad16f9a1ab3375933819/deadmines_creature_aggro.jpg)

In the above map from Deadmines, "P" is the player and "X" is the intended target.

When "P" shoots "X", you would naturally expect to aggro both creatures labeled "5". The problem is as follows:

> 1. The lower "5" chains the assist aggro onto the "6" group
> 2. The upper "5" chains the assist aggro onto the "1" group.
> 3. As "X" runs past the "3" group, they aggro and chain assist aggro onto the "2" group

At first only X and the "5" group come to fight. After whatever the assist delay (CONF) passes, you suddenly hear aggro sounds from all the other groups mentioned and they come join the fight.

In a dungeon this actually extends beyond the "6" group but I didn't want to spend all day making a picture. In my testing, I at one point pulled over 15 mobs with a single shot and all but 3 of them were so far out of LOS that they should not have been aggro'd.

Assist aggro chaining is broken and makes dungeons annoying.

**Notes:**

Thanks to Atlas Mod for the BLP of the Deadmines map for me to edit.
##

**Comment by Rushor** [comment]
@LordUsagi could you make a pr for your fix?  https://github.com/TrinityCore/TrinityCore/issues/8972#issuecomment-13615287 :)

**Comment by Killyana** [comment]
Cannot reproduce it on rev. fa3eb754cbe1 as npcs that aggro via an assist will never trigger an assist.
