### ISSUE TITLE
Waypoint stops after interaction

### ISSUE THREAD

**Issue by Persephone** [TrinityCore/TrinityCore#8976]
Moving npcs that follow a path of waypoints, stops when you talk to them but they do not continue to walk after you have talked with them. 
##

**Comment by Killyana** [comment]
on rev. cc4f86cc2bf4 The NPC resume the wp after exactly 3 minutes, someone must check if it's the same on retail.

**Comment by Kittnz** [comment]
Depence on npc, some go rather quickly, some stay for ages.

**Comment by Skiopz** [comment]
This is situed here : 

if (unit->IsArmorer() || unit->IsCivilian() || unit->IsQuestGiver() || unit->IsServiceProvider() || unit->IsGuard())
        unit->StopMoving();

**Comment by AgencyDev** [comment]
BUMP, is there a way to make a certain NPC not stop waypointing for so long? I want it to move after 5 seconds for example.

**Comment by Killyana** [comment]
Yes you can add "continue the waypoint" 5s after the gossip close.

**Comment by Rushor** [comment]
change the timer in https://github.com/TrinityCore/TrinityCore/blob/7d9843c380cf00f38ad0c5bc75fd387e50ee11da/src/server/game/Movement/MovementGenerators/WaypointMovementGenerator.h#L38

**Comment by AgencyDev** [comment]
@Rushor This will cause all NPC's to do this though, and i rather do it for a spesific NPC.

**Comment by Rushor** [comment]
the move the waypoint to sai,
call: on reset - start waypoint
and: on gossip hello - stop waypoint  - for xx sec

**Comment by Aokromes** [comment]
This bug is still valid?

**Comment by Killyana** [comment]
We add it a config value for this so it could be closed https://github.com/TrinityCore/TrinityCore/commit/d5f04f5a387d8c41f9d54d5d8a0ff007209148a8

**Comment by tkrokli** [comment]
The waypoint system has received some changes since this issue was posted first time, so there may not be the same reasons why some things don't work now. I suggest closing this issue and ask for new reports in a new issue ticket if this kind of issue still happens, preferably with a reproducible list of NPCs with waypoints where there should be a shorter wait time before NPC starts moving again.

**Comment by ccrs** [comment]
actually this issue was valid till 7fff83d67526efff63867d41b9e036a19a9287b3

**Comment by tkrokli** [comment]
Good point. Thanks for confirming which change made it worth closing.
