### ISSUE TITLE
[Quest / NPC] Razormaw from quest 'Razormaw' does not attack [$15]

### ISSUE THREAD

**Issue by MrSmite** [TrinityCore/TrinityCore#8988]
__Rev:__ 98f502f32f092fe1bcb9e19c32c189d2ea552d19

__Bug:__

[Razormaw](http://www.wowhead.com/npc=17592) from quest [Razormaw](http://www.wowhead.com/quest=9689) does not fight, he just stands there while you attack.

__Notes:__

I'm not sure if it is because he becomes attackable before he lands or not. I was spamming Hunter's Mark which kept saying "invalid target". Once it actually cast I sent my pet in. We killed Razormaw without him attacking.

When I went to loot his body, I noticed he was still a few yards off the ground.

**Comment by Killyana** [comment]
The inactive grid cell is a general issue, increasing Visibility.Distance.Continents  to 170 on server config fix the problem in this case.

For the script:

``` sql
UPDATE creature_template SET InhabitType=4, unit_flags=64 WHERE Entry=17592;
DELETE FROM `smart_scripts` WHERE `entryorguid`=17592 AND `source_type`=0 AND `id`IN(5, 6, 7);
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(17592, 0, 5, 6, 40, 0, 100, 0, 10, 17592, 0, 0, 101, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Razormaw - On Waypoint 10 Reached - Set Home Position'),
(17592, 0, 6, 0, 61, 0, 100, 0, 0, 0, 0, 0, 8, 2, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Razormaw - On Waypoint 10 Reached - Set Agressive'),
(17592, 0, 7, 0, 11, 0, 100, 0, 0, 0, 0, 0, 18, 256, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Razormaw - On Respawn - Add unit_flag');

**Comment by jackpoz** [comment]
how was the issue fixed ? the commit log doesn't explain anything

**Comment by djbeauchamp** [comment]
I tested the DB change and the server config together and they did resolve the problem, but I don't know if that should be considered a fix as you have to change the whole server's config to a non default setting for a limited problem.

**Comment by jackpoz** [comment]
the commit https://github.com/TrinityCore/TrinityCore/commit/c8c6b0fbf5b0e9556852d8cfde319e2af1b113e0 doesn't show any config change

**Comment by djbeauchamp** [comment]
Sorry, I was referring to https://github.com/TrinityCore/TrinityCore/issues/8988#issuecomment-75433449

**Comment by Kittnz** [comment]
@pete318 would you dare to touch grid for "any TempSummon summoned by a Player makes a grid cell active ?" This would fix loads of problems.

**Comment by pete318** [comment]
What should be the desired outcome? Despawn the tempsummon, or leave it and let the grid deactivate as if it were a normal creature?

With the latter, you have the problem that with grid unload enabled, if the grid is unloaded when it reloads the temp summon will be lost (with a warning about unable to load creature from db) sent to the console I suspect.

**Comment by Kittnz** [comment]
Despawn them because they are tempsummon's.

**Comment by pete318** [comment]
Reading the rest of the text in this issue, it seems the problem is the grid is deactivated. So, I just need to be sure of the problem.

Is the problem that the temp summons keep the grid active and don't do anything? Or, is the problem that the temp summons don't keep the grid active, players move from visibility range and then updates cease on them causing problems with waypoints etc (as per the comments above)?

If the latter, then a similar change to the combat bug PR I made can be applied. If it's the former than I can probably look some time soon. However, I'll need an example of that scenario I can test with too.

**Comment by Killyana** [comment]
The commit fix the non_attackable issue and if the player dies the npc will stay in the updated position and will not return in the spawn coords.
The non active grid is a general issue.

**Comment by pete318** [comment]
It might be as simple as using the same solution I used here https://github.com/TrinityCore/TrinityCore/pull/14199

Specifically:

https://github.com/TrinityCore/TrinityCore/pull/14199/files#diff-4522eeffcbc961602e86620011a2d579R9048

Of course important to ensure it's unset in the right circumstance too. I would should only be allowed for those creatures that either:

1: Have a fixed waypoint that will have them despawn at the end
2: Have the setting to despawn at too much range.

Otherwise, there is the situation that a player is long gone, but a "tempspawn" is sitting around keeping a cell active that doesn't need to be. If a lot of these are around it's bad for the server.

Of course there is the issue as to how these states are determined.. 2 is fine, 1 maybe not. Also there may be other situations that need the creature to keep active too. For sure it shouldn't automatically be the case I think.

So, while it's possible to make this happen - there needs to be limits. For example in my combat PR, once the creature leaves combat with a player it's set as inactive and the cell goes to sleep.

**Comment by MrSmite** [comment]
What about checking the tempsummon state periodically: *InCombat()* (or *InUse()* for case of a GO) and if too much time passes where they return *False*, despawn it.

eg: In the case of my OP, when the player leaves the area, Razormaw will report *False* for InCombat() and after (for example) 5 minutes it's safe to assume he's not needed.

**Comment by Killyana** [comment]
The despawn time is already set to 150 secs on event script datalong2.

**Comment by pete318** [comment]
In both cases, presumably the problem is that the update (regardless of IC/OOC) isn't run when there's no character in the area. Try setting the "SET_ACTIVE" action to 1 on reset event (maybe just summoned is called instead for these, try both), and then set the despawn timer and see if that improves matters.

I don't know the exact steps to reproduce the problem, so I can't really try it myself.

**Comment by pete318** [comment]
I just tried and SET_ACTIVE works (set it on respawn). However I couldn't work out why he sinks into the ground on the final waypoint. He also refuses to melee. So probably claw should be much more common and so on..

**Comment by Killyana** [comment]
He sinks into the ground because: 33554432 = Hover mode is ON on creature_template_addon and for me he hit on melee and cast other spells normally.

**Comment by pete318** [comment]
Well, if the spawn distance and despawn were the only problems I'd suggest adding the set_active at the respawn event, and then set maybe 10minutes OOC update initial timer with a despawn (with maybe 2 minutes so, if death counts as OOC update, he doesn't despawn before being looted).

That would solve the spawn issues I think.

**Comment by pete318** [comment]
Try this

```SQL
-- Razormaw SAI
SET @ENTRY := 17592;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,0,0,100,0,1000,3000,3000,5000,11,31279,64,0,0,0,0,2,0,0,0,0,0,0,0,"Razormaw - In Combat - Cast 'Swipe'"),
(@ENTRY,0,1,0,0,0,100,0,8000,12000,6000,8000,11,8873,64,0,0,0,0,1,0,0,0,0,0,0,0,"Razormaw - In Combat - Cast 'Flame Breath'"),
(@ENTRY,0,2,0,2,0,50,1,0,50,0,0,11,14100,64,0,0,0,0,1,0,0,0,0,0,0,0,"Razormaw - Between 0-50% Health - Cast 'Terrifying Roar' (No Repeat)"),
(@ENTRY,0,3,11,11,0,100,0,0,0,0,0,53,1,17592,0,0,0,0,1,0,0,0,0,0,0,0,"Razormaw - On Respawn - Start Waypoint"),
(@ENTRY,0,4,18,40,0,100,0,10,17592,0,0,19,256,0,0,0,0,0,1,0,0,0,0,0,0,0,"Razormaw - On Waypoint 10 Reached - Remove Flag Immune To Players"),
(@ENTRY,0,11,0,61,0,100,0,0,0,0,0,48,1,0,0,0,0,0,1,0,0,0,0,0,0,0,"Razormaw - On Respawn - Set Active On"),
(@ENTRY,0,14,18,40,0,100,0,9,17592,0,0,91,2,3,0,0,0,0,1,0,0,0,0,0,0,0,"Razormaw - On Waypoint 9 Reached - Remove Flag Hover"),
(@ENTRY,0,18,0,61,0,100,0,10,17592,0,0,8,2,0,0,0,0,0,1,0,0,0,0,0,0,0,"Razormaw - On Waypoint 10 Reached - Set Reactstate Aggressive"),
(@ENTRY,0,19,0,40,0,100,0,10,17592,0,0,101,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Razormaw - On Waypoint 10 Reached - Set Home Position");
```

Although, I might have tuned the difficulty a bit high.. Who knows there was just one of me and I found him tricky..

Basically set active, to ensure he can complete the way points..
At point 9, turn off hover, so he hits the ground, at point 10, set react state aggressive and store home position.
Then the rest is straight out combat. He'll despawn after some time of inactivity.

If you die/he resets hover is re-enabled.. Not sure of a real way to fix that, unless reset isn't called on the spawn. I never tried. I think this is "good enough".

**Comment by Killyana** [comment]
Yes, it's better like this, any way we need to implement the "permanent_active_grid" on creature_template and creature_template_addon to fix some other issues like this.

**Comment by MrSmite** [comment]
> The despawn time is already set to 150 secs on event script datalong2.

True but the core doesn't seem to do anything if there's no player in the grid (as mentioned above). I was suggesting forcing the core to do a check at an interval and 5 minutes was only an example.

**Comment by Kittnz** [comment]
Another great example is: https://github.com/TrinityCore/TrinityCore/issues/6710#issuecomment-80927524.

**Comment by pete318** [comment]
I'm not sure if there should ever be an "always active grid". I think there should be zone-wide active. As in, if a player is in the same zone, the creature is active. This would work for things like Fel Reaver etc.

**Comment by Kittnz** [comment]
I agree with you on that :+1:

**Comment by pete318** [comment]
Yep, except it's probably not at all easy to do. Hmm.

**Comment by MrSmite** [comment]
> Yep, except it's probably not at all easy to do. Hmm.

A while ago I wrote a patch to keep flightmaster grids from unloading to help reduce the lag for low-pop servers when a player flew on long flightpaths.

I would think instead of having the whole zone loaded it would use less overhead to only keep grids loaded that are actually used by an NPC. An NPC on patrol should be able to load the next grid on its path just like a player does. These creatures could be identified by a new field in `creature_template` called `isGridLoader` (or something). Then it would be up to the movement generator to check this flag and keep loading grids for the NPCs that need them, otherwise let them go idle and let the grid unload.

**Comment by pete318** [comment]
As I understand the system, if a creature is "active" it also activates grids in a similar way to a player in that grid would.

However, what I was actually talking about is creatures that are meant to be seen zone-wide (like Fel Reaver). In this case I think they should be active if any player is in that zone. But, I don't like the idea that they'd be active if there were no-one in that zone.

So it's a real nice-to-have I think to have some kind of zone-wide active flag. I'm just wondering how the best way to implement it would be.

**Comment by Kittnz** [comment]
That's a big task to give every NPC entry a flag 0/1.

**Comment by Killyana** [comment]
By default all the npcs will have this flag=0, when someone write a script he can change this value if needed. (I still think using creature_template_addon and creature_addon is a better way to do this) sometimes we need to keep the grid active even if the npc is not moving)

**Comment by Kittnz** [comment]
@pete318 mind hoping in IRC land?

**Comment by MrSmite** [comment]
> As I understand the system, if a creature is "active" it also activates grids in a similar way to a player in that grid would.

Honestly I'm not sure right now. It used to be that a creature moving on a path would not load the grid containing its next waypoint if that grid had been unloaded. This is why quest NPCs such as The Forsaken Courier don't work properly. Usually they get stuck at their spawn point because the grids unload so they can't path between Southshore and Arathi Highlands.

Which also goes to your point about zone-wide grid loading. In the case of the aforementioned NPC, it crosses zones so that wouldn't work on small-pop servers where one zone might be empty. This really needs to be tied to the NPC / pathing system.

> That's a big task to give every NPC entry a flag 0/1

Not really, when you alter the table to add the field you set default to 0. Then you can run a script to change any creature with waypoint data to 1.

**Comment by pete318** [comment]
Ah well unloaded and inactive are two different matters. I doubt an active creature would load a grid. But, then I don't know how that would be handled either.

That is a tricky one. In that case I think "load all grids" at startup could make sense for those with the ram to do so. But active grids is what needs to be guarded more carefully since that is CPU activity which matters a lot more I think.

**Comment by pete318** [comment]
So, after some discussion and some more messing around. This is my next iteration. It involves changing the template which surely in this case is wrong (not set to "can fly").

```SQL
-- Update template to allow flying (Razormaw 17592) - InhabitType was 3, flags was 320 (remove PC immunity, it's added in SAI)
UPDATE creature_template SET InhabitType=7, unit_flags=64 WHERE entry=17592;

-- Change last waypoint to be a little lower for final landing spot
UPDATE waypoints SET position_z = 96.5391 WHERE entry=17592 and pointid=11;

-- Razormaw SAI
SET @ENTRY := 17592;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,0,0,100,0,1000,3000,3000,5000,11,31279,64,0,0,0,0,2,0,0,0,0,0,0,0,"Razormaw - In Combat - Cast 'Swipe'"),
(@ENTRY,0,1,0,0,0,100,0,8000,12000,6000,8000,11,8873,64,0,0,0,0,1,0,0,0,0,0,0,0,"Razormaw - In Combat - Cast 'Flame Breath'"),
(@ENTRY,0,2,0,2,0,50,1,0,50,0,0,11,14100,64,0,0,0,0,1,0,0,0,0,0,0,0,"Razormaw - Between 0-50% Health - Cast 'Terrifying Roar' (No Repeat)"),
(@ENTRY,0,3,11,11,0,100,0,0,0,0,0,53,1,17592,0,0,0,0,1,0,0,0,0,0,0,0,"Razormaw - On Respawn - Start Waypoint"),
(@ENTRY,0,4,18,40,0,100,0,10,17592,0,0,19,256,0,0,0,0,0,1,0,0,0,0,0,0,0,"Razormaw - On Waypoint 10 Reached - Remove Flag Immune To Players"),
(@ENTRY,0,11,0,61,0,100,0,0,0,0,0,48,1,0,0,0,0,0,1,0,0,0,0,0,0,0,"Razormaw - On Respawn - Set Active On"),
(@ENTRY,0,14,18,40,0,100,0,9,17592,0,0,91,2,3,0,0,0,0,1,0,0,0,0,0,0,0,"Razormaw - On Waypoint 9 Reached - Remove Flag Hover"),
(@ENTRY,0,18,0,61,0,100,0,10,17592,0,0,8,2,0,0,0,0,0,1,0,0,0,0,0,0,0,"Razormaw - On Waypoint 10 Reached - Set Reactstate Aggressive"),
(@ENTRY,0,19,0,40,0,100,0,11,17592,0,0,101,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Razormaw - On Waypoint 11 Reached - Set Home Position"),
(@ENTRY,0,20,23,40,0,100,0,1,17592,0,0,18,256,0,0,0,0,0,1,0,0,0,0,0,0,0,"Razormaw - On Waypoint 1 Reached - Set Flag Immune To Players"),
(@ENTRY,0,21,22,25,0,100,0,0,0,0,0,8,2,0,0,0,0,0,1,0,0,0,0,0,0,0,"Razormaw - On Reset - Set Reactstate Aggressive"),
(@ENTRY,0,22,0,61,0,100,0,0,0,0,0,91,2,3,0,0,0,0,1,0,0,0,0,0,0,0,"Razormaw - On Reset - Remove Flag Hover"),
(@ENTRY,0,23,0,61,0,100,0,1,17592,0,0,90,2,3,0,0,0,0,1,0,0,0,0,0,0,0,"Razormaw - On Waypoint 1 Reached - Set Flag Hover");
```

Give it a go. Stops the stuttering and also resolves most issues with resetting.

It has some workarounds for hover states etc. But it should make it such that it's about as original as I could get it to be.

**Comment by MrSmite** [comment]
> Ah well unloaded and inactive are two different matters. I doubt an active creature would load a grid. But, then I don't know how that would be handled either.

I know this is a bit off-topic to Razormaw but since the discussion has been going on here...

Without having looked at the code in a while, I think there used to be a function in *Map* that would load a grid based on a set of *XYZ* parameters. So we could handle this one of two ways:

* Load all grids at creature spawn if the NPC has waypoints and prevent them from unloading (by adding a flag to the grid class: *canUnload*
* Load a grid in the waypoint movement generator based on the next waypoint's *XYZ* prior to trying to move the NPC there.

**Comment by djbeauchamp** [comment]
Should this issue be closed still? There seems to be a lot of discussion on how to fix the off grid part.

**Comment by pete318** [comment]
@MrSmite I'm going to investigate options regarding long WP creatures and activation based on players in either zone or grid level and then post to the forum regarding my result. Not sure when I'll get the chance though.

@djbeauchamp the last SAI I posted will resolve the off grid issue for Razormaw. However it's only valid for temporary spawns that have a despawn timer. Since they will keep the cell active even if there are no players in the zone.

**Comment by djbeauchamp** [comment]
Not to be a pain, but my point is without a complete fix in the core it seems premature to close the issue is all. 

Having it closed signifies that it's been resolved is all.

**Comment by pete318** [comment]
This issue is about Razormaw not spawning/not attacking. Apply the most recent SAI + DB changes by me and Razormaw will do all these things (and a bit more).

For other creatures in the world that aren't tempsummons controlled by SAI there is a discussion ongoing. But, it's an entirely different issue, in my opinion.

**Comment by MrSmite** [comment]
@djbeauchamp The conversation sort of got derailed by me and @pete318 discussing something a little off-topic (though somewhat related). The Razormaw issue seems to be fixed so closing this isn't inappropriate.

If desired, a new issue could be opened to continue the discussion about grid loading / pathing.

**Comment by MrSmite** [comment]
Small update, I just tried the Razormaw quest and it doesn't work well at all.

For some reason I have no waypoints for him so he spawns on the ground below the mountain, flies up to the mountain and back down. When I attack him I get "absorb".

42f1a0babfaacf64df31a934288979f8edfec940

**Comment by tkrokli** [comment]
According to the Bountysource page https://www.bountysource.com/issues/104187-quest-npc-razormaw-from-quest-razormaw-does-not-attack , "This issue has a $15 bounty that can be claimed."

If @djbeauchamp does not object or claim that it is not solved, I believe the money goes to @Killyana  :+1:

**Comment by djbeauchamp** [comment]
No complaints here, just waiting for someone to make the claim.

**Comment by tkrokli** [comment]
Very well, then. @Killyana, just go to the page https://www.bountysource.com/issues/104187-quest-npc-razormaw-from-quest-razormaw-does-not-attack/developers and claim the bounty. :moneybag:

**Comment by Killyana** [comment]
Thanks but I'm doing this for fun not money.

**Comment by Frytiks** [comment]
What a nice man ^^

**Comment by tkrokli** [comment]
Sure, of course we appreciate that. I could say the same for myself. How about considering it as a gift? :)
