### ISSUE TITLE
[NPC] Razormaw from quest 'Razormaw' cannot be skinned

### ISSUE THREAD

**Issue by MrSmite** [TrinityCore/TrinityCore#8989]
__Rev:__ https://github.com/TrinityCore/TrinityCore/commit/98f502f32f092fe1bcb9e19c32c189d2ea552d19

__Bug:__

After killing [Razormaw](http://www.wowhead.com/npc=17592) from quest [Razormaw](http://www.wowhead.com/quest=9689) you cannot skin him. The tooltip shows "skinnable" but when you right-click, the skinning cursor changes to a glowing hand cursor.

**Comment by Killyana** [comment]
Fixed.

**Comment by MrSmite** [comment]
> Fixed.

Just curious, was it a recent commit or @Svannon 's sql?

**Comment by Killyana** [comment]
No Idea, I just killed it and skin it.
