### ISSUE TITLE
Wintergrasp Spirit Guide not working

### ISSUE THREAD

**Issue by lvalladares** [TrinityCore/TrinityCore#9035]
The spirit guides of wintergrasp:
31841 - Taunka Spirit Guide 
31842 - Dwarven Spirit Guide

Dont work at all, the gossips text is < erro r> and when you die, it dont revive you

How to reproduce

Start the battle for wintergrasp

Die and release

You'll be teleported to one of this spirit guide, if you talk with him, all the gossips he have says < error > but if you click it, he will teleport you (The action do work)

Also, wait 30 sec for resurrection timer

What should happen?

You Should revive like in any other BG

What happens?

You stay dead, and must fly to your body for be resurrected

Screenshot: http://i47.tinypic.com/2lm49ib.jpg

Hash: 5e367c910a0bdcad9dbb4881c9bb00be05181292
DB: TDB_FULL049_UP_23_01_05
##

**Comment by Aokromes** [comment]
IMHO the way to go is remove c++ spawns.

**Comment by mik1893** [comment]
there is probably a need to adjust the process so the fixed spawns are handled from DB and the dynamic ones (depending on faction) are handled by the core.... but not sure, not really a great fan of wintergrasp, no idea how it works

**Comment by Kittnz** [comment]
https://github.com/TrinityCore/TrinityCore/tree/dynamic_spawning

**Comment by Irome** [comment]
It's been many years since it was first encountered this bug, and there are many people waited until this bug is fixed. There is nobody who is able to solve this problem?

**Comment by Aokromes** [comment]
this issue is still valid?

**Comment by Aokromes** [comment]
i have seen them working on recent versions.
