### ISSUE TITLE
Trial of Crusade - some bosses have problem getting on the floor

### ISSUE THREAD

**Issue by Orphus** [TrinityCore/TrinityCore#9053]
Hello there,
after mmaps were pushed into master I noticed a problem in Trial of Crusade. 
The bosses that are supposed to come from the gate are stuck just behind the gate(in the arena).
This is probably caused by mmaps. They are unable to "go" onto gameobjects(which toc floor is).
Is there any way how to fix it ?

revision https://github.com/TrinityCore/TrinityCore/commit/54027803bdcdefb48007e791f02202a23bf10076 
Ubuntu 11
##

**Comment by Aokromes** [comment]
Work around pushed on 826717de1b184c0e4eb41735b56622bd85a6ba6c, if someone have the knowledge to fix this properly it will be welcomed.

**Comment by Killyana** [comment]
Cannot reproduce on TrinityCore rev. 9614f9d8cf29
