### ISSUE TITLE
[Core / Spell] Hand Of Reckoning no damage when taunting players pet

### ISSUE THREAD

**Issue by blindspell** [TrinityCore/TrinityCore#9068]
Rev:https://github.com/TrinityCore/TrinityCore/commit/9a652b390a82edf897cfc3e46d508a3fedf0fa8f

Bug: The Paladin Spell Hand Of Reckoning should deal damage to  targets which can be taunted and are not currently targeting you . It currently works only for creatures that are not controlled by the player . That should not happen , the spell should also work for creatures that the player controls . When you cast the spell on a pet that the player controls the pet will only receives the taunt effect and not the damage .

Currently the code is only 2 lines in spelleffects.cpp

 if (m_spellInfo->Id == 62124)
        m_caster->CastSpell(unitTarget, 67485, true);

The first id is the taunt effect , the second one is the damage.
##

**Comment by Aokromes** [comment]
If the fix here is valid, plz open a PR.
