### ISSUE TITLE
blackwing lair nefarian Mmaps 

### ISSUE THREAD

**Issue by milotic** [TrinityCore/TrinityCore#9083]
Hi, http://www.wowhead.com/npc=11583 have problem in seccond phase of encounter and fall outside raid.

http://imageshack.us/photo/my-images/585/wowscrnshot012813141130.jpg/

rev: https://github.com/TrinityCore/TrinityCore/commit/da080ac4e796be6039a239b7e035ead02e73b333
##

**Comment by Pirricli** [comment]
Any fix working here? problem persist on 3ea97450aec21619b953753430750e0b4ec92920

**Comment by Pirricli** [comment]
The problem now is different for me. I'll try to explain. Lord Victor Nefarius is not sitting in his throne, but you can speak with him. Once you run the event all is ok until the dragon Nefarian appears. The dragon is on the screen for a few seconds without moving and after that it disappears but I think that it doesn't fall. At this point, change to GM mode on and you will see Lord Victor Nefarius again.

**Comment by sova-bogdan** [comment]
+1 problem

**Comment by Aokromes** [comment]
Can't we enable grid on door open?

**Comment by Rushor** [comment]
the dragon Nefarian spawns manually after the door was opened and Lord Victor Nefarius was in combat for several minutes

we could set him active + load grid on spawn maybe

**Comment by Rushor** [comment]
the dragon Nefarian spawns manually after the door was opened and Lord Victor Nefarius was in combat for several minutes. 

we could set him active + load grid on spawn maybe

**Comment by TecDian** [comment]
The Dragon lands outside the boundaries making it impossible to attack. This is because the landing coordinates are wrong.

Look below - this way the dragon spawns roughly above the despawning human form and descends in the middle of the melee - everything works just fine.

```
 Position const NefarianLoc[2] =
 {
    {-7534.125488f, -1273.477539f, 526.783691f, 3.0f}, // nefarian spawn
    {-7534.125488f, -1273.477539f, 476.798187f, 3.0f}  // nefarian move
 };
```

**Comment by bblewittAG** [comment]
Still getting this issue and is there away to fix this yet without having to recompile the core?

**Comment by Killyana** [comment]
Cannot reproduce on  rev. e4658a1307b1 2019-01-27 15:20:38 +0100 (3.3.5 branch) (Win64, Release, Static)

**Comment by TheWinchesters** [comment]
If this is closed, should I open a issue for the Skadi situation?

**Comment by Killyana** [comment]
Is Skadi  has an issue in the current revision, yes.
