### ISSUE TITLE
mmaps_generator: optimize queue entries

### ISSUE THREAD

**Issue by mweinelt** [TrinityCore/TrinityCore#9091]
The mmaps_generator currently queues whole maps only for generation. 
When starting with alot of threads (--threads 64 or s.th. like that) you can notice that most threads despawn rather quickly (~up to 10 minutes) because the queue is empty. However larger maps are still running for about 2 hours, so threading has basically a weak design for their queue items, because 80% of the time cpu power is not properly being utilized.

for a lack of a better description:
```
<Machiavelli> ah, like multiple threads generating the same map concurrently
<Machiavelli> yeah, maybe BuildMap can be split up into different tasks, that schedule the next part of the task in the queue upon completion (in case of dependencies)
<Machiavelli> will have to look at that into more detail as currently I'm not sure what kind of dark magic BuildMap actually does
```

master / da080ac4e796be6039a239b7e035ead02e73b333

**Comment by danlapps** [comment]
no news since then, did https://github.com/TrinityCore/TrinityCore/commit/ff257363383a4411c013879804512bbef272ba4c fix problem ?

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/ff257363383a4411c013879804512bbef272ba4c didn't fix the problem but it probably mitigated it

**Comment by danlapps** [comment]
Try after https://github.com/TrinityCore/TrinityCore/commit/ff257363383a4411c013879804512bbef272ba4c ?
