### ISSUE TITLE
Zul'Jin

### ISSUE THREAD

**Issue by Razoraxe** [TrinityCore/TrinityCore#9108]
Zul'Jin bugs on 1st phase. He transforms into the eagle and the vortex is cast, but no damage is dealt at all, he just stands there. He can be damaged further, and when reaching 2nd phase (lynx) he attacks normally again.

Revision: 67d46ae
Core Addons: None

**Comment by Killyana** [comment]
Dup: https://github.com/TrinityCore/TrinityCore/issues/4943#issuecomment-81612509
