### ISSUE TITLE
Some quests show the yellow ? even after completed

### ISSUE THREAD

**Issue by Aokromes** [TrinityCore/TrinityCore#9109]
From ticket #9104 that the ticket opener closes every time we reopen.

Quest 8649 and more have the yellow ? even completed, relog stops the quest to be show
Also, if you move outside npc range where you can't see it, and return the npc doesn't show the ? again.

TC: from 3f4c6a9d45a5994bbf5d1dff42038cd3ab6f3535 up to b9074f3491a2.

After complete quest, before relog.
![Clipboard-1](https://f.cloud.github.com/assets/539374/113795/4d4f5fc8-6b78-11e2-8afe-cc40bf3b86cd.jpg)
After complete quest, after relog.
![Clipboard-2](https://f.cloud.github.com/assets/539374/113796/4d561e08-6b78-11e2-97af-d544a59fec83.jpg)

**Comment by Aokromes** [comment]
Another year, 2ed0af7d752b

**Comment by XaveT** [comment]
Still happening... another year later.

TrinityCore rev. 3f886025a255 2016-01-22 22:14:28 +0100 (3.3.5 branch) (Unix, Release)

**Comment by tkrokli** [comment]
TrinityCore rev. e6a7818a9a12 2016-01-24 16:47:39 +0100 (3.3.5 branch) (Win64, Release)
Also confirmed happening with Draenei low-level trainers in the start area 'Crash Site' in Ammen Vale.

Could this be some sort of lag or untriggered event in the server <=> client update procedure?

**Comment by Aokromes** [comment]
7db377c
