### ISSUE TITLE
Player Can't link Quest

### ISSUE THREAD

**Issue by Kingswow** [TrinityCore/TrinityCore#9115]
when i change ChatStrictLinkChecking.Severity = 0 to 3 and set UI.ShowQuestLevelsInDialogs = 1 , players can't link their quests

with UI.ShowQuestLevelsInDialogs = 1 quest helper send error to player and don't work , ofc i know this problem is not your problem and just i say for more info

Core rev : 754418a8de569c2cb4d28e9dde5cf257490b73b9
TDB 335.50 + updates

sry for my bad english
##

**Comment by jackpoz** [comment]
@MrSmite is this related to a feature you added ?

**Comment by MrSmite** [comment]
If it's not an issue with Locales (dbc or table) then it's possible the security check is being done after the quest level is added to the output which might make it appear different than the DBC.

We didn't have Locales when I wrote the patch and this is the first bug report I've seen. Most likely the security check needs to be done before the output string is modified.

**Comment by MrSmite** [comment]
Might I suggest that a quick fix would be to remove the quest level from the chat text and simply leave it in the dialogs (eg: NPC, quest log).

**Comment by jackpoz** [comment]
that might aswell be the proper fix

**Comment by Aokromes** [comment]
any new on this?

**Comment by Killyana** [comment]
Fixed on https://github.com/TrinityCore/TrinityCore/commit/2a531eee68e336f84faffe1f1f4cbcc5a115ca8c
