### ISSUE TITLE
[Vehicule's NPC] Attacking nearby NPC's

### ISSUE THREAD

**Issue by Oxtar** [TrinityCore/TrinityCore#9117]
Well i've crossed it with numerous quest vehicule NPC's (like the Onslaught Warhorse in Dragonblight) once you mount it, it act like a normal NPC.

Example : 

I need to bring that npc to a specific location, i start moving(on the vehicule npc) and if i come accross an npc that aggro me, it will start running toward him and attack him.

The vehicule should not *move* on his own, and above all, not attack. It should be like any vehicule(catapult, etc).

TDB: 335.11.50+
Revision: Latest

Onslaught Warhorse id : 27213

PS: I could get through all of them but i assume if we find out what's happening with 1, we could easily fix the other ones.

**Comment by Aokromes** [comment]
A lot of months since i asked feedback, closing. If this bug is still valid open a new ticket.
