### ISSUE TITLE
[Core / NPC] Mobs chasing you don't attack - just out of range

### ISSUE THREAD

**Issue by MrSmite** [TrinityCore/TrinityCore#9191]
__Rev:__ 1b4a6109764d74d6b440bcd796c2b375aa660096

__Bug:__

When a mob is chasing you, they never seem to catch up to you. They follow you just out of melee range doing a sort of stutter-step. You can pretty much escape from any mob.

__Details:__

To test:

> * Aggro any mob and wait for it to smack you (melee range)
> * Turn around and run away (no speed buffs)
> * Observe the mob just out of melee range, never attacking you
> * Observe the mob doing a stutter-step once in a while (typically on the step that would bring it within melee range)

__Note:__

At first I thought this might be an MMaps issue but it does it without MMaps enabled. Maybe an issue with the new maps themselves? Possibly a vmaps issue?

**Comment by Killyana** [comment]
Cannot reproduce on rev. 5dba91fb0e38

**Comment by MrSmite** [comment]
> Cannot reproduce on rev. 5dba91f

Seems as if the problem is largely resolved. I still occasionally see my pets do it but it's rare and may even just be a visual bug.
