### ISSUE TITLE
shaman "Sentry Totem" explained

### ISSUE THREAD

**Issue by ghost** [TrinityCore/TrinityCore#9197]
6495 - [Sentry Totem, rank1 enUS]

when you cast this spell you get a buff named  6277- "Bind Sight (PT)" and your getting possed in a totem somewhere around the map, weird. I think the totem should be the one who receives the buff not the player, or something is wrong.

The totem is spawned too far away from the caster

Ok I reproduced, compiled the core again right now:

screenshot ingame bug here http://img12.imageshack.us/img12/4189/wowscrnshot021113201928.jpg

Using configuration file worldserver.conf.
Using SSL version: OpenSSL 1.0.1c 10 May 2012 (library: OpenSSL 1.0.1c 10 May 2012)
Using ACE version: 6.1.4
TrinityCore rev. 2013-02-11 14:51:26 +0100 (620a43b4efa4) (Win32, Release) (worldserver-daemon)

Realm running as realm ID 1
Using World DB: TDB 335.49

**Comment by Killyana** [comment]
Works correctly on rev. 5dba91fb0e38
Also wrong report as the player and the totem both must have the aura: https://www.youtube.com/watch?v=ameF6Wl9pSs
