### ISSUE TITLE
Wintergrasp Walls & Workshops - Visibility Range

### ISSUE THREAD

**Issue by Ric101** [TrinityCore/TrinityCore#9205]
Wintergrasp as a whole, perhaps even given objects in SotA are supposed to be able to see from quite a large distance, though I cannot dictate exact measures, it's far, far larger than the standard object sighting. This issue includes all walls, and all workshops - as well as the gates.
##

**Comment by offl** [comment]
#21111

**Comment by tkrokli** [comment]
Agreed. General issue #21111 -- please post helpful comments in that ticket.
