### ISSUE TITLE
[Bug} halion Outside the scope of the fire

### ISSUE THREAD

**Issue by MMRm** [TrinityCore/TrinityCore#9241]
hi

1 - halion Move Outside the scope of the fire
2 - start fight 
3 - Easy kill boss 

Core: b38fc89
DB: TDB b38fc89

**Comment by Killyana** [comment]
The radius must be reduced
https://github.com/TrinityCore/TrinityCore/commit/335fe8e1b05edfe41d29fee92ee32f356270cff9#diff-dfac192243acf131fde34c6fc9012617R398

**Comment by Keader** [comment]
i cant reproduce this on rev b646bcbb915ad6abcec5d349b28a74991e1c8cad
