### ISSUE TITLE
[Volkhan] - Heat

### ISSUE THREAD

**Issue by click** [TrinityCore/TrinityCore#925]
NPC: [http://www.wowhead.com/npc=28587]

Spell:
Normal: [http://old.wowhead.com/spell=52387]
Heroic: [http://old.wowhead.com/spell=59528]

Error: Spell not work

Core: https://github.com/TrinityCore/TrinityCore/commit/13acb0e4f9e8aef13f20eefd74bb0b0f94520120

**Comment by Aokromes** [comment]
This is fixed already no?

**Comment by Rushor** [comment]
yep:
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Northrend/Ulduar/HallsOfLightning/boss_volkhan.cpp#L206
