### ISSUE TITLE
Pets Haste benefit Owner Haste

### ISSUE THREAD

**Issue by saqirmdev** [TrinityCore/TrinityCore#9279]
Pet dont have Haste from his owner.

![WoWScrnShot_022213_231056](https://f.cloud.github.com/assets/2022891/186899/729cbb6e-7d3d-11e2-913f-6d76720a6d13.jpg)
rev: https://github.com/TrinityCore/TrinityCore/commit/729a37363b7613b95fa2c629adfa68c0b7dc3835

**Comment by Killyana** [comment]
Same issue as https://github.com/TrinityCore/TrinityCore/issues/874 possible fix: https://github.com/TrinityCore/TrinityCore/issues/9526
