### ISSUE TITLE
[6.x] Camera height and collision box

### ISSUE THREAD

**Issue by Drakhian** [TrinityCore/TrinityCore#9285]
TrinityCore rev. 2013-02-22 23:10:30 +0100 (2672d134436b)
DB rev TDB_full_434.04_2013_02_14 with updates

Hello, there is a problem with the camera and the player's character collision box when the character grow or shrink or when the character is mounted. I'm not sure if it is a known issue. This doesn't happening on blizzard's server.
It seems that the camera and the collision box aren't updated until a logout or a map change.

![screen1](https://f.cloud.github.com/assets/3681222/188617/9e6a6842-7dfe-11e2-8533-8f862963dc17.jpg)

As you can see above the camera it at the head level.
But when the character grow with spells like "Elite" "Experienced" or "Unholy Growth" for example, the camera's height stay the same.
The same applies to the collision box, the character can pass through objects.

![screen2](https://f.cloud.github.com/assets/3681222/188619/c62b030a-7dfe-11e2-8a4e-cd0548fa3a4c.jpg)
![screen3](https://f.cloud.github.com/assets/3681222/188625/3ec6f328-7dff-11e2-8560-53bbe417fe2d.jpg)

But after a logout or a map change the camera is updated at the head position with the collision box.

![screen4](https://f.cloud.github.com/assets/3681222/188631/a82fcdf8-7dff-11e2-8799-827c9801b047.jpg)
![screen5](https://f.cloud.github.com/assets/3681222/188632/fdd54d1e-7dff-11e2-814e-2aa5142cd870.jpg)

A same thing happen with mounts, after a dismount the camera goes to the ground.

![screen6](https://f.cloud.github.com/assets/3681222/188635/8755a85e-7e00-11e2-9c6a-2216142e70de.jpg)
![screen7](https://f.cloud.github.com/assets/3681222/188636/9245a520-7e00-11e2-9c28-4914a9bbb954.jpg)

And after a logout or a map change the camera come back to the head.

![screen8](https://f.cloud.github.com/assets/3681222/188637/c20642ec-7e00-11e2-9cee-2300dd55071f.jpg)

I remember a long time ago that the camera and the collision box were updated immediately after the character modification.

Voilà, it's not an important issue but I hope this will be useful.

**Comment by Krudor** [comment]
Still an issue on 6.x branch, missing label? :)
