### ISSUE TITLE
[Quest] Reborn From The Ashes

### ISSUE THREAD

**Issue by TheMaaster** [TrinityCore/TrinityCore#9286]
i was as usual looking for more quests to do...
this time i tought i could find [Reborn From The Ashes](http://old.wowhead.com/quest=13347) from [Alexstrasza the Life-Binder](http://old.wowhead.com/npc=31333) but can't seem to find her
i did manage to find a shield looking the part at the location
but not sure if its [Fordragon's Shield](http://www.wowhead.com/object=193196) as i can't interact with it in any way
let alone get the item [Fordragon's Shield](http://www.wowhead.com/item=44474)

Core revision: Trinity Core b1d43f837a2c+ 
Database revision: TDB 335.51

**Comment by Killyana** [comment]
Fixed for both factions, (Darkness Stirs) for the horde.
rev. 5dba91fb0e38
