### ISSUE TITLE
[4.3.4] Problem Mirror Image Spell

### ISSUE THREAD

**Issue by weyderfs** [TrinityCore/TrinityCore#9287]
Hi, 

I have a problem in mirror images mage:

First - Casting them and following an error saying it can not clone weapons;

Second - Sometimes they stand, sometimes out of running near us but still standing absolutely not do anything.

Would you like some help in order to solve this problem.
Already grateful.
##

**Comment by danlapps** [comment]
Is this considered valid fix ?

**Comment by Aokromes** [comment]
This is needed on 6.x?

**Comment by Aokromes** [comment]
IDK if valid.

https://github.com/ProjectSkyfire/SkyFire.548/commit/e5eeb65163445c5bd5436919576b0beea0baeebc

**Comment by Aokromes** [comment]
superseded by https://github.com/TrinityCore/TrinityCore/issues/19590
