### ISSUE TITLE
[Suggestion] Quest flags - do not recast reward spells at login

### ISSUE THREAD

**Issue by dr-j** [TrinityCore/TrinityCore#9305]
This is really a suggestion for a new flag for quests to tell core not to recast reward spells at login for given quest,

The idea behind this to to fix the issue with tailoring, alchemy and other profession specialisations where by if you change specialisation even though the specialisation does get removed when you you pay the gold to change specialisation upon relog this reappears in spellbook, from what I can work out this is because spellcasts which are rewarded from quests are recast at login, worked this out as if you remove the quest which rewarded the spell from player via db this no longer happens.

at the moment if you change specialisations to a different specialisation to a different one to you picked originally you end up with 2 specialations in spellbook after you relog once.
##

**Comment by Killyana** [comment]
Cannot reproduce on rev. fa3eb754cbe1
