### ISSUE TITLE
RDF - Random Dungeon reward problem

### ISSUE THREAD

**Issue by Vasago** [TrinityCore/TrinityCore#9307]
Hello, 
I have active event with headless horseman for testing ... And I noticed when I use RDF to kill only the boss Headless Horseman - I get reward - that is ok but When I go random dungeon heroic, I do not get the reward for first time  but like I was it the second time. 

There should be separate rewards for event RDF rewards and normal RDF rewards. I think this is just one line code fix to add exception?

Core: https://github.com/TrinityCore/TrinityCore/commit/d3ad8a4941124aae2b2ced6cc75c18ec8498664a

**Comment by Treeston** [comment]
Still exists ae58f8e616362a6d92e317e6edc576054da14975

**Comment by Treeston** [comment]
Fixed in 97e0d1b
