### ISSUE TITLE
[Icc/Lich King] Val'kyr Shadowguard stun too soon bug.

### ISSUE THREAD

**Issue by Sqruel** [TrinityCore/TrinityCore#9309]
Problem: If you stun(freeze etc) the Val'kyrs too soon (before they grab players and start moving) they will fly instantly to the far edge and ppl can't be saved.

How it should work: They should be stunned and stay in place.

**Comment by Killyana** [comment]
As there's already an issue for this npc I will close this one https://github.com/TrinityCore/TrinityCore/issues/7266
