### ISSUE TITLE
[FIX] NPC Infernal Hound (TC 3.3.5a)

### ISSUE THREAD

**Issue by SignFinder** [TrinityCore/TrinityCore#9319]
NPC Infernal Hound (19207) have not right type and flags.
http://www.wowwiki.com/Highlord_Kruul
http://www.wowwiki.com/Infernal_Hound
This NPC - daemon and not taimed.
IN TDB - this NPC - beast and taimed with hunters.

Fix
```SQL
-- Infernal Hound - is daemon and can't be tamed
UPDATE `creature_template` SET `type` = 3, `type_flags` = 0 WHERE  `entry` = 19207;
```

**Comment by Killyana** [comment]
As you can see: http://www.wowhead.com/npc=19207/infernal-hound : Tameable (Core Hound)
So it's correct.
