### ISSUE TITLE
Bloodthistle Withdrawal not triggered

### ISSUE THREAD

**Issue by Registrar** [TrinityCore/TrinityCore#9343]
Rev: 5d4e657e91604b37dc0af814ff7562e3a084139b
TDB: Updated 51

As current, when the buff "Bloodthistle" (spell=28273) ends, the debuff "Bloodthistle Withdrawal" (spell=28274) is not triggered. This is not WAI.

AFAIK, the negative aura Bloodthistle Withdrawal (spell=28274) should also be removed when a character consumes another Bloodthistle (spell=28273/item=22710). Currently this is not the case. This is also not WAI.

This issue is small and I'd fix it myself if I had any knowledge of the core whatsoever. Sorry!

**Comment by danlapps** [comment]
Nothing on that for 2 years, is this still valid ?

**Comment by Killyana** [comment]
``` sql
INSERT INTO `spell_linked_spell` VALUES (28273, -28274, 0, 'Bloodthistle');
INSERT INTO `spell_linked_spell` VALUES (-28273, 28274, 0, 'Bloodthistle');
DELETE FROM `spell_linked_spell` WHERE `spell_trigger` = 28273;
DELETE FROM `spell_linked_spell` WHERE `spell_trigger` = -28273;
