### ISSUE TITLE
Some visual Bugs to Profession trainers

### ISSUE THREAD

**Issue by ghost** [TrinityCore/TrinityCore#9353]
In the top left near the Filter dropbox you'll see something like:

4331603 + 632835424/0 or  4331603 + 549943568

For every profession trainer it shows a long number!
tradeskills trade skills

---

Screens:

Minning trainer: http://img40.imageshack.us/img40/4276/wowscrnshot030513192038.jpg

Blacksmithing Trainer: http://img203.imageshack.us/img203/5070/wowscrnshot030513192718.jpg

---

Using configuration file worldserver.conf.
Using SSL version: OpenSSL 1.0.1c 10 May 2012 (library: OpenSSL 1.0.1c 10 May 2012)
Using ACE version: 6.1.4
TrinityCore rev. 4b4199d75b59 2013-03-04 23:44:25 +0100 (4.3.4 branch) (Win32, Release) (worldserver-daemon)

Realm running as realm ID 1
Using World DB: TDB 434.04
##

**Comment by giridhar123** [comment]
Confimed!

**Comment by tkrokli** [comment]
@giridhar123 : please add commit hash & TDB version to your comment, for future reference.

**Comment by Aokromes** [comment]
Still bugged on 42ab42ce2781.
http://i.imgur.com/Du3Yfnk.png

**Comment by Aokromes** [comment]
BTW this bug is only show when you don't known the skill, valgrid and sniffs don't helps to see what's incorrect here.

**Comment by killradio** [comment]
Here what I found:
From trainerUI addon - if GetTrainerServiceStepIndex() returns value > 0 - bar with huge numbers is shown. From IDA pseudocode:
```cpp
signed int __cdecl Script_GetTrainerServiceStepIndex(int a1)
{
  signed int result; // eax@2

  if ( dword_D15A28 < 0 )
  {
    result = 0;
  }
  else
  {
    FrameScript::PushInteger(a1, dword_D15A28 + 1);
    result = 1;
  }
  return result;
}
```
Most interesting part is ```( dword_D15A28 < 0 )``` - I suppose ```dword_D15A28``` is one of the player fields, but the problem is all player fields related to professions/skills can't be negative (from _LoadSkills):
```cpp
    for (; count < PLAYER_MAX_SKILLS; ++count)
    {
        uint16 field = count / 2;
        uint8 offset = count & 1;

        SetUInt16Value(PLAYER_SKILL_LINEID_0 + field, offset, 0);
        SetUInt16Value(PLAYER_SKILL_STEP_0 + field, offset, 0);
        SetUInt16Value(PLAYER_SKILL_RANK_0 + field, offset, 0);
        SetUInt16Value(PLAYER_SKILL_MAX_RANK_0 + field, offset, 0);
        SetUInt16Value(PLAYER_SKILL_MODIFIER_0 + field, offset, 0);
        SetUInt16Value(PLAYER_SKILL_TALENT_0 + field, offset, 0);
    }
```
Mb someone more familiar with IDA can find the meaning of ```dword_D15A28``` and how it can be initialized. Link to idb (15595) - https://mega.nz/#!L0hygI4Q

**Comment by Aokromes** [comment]
I found retail 4.3.4 and 7.03 sniffs  sends 

CMSG_TRAINER_LIST 

before SMSG_TRAINER_LIST

**Comment by killradio** [comment]
Another question, do we rly need this part:
```cpp
    for (; count < PLAYER_MAX_SKILLS; ++count)
    {
        uint16 field = count / 2;
        uint8 offset = count & 1;

        SetUInt16Value(PLAYER_SKILL_LINEID_0 + field, offset, 0);
        SetUInt16Value(PLAYER_SKILL_STEP_0 + field, offset, 0);
        SetUInt16Value(PLAYER_SKILL_RANK_0 + field, offset, 0);
        SetUInt16Value(PLAYER_SKILL_MAX_RANK_0 + field, offset, 0);
        SetUInt16Value(PLAYER_SKILL_MODIFIER_0 + field, offset, 0);
        SetUInt16Value(PLAYER_SKILL_TALENT_0 + field, offset, 0);
    }
```
to populate rest of player fields with zero values?

**Comment by msoky** [comment]
try test after https://github.com/TrinityCore/TrinityCore/commit/21f4ee8a9ae7ec108f87729a17c6fccc2847c040

**Comment by Aokromes** [comment]
totaly unrelated.

**Comment by msoky** [comment]
but it can helps in future, maybe something changed..

**Comment by Killyana** [comment]
Fixed
