### ISSUE TITLE
Quest (Death From Above)

### ISSUE THREAD

**Issue by Expecto** [TrinityCore/TrinityCore#9359]
Doesn*t Work Spell http://www.wowhead.com/spell=46361 For quest http://www.wowhead.com/quest=11889

NPC does not fall on the ground after use Item

Rev Hash 7508e8cf6579c7c9e5cdaae6cde3c00ab6fa2d8a

DB TDB 11.50

Screenshot: http://www.imageup.ru/img281/1238026/wowscrnshot_030613_173921.jpg

**Comment by Killyana** [comment]
Fixed.
rev. 5dba91fb0e38
