### ISSUE TITLE
Entering and Leaving combat stance too soon.

### ISSUE THREAD

**Issue by Ricky93** [TrinityCore/TrinityCore#9366]
Hi, If the realm type is set to Normal you enter and leave combat stance too soon when fighting players. You need to set it to PvP.
![WoWScrnShot_030513_082722](https://f.cloud.github.com/assets/3792753/230656/730e24e6-86cc-11e2-979d-89bb1c236c7b.jpg)

**Comment by Killyana** [comment]
Cannot reproduce on rev. 5dba91fb0e38
