### ISSUE TITLE
[SPELL] Seal of Vengeance Melee

### ISSUE THREAD

**Issue by Mercilessss** [TrinityCore/TrinityCore#9374]
I have a question.

Why Seal of Vengeance isn't considered melee attack in this rev?

http://www.wowwiki.com/Seal_of_Vengeance

After 3.2 patch, Seal of Vengeance dmg can be parried, dodged, blocked or missed BUT isn't work, SOV sill working about magic damage and can't be parried blocked dodged or missed.

Im using bed73397b6bb288388d6b069af75361d5c45613c

I think so this the Tiny Abomination in a Jar doesn't work properly.

**Comment by Killyana** [comment]
Dup https://github.com/TrinityCore/TrinityCore/issues/3463
