### ISSUE TITLE
EOE Hover disc+druid feral+scion 

### ISSUE THREAD

**Issue by milotic** [TrinityCore/TrinityCore#9389]
Hi, if druid feral player take http://www.wowhead.com/npc=30248/ for fight http://www.wowhead.com/npc=30249 any spell use for druid dont put combo points on this npc

rev: https://github.com/TrinityCore/TrinityCore/commit/b4542c65048344019007a666a2bd35f9453d5664
##

**Comment by offl** [comment]
Should be tested after 489478b74d96c2ea940a2316fd11f8e81991cf07

**Comment by Killyana** [comment]
Cannot reproduce on rev. 95d298780010
