### ISSUE TITLE
Quest # 10055 Waste not want.  Gameobjects not working for all races.

### ISSUE THREAD

**Issue by kelsarhu** [TrinityCore/TrinityCore#9428]
The gameobjects are faction restricted when they are not supposed to be.
here is the fix to make them all non-faction dependant.

UPDATE gameobject_template
SET faction = 94
WHERE
	entry IN (
		182797,
		182798,
		182799,
		182936,
		182937,
		182938
	)

**Comment by Aokromes** [comment]
Near 1 year since my feedback request, closing. If this bug is still valid open a new ticket.
