### ISSUE TITLE
[Warrior] Fury Warrior Auto-Attack

### ISSUE THREAD

**Issue by click** [TrinityCore/TrinityCore#945]
While using Titan's grip [46917] in the talent tree and equipping two-handed weapons in both hands 
on the first weapons swing the warrior lands a hit only with his Main-handed weapon this is a rage, dps and proc chance loss for trinkets and talent bonuses.
The bug has been confirmed buy Gm and by some players.
Thank you for your help.
Rev:11271 Hash:e918a7f Tdb: 33.11.36

**Comment by ariel-** [comment]
The problem is here:

https://github.com/TrinityCore/TrinityCore/blob/6.x/src/server/game/Entities/Unit/Unit.cpp#L6935-L6937

Not only affects titan grip warriors, but every dual wield class gets a full swing timer delay with his offhand.
