### ISSUE TITLE
Professor Putricide Slimes

### ISSUE THREAD

**Issue by Ganztxd** [TrinityCore/TrinityCore#9450]
Hello everyone, on ICC 25 player when Professor Putricide summons a slime, this one cast a spell.
Problem is that this cast can be interrupt with fear, silence, charge/intercept and maybe i forgot another cc spell.
This slimes should be inmune to cc.

**Comment by Pirricli** [comment]
Confirmed. It's easy to kill casting fear or stunning.

cac4f95976989a70fc7f5b50f0d76100300af067

**Comment by Aokromes** [comment]
#12020
