### ISSUE TITLE
[4.3.4] [Spell System] Spell radius calculation

### ISSUE THREAD

**Issue by joshwhedon** [TrinityCore/TrinityCore#9457]
SpellEffectInfo::CalcRadius(Unit* caster, Spell* spell) const

From what I saw there is something basically wrong with the radius calculation in 4.3.4. A lot of spells I've encountered (particularly boss spells) have a max radius inferior to the Radius, and the max radius seems more correct in game for the distance calculation than the radius. (examples : 88814, 91196, 89133)
In some cases, when there is both a radius and a max radius, and when the max radius is superior to the radius, the max radius seems more correct than the radius too. (example : spell 76684, visual on the floor is clearly larger than 4 yards, but damage is taken only when 4 yards away).

Core version:
https://github.com/TrinityCore/TrinityCore/commit/d06ada08077f770c84f2ffde898b9c5966187f9c

**Comment by Killyana** [comment]
Dupe https://github.com/TrinityCore/TrinityCore/issues/3923
