### ISSUE TITLE
[NPC/Text] Death's Challenge

### ISSUE THREAD

**Issue by Master-Warrior** [TrinityCore/TrinityCore#9464]
When you duel the Death Knights Initiate for quest (http://old.wowhead.com/quest=12733) should say something like this:
Are you challenging me, $g brother:sister;?

http://old.wowhead.com/npc=28406

All it does is show an error in the worldserver, when you try to duel the npc:
CreatureTextMgr: Could not find TextGroup 1 for Creature(Death Knight Initiate) GuidLow 129546 Entry 28406. Ignoring.

Hash: 52340e74e288377cdcd05821bc6b1507d10c6ee6
TDB 335.51+ updates
OS: Unix

**Comment by Aokromes** [comment]
This bug is still valid?

**Comment by Rushor** [comment]
http://pokit.org/get/?7ce95d0e795a3871894c8f802d731e01.jpg
texts are given

no runtimeerrors
- > last messages while doing the quest 
http://pokit.org/get/?1bd4c80195081e109a146fba85837e6f.jpg
- > so nothing related to the quest
