### ISSUE TITLE
Friend or Fowl achievement

### ISSUE THREAD

**Issue by Lat89** [TrinityCore/TrinityCore#9497]
Its still bugged. @ rev 7aa23809138c4b7acf08d08eeebf9a330a66844e

In #3609 its stated that the marker doesnt stack from different casters, meaning different turkeys, but currently it does. As you can see here http://oi50.tinypic.com/fctx1i.jpg after killing 2 different turkeys, ive listed my auras and i got 2 stacks of turkey marker. The problem is, after you get 15 stacks of turkey marker, you dont receive the achievement. Any solutions?

**Comment by D4R4** [comment]
As a hack you could just remove the OnApply completely and add this check to your OnPeriodic

```
				Unit* target = GetTarget();
				if (GetStackAmount() >= 15)
				{
					target->CastSpell(target, SPELL_TURKEY_VENGEANCE, true, NULL, aurEff, GetCasterGUID());
					target->RemoveAura(25281);
				}
```

**Comment by GeneralSaurfang** [comment]
Warriors' Sunder Armor works fine:
Warrior A: Casts Sunder Armor.
(1 stack on the target)
Warrior B: Casts Sunder Armor.
(2 stacks on the target)

So in the case of sunder armor, same auras from different sources are stacking properly.
Can't this issue here get fixed the same way sunder armor was fixed?

**Comment by Rushor** [comment]
wrong issue @GeneralSaurfang?

**Comment by tkrokli** [comment]
@Rushor : I don't think so. He compared the 'Sunder Armor' aura stacks on the warriors' combat target
to the player character being a target for the 'Turkey Marker' auras from the 15 turkey kills
(required for the achievement).

**Comment by GeneralSaurfang** [comment]
@Rushor & @tkrokli : Yes I meant what tkrokli said.

The problem with this achievement here seems to that auras cast by different turkeys on the player do not stack together. But in case of Sunder Armor, they do. So maybe what was done for Sunder Armor can be done here too?

**Comment by Killyana** [comment]
No, the auras stack correctly, just once the player get 15, this spell http://wotlk.openwow.com/spell=25285 must be casted to give him the Achievement and start the event.

**Comment by Killyana** [comment]
DRJ find out that if you get the 15 stack than logout and login you the spell will be casted and you will get the achievement.
Something is wrong here: 
https://github.com/TrinityCore/TrinityCore/blob/675a2fcd3b4e46b79c57ead0fc455c4f6e4b03db/src/server/scripts/Spells/spell_generic.cpp#L3363
