### ISSUE TITLE
[Core/Entities] Regenerating HP of vehicles part 2

### ISSUE THREAD

**Issue by click** [TrinityCore/TrinityCore#950]
CORE revision number : e4c0a8033680e
Database: TDB 335.11.38
Patches: None

Continuation from this ticket http://www.trinitycore.org/t/trinitycore/ticket/317 it was not fixed. New things i have learned:
- It seems only in raids in battlegrounds there is not applied this condition to not regenerate HP from vehicles, because in one by one testing it seems to be working sometimes vehicle is destroyed after reload vehicle with less HP.

What steps will reproduce the problem?
1. Get on vehicle for example in sota
2. Damge this vehicle to have less HP
3. Get off and on vehicle again it has full HP even when in DB is disabled 

It seems it is NOT DB problem because when I set RegenHealth=0 it is still regenerating after reload the vehicle.
##

**Comment by Keader** [comment]
still bugged on 41e62739942907e1efa2a4656b4717c885873f1d
Also I think it's something with the 'Evade Mode'

**Comment by Laintime** [comment]
Confirm.Baged What steps will reproduce the problem?

Damge this vehicle to have less HP
Get off and on vehicle again it has full HP

**Comment by Laintime** [comment]
Confirm https://github.com/TrinityCore/TrinityCore/commit/c6060dd0c511ddad3cb1f0423aa9ccf2de7aedec 
Maybe hack this?

**Comment by Keader** [comment]
https://github.com/TrinityCore/TrinityCore/issues/19178#issuecomment-281228526

**Comment by Jildor** [comment]
@Keader I'm not test fix of @sirikfoll, but I think if add this when vehicle respawn, the vehicle appear dead (same if change regenHealth=0 in BD)

**Comment by Noryad** [comment]
@Keader @Jildor 
>#19178 (comment)

The @sirikfoll  fix works ok for me.

**Comment by Jildor** [comment]
@Noryad try to kill vehicles in isle of conquest and wait to respawn (or in SotA I think the same)
I not try with this fix but I think is the same change it in creature_template

**Comment by Noryad** [comment]
@Jildor you are right, the vehicle appear dead :(
