### ISSUE TITLE
[SAI] Unable to target vehicle passengers

### ISSUE THREAD

**Issue by Ric101** [TrinityCore/TrinityCore#9511]
Mostly, in vehicle situations (mostly where there's spellcasting, and we wish to use EVENT_SPELLHIT), there's no option when the ACTION_INVOKER is the vehicle itself to do actions on the player of that vehicle - which would be true ACTION_INVOKER
Not a spellsystem problem, perhaps not even an issue (just a missing feature?)

I have a suggestion nonetheless, why not multi-use 'SMART_TARGET_ACTION_INVOKER_VEHICLE'? If the target is a vehicle, we target the vehicle's passenger by one of the provided target fields (seat?), and if the target is not a vehicle (how it is currently) the VehicleBase is taken
##

**Comment by Killyana** [comment]
Looks to be fixed as here you can see the target 23 is used by the vehicle to cast the spell on its owner: https://github.com/TrinityCore/TrinityCore/commit/210e45e303b1ae33ff4bb2c21727b27ae58f0a6c#diff-818d7b242b28f42f86ca2acc93dd3413R78
