### ISSUE TITLE
[4.3.4] Missing Firelands Scripts

### ISSUE THREAD

**Issue by silvermcd123** [TrinityCore/TrinityCore#9529]
This is not a priority but still i think is good to keep it tracked

Rev: https://github.com/TrinityCore/TrinityCore/commit/f63fd0bc184448c0a910da52ad71332063857e28
Using: TDB
No Costum Patches

There is no scripts on firelands.

Also i would like to suggest this repo:
https://github.com/Naios/CataclysmScripts/tree/master/misc/Dreadiis%20old%20Scriptrepo

it has all scripts, we could test them on trinitycore and upgrade them :)

**Comment by Walkum** [comment]
Don't try fool anyone, you don't want unite forces, you only want get the work of other persons for your private server, if you want something, first contribute and help community.
