### ISSUE TITLE
vehicles hp regeneration on dismount

### ISSUE THREAD

**Issue by xpund1** [TrinityCore/TrinityCore#9531]
void Vehicle::RemovePassenger(Unit* unit)
 {
    if(unit->GetVehicle() != this)
        return;
+   if(unit->GetTypeId() == TYPEID_PLAYER && unit->HasUnitState(UNIT_STAT_DIED))
+       sScriptMgr->OnRemovePassenger(this, unit);

This is fix bug HP

**Comment by Aokromes** [comment]
#950
