### ISSUE TITLE
[4.3.4] creature_(template_)addons should be removed on npc death

### ISSUE THREAD

**Issue by ghost** [TrinityCore/TrinityCore#9537]
After some research i found the reason of some client crashes on dead npc's: the core still tries to play emotes if the npc's is dead. so we need to kill the emote value set in creature template addon. btw this only happens in 3rd class made npc's like the 2 guards at Instructor Razovious. just move emote 36 npc's to smartai and handle the emote each second

**Comment by tkrokli** [comment]
The first query returns 3212 rows from TDB 6.04 + updates up to and including `2016_06_14_00_world.sql`
The second query returns only 377 NPC rows. Not quite sure about the distinction between them yet.

**Comment by Aokromes** [comment]
#15263 more detailed
