### ISSUE TITLE
[3.3.5a] [Spell] Dispersion

### ISSUE THREAD

**Issue by Loginisalreadytaken** [TrinityCore/TrinityCore#9560]
http://www.wowhead.com/spell=47585
http://www.wowhead.com/spell=72999

Version: 3.3.5a (12340)
Core revision: Trinity Core b78885622078+
Database revision: TDB 335.51

Dispersion doesn't reduce the Shadow Prison damage. I am certain there are a few more spells that are ignoring it in ICC (when they shouldn't), but this one I know for sure.
##

**Comment by Rushor** [comment]
remove the attribute:
AttributesEx3: 0x20000000 (SPELL_ATTR3_NO_DONE_BONUS)

from the spell - btw someone has a proof for this?

**Comment by P-Kito** [comment]
Alot of spells on retail pierce through dispersion or divine shield, I think this is intended.

**Comment by Killyana** [comment]
@ariel-  this issue is valid ?

**Comment by ariel-** [comment]
Yes, still valid, the problem is the spellscript is calculating the damage after reduction from Dispersion
