### ISSUE TITLE
[3.3.5a] joining arena queue after server re-start

### ISSUE THREAD

**Issue by Kurukuku** [TrinityCore/TrinityCore#9570]
there is an old bug that happens when the server re-starts.
the first 5-10 min after the re-start, if you join arena queue, the server do not care your mmr, so, you can battle versus the next team who queue. 

for instance, the server re-start, you enter and you join arena queue and your team has 2400 mmr. Then another team joins, it has 1400 mmr. It is totally imposible they battle together because the high difference of mmr (in the server we have 150 of mmr diference to battle and 10 min if noone with the requiered mmr joined), but in this period of time they can battle. 
 
P:S: If you dont know how arena system works, just tell it and i will be glad to explain

**Comment by Carbenium** [comment]
6a637f6b1c186eb15373fce443d729dcc74e5361
