### ISSUE TITLE
[3.3.5a] [Spell] Felguard's Cleave stuck on autocast

### ISSUE THREAD

**Issue by Loginisalreadytaken** [TrinityCore/TrinityCore#9575]
https://github.com/TrinityCore/TrinityCore/issues/9576
spell=30223 (?)

Version: 3.3.5a (12340)
Core revision: Trinity Core b788856+
Database revision: TDB 335.51

The felguard's Cleave is one of those pet abilities that can be autocast. The issue here is that no matter if the autocast is on or off (which seems to be saved properly), every time the felguard is summoned, it uses Cleave automatically. It's a minor inconvenience and can be temporarily fixed by turning autocast on and off again.
I'm not sure, but I'd suspect that this error is a general one for other pets and abilities as well.
This bug can cause a moderate headache in situations described in my next bug report. (adding a link at the top in a few minutes)
##

**Comment by Rushor** [comment]
the problem also affects the 'fireshield' cast from the imp - the option if the autocast was enabled or not on the very first summon will not be saved and resets to 'autocast' on the second summon.

probably all pets are affected by that?

**Comment by ariel-** [comment]
> (adding a link at the top in a few minutes)

I'm still waiting

**Comment by Keader** [comment]
Fixed by 906498e9f4d80ff10094cd3f365b310d9dec4521 and ecf59786085cb8750bf48bbfa4f4f3d49b924dbd
