### ISSUE TITLE
[3.3.5a] [Spell] Felguard's Cleave hits friendlies

### ISSUE THREAD

**Issue by Loginisalreadytaken** [TrinityCore/TrinityCore#9576]
https://github.com/TrinityCore/TrinityCore/issues/9575
http://www.wowhead.com/npc=37119
http://www.wowhead.com/npc=37129
http://www.wowhead.com/npc=37125

Version: 3.3.5a (12340)
Core revision: Trinity Core b788856+
Database revision: TDB 335.51

Yep, that it does. The three guys linked above (among others) are NPCs that the felguard can get in combat with - someone buffs the demon and soon the whole raid is permanently in combat with the muppets.
This one time (at band camp), Captain Rupert started whacking my precious and so Svalna didn't kill him. I set the demon on defensive and healed when needed. We defeated her and the undead former friendlies and eventually, while rescuing Valithria, Rupert got defeated by Haatom!
##

**Comment by Killyana** [comment]
Cannot reproduce on rev. fa3eb754cbe1
