### ISSUE TITLE
Spell Chakra 4.3.4

### ISSUE THREAD

**Issue by XPaiN2008** [TrinityCore/TrinityCore#9582]
Full bug! You don't have http://www.wowhead.com/spell=81208
Holy Word: Chastise  NEVER Active... http://www.wowhead.com/spell=88625

Chakra: Serenity  http://www.wowhead.com/spell=81208
Chakra: Sanctuary http://www.wowhead.com/spell=81206
Chakra: Chastise http://www.wowhead.com/spell=81209

http://www.wowhead.com/spell=88625#comments
##

**Comment by Killyana** [comment]
Patch 7.0.3 (2016-07-19): Chakras have been removed.
