### ISSUE TITLE
[Achievement] Full House

### ISSUE THREAD

**Issue by Ryosan23** [TrinityCore/TrinityCore#9597]
Full House (10-25 player)
Defeat Lady Deathwhisper with at least five different types of Cultists active at the time of her demise in 10-25 player mode. 

http://www.wowhead.com/achievement=4535/full-house-10-player
http://www.wowhead.com/achievement=4611/full-house-25-player

How to reproduce the bug: 
- The achievement doesn't count. Must count when at least five adds is alive, and in the script is correct implement:

                // Full House achievement
                for (SummonList::iterator itr = summons.begin(); itr != summons.end(); ++itr)
                    if (Unit* unit = ObjectAccessor::GetUnit(*me, *itr))
                        if (unit->isAlive() && unit->GetEntry() != NPC_VENGEFUL_SHADE)
                            livingAddEntries.insert(unit->GetEntry());

                if (livingAddEntries.size() >= 5)
                    instance->DoUpdateAchievementCriteria(ACHIEVEMENT_CRITERIA_TYPE_BE_SPELL_TARGET, SPELL_FULL_HOUSE, 0, me);

The problem is in the spell, that doesn't exist in the dbc, concretly: 

    // Achievement
    SPELL_FULL_HOUSE  = 72827, // does not exist in dbc but still can be used for criteria check

TDB: 11.49
Win 7

**Comment by sirikfoll** [comment]
The Achievement ,already scripted, works fine, but at the moment it's unobtainable because of the issue with the NPCs in #5549
