### ISSUE TITLE
[3.3.5a] [NPC] Weaponsmith Trainer

### ISSUE THREAD

**Issue by Loginisalreadytaken** [TrinityCore/TrinityCore#9635]
https://github.com/TrinityCore/TrinityCore/issues/609 (could be related)
http://old.wowhead.com/npc=7232 (Borgus Steelhand)
http://old.wowhead.com/npc=29505 (Imindril Spearsong)
http://old.wowhead.com/npc=11146 (Ironus Coldsteel)
http://old.wowhead.com/npc=11178 (Borgosh Corebender)
http://old.wowhead.com/npc=20124 (Kradu Grimblade)
http://old.wowhead.com/npc=7231 (Kelgruk Bloodaxe)??
http://wow.crafterstome.com/recipes/blacksmithing.html (Crafter's Tome)
- Skill Level: 235-260
- Specialty: (only) No Specialty (or in combination with Armorsmith)
- Expansion: (only) Classic, The Burning Crusade, Wrath of the Lich King
- Source: (only) Trainer

http://www.wowhead.com/spell=10003 (The Shatterer)
http://www.wowhead.com/spell=10007 (Phantom Blade)
http://www.wowhead.com/spell=10011 (Blight)
http://www.wowhead.com/spell=10015 (Truesilver Champion)
http://www.wowace.com/addons/arl/files/10289-v2-0/ (Ackis Recipe List)

Version: 3.3.5a (12340)
Core revision: Trinity Core 81908c7d7bc7+
Database revision: TDB 335.51

My suspicions started with the above mentioned addon. It shows several blacksmithing plans that are supposed to be taught by weaponsmith trainers to all smiths (not only weapon-). However, none of the trainers friendly to Horde characters offer to train anything to armorsmiths.
I couldn't find any information on WoWhead about this and on other sites, it seems that these plans were indeed for weaponsmiths only before WotLK but not during.
The only references I have found to support this issue are the addon and Crafter's Tome site above - if the filter is set correctly, it shows that all smiths should be able to learn the listed plans.
Kelgruk Bloodaxe is supposed to teach the last two plans, but unlike the other NPCs on old.wowhead, he lacks a "Teaches" list entirely, so I have no idea about this guy.

So the idea here is to let all weaponsmith trainers to train all smiths with the plans they should be able to learn but not the ones that require a specialization.
##

**Comment by Killyana** [comment]
wip
``` sql
UPDATE `trainer_spell` SET `ReqAbility1`=9788 WHERE `SpellId`=36124;
