### ISSUE TITLE
[3.3.5a] Auction House deposit fee

### ISSUE THREAD

**Issue by Loginisalreadytaken** [TrinityCore/TrinityCore#9644]
http://www.wowwiki.com/Auction_House#Selling_items

Version: 3.3.5a (12340)
Core revision: Trinity Core 81908c7d7bc7+
Database revision: TDB 335.51

Quote:
A Deposit fee will be charged when you list an item for auction. This fee is based on the length of the auction as well as the vendor value of the item: minimum fee of 1 silver. If your item is bid on and eventually sells, the fee will be refunded, but a 5% cut will be taken by the auction house (15% in neutral auction houses). If the auction ends without a bid, the fee is lost (see Formulas: Auction House: Fees).

When an item sells, the correct fee is not refunded; 1s is refunded for all items.
##

**Comment by Jinnaix** [comment]
can be closed

![image](https://user-images.githubusercontent.com/37972361/91421243-fb0cb680-e855-11ea-863f-58ef0ca2e36b.png)

**Comment by illfated** [comment]
I think this was fixed back in 2015 or 2016, possibly in some of the work done by @r00ty-tc . I can only assume this ticket went unnoticed back then. Oh well, "water under the bridge".

Thanks for finding and closing this ticket.
