### ISSUE TITLE
[The Storm Peaks Zone] Minefield bugged

### ISSUE THREAD

**Issue by click** [TrinityCore/TrinityCore#965]
There is a minefield in that zone, that is completelly wrong:
Mines do appear, but when you step them, green creatures appear instead of exploding and taking you to the air.
Also, when you are in that zone, and do not step mines, you enter in battle with some invisible creatures that eventually kills you.
Also, Achievement Mine Sweeper (1428) is impossible to obtain. (Should it be added to disables?)

**Comment by Killyana** [comment]
Everything works just the Knock Back is not linked to the main spell:
```sql
DELETE FROM `spell_linked_spell` WHERE `spell_trigger` = 54355 AND `spell_effect` = 54402;
INSERT INTO `spell_linked_spell` (`spell_trigger`,`spell_effect`,`type`,`comment`) VALUES
(54355, 54402, 0, 'Land Mine');

**Comment by ccrs** [comment]
@Killyana Is the achievement also working?

**Comment by Killyana** [comment]
Don't know.

**Comment by Killyana** [comment]
id: 57099 [Landmine Knockback Achievement Aura] is stucked correctly, so just 57064 need to be scripted.

**Comment by ccrs** [comment]
so it seems like https://github.com/TrinityCore/TrinityCore/issues/965#issuecomment-4863094 is the last thing remaining

**Comment by Killyana** [comment]
Yes.

**Comment by fvicaria** [comment]
It looks like the blowing up in the air effect is still missing.

**Comment by fvicaria** [comment]
Still don't fly in the air. Can someone confirm this please.

**Comment by Killyana** [comment]
Here a screen: http://imgur.com/Wm3WAYn

**Comment by fvicaria** [comment]
You were faster than me. :)
I got it to work thanks.

**Comment by Keader** [comment]
Achievement Mine Sweeper (1428) still dont work

**Comment by ccrs** [comment]
open a new issue with this pls https://github.com/TrinityCore/TrinityCore/issues/965#issuecomment-4863094
