### ISSUE TITLE
[3.3.5a] Wintergrasp Turrets 

### ISSUE THREAD

**Issue by robertyanta** [TrinityCore/TrinityCore#9657]
When u are defending the fortress, the turrets can be moved after you mount and dismount, so imagine all the turrets moving around defending the fortress, there is no way that the attack team get to win.

TDB: TDB_full_335.51_2013_02_14 + updates
Core: 51f6db79159576d6b8f550670629a8eb65fa2150

**Comment by Aokromes** [comment]
#8736
