### ISSUE TITLE
[DB/Misc] Wrong NPC Model

### ISSUE THREAD

**Issue by JunkyBulgaria** [TrinityCore/TrinityCore#9679]
The NPC Ornok Torn-heart(21183) has different model in retail, there he got armors and staff, at TDB r51 he's nude w/out staff.

Retail: http://www.wowhead.com/npc=21183
TDB: http://store.picbg.net/pubpic/E1/1B/c7fb7d1093c6e11b.jpg

**Comment by Killyana** [comment]
The model id is for http://www.wowhead.com/npc=21685/oronok-torn-heart involved in http://www.wowhead.com/quest=10588/the-cipher-of-damnation (Scripted by DRJ)
