### ISSUE TITLE
[6.x] Core/Creature: Raid training dummy cast KSp on DT

### ISSUE THREAD

**Issue by vendethiel** [TrinityCore/TrinityCore#9681]
TrinityCore 4.3.4 647a20138f824a1f03eb57c928d8e114dcf06d9f
Casting deadly throw (CP count doesn't matter) or fan of knives on a raid training dummy will make him cast Killing Spree. Neither melee attacks nor throw show this behavior (seems like it tries to reach for the target)
They can cast it 10 times straight
http://puu.sh/2EjHO.jpg
##

**Comment by Aokromes** [comment]
If this fix is valid plz open a pr for it.

**Comment by vendethiel** [comment]
Yeah it'd be nice not to get notifications :P. But I won't close it since it's not fixed.

**Comment by Aokromes** [comment]
You can click unsuscribe.

**Comment by vendethiel** [comment]
Still shows up in "participating" as I created it.

**Comment by Killyana** [comment]
Cannot reproduce in rev. c4f114475468 or 4.3.4
