### ISSUE TITLE
[3.3.5a] [Spell] Ice Block / Mutated Transformation

### ISSUE THREAD

**Issue by Loginisalreadytaken** [TrinityCore/TrinityCore#9695]
http://old.wowhead.com/spell=45438
http://old.wowhead.com/spell=70402

Version: 3.3.5a (12340)
Core revision: Trinity Core 5c2203f185ec+
Database revision: TDB 335.51

Ice Block doesn't prevent damage from Mutated Transformation.
##

**Comment by ariel-** [comment]
Shares cause with #8844
