### ISSUE TITLE
Bounding Radius/Combat Reach

### ISSUE THREAD

**Issue by Ric101** [TrinityCore/TrinityCore#9708]
In http://archive.trinitycore.info/Creature_model_info_tc2, it's written that bounding radius 'is the distance the creature stands from the player to attack him while in melee', while combat reach 'maximum distance the creature can reach the player in ranged attack'.

Both of these fields are public, combat reach at least has direct influence in how far a spell can be cast towards a unit given a range - as if that's the object's actual size in the specific situation. However - bounding radius is used nowhere in the Core, and does not seem to have any influence in the client (at first sight) either.

There are cases where according to videos, there's a given distance to which a player can cast a spell at a unit, and a given melee reach which does not match what the Core currently does.

In http://www.youtube.com/watch?v=xG3lJGr_w4w, you can see a Mage casting 'Living Bomb' (35 yards) at a considerably large distance from Vezax - which you cannot reproduce in the current Core unless you change the modelinfo of Vezax to over 20 in the combat reach field of his creature_model_info for his specific modelid. However, if you do this - the melee reach/engagement range becomes ridiculously large. Very, very large. Far larger than it's shown in the same video. Is it perhaps because Bounding Radius is not being used?
##

**Comment by Frytiks** [comment]
Confirmed !

**Comment by Skiopz** [comment]
Still present on [code]db3a355[/code]

**Comment by chaodhib** [comment]
The validation of spell range on the server side has been fixed with https://github.com/TrinityCore/TrinityCore/commit/e6a52d4aae9e8facc46c3b05e0560d540a928d73. This only uses the 'combat reaches' of the units involved. The 'bounding radius' of units is still unused by the core. Therefore, I'm closing this issue and I'm opening a separate one specially addressed to find the use of the 'bounding radius'.

**Comment by ariel-** [comment]
Reference issue #19396

**Comment by chaodhib** [comment]
@ariel- sorry, forgot to add it. thank you.
