### ISSUE TITLE
whirlwind hits twice with 2-handed weapons

### ISSUE THREAD

**Issue by bidibam** [TrinityCore/TrinityCore#9721]
Whirlwind should only hit once per weapons wielded... right now its hitting with a two-handed weapon + off-hand (naked)

118ec195a64bf706b65bbf8c292232148ae84de9
##

**Comment by Keader** [comment]
still dont work :(
on rev 02d014c69d53a4298db1747e9c848d10b84e91d2

**Comment by Keader** [comment]
@robinsch can you take a look this?

**Comment by Keader** [comment]
@jackpoz Can you confirm if 20e913efa685695a721e44931b4f939e6bfe7733 can be reverted? it shouldnt skip checks?! can you analyze and confirm with similar spells?!

**Comment by Shocker** [comment]
I don't consider reverting the commit to be the correct approach. Probably an additional check for whirlwind should be done. Still, any other spells in this situation?

**Comment by Keader** [comment]
@Shocker nop, i noticed this only gives problem

**Comment by Voidx** [comment]
important bug here

**Comment by noryad** [comment]
@ariel- Please this is a very important bug. Confirmed in aeb5762.

**Comment by ariel-** [comment]
This is because triggered spells ignore equipped item check. If whirlwind should be the exception, it can be fixed with a SpellScript.

If this is the rule, triggered support for ignoring items shall be dropped.
