### ISSUE TITLE
Preparin' For Battle

### ISSUE THREAD

**Issue by milotic** [TrinityCore/TrinityCore#9743]
Hi, http://es.wowhead.com/quest=25495 when player get this quest and use fly master to go echo islands, player should be in Phasing echo isles, but Phasing not work

rev: https://github.com/TrinityCore/TrinityCore/commit/2e1b1b8ceb08dcbe35f11605486c45f52717f2e2

**Comment by Wylath** [comment]
```sql
DELETE FROM `spell_area` WHERE `spell` IN (74092, 74310);
INSERT INTO `spell_area` (`spell`, `area`, `quest_start`, `quest_end`, `aura_spell`, `racemask`, `gender`, `autocast`, `quest_start_status`) VALUES
(74092,368,25495,25445,0,0,2,1,74),
(74310,133,25287,25393,0,0,2,1,74);
```
