### ISSUE TITLE
[3.3.5][Warrior] Spell Reflection

### ISSUE THREAD

**Issue by Natureknight** [TrinityCore/TrinityCore#9745]
1.Get a warrior with spell reflection.
2.Get a priest with penance and dispel magic.
3.Cast spell reflect, and let priest to cast penance or dispel magic to warrior.

Bug:
Spell reflection not reflecting penance tick or dispel magic.

Spell reflection should reflect the penance and dispel magic back to the priest.

rev: 2e1b1b8
##

**Comment by Raydor** [comment]
Death grip reflect got fixed but I think it was unintended, no one said anything about the fix and also, you can reflect death grip but nothing happens after that, its supposed to move the DK to the warrior but it only shows "Reflect".

![](http://puu.sh/e1B71/e72973ea27.jpg)

![](http://puu.sh/e1B7N/5c81cca4c2.jpg)

**Comment by Nyeriah** [comment]
What happens is that spell reflection doesn't work with triggered spells. Now that yesitsme moved it from the database triggered spells and now it is directly cast by the death knight, it can be reflected. However there are still issues handling the target in case of a spell reflect.

**Comment by Raydor** [comment]
Dispel Magic still can not be reflected neither penance. https://github.com/TrinityCore/TrinityCore/commit/23e4472d14bbf24722277d9d49c62ea7e39821c7

**Comment by Rushor** [comment]
do you tried it with a spellscript? if the caster is the target the  remove the debuff from the target on spellhit?

**Comment by Raydor** [comment]
@Rushor No, I didn't try anything, just tested today in the last revision and saw it is still bugged.

**Comment by robinsch** [comment]
It's because Dispel Magic is a positive and negative effect. You need to add a exception for this.

**Comment by Raydor** [comment]
@robinsch Anyways, it does not do all of the effect with Dispel Magic, it gets reflected but it doesn't dispel anything from the priest.

Tried a fast way to test it:
```diff
diff --git a/src/server/game/Spells/Spell.cpp b/src/server/game/Spells/Spell.cpp
index 0f84c63..6ce0577 100644
--- a/src/server/game/Spells/Spell.cpp
+++ b/src/server/game/Spells/Spell.cpp
@@ -620,6 +620,12 @@ m_caster((info->AttributesEx6 & SPELL_ATTR6_CAST_BY_CHARMER && caster->GetCharme
         && !(m_spellInfo->AttributesEx & SPELL_ATTR1_CANT_BE_REFLECTED) && !(m_spellInfo->Attributes & SPELL_ATTR0_UNAFFECTED_BY_INVULNERABILITY)
         && !m_spellInfo->IsPassive() && !m_spellInfo->IsPositive();

+    // Disipar magia del priest se puede dispelear
+    // Penitencia del priest se puede dispelear
+    if (m_spellInfo->SpellFamilyName == SPELLFAMILY_PRIEST && m_spellInfo->SpellIconID == 74 // Dispel Magic
+        || m_spellInfo->SpellFamilyName == SPELLFAMILY_PRIEST && m_spellInfo->SpellIconID == 2818) // Penance
+        m_canReflect = true;
+
     CleanupTargetList();
     memset(m_effectExecuteData, 0, MAX_SPELL_EFFECTS * sizeof(ByteBuffer*));

```
![](http://puu.sh/iRrC1/feb98289d1.jpg)

**Comment by robinsch** [comment]
First of all, I don't think reflected Dispels should dispel anything. 

Because the caster is still the Priest, therefore he can't dispel positive buffs.

**Comment by Raydor** [comment]
http://www.arenajunkies.com/topic/111138-priest-best-spell-to-cast-when-warior-spell-reflects/#entry1527162 I'm not sure it you are right or i'm right, didn't find any proof of it, except this one which might be true.

**Comment by robinsch** [comment]
Hydra. Lightdoom movies, might check those out.

**Comment by Rushor** [comment]
http://www.arenajunkies.com/topic/89975-how-do-you-remove-spell-reflect/

if should remove a buff from the one who casted dispel

**Comment by robinsch** [comment]
As I stated above it fails because caster is still the pirest. EffectDispel has this check

**Comment by Raydor** [comment]
Haven't tested it yet (no time for it) but seeing the diff, it seems like you implement the bool but you don't use it in Unit::GetDispellableAuraList, didn't you miss something?

**Comment by robinsch** [comment]
Edited above.

**Comment by Raydor** [comment]
It is working nicely <3.

**Comment by Aokromes** [comment]
If the fix here is valid, plz open a PR.

**Comment by Ascathor** [comment]
Probably not the cleanest but a damn good start to fix it.

**Comment by Keader** [comment]
i'm using robinsch fix and have no issues :)

**Comment by Aokromes** [comment]
@Keader can you create a pr for this?

**Comment by Keader** [comment]
@robinsch can you open pr about https://github.com/TrinityCore/TrinityCore/issues/9745#issuecomment-119551417 ?

**Comment by Aokromes** [comment]
f0772ee
