### ISSUE TITLE
Mobs air-stepping into cave ceilings

### ISSUE THREAD

**Issue by ghost** [TrinityCore/TrinityCore#9753]
My character is only in Westfall, but so far all of the caves he's been in so far, the mobs while fleeing will start to step up into the air untill they have vanished into the roof of the cave. I have tried with MMaps on and off and still get the same results. I have tried re-compiling the map extractors in Tools and re extract the maps then deleted all folders in my bin/release folder and copied the new folders into the bin/release folder and rerun mmaps_generator, and still not fixed. Any ideas out there on how to fix this?

TrinityCore rev. b1e8c422593f 2013-05-01 21:56:39 +0200 (master branch) (Win64, Release)
TDB 335.51 `2013_05_04_01_world_creature_template.sql`
##

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/1413005-mobs-air-stepping-into-cave-ceilings?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github).

**Comment by Killyana** [comment]
This issue can be observed here: Map: 571 (Northrend) Zone: 210 (Icecrown) Area: 4595 (Hall of Horrors)  X: 8002.013184 Y: 3312.416748 Z: 632.395935 Orientation: 4.051054
Spawn any npc and aggro him, he will go to the roof.

**Comment by Killyana** [comment]
This issue seems happening only if the nps is in the water.

**Comment by Killyana** [comment]
https://github.com/TrinityCore/TrinityCore/commit/0df0cb30ca9de2015ec774e50bb69337382576d3
