### ISSUE TITLE
[3.3.5] Hunter Traps vs Stealth

### ISSUE THREAD

**Issue by Natureknight** [TrinityCore/TrinityCore#9768]
When hunter place a freezing trap, and stealthed rogue step into it, sometimes the trap just dissapear without applying the frozen effect on the rogue. 

Same with Shadow Sight arena "eyes" - Stealthed rogue step on the eye and nothing happens, the eye just dissapear. Not applying Shadow Sight debuff always.

rev: 2e1b1b8

**Comment by Killyana** [comment]
Dup: https://github.com/TrinityCore/TrinityCore/issues/10179
