### ISSUE TITLE
4.3.4 Mage

### ISSUE THREAD

**Issue by XPaiN2008** [TrinityCore/TrinityCore#9792]
When I cast frostbolt It heals pet for 3 times.

http://oi43.tinypic.com/2055jye.jpg

core last core
db tdb
##

**Comment by Killyana** [comment]
The heal effect is no longer present on master.

**Comment by offl** [comment]
<details>

![231pmz](https://user-images.githubusercontent.com/11556157/35187427-4881e5c8-fe2c-11e7-92b1-9cc9c731e554.jpg)
