### ISSUE TITLE
{Talent} Killing Spree (Under water)

### ISSUE THREAD

**Issue by durrrr** [TrinityCore/TrinityCore#9882]
Hello,
I have encountered a problem while playing in water in every zone of the game.

How to reproduce the bug:
1. Use talent: "Killing Spree" while underwater.

What should happen, what happens instead:
What should happen is the talent shold work properly under water, what happens instead is when you use "Killing Spree" while underwater you get launched to the bottom of the water that you are in.

A link:
http://www.wowhead.com/spell=51690 --> The Spell

I'm running Unix on hash: 9c0d69e , TDB 335.51
Addons: AH bot and WG.

Regards,
durrrr
##

**Comment by Killyana** [comment]
Works correctly on rev. fa3eb754cbe1
