### ISSUE TITLE
[Quest] The Brothers Bronzebeard

### ISSUE THREAD

**Issue by TheMaaster** [TrinityCore/TrinityCore#9889]
when i take [The Brothers Bronzebeard] (http://www.wowhead.com/quest=12973) from [Brann Bronzebeard] (http://www.wowhead.com/npc=30107) (or [Brann Bronzebeard] (http://www.wowhead.com/npc=30382) ) nothing happens. 
Looking on youtube, i think it needs plenty scripting. (http://www.youtube.com/watch?v=SblDX-y8Wsc)
and when set to complete, [Velog Icebellow] (http://www.wowhead.com/npc=30401) still missing to turn it in to (phasing?)

**Comment by grimgravy** [comment]
The mission're still bugged by the time it arrives in the area to complete the mission not complete

**Comment by grimgravy** [comment]
The mission're still bugged by the time it arrives in the area to complete the mission not complete

**Comment by grimgravy** [comment]
The mission're still bugged by the time it arrives in the area to complete the mission not complete

**Comment by grimgravy** [comment]
The mission're still bugged by the time it arrives in the area to complete the mission not complete

**Comment by grimgravy** [comment]
The mission're still bugged by the time it arrives in the area to complete the mission not complete

**Comment by grimgravy** [comment]
The mission're still bugged by the time it arrives in the area to complete the mission not complete

**Comment by grimgravy** [comment]
The mission're still bugged by the time it arrives in the area to complete the mission not complete

**Comment by grimgravy** [comment]
The mission're still bugged by the time it arrives in the area to complete the mission not complete

**Comment by grimgravy** [comment]
The mission're still buggy when it comes in the area to complete the mission not complete

**Comment by Killyana** [comment]
Still waiting for a c++ dev to make a PR fixing the dismount issue.

**Comment by Rushor** [comment]
even if we manually add:

machine->GetVehicleKit()->InstallAccessory(NPC_SOLDIER, 2, true, TEMPSUMMON_DEAD_DESPAWN, 0);

the accesoorynpc will cast 30383 on the vehicle and cicks the player out if the second soldier wants to jumb on the vehicle

**Comment by Killyana** [comment]
Script updated, spell 56603 used by the player,  55089 by soldiers, and 43671 by Brann exactly as on retail, but still Brann is ejected when a soldier ride the plane. In this case I can't find the problem.

**Comment by Killyana** [comment]
A solution by @whoami : http://pastebin.com/ESL4w3nJ
This is considered as a hack, so if someone can help to find a clean solution.

**Comment by Killyana** [comment]
Another solution: http://pastebin.com/HPpKPjCW
Sniffs: http://pastebin.com/hn7C8ANK

**Comment by SeTM** [comment]
@Killyana thx for great work. Strange, that vehicle spells is not working, because on code we -1 from aura amount, so 3 basepoint becomes 2 vehicle seat.

**Comment by Killyana** [comment]
The only problem is that VEHICLE_SEAT_FLAG_UNK3 must be implemented like here http://pastebin.com/HPpKPjCW but there's no dev core available to do it.

**Comment by SeTM** [comment]
I did so: 
http://paste2.org/h6w2t7LG

DELETE FROM `spell_area` WHERE `spell`=55782 AND `area`=4432;
mb area 4431?

**Comment by Killyana** [comment]
No the phasing is correct.

**Comment by SeTM** [comment]
Strange, because quest area is 4431.

**Comment by Killyana** [comment]
There's no phasing spell for the are 4431 so when the player takes the quest he will be set on phase 3 by SAI
``` sql
(@brann1*100, 9, 2, 0, 0, 0, 100, 0, 0, 0, 0, 0, 44, 3, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'Brann  - On ActionList - Set phase 3'),

**Comment by SeTM** [comment]
Yep, you right.

**Comment by sirikfoll** [comment]
this can't be merged? since the script is already working.
the problem with the seat is a different issue

**Comment by Killyana** [comment]
No if I merge this the seat issue will never be fixed.

**Comment by sirikfoll** [comment]
What about the fix suggested by @SeTM, is hacky too?
```diff
diff --git a/src/server/game/DataStores/DBCStructure.h b/src/server/game/DataStores/DBCStructure.h
index 5ccd5d2..2522708 100644
--- a/src/server/game/DataStores/DBCStructure.h
+++ b/src/server/game/DataStores/DBCStructure.h
@@ -2072,7 +2072,8 @@ struct VehicleSeatEntry
     uint32  m_flagsB;                                       // 45
                                                             // 46-57 added in 3.1, floats mostly
 
-    bool CanEnterOrExit() const { return (m_flags & VEHICLE_SEAT_FLAG_CAN_ENTER_OR_EXIT) != 0; }
+    bool CanEnterOrExit() const { return (m_flags & (VEHICLE_SEAT_FLAG_CAN_ENTER_OR_EXIT | VEHICLE_SEAT_FLAG_UNK3)) || CanEnterOrExitReserved(); }
+    bool CanEnterOrExitReserved() const { return m_flags & (VEHICLE_SEAT_FLAG_HAS_LOWER_ANIM_FOR_ENTER | VEHICLE_SEAT_FLAG_HAS_LOWER_ANIM_FOR_RIDE); }  // Veh Id 700 for example.
     bool CanSwitchFromSeat() const { return (m_flags & VEHICLE_SEAT_FLAG_CAN_SWITCH) != 0; }
     bool IsUsableByOverride() const { return (m_flags & (VEHICLE_SEAT_FLAG_UNCONTROLLED | VEHICLE_SEAT_FLAG_UNK18)
                                     || (m_flagsB & (VEHICLE_SEAT_FLAG_B_USABLE_FORCED | VEHICLE_SEAT_FLAG_B_USABLE_FORCED_2 |
