### ISSUE TITLE
[3.5.5a][bug] Slag Covered Metal (part of son of hodir questline)

### ISSUE THREAD

**Issue by shadowstepper** [TrinityCore/TrinityCore#9902]
Hash: 9c0d69e
Version: 3.5.5a (123450)
on Unix

the quest item: Slag Covered Metal (id:41556)
should be dropped normally like any other quest item, 
from the mob: Stormforged Iron Giant (id: 29375)
which located in the Storm Peaks, Frostfield Lake 

what is actually happening right now is the quest item will not be dropped from the mob
unless a player is on the quest:  Mending Fences (id:12915)
if a player dont have this quest on thier log the item will not be dropped as it should.

this quest is part of the Sons of Hodir questline which grand reputation with the mentioned faction,
when a player finish the whole line they're able to buy exotic items from the NPC: 
Lillehoff <The Sons of Hodir Quartermaster> (id: 32540)

**Comment by Killyana** [comment]
DROP Slag Covered Metal ON quest Mending Fences taken
DROP Slag Covered Metal ON quest Mending Fences rewarded
STOP dropping Slag Covered Metal ON quest The Refiner's Fire
Conditions are correct on  rev. 5dba91fb0e38
