### ISSUE TITLE
[3.5.5a][Boss] Naxxramas - Kel'Thuzad

### ISSUE THREAD

**Issue by shadowstepper** [TrinityCore/TrinityCore#9903]
Hash: 9c0d69e
Version: 3.5.5a (123450)
on Unix

Phase 1: Kel'Thuzad begins the encounter invulnerable, and you need to kill adds which come from the seven alcoves of the room. This includes the entrance. 

what is actually happening is: big most of the summoned creatures
Soldier of the Frozen Wastes
Unstoppable Abomination
Soul Weaver
are summon normally but big amount of the Unstoppable Abominations(id:23562) summoned are not aggresive and not targeting any players as they should do.
and instead they're wandering from wall to wall in the room

Phase 2 works fine. excpet for 1 spell : 
Shadow Fissure(id:27810) - Summons a very noticeable red fissure around the targeted player which does 62500-137500 Shadow damage after 5 seconds as Void Blast. Easily avoidable by running out of the fissure. 

what actually happens is the spell is applied as it should from time to time
but it does not causing the mentioned damage.

**Comment by danlapps** [comment]
Is this a valid issue ?  Phase 2 seems to work ok, as of phase 1, I find it hard to believe some works ok but some bugs, they should all have same behaviors.  Is this still valid or has it been fixed since then ?

**Comment by Killyana** [comment]
Only the issue with the Unstoppable Abominations is valid, and there's already an opened issue https://github.com/TrinityCore/TrinityCore/issues/12037
rev. 5dba91fb0e38
