### ISSUE TITLE
[Ulduar] Flame Leviathan problems

### ISSUE THREAD

**Issue by GanjaNoel** [TrinityCore/TrinityCore#9939]
TDB: 335.51
rev: 872c0c9c7315 
-Flame Leviathan: http://old.wowhead.com/npc=33113

Problem: Activating hard mode on Flame Leviathan through http://old.wowhead.com/npc=33686 doesn't buff him at all with 4 towers up, while it should (25% more physical damage, 1% AOE damage beam, 50% more fire damage, 10% less fire damage taken and some helping adds from Freya), and it drops the normal loot for every tower there is up, he drops about 9 equips on his full hard mode 25-player.

**Comment by Killyana** [comment]
This issue is no longer valid as the boss get the 4 buffs and for the loot the issue is not the same.
