### ISSUE TITLE
character with guid 1 stuck when killing mobs

### ISSUE THREAD

**Issue by morpheus4hire** [TrinityCore/TrinityCore#9960]
Revision 1adf4624bb3e
Mob GUID 34980 
Name Ghostpaw Runner

When I attack and kill this mob my hunter gets froze in place. If i switch to a differnet aspect or mount up I can then move again. This is the same bug that was reported sometime ago in 8980

Thanks

**Comment by tkrokli** [comment]
Wasn't this issue fixed last year, either the GUID=1 issue or by hackfixed by setting the CreatureFamilyFleeAssistanceRadius = 0 in Worldserver.conf ? Or perhaps I don't remember correctly?
I can't remember anyone mentioning this issue since last summer. Anyone got this issue now at all?

**Comment by MrSmite** [comment]
> Wasn't this issue fixed last year

Not sure but I still haven't had any issue with freezing on mob flee. In fact I just ran through Ashenvale to get flightpaths and killed a few beasts just for good measure.

**Comment by tkrokli** [comment]
I can't point out exactly when or how, but I think it was fixed at least a year ago, if not more. I will do some testing with GUID=1 characters, but I am fairly certain that the issue no longer exists.

**Comment by Killyana** [comment]
Cannot reproduce with guid=1 character on rev. 5dba91fb0e38
