### ISSUE TITLE
[Gossip] Wrong gossip for Egan Peltskinner (quest turn-in) (SQL fix added 2014-07-23)

### ISSUE THREAD

**Issue by MrSmite** [TrinityCore/TrinityCore#9964]
Core: 3e108f068026e6bc54828c2f829c728928c349c7
DB: TDB_full_335.11.46_2012_02_13.sql + updates
OS: XP SP3

__Bug:__

Egan Peltskinner 196 (guid 79971) displays wrong (obsolete) gossip when handing in the quest
"Wolves Across The Border" (id: 33)

__Details:__

Egan sends you out to get diseased wolf pelts but when you hand them in he displays the old gossip "I'm hungry did you get that tough wolf meat?". This gossip is from the old, obsolete version of the quest. 

The quest works though (requires pelts), this is just a gossip error.

**Comment by Aokromes** [comment]
Already fixed, who knows when.

**Comment by tkrokli** [comment]
I think I know, I just searched for the name of the quest and found this:
**[SQL] Fix gossip text for quest: Wolves Across The Border** #11585

**Comment by MrSmite** [comment]
> Already fixed, who knows when.

Actually this report was from 2013, the fix is from 2014 ;)

I forgot to link this OP in the fix so it seems to have a disconnect.
