### ISSUE TITLE
Everlasting Affliction + Mage Armor

### ISSUE THREAD

**Issue by Massex** [TrinityCore/TrinityCore#9992]
Talent http://wotlk.openwow.com/spell=47205 if use Drain Life, Drain Soul, Shadow Bolt or Haunt doesnt refresh Corruption full duration on Mage with Mage Armor.

evidence: http://www.arenajunkies.com/topic/130545-swp-and-mage-armor/

https://github.com/TrinityCore/TrinityCore/commit/e5ec998864c83254842c41e14d8373a081fc57ea

**Comment by Killyana** [comment]
Fixed.
rev. 5dba91fb0e38
